VERSION --use-cache-command 0.6

IMPORT github.com/powertoolsdev/shared-configs:main
FROM ghcr.io/powertoolsdev/ci-go-builder

WORKDIR /src

ARG EARTHLY_GIT_PROJECT_NAME
ARG GHCR_IMAGE=ghcr.io/${EARTHLY_GIT_PROJECT_NAME}
ARG SERVICE=workers-apps
ARG GOCACHE=/go-cache
ARG GOMODCACHE=/go-mod-cache

CACHE $GOCACHE
CACHE $GOMODCACHE

code:
    FROM ../../.+deps
    COPY ../../pkg+code/pkg pkg
    COPY --dir . ./services/$SERVICE
    WORKDIR services/$SERVICE
    RUN go generate ./...

test:
    FROM +code
    RUN go test ./...

test-integration:
    RUN echo "noop..."

build:
    FROM +code
    RUN go \
        build \
        -ldflags="-X 'github.com/powertoolsdev/mono/pkg/config.Version=$EARTHLY_TARGET_TAG_DOCKER'" \
        -o bin/service \
        .
    SAVE ARTIFACT bin/service /service
    SAVE IMAGE --push $GHCR_IMAGE:build

docker:
    FROM alpine:3.16
    ARG EARTHLY_GIT_ORIGIN_URL
    ARG EARTHLY_GIT_SHORT_HASH
    ARG EARTHLY_SOURCE_DATE_EPOCH
    ARG EARTHLY_TARGET_PROJECT_NO_TAG
    ARG EARTHLY_TARGET_TAG_DOCKER

    # These are set to run locally. They _must_ be overridden in CI.
    ARG repo=$EARTHLY_TARGET_PROJECT_NO_TAG
    ARG cache_tag=$EARTHLY_TARGET_TAG_DOCKER
    ARG image_tag=$EARTHLY_TARGET_TAG_DOCKER

    RUN apk add --update --no-cache \
      git \
      zip

    COPY +build/service /bin/service
    ENTRYPOINT ["/bin/service", "all"]
    LABEL org.opencontainers.image.created=$EARTHLY_SOURCE_DATE_EPOCH
    LABEL org.opencontainers.image.revision=$EARTHLY_GIT_SHORT_HASH
    LABEL org.opencontainers.image.version=$image_tag
    LABEL org.opencontainers.image.source=$EARTHLY_GIT_ORIGIN_URL
    LABEL org.opencontainers.image.authors=nuon
    LABEL org.opencontainers.image.vendor=nuon
    SAVE IMAGE --push --cache-from=$repo:$cache_tag $repo:$image_tag

# TODO(jm): this should be a shared earthfile between all services
helm-bump-and-publish:
    FROM ghcr.io/powertoolsdev/ci-helm-releaser
    ARG chart_version
    ARG repos
    WORKDIR /work
    COPY --dir k8s /work/k8s
    DO shared-configs+HELM_RELEASE \
        --chart_version=$chart_version \
        --repos=$repos

deploy:
    FROM ghcr.io/powertoolsdev/ci-helm-releaser
    WORKDIR /work
    COPY --dir k8s /work/k8s
    ARG env
    ARG cluster_name
    ARG role_arn
    ARG chart_version
    ARG repository
    ARG image_tag
    ARG tfenv=.tfenv
    ARG repos
    DO shared-configs+HELM_SETUP \
        --repos="$repos"

    WORKDIR /work/k8s
    COPY $tfenv .
    RUN while IFS='=' read -r k v; do eval export "$k='$v'"; done < "$tfenv" \
        && envsubst < "values.$env.tmpl" > "values.$env.yaml"

    DO shared-configs+K8S_DEPLOY \
        --env=$env \
        --cluster_name=$cluster_name \
        --role_arn=$role_arn \
        --chart_version=$chart_version \
        --repository=$repository \
        --image_tag=$image_tag
