VERSION --use-cache-command 0.6

IMPORT github.com/powertoolsdev/shared-configs:main
FROM ghcr.io/powertoolsdev/ci-go-builder

WORKDIR /src

ARG EARTHLY_GIT_PROJECT_NAME
ARG GHCR_IMAGE=ghcr.io/${EARTHLY_GIT_PROJECT_NAME}
ARG SERVICE=workers-apps
ARG GOCACHE=/go-cache
ARG GOMODCACHE=/go-mod-cache
ARG GITHUB_ACTIONS=

CACHE $GOCACHE
CACHE $GOMODCACHE

code:
    FROM ../../.+deps --GITHUB_ACTIONS=$GITHUB_ACTIONS
    COPY ../../pkg+code/pkg --GITHUB_ACTIONS=$GITHUB_ACTIONS pkg
    COPY --dir . ./services/$SERVICE
    WORKDIR services/$SERVICE
    RUN go generate ./...

test:
    FROM +code
    RUN go test ./...

test-integration:
    RUN echo "noop..."

build:
    FROM +code
    RUN go \
        build \
        -ldflags="-X 'github.com/powertoolsdev/mono/pkg/config.Version=$EARTHLY_TARGET_TAG_DOCKER'" \
        -o bin/service \
        .
    SAVE ARTIFACT bin/service /service
    SAVE IMAGE --push $GHCR_IMAGE:build

docker:
    FROM alpine:3.16
    ARG EARTHLY_GIT_ORIGIN_URL
    ARG EARTHLY_GIT_SHORT_HASH
    ARG EARTHLY_SOURCE_DATE_EPOCH
    ARG EARTHLY_TARGET_PROJECT_NO_TAG
    ARG EARTHLY_TARGET_TAG_DOCKER

    # These are set to run locally. They _must_ be overridden in CI.
    ARG repo=$EARTHLY_TARGET_PROJECT_NO_TAG
    ARG cache_tag=$EARTHLY_TARGET_TAG_DOCKER
    ARG image_tag=$EARTHLY_TARGET_TAG_DOCKER

    RUN apk add --update --no-cache \
      git \
      zip

    COPY +build/service /bin/service
    ENTRYPOINT ["/bin/service", "all"]
    LABEL org.opencontainers.image.created=$EARTHLY_SOURCE_DATE_EPOCH
    LABEL org.opencontainers.image.revision=$EARTHLY_GIT_SHORT_HASH
    LABEL org.opencontainers.image.version=$image_tag
    LABEL org.opencontainers.image.source=$EARTHLY_GIT_ORIGIN_URL
    LABEL org.opencontainers.image.authors=nuon
    LABEL org.opencontainers.image.vendor=nuon
    SAVE IMAGE --push --cache-from=$repo:$cache_tag $repo:$image_tag
