import '@test/mock-fetch-options'
import { badResponseCodes } from '@test/utils'
import { describe, expect, test } from 'vitest'
import {
  createInstall,
  getInstalls,
  getInstall,
  getInstallComponent,
  getInstallComponents,
  getInstallComponentDeploys,
  getInstallDeploy,
  getInstallEvents,
  getInstallRunnerGroup,
  getInstallReadme,
  getInstallSandboxRun,
  getInstallActionWorkflowRun,
  getInstallActionWorkflowRuns,
  reprovisionInstall,
  runInstallActionWorkflow,
  getInstallActionWorkflowLatestRun,
  getInstallActionWorkflowRecentRun,
  deployComponents,
  deployComponentBuild,
  getInstallDeployPlan,
  getInstallCurrentInputs,
  getInstallComponentOutputs,
} from './installs'

describe('getInstalls should handle response status codes from GET installs endpoint', () => {
  const orgId = 'test-id'
  test('200 status', async () => {
    const spec = await getInstalls({ orgId })
    spec.forEach((s) => {
      expect(s).toHaveProperty('id')
      expect(s).toHaveProperty('name')
      expect(s).toHaveProperty('composite_component_status')
    })
  })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstalls({ orgId }).catch((err) => expect(err).toMatchSnapshot())
  })
})

describe('getInstall should handle response status codes from GET installs/:id endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  test('200 status', async () => {
    const spec = await getInstall({ installId, orgId })
    expect(spec).toHaveProperty('id')
    expect(spec).toHaveProperty('name')
    expect(spec).toHaveProperty('composite_component_status')
  })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstall({ installId, orgId }).catch((err) =>
      expect(err).toMatchSnapshot()
    )
  })
})

describe('getInstallComponents should handle response status codes from GET installs/:id/components endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  test('200 status', async () => {
    const spec = await getInstallComponents({ installId, orgId })
    spec.forEach((s) => {
      expect(s).toHaveProperty('id')
      expect(s).toHaveProperty('status')
    })
  })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstallComponents({ installId, orgId }).catch((err) =>
      expect(err).toMatchSnapshot()
    )
  })
})

describe('getInstallComponent should handle response status codes from GET installs/:id/components endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  const installComponentId = 'test-id'
  /*
    @FIXME: @nnnnat
    getInstallComponent filters on installComponentId which is dynamically generated by faker
    and will never be the same as the provided ID
    therefor the returned spec will always null

    @TODO: add get install component by run id path to rest api
  */
  test('200 status', async () => {
    const spec = await getInstallComponent({
      installComponentId,
      installId,
      orgId,
    })
    expect(spec).toBeUndefined()
    // expect(spec).toHaveProperty('id')
    // expect(spec).toHaveProperty('status')
  })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstallComponent({ installComponentId, installId, orgId }).catch(
      (err) => expect(err).toMatchSnapshot()
    )
  })
})

describe('getInstallComponentDeploys should handle response status codes from GET installs/:id/components/:id/deploys endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  const installComponentId = 'test-id'
  test('200 status', async () => {
    const spec = await getInstallComponentDeploys({
      installComponentId,
      installId,
      orgId,
    })
    spec.forEach((s) => {
      expect(s).toHaveProperty('id')
      expect(s).toHaveProperty('status')
    })
  })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstallComponentDeploys({
      installComponentId,
      installId,
      orgId,
    }).catch((err) => expect(err).toMatchSnapshot())
  })
})

describe('getInstallDeploy should handle response status codes from GET installs/:id/deploys/:id endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  const installDeployId = 'test-id'
  test('200 status', async () => {
    const spec = await getInstallDeploy({ installDeployId, installId, orgId })
    expect(spec).toHaveProperty('id')
    expect(spec).toHaveProperty('status')
  })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstallDeploy({ installDeployId, installId, orgId }).catch((err) =>
      expect(err).toMatchSnapshot()
    )
  })
})

describe('getInstallEvents should handle response status codes from GET installs/:id/events endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  test('200 status', async () => {
    const spec = await getInstallEvents({ installId, orgId })
    spec.forEach((s) => {
      expect(s).toHaveProperty('id')
      expect(s).toHaveProperty('operation_status')
    })
  })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstallEvents({ installId, orgId }).catch((err) =>
      expect(err).toMatchSnapshot()
    )
  })
})

describe('getInstallRunnerGroup should handle response status codes from GET installs/:id/runner-group endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  test('200 status', async () => {
    const spec = await getInstallRunnerGroup({ installId, orgId })
    expect(spec).toHaveProperty('id')
    expect(spec).toHaveProperty('type')
  })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstallRunnerGroup({ installId, orgId }).catch((err) =>
      expect(err).toMatchSnapshot()
    )
  })
})

// TODO(nnnat): deal with this failing readme test
describe.skip('getInstallReadme should handle response status codes from GET installs/:id/readme endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  test('200 status', async () => {
    const spec = await getInstallReadme({ installId, orgId })
    expect(spec).toHaveProperty('readme')
  })

  // test('206 status', async () => {
  //   const spec = await getInstallReadme({ installId, orgId })
  //   expect(spec).toHaveProperty('warnings')
  // })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstallReadme({ installId, orgId }).catch((err) =>
      expect(err).toMatchSnapshot()
    )
  })
})

describe('getInstallSandboxRun should handle response status codes from GET installs/:id/sandbox-runs endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  const installSandboxRunId = 'test-id'
  /*
    @FIXME: @nnnnat
    getInstallSandboxRun filters on run ID which is dynamically generated by faker
    and will never be the same as the provided run ID
    therefor the returned spec will always null

    @TODO: add get sandbox run by run id path to rest api
  */
  test('200 status', async () => {
    const spec = await getInstallSandboxRun({
      installSandboxRunId,
      installId,
      orgId,
    })
    expect(spec).toBeUndefined()
    // expect(spec).toHaveProperty('id')
    // expect(spec).toHaveProperty('status')
  })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstallSandboxRun({ installSandboxRunId, installId, orgId }).catch(
      (err) => expect(err).toMatchSnapshot()
    )
  })
})

describe('getInstallActionWorkflowRun should handle response status codes from GET installs/:id/action-workflows/runs/:id endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  const actionWorkflowRunId = 'test-id'
  test('200 status', async () => {
    const spec = await getInstallActionWorkflowRun({
      actionWorkflowRunId,
      installId,
      orgId,
    })
    expect(spec).toHaveProperty('id')
    expect(spec).toHaveProperty('status')
  })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstallActionWorkflowRun({
      actionWorkflowRunId,
      installId,
      orgId,
    }).catch((err) => expect(err).toMatchSnapshot())
  })
})

describe('getInstallActionWorkflowRuns should handle response status codes from GET installs/:id/action-workflows/runs endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  test('200 status', async () => {
    const spec = await getInstallActionWorkflowRuns({ installId, orgId })
    spec.forEach((s) => {
      expect(s).toHaveProperty('id')
      expect(s).toHaveProperty('status')
    })
  })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstallActionWorkflowRuns({ installId, orgId }).catch((err) =>
      expect(err).toMatchSnapshot()
    )
  })
})

describe('reprovisionInstall should handle response status codes from POST installs/:id/reprovision endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  test('200 status', async () => {
    const spec = await reprovisionInstall({ installId, orgId })
    expect(spec).not.toBeNull()
  })

  test.each(badResponseCodes)('%s status', async () => {
    await reprovisionInstall({ installId, orgId }).catch((err) =>
      expect(err).toMatchSnapshot()
    )
  })
})

describe('runInstallActionWorkflow should handle response status codes from POST installs/:id/reprovision endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  const actionWorkflowConfigId = 'test-id'
  test('200 status', async () => {
    const spec = await runInstallActionWorkflow({
      actionWorkflowConfigId,
      installId,
      orgId,
    })
    expect(spec).toHaveProperty('id')
    expect(spec).toHaveProperty('status')
    expect(spec).toHaveProperty('trigger_type')
  })

  test.each(badResponseCodes)('%s status', async () => {
    await runInstallActionWorkflow({
      actionWorkflowConfigId,
      installId,
      orgId,
    }).catch((err) => expect(err).toMatchSnapshot())
  })
})

describe('getInstallActionWorkflowLatestRun should handle response status codes from GET installs/:id/action-workflows/latest-runs endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  test('200 status', async () => {
    const spec = await getInstallActionWorkflowLatestRun({ installId, orgId })
    spec.forEach((s) => {
      expect(s).toHaveProperty('action_workflow')
      expect(s).toHaveProperty('install_action_workflow_run')
    })
  })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstallActionWorkflowLatestRun({ installId, orgId }).catch((err) =>
      expect(err).toMatchSnapshot()
    )
  })
})

describe('getInstallActionWorkflowRecentRun should handle response status codes from GET installs/:id/action-workflows/:id/recent-runs endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  const actionWorkflowId = 'test-id'
  test('200 status', async () => {
    const spec = await getInstallActionWorkflowRecentRun({
      actionWorkflowId,
      installId,
      orgId,
    })
    expect(spec).toHaveProperty('action_workflow')
    expect(spec).toHaveProperty('recent_runs')
  })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstallActionWorkflowRecentRun({
      actionWorkflowId,
      installId,
      orgId,
    }).catch((err) => expect(err).toMatchSnapshot())
  })
})

describe('deployComponents should handle response status codes from POST installs/:id/components/deploy-all endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  test('200 status', async () => {
    const spec = await deployComponents({ installId, orgId })
    expect(spec).not.toBeNull()
  })

  test.each(badResponseCodes)('%s status', async () => {
    await deployComponents({ installId, orgId }).catch((err) =>
      expect(err).toMatchSnapshot()
    )
  })
})

describe('deployComponentBuild should handle response status codes from POST installs/:id/deploys endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  const buildId = 'test-id'
  test('200 status', async () => {
    const spec = await deployComponentBuild({ buildId, installId, orgId })
    expect(spec).not.toBeNull()
  })

  test.each(badResponseCodes)('%s status', async () => {
    await deployComponentBuild({ buildId, installId, orgId }).catch((err) =>
      expect(err).toMatchSnapshot()
    )
  })
})

describe('getInstallDeployPlan should handle response status codes from GET installs/:id/deploys/:id/plan endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  const deployId = 'test-id'
  test('200 status', async () => {
    const spec = await getInstallDeployPlan({
      deployId,
      installId,
      orgId,
    })
    expect(spec).toHaveProperty('actual')
  })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstallDeployPlan({
      deployId,
      installId,
      orgId,
    }).catch((err) => expect(err).toMatchSnapshot())
  })
})

describe('getInstallCurrentInputs should handle response status codes from GET installs/:id/inputs/current endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  test('200 status', async () => {
    const spec = await getInstallCurrentInputs({
      installId,
      orgId,
    })
    expect(spec).toHaveProperty('redacted_values')
  })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstallCurrentInputs({
      installId,
      orgId,
    }).catch((err) => expect(err).toMatchSnapshot())
  })
})

describe('getInstallComponentOutputs should handle response status codes from GET installs/:id/components/:id/outputs endpoint', () => {
  const orgId = 'test-id'
  const installId = 'test-id'
  const componentId = 'test-id'
  test('200 status', async () => {
    const spec = await getInstallComponentOutputs({
      componentId,
      installId,
      orgId,
    })
    expect(spec).not.toBeUndefined()
  })

  test.each(badResponseCodes)('%s status', async () => {
    await getInstallComponentOutputs({
      componentId,
      installId,
      orgId,
    }).catch((err) => expect(err).toMatchSnapshot())
  })
})

describe('createInstall should handle response status codes from POST apps/:id/installs endpoint', () => {
  const orgId = 'test-id'
  const appId = 'test-id'
  const data = {
    name: 'test',
    aws_account: {
      iam_role_arn: 'role',
      region: 'us-east-1',
    },
  }
  test('200 status', async () => {
    const spec = await createInstall({
      appId,
      orgId,
      data,
    })
    expect(spec).toHaveProperty('name')
  })

  test.each(badResponseCodes)('%s status', async () => {
    await createInstall({
      appId,
      orgId,
      data,
    }).catch((err) => expect(err).toMatchSnapshot())
  })
})
