#!/bin/sh

set -e
set -o pipefail
set -u

app_id=$(cat $TF_OUTPUTS_PATH | jq -r .app.id)
app_name=$(cat $TF_OUTPUTS_PATH | jq -r .app.name)

echo >&2 "getting app $app_id ..."
nuon -j apps get -a $app_id

echo >&2 "getting app by name ..."
nuon -j apps get -a $app_name

echo >&2 "getting app input config ..."
nuon -j apps input-config -a $app_id

echo >&2 "sandbox-config ..."
nuon -j apps sandbox-config -a $app_id

echo >&2 "set app ..."
nuon -j apps set-current -a $app_id

echo >&2 "get app after setting app..."
nuon -j apps get
