#!/bin/sh

set -e
set -o pipefail
set -u

echo >&2 "testing get components..."

cat $TF_OUTPUTS_PATH | jq -r '.component_ids[]' | while read -r component_id ; do
  echo >&2 "getting component $component_id..."
  nuon -j components get -c $component_id
done
