#!/bin/bash

set -euo pipefail

component_id=$(cat $TF_OUTPUTS_PATH | jq -r '.component_ids[0]')
component_name="e2e_external_image"

echo >&2 -e "testing nuon components command\n"

echo >&2 -e "nuon components list\n"
nuon -j components list
echo -e "\n"

echo >&2 -e "nuon components get -c $component_id\n"
nuon -j components get -c $component_id
echo -e "\n"

echo >&2 -e "nuon components get -c $component_name\n"
nuon -j components get -c $component_name
echo -e "\n"

echo >&2 -e "nuon components latest-config -c $component_id\n"
nuon -j components latest-config -c $component_id
echo -e "\n"

echo >&2 -e "[SKIP] [SANDBOX=true] nuon components delete -c $component_id\n"
# if [[ "$SANDBOX" == "false" ]]; then
#   echo >&2 "skipping components delete outside of sandbox mode"
# else  
#   nuon -j components delete -c "e2e_docker_build"  
# fi
