#!/bin/bash

set -euo pipefail

echo >&2 -e "pinning app"
app_id=$(cat $TF_OUTPUTS_PATH | jq -r .app.id)
nuon apps select --app $app_id

component_name="e2e_external_image"
build_id=$(nuon builds list -j -c $component_name | jq -r .[0].id)

echo >&2 -e "testing nuon releases command with existing builds\n"

echo >&2 -e "nuon releases create -c $component_name --latest-build\n"
nuon -j releases create -c $component_name --latest-build
echo -e "\n"

echo >&2 -e "nuon releases create -c $component_name --build-id=$build_id\n"
nuon -j releases create -c $component_name --build-id=$build_id
echo -e "\n"

echo >&2 -e "nuon releases list -c $component_name\n"
nuon -j releases list -c $component_name
echo -e "\n"

echo >&2 -e "nuon releases list -a $app_id\n"
nuon -j releases list -a $app_id
echo -e "\n"

echo >&2 -e "nuon releases get -r {release-id}\n"
release_id=$(nuon -j releases ls -c $component_name | jq -r .[0].id)
nuon -j releases get -r $release_id
echo -e "\n"

echo >&2 -e "nuon releases steps -r {release-id}\n"
release_id=$(nuon -j releases ls -c $component_name | jq -r .[0].id)
nuon -j releases steps -r $release_id
echo -e "\n"

component_name=e2e_infra
echo >&2 -e "switched to different component $component_name\n"
echo >&2 -e "nuon releases create --auto-build -c $component_name\n"
nuon -j releases create --auto-build -c $component_name

echo >&2 -e "polling until build is finished\n"
building=true
while [ $building = true ]
do
  build_status=$(nuon -j builds ls -c $component_name | jq -r .[0].status)
  echo $build_status
  if [[ $build_status == "active" ]]; then
    echo >&2 -e "build is active\n"
    building=false
  fi

  echo >&2 -e "waiting for build status to be active\n"
  sleep 1
done
