#!/bin/sh

set -e
set -o pipefail
set -u

echo >&2 "testing building components..."

cat $TF_OUTPUTS_PATH | jq -r '.component_ids[]' | while read -r component_id ; do
  echo >&2 "building component $component_id..."
  nuon builds -j create -c $component_id
done
