#!/bin/bash

set -euo pipefail

APP_NAME="sources"

echo >&2 "creating app $APP_NAME"
nuon apps create --no-template --name=$APP_NAME

echo >&2 "changing into test/configs dir"
cd $TEST_DIR/configs

echo >&2 "validating app configuration"
nuon apps validate -c nuon.$APP_NAME.toml

echo >&2 "syncing app configuration"
nuon apps sync -c nuon.$APP_NAME.toml
