#!/bin/sh

set -e
set -o pipefail
set -u

echo >&2 "testing releasing components..."

cat $TF_OUTPUTS_PATH | jq -r '.component_ids[]' | while read -r component_id ; do
  echo >&2 "releasing component $component_id..."
  nuon -j releases create -c $component_id
done
