#!/bin/sh

set -e
set -o pipefail
set -u

echo >&2 "listing builds..."

cat $TF_OUTPUTS_PATH | jq -r '.component_ids[]' | while read -r component_id ; do
  echo >&2 "listing builds $component_id..."
  nuon builds list -c $component_id
done
