FROM golang:1.24

FROM golang:1.24

ARG GOLANGCI_LINT_VERSION=v1.55.2

ENV CGO_ENABLED=0
ENV GOCACHE=/go-cache
ENV GOMODCACHE=/go-mod-cache
ENV CGO_ENABLED=0
ENV GOPRIVATE=github.com/powertoolsdev/*

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
  | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

RUN apt-get update && \
  apt-get install -y ca-certificates \
    coreutils \
    make \
    git \
    curl \
    protobuf-compiler \
    jq
