package services

import (
	"context"

	"github.com/powertoolsdev/mono/pkg/shortid/domains"
	"github.com/powertoolsdev/mono/services/api/internal/models"
	"github.com/powertoolsdev/mono/services/api/internal/repos"
	"github.com/powertoolsdev/mono/services/api/internal/utils"
	tclient "go.temporal.io/sdk/client"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

//go:generate -command mockgen go run github.com/golang/mock/mockgen
//go:generate mockgen -destination=mock_install_service.go -source=install_service.go -package=services
type InstallService interface {
	DeleteInstall(context.Context, string) (bool, error)
	GetInstall(context.Context, string) (*models.Install, error)
	GetAppInstalls(context.Context, string, *models.ConnectionOptions) ([]*models.Install, *utils.Page, error)
	UpsertInstall(context.Context, models.InstallInput) (*models.Install, error)
}

var _ InstallService = (*installService)(nil)

type installService struct {
	adminRepo repos.AdminRepo
	appRepo   repos.AppRepo
	log       *zap.Logger
	repo      repos.InstallRepo
}

func NewInstallService(db *gorm.DB, temporalClient tclient.Client, log *zap.Logger) *installService {
	return &installService{
		adminRepo: repos.NewAdminRepo(db),
		appRepo:   repos.NewAppRepo(db),
		log:       log,
		repo:      repos.NewInstallRepo(db),
	}
}

func (i *installService) DeleteInstall(ctx context.Context, installID string) (bool, error) {
	success, err := i.repo.Delete(ctx, installID)
	if err != nil {
		i.log.Error("failed to delete install",
			zap.String("installID", installID),
			zap.String("error", err.Error()))
		return false, err
	}

	return success, nil
}

func (i *installService) GetInstall(ctx context.Context, installID string) (*models.Install, error) {
	install, err := i.repo.Get(ctx, installID)
	if err != nil {
		i.log.Error("failed to retrieve install",
			zap.String("installID", installID),
			zap.String("error", err.Error()))
		return nil, err
	}

	return install, nil
}

func (i *installService) GetAppInstalls(ctx context.Context, appID string, options *models.ConnectionOptions) ([]*models.Install, *utils.Page, error) {
	installs, pg, err := i.repo.ListByApp(ctx, appID, options)
	if err != nil {
		i.log.Error("failed to retrieve app's installs",
			zap.String("appID", appID),
			zap.Any("options", *options),
			zap.String("error", err.Error()))
		return nil, nil, err
	}

	return installs, pg, nil
}

func (i *installService) updateInstall(ctx context.Context, input models.InstallInput) (*models.Install, error) {
	install, err := i.GetInstall(ctx, *input.ID)
	if err != nil {
		i.log.Error("failed to retrieve install",
			zap.String("installID", *input.ID),
			zap.String("error", err.Error()))
		return nil, err
	}

	// NOTE: we do not support changing region or account ID on an install
	install.Name = input.Name
	if input.AwsSettings != nil && install.AWSSettings == nil {
		install.AWSSettings = &models.AWSSettings{
			Region: input.AwsSettings.Region,
			// TODO: support accepting cloud account ids from inputs
			AccountID: "548377525120",
		}
		install.Settings = install.AWSSettings
	}

	updatedInstall, err := i.repo.Update(ctx, install)
	if err != nil {
		i.log.Error("failed to update install",
			zap.Any("install", install),
			zap.String("error", err.Error()))
		return nil, err
	}

	return updatedInstall, nil
}

func (i *installService) UpsertInstall(ctx context.Context, input models.InstallInput) (*models.Install, error) {
	if input.ID != nil {
		return i.updateInstall(ctx, input)
	}

	var install models.Install
	install.ID = domains.NewInstallID()
	if input.OverrideID != nil {
		install.ID = *input.OverrideID
	}

	install.Name = input.Name
	install.AppID = input.AppID
	install.CreatedByID = *input.CreatedByID
	install.Domain = models.Domain{
		// NOTE: this will need to be passed onto the app install job to set up the root domain once it's
		// created
		Domain:        "nuon.run",
		AutoGenerated: true,
	}
	install.Domain.ID = domains.NewDomainID()
	if input.AwsSettings != nil {
		install.AWSSettings = &models.AWSSettings{
			Region: input.AwsSettings.Region,
			// TODO: support accepting cloud account ids from inputs
			AccountID:  "548377525120",
			IamRoleArn: input.AwsSettings.IamRoleArn,
		}
		install.AWSSettings.ID = domains.NewAWSSettingsID()
		install.Settings = install.AWSSettings
	}

	savedInstall, err := i.repo.Create(ctx, &install)
	if err != nil {
		i.log.Error("failed to create install",
			zap.Any("install", install),
			zap.String("error", err.Error()))
		return nil, err
	}

	return savedInstall, nil
}
