//  THIS FILE IS GENERATED. DO NOT EDIT.
//  Generated by temporal-gen-v2

package activities

import (
	"context"
	"time"

	"go.temporal.io/sdk/workflow"
)

type SyncCustomAppConfigRequest struct {
	OnboardingID string `validate:"required"`
}

// SyncCustomAppConfig is a wrapper for the syncCustomAppConfig activity
func (a *Activities) SyncCustomAppConfig(ctx context.Context, req SyncCustomAppConfigRequest) (*SyncCustomAppConfigOutput, error) {
	return a.syncCustomAppConfig(ctx, req.OnboardingID)
}

// AwaitSyncCustomAppConfig is a wrapper for the SyncCustomAppConfig activity
func AwaitSyncCustomAppConfig(ctx workflow.Context, input SyncCustomAppConfigRequest, opts ...*workflow.ActivityOptions) (*SyncCustomAppConfigOutput, error) {
	var result *SyncCustomAppConfigOutput
	options := workflow.GetActivityOptions(ctx)
	options.StartToCloseTimeout = time.Duration(300000000000)

	for _, opt := range opts {
		if opt != nil {
			if opt.TaskQueue != "" {
				options.TaskQueue = opt.TaskQueue
			}
			if opt.ScheduleToCloseTimeout != 0 {
				options.ScheduleToCloseTimeout = opt.ScheduleToCloseTimeout
			}
			if opt.StartToCloseTimeout != 0 {
				options.StartToCloseTimeout = opt.StartToCloseTimeout
			}
			if opt.ScheduleToStartTimeout != 0 {
				options.ScheduleToStartTimeout = opt.ScheduleToStartTimeout
			}
			if opt.HeartbeatTimeout != 0 {
				options.HeartbeatTimeout = opt.HeartbeatTimeout
			}
			if opt.WaitForCancellation {
				options.WaitForCancellation = opt.WaitForCancellation
			}
			if opt.ActivityID != "" {
				options.ActivityID = opt.ActivityID
			}
			if opt.RetryPolicy != nil {
				options.RetryPolicy = opt.RetryPolicy
			}
			if opt.DisableEagerExecution {
				options.DisableEagerExecution = opt.DisableEagerExecution
			}
		}
	}

	ctx = workflow.WithActivityOptions(ctx, options)
	err := workflow.ExecuteActivity(ctx, (*Activities).SyncCustomAppConfig, input).Get(ctx, &result)
	return result, err
}
