---
region: us-west-2
pool: nuon
image_tag: "24.3.7"
data_volume_storage: 1Gi

logLevel: information

hosts: 1 # min number of hosts to deploy to
replicas: 2
shards: 1
keeperReplicaCount: 3

# zones controls where the ch NodePool will stand up new nodes
availability_zones: ["us-west-2c"]

# tables we want to backup
tables:
 - ctl_api.otel_log_records
 # - ctl_api.otel_metrics_exponential_histogram
 # - ctl_api.otel_metrics_gauge
 # - ctl_api.otel_metrics_histogram
 # - ctl_api.otel_metrics_sum
 # - ctl_api.otel_traces
 - ctl_api.runner_heart_beats
 - ctl_api.runner_health_checks

expireAfter: 2160h
