---
account: prod
env: prod
data_volume_storage: 100Gi

logLevel: warning

hosts: 3
replicas: 3
shards: 3

# zones controls where the ch NodePool will stand up new nodes
availability_zones: ["us-west-2c"] # based on ctl-api prod db location
