---
account: prod
env: prod
data_volume_storage: 200Gi

logLevel: warning

replicas: 2
shards: 1
keeperReplicaCount: 3

# zones controls where the ch NodePool will stand up new nodes
# in prod: we want these distributed across all three zones
# yes, we will take a performance hit but we'll eat it in exchange
# for reduced risk.
availability_zones: [
  "us-west-2a",
  "us-west-2b",
  "us-west-2c",
]
