---
account: stage
env: stage
data_volume_storage: 50Gi

logLevel: warning

replicas: 2
shards: 1
keeperReplicaCount: 3

# zones controls where the ch NodePool will stand up new nodes
availability_zones: [
  "us-west-2a",
  "us-west-2b",
]

expiresAfter: 1h
