---
version: "2"
linters:
  default: none
  exclusions:
    generated: lax
    paths:
      - exp/
  enable:
    - dogsled
    - funlen
    - gochecknoinits
    - gocyclo
    - goprintffuncname
    - govet
    - ineffassign
    - nakedret
    - nolintlint
    - staticcheck
    - whitespace
    # - bodyclose
    # - goconst
    # - noctx
    # - unconvert
    # - unparam
    # - unused
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    gocyclo:
      min-complexity: 15
    # gomnd:
    #   settings:
    #     mnd:
    #       # don't include the "operation" and "assign"
    #       checks: argument,case,condition,return
    #       ignored-numbers: 0,1,2,3
    #       ignored-functions: strings.SplitN
    govet:
      # https://golangci-lint.run/usage/linters/#govet
      enable:
        - shadow
    lll:
      line-length: 140
    misspell:
      locale: US
    nolintlint:
      # https://golangci-lint.run/usage/linters/#nolintlint
      allow-unused: false
      require-explanation: false
      require-specific: false

formatters:
  enable:
    - gofmt
    - goimports
    - golines
  exclusions:
    generated: lax
run:
  timeout: 5m
  go: "1.24"
