apiVersion: v1
kind: Service
metadata:
  name: workers-executors-profiler
  namespace: workers-executors
spec:
  selector:
    app.kubernetes.io/instance: workers-executors-stage
    app.kubernetes.io/name: workers-executors
  ports:
  - name: profiling
    protocol: TCP
    port: 6060
    targetPort: 6060
  type: ClusterIP
