---
name: action-reviewdog
description: |
  Runs Nuon standard linters via reviewdog
author: "@powertoolsdev/team"
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  run_all:
    description: Whether to run all linters or to stop on first failure
    default: 'true'
  terraform:
    description: |
      Whether to run terraform checks
      `terraform init` must be called before invoking this action
    default: 'true'
  terraform_dir:
    description: |
      The terraform directory
      required if `terraform: 'true'`
    default: infra
  terraform_workspace:
    description: |
      The terraform directory
      required if `terraform: 'true'`
    default: default
  hadolint:
    description: |
      Whether to run hadolint
      Only applicable for repos with Dockerfile(s)
    default: 'false'
  node:
    description: |
      Whether to run `npm run lint`
      Only applicable for repos with package.json
    default: 'false'
  go:
    description: |
      Whether to run go linting checks
      Only applicable for repos with .golangci.yml
    default: 'false'

runs:
  using: 'composite'
  steps:
    - uses: reviewdog/action-setup@v1

    # use github-pr-check for PRs
    - if: github.event_name == 'pull_request'
      shell: bash
      run: echo "REVIEWDOG_REPORTER=github-pr-check" >> "$GITHUB_ENV"

    # use github-check otherwise
    - if: github.event_name != 'pull_request'
      shell: bash
      run: echo "REVIEWDOG_REPORTER=github-check" >> "$GITHUB_ENV"

    # actions
    - if: (success() || inputs.run_all == 'true')
      uses: reviewdog/action-actionlint@v1
      with:
        github_token: ${{ inputs.github_token }}
        reporter: ${{ env.REVIEWDOG_REPORTER }}
        fail_on_error: true
        level: error
        filter_mode: nofilter

    # yaml
    - if: (success() || inputs.run_all == 'true')
      uses: reviewdog/action-yamllint@v1
      with:
        github_token: ${{ inputs.github_token }}
        reporter: ${{ env.REVIEWDOG_REPORTER }}
        fail_on_error: true
        level: error
        filter_mode: nofilter

    # shellcheck
    - if: (success() || inputs.run_all == 'true')
      uses: reviewdog/action-shellcheck@v1
      with:
        github_token: ${{ inputs.github_token }}
        reporter: ${{ env.REVIEWDOG_REPORTER }}
        fail_on_error: true
        level: error
        filter_mode: nofilter
        exclude: |
          */.terraform/*
          */node_modules/*

    # terraform
    - if: (success() || inputs.run_all == 'true') && inputs.terraform == 'true'
      uses: reviewdog/action-tflint@v1
      with:
        github_token: ${{ inputs.github_token }}
        reporter: ${{ env.REVIEWDOG_REPORTER }}
        fail_on_error: true
        level: error
        working_directory: ${{ inputs.terraform_dir}}
        flags: --format=checkstyle --color
        filter_mode: nofilter

    # on PR, actually format. if there are changes, suggest them in the PR
    - if: (success() || inputs.run_all == 'true') && inputs.terraform == 'true' && github.event_name == 'pull_request'
      working-directory: ${{ inputs.terraform_dir }}
      shell: bash
      run: |
        terraform fmt -recursive

    - if: (success() || inputs.run_all == 'true') && inputs.terraform == 'true' && github.event_name == 'pull_request'
      uses: reviewdog/action-suggester@v1
      with:
        github_token: ${{ inputs.github_token }}
        fail_on_error: true
        tool_name: terraform fmt
        filter_mode: nofilter

    # outside PR, just check
    - if: (success() || inputs.run_all == 'true') && inputs.terraform == 'true' && github.event_name != 'pull_request'
      working-directory: ${{ inputs.terraform_dir }}
      shell: bash
      run: |
        terraform fmt -check -recursive

    - if: (success() || inputs.run_all == 'true') && inputs.terraform == 'true'
      working-directory: ${{ inputs.terraform_dir }}
      shell: bash
      env:
        TF_WORKSPACE: ${{ inputs.terraform_workspace }}
      run: |
        terraform validate

    - if: (success() || inputs.run_all == 'true') && inputs.hadolint == 'true'
      uses: reviewdog/action-hadolint@v1
      with:
        github_token: ${{ inputs.github_token }}
        reporter: ${{ env.REVIEWDOG_REPORTER }}
        fail_on_error: true
        level: error
        filter_mode: nofilter

    # node
    - if: (success() || inputs.run_all == 'true') && inputs.node == 'true'
      shell: bash
      run: npm run lint

    # golang
    - if: (success() || inputs.run_all == 'true') && inputs.go == 'true'
      uses: reviewdog/action-golangci-lint@v2
      with:
        github_token: ${{ inputs.github_token }}
        reporter: ${{ env.REVIEWDOG_REPORTER }}
        fail_on_error: true
        level: warning  # don't think we can make this error yet
        filter_mode: nofilter

branding:
  icon: 'check'
  color: 'blue'
