// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: shared/v1/response.proto

package sharedv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	v12 "github.com/powertoolsdev/mono/pkg/types/workflows/apps/v1"
	v1 "github.com/powertoolsdev/mono/pkg/types/workflows/installs/v1"
	v11 "github.com/powertoolsdev/mono/pkg/types/workflows/orgs/v1"
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseStatus int32

const (
	ResponseStatus_RESPONSE_STATUS_UNSPECIFIED ResponseStatus = 0
	ResponseStatus_RESPONSE_STATUS_OK          ResponseStatus = 1
	ResponseStatus_RESPONSE_STATUS_ERROR       ResponseStatus = 2
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0: "RESPONSE_STATUS_UNSPECIFIED",
		1: "RESPONSE_STATUS_OK",
		2: "RESPONSE_STATUS_ERROR",
	}
	ResponseStatus_value = map[string]int32{
		"RESPONSE_STATUS_UNSPECIFIED": 0,
		"RESPONSE_STATUS_OK":          1,
		"RESPONSE_STATUS_ERROR":       2,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_v1_response_proto_enumTypes[0].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_shared_v1_response_proto_enumTypes[0]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_v1_response_proto_rawDescGZIP(), []int{0}
}

// FinishActivityRequest is used by clients to implement a finish activity
type FinishActivityRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	MetadataBucket              string                 `protobuf:"bytes,1,opt,name=metadata_bucket,json=metadataBucket,proto3" json:"metadata_bucket,omitempty"`
	MetadataBucketAssumeRoleArn string                 `protobuf:"bytes,2,opt,name=metadata_bucket_assume_role_arn,json=metadataBucketAssumeRoleArn,proto3" json:"metadata_bucket_assume_role_arn,omitempty"`
	MetadataBucketPrefix        string                 `protobuf:"bytes,3,opt,name=metadata_bucket_prefix,json=metadataBucketPrefix,proto3" json:"metadata_bucket_prefix,omitempty"`
	ResponseRef                 *ResponseRef           `protobuf:"bytes,4,opt,name=response_ref,json=responseRef,proto3" json:"response_ref,omitempty" faker:"-"`
	Status                      ResponseStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=shared.v1.ResponseStatus" json:"status,omitempty"`
	ErrorMessage                string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Other                       *anypb.Any             `protobuf:"bytes,7,opt,name=other,proto3" json:"other,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *FinishActivityRequest) Reset() {
	*x = FinishActivityRequest{}
	mi := &file_shared_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishActivityRequest) ProtoMessage() {}

func (x *FinishActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishActivityRequest.ProtoReflect.Descriptor instead.
func (*FinishActivityRequest) Descriptor() ([]byte, []int) {
	return file_shared_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *FinishActivityRequest) GetMetadataBucket() string {
	if x != nil {
		return x.MetadataBucket
	}
	return ""
}

func (x *FinishActivityRequest) GetMetadataBucketAssumeRoleArn() string {
	if x != nil {
		return x.MetadataBucketAssumeRoleArn
	}
	return ""
}

func (x *FinishActivityRequest) GetMetadataBucketPrefix() string {
	if x != nil {
		return x.MetadataBucketPrefix
	}
	return ""
}

func (x *FinishActivityRequest) GetResponseRef() *ResponseRef {
	if x != nil {
		return x.ResponseRef
	}
	return nil
}

func (x *FinishActivityRequest) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_RESPONSE_STATUS_UNSPECIFIED
}

func (x *FinishActivityRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FinishActivityRequest) GetOther() *anypb.Any {
	if x != nil {
		return x.Other
	}
	return nil
}

type FinishActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishActivityResponse) Reset() {
	*x = FinishActivityResponse{}
	mi := &file_shared_v1_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishActivityResponse) ProtoMessage() {}

func (x *FinishActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishActivityResponse.ProtoReflect.Descriptor instead.
func (*FinishActivityResponse) Descriptor() ([]byte, []int) {
	return file_shared_v1_response_proto_rawDescGZIP(), []int{1}
}

// Response represents a workflow execution
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ResponseStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=shared.v1.ResponseStatus" json:"status,omitempty"`
	Response      *ResponseRef           `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty" faker:"-"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_shared_v1_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_shared_v1_response_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_RESPONSE_STATUS_UNSPECIFIED
}

func (x *Response) GetResponse() *ResponseRef {
	if x != nil {
		return x.Response
	}
	return nil
}

// ResponseRef represents the request that was passed in
type ResponseRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ResponseRef_InstallProvision
	//	*ResponseRef_InstallDeprovision
	//	*ResponseRef_OrgSignup
	//	*ResponseRef_OrgTeardown
	//	*ResponseRef_AppsProvision
	Response      isResponseRef_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseRef) Reset() {
	*x = ResponseRef{}
	mi := &file_shared_v1_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRef) ProtoMessage() {}

func (x *ResponseRef) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRef.ProtoReflect.Descriptor instead.
func (*ResponseRef) Descriptor() ([]byte, []int) {
	return file_shared_v1_response_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseRef) GetResponse() isResponseRef_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ResponseRef) GetInstallProvision() *v1.ProvisionResponse {
	if x != nil {
		if x, ok := x.Response.(*ResponseRef_InstallProvision); ok {
			return x.InstallProvision
		}
	}
	return nil
}

func (x *ResponseRef) GetInstallDeprovision() *v1.DeprovisionResponse {
	if x != nil {
		if x, ok := x.Response.(*ResponseRef_InstallDeprovision); ok {
			return x.InstallDeprovision
		}
	}
	return nil
}

func (x *ResponseRef) GetOrgSignup() *v11.ProvisionResponse {
	if x != nil {
		if x, ok := x.Response.(*ResponseRef_OrgSignup); ok {
			return x.OrgSignup
		}
	}
	return nil
}

func (x *ResponseRef) GetOrgTeardown() *v11.DeprovisionResponse {
	if x != nil {
		if x, ok := x.Response.(*ResponseRef_OrgTeardown); ok {
			return x.OrgTeardown
		}
	}
	return nil
}

func (x *ResponseRef) GetAppsProvision() *v12.ProvisionResponse {
	if x != nil {
		if x, ok := x.Response.(*ResponseRef_AppsProvision); ok {
			return x.AppsProvision
		}
	}
	return nil
}

type isResponseRef_Response interface {
	isResponseRef_Response()
}

type ResponseRef_InstallProvision struct {
	InstallProvision *v1.ProvisionResponse `protobuf:"bytes,2,opt,name=install_provision,json=installProvision,proto3,oneof"`
}

type ResponseRef_InstallDeprovision struct {
	InstallDeprovision *v1.DeprovisionResponse `protobuf:"bytes,3,opt,name=install_deprovision,json=installDeprovision,proto3,oneof"`
}

type ResponseRef_OrgSignup struct {
	OrgSignup *v11.ProvisionResponse `protobuf:"bytes,4,opt,name=org_signup,json=orgSignup,proto3,oneof"`
}

type ResponseRef_OrgTeardown struct {
	OrgTeardown *v11.DeprovisionResponse `protobuf:"bytes,5,opt,name=org_teardown,json=orgTeardown,proto3,oneof"`
}

type ResponseRef_AppsProvision struct {
	AppsProvision *v12.ProvisionResponse `protobuf:"bytes,7,opt,name=apps_provision,json=appsProvision,proto3,oneof"`
}

func (*ResponseRef_InstallProvision) isResponseRef_Response() {}

func (*ResponseRef_InstallDeprovision) isResponseRef_Response() {}

func (*ResponseRef_OrgSignup) isResponseRef_Response() {}

func (*ResponseRef_OrgTeardown) isResponseRef_Response() {}

func (*ResponseRef_AppsProvision) isResponseRef_Response() {}

var File_shared_v1_response_proto protoreflect.FileDescriptor

const file_shared_v1_response_proto_rawDesc = "" +
	"\n" +
	"\x18shared/v1/response.proto\x12\tshared.v1\x1a\x17apps/v1/provision.proto\x1a\x19google/protobuf/any.proto\x1a\x1dinstalls/v1/deprovision.proto\x1a\x1binstalls/v1/provision.proto\x1a\x19orgs/v1/deprovision.proto\x1a\x17orgs/v1/provision.proto\x1a\x13tagger/tagger.proto\x1a\x17validate/validate.proto\"\xa6\x03\n" +
	"\x15FinishActivityRequest\x120\n" +
	"\x0fmetadata_bucket\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x05R\x0emetadataBucket\x12M\n" +
	"\x1fmetadata_bucket_assume_role_arn\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x05R\x1bmetadataBucketAssumeRoleArn\x12=\n" +
	"\x16metadata_bucket_prefix\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x05R\x14metadataBucketPrefix\x12I\n" +
	"\fresponse_ref\x18\x04 \x01(\v2\x16.shared.v1.ResponseRefB\x0e\x9a\x84\x9e\x03\tfaker:\"-\"R\vresponseRef\x121\n" +
	"\x06status\x18\x05 \x01(\x0e2\x19.shared.v1.ResponseStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12*\n" +
	"\x05other\x18\a \x01(\v2\x14.google.protobuf.AnyR\x05other\"\x18\n" +
	"\x16FinishActivityResponse\"\x81\x01\n" +
	"\bResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.shared.v1.ResponseStatusR\x06status\x12B\n" +
	"\bresponse\x18\x02 \x01(\v2\x16.shared.v1.ResponseRefB\x0e\x9a\x84\x9e\x03\tfaker:\"-\"R\bresponse\"\x82\x03\n" +
	"\vResponseRef\x12M\n" +
	"\x11install_provision\x18\x02 \x01(\v2\x1e.installs.v1.ProvisionResponseH\x00R\x10installProvision\x12S\n" +
	"\x13install_deprovision\x18\x03 \x01(\v2 .installs.v1.DeprovisionResponseH\x00R\x12installDeprovision\x12;\n" +
	"\n" +
	"org_signup\x18\x04 \x01(\v2\x1a.orgs.v1.ProvisionResponseH\x00R\torgSignup\x12A\n" +
	"\forg_teardown\x18\x05 \x01(\v2\x1c.orgs.v1.DeprovisionResponseH\x00R\vorgTeardown\x12C\n" +
	"\x0eapps_provision\x18\a \x01(\v2\x1a.apps.v1.ProvisionResponseH\x00R\rappsProvisionB\n" +
	"\n" +
	"\bresponse*d\n" +
	"\x0eResponseStatus\x12\x1f\n" +
	"\x1bRESPONSE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RESPONSE_STATUS_OK\x10\x01\x12\x19\n" +
	"\x15RESPONSE_STATUS_ERROR\x10\x02B\xa9\x01\n" +
	"\rcom.shared.v1B\rResponseProtoP\x01ZDgithub.com/powertoolsdev/mono/pkg/types/workflows/shared/v1;sharedv1\xa2\x02\x03SXX\xaa\x02\tShared.V1\xca\x02\tShared\\V1\xe2\x02\x15Shared\\V1\\GPBMetadata\xea\x02\n" +
	"Shared::V1b\x06proto3"

var (
	file_shared_v1_response_proto_rawDescOnce sync.Once
	file_shared_v1_response_proto_rawDescData []byte
)

func file_shared_v1_response_proto_rawDescGZIP() []byte {
	file_shared_v1_response_proto_rawDescOnce.Do(func() {
		file_shared_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_v1_response_proto_rawDesc), len(file_shared_v1_response_proto_rawDesc)))
	})
	return file_shared_v1_response_proto_rawDescData
}

var file_shared_v1_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shared_v1_response_proto_goTypes = []any{
	(ResponseStatus)(0),             // 0: shared.v1.ResponseStatus
	(*FinishActivityRequest)(nil),   // 1: shared.v1.FinishActivityRequest
	(*FinishActivityResponse)(nil),  // 2: shared.v1.FinishActivityResponse
	(*Response)(nil),                // 3: shared.v1.Response
	(*ResponseRef)(nil),             // 4: shared.v1.ResponseRef
	(*anypb.Any)(nil),               // 5: google.protobuf.Any
	(*v1.ProvisionResponse)(nil),    // 6: installs.v1.ProvisionResponse
	(*v1.DeprovisionResponse)(nil),  // 7: installs.v1.DeprovisionResponse
	(*v11.ProvisionResponse)(nil),   // 8: orgs.v1.ProvisionResponse
	(*v11.DeprovisionResponse)(nil), // 9: orgs.v1.DeprovisionResponse
	(*v12.ProvisionResponse)(nil),   // 10: apps.v1.ProvisionResponse
}
var file_shared_v1_response_proto_depIdxs = []int32{
	4,  // 0: shared.v1.FinishActivityRequest.response_ref:type_name -> shared.v1.ResponseRef
	0,  // 1: shared.v1.FinishActivityRequest.status:type_name -> shared.v1.ResponseStatus
	5,  // 2: shared.v1.FinishActivityRequest.other:type_name -> google.protobuf.Any
	0,  // 3: shared.v1.Response.status:type_name -> shared.v1.ResponseStatus
	4,  // 4: shared.v1.Response.response:type_name -> shared.v1.ResponseRef
	6,  // 5: shared.v1.ResponseRef.install_provision:type_name -> installs.v1.ProvisionResponse
	7,  // 6: shared.v1.ResponseRef.install_deprovision:type_name -> installs.v1.DeprovisionResponse
	8,  // 7: shared.v1.ResponseRef.org_signup:type_name -> orgs.v1.ProvisionResponse
	9,  // 8: shared.v1.ResponseRef.org_teardown:type_name -> orgs.v1.DeprovisionResponse
	10, // 9: shared.v1.ResponseRef.apps_provision:type_name -> apps.v1.ProvisionResponse
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_shared_v1_response_proto_init() }
func file_shared_v1_response_proto_init() {
	if File_shared_v1_response_proto != nil {
		return
	}
	file_shared_v1_response_proto_msgTypes[3].OneofWrappers = []any{
		(*ResponseRef_InstallProvision)(nil),
		(*ResponseRef_InstallDeprovision)(nil),
		(*ResponseRef_OrgSignup)(nil),
		(*ResponseRef_OrgTeardown)(nil),
		(*ResponseRef_AppsProvision)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_v1_response_proto_rawDesc), len(file_shared_v1_response_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_v1_response_proto_goTypes,
		DependencyIndexes: file_shared_v1_response_proto_depIdxs,
		EnumInfos:         file_shared_v1_response_proto_enumTypes,
		MessageInfos:      file_shared_v1_response_proto_msgTypes,
	}.Build()
	File_shared_v1_response_proto = out.File
	file_shared_v1_response_proto_goTypes = nil
	file_shared_v1_response_proto_depIdxs = nil
}
