---
apps:
  - name: electric_sql
    installs:
      - Pepsi
      - Coca Cola
    installer:
      slug: electric-sql
      description: Build reactive, realtime, local-first apps directly on Postgres.
      name: Electric SQL
    urls:
      documentation: https://electric-sql.com/docs
      logo: https://electric-sql.com/assets/files/logo@2x-0ee9333aea8b7813fcc4394972cc925f.png
      github: https://github.com/electric-sql
      community: https://discord.com/invite/B7kHGwDcbj
      homepage: https://electric-sql.com/
      demo: https://www.youtube.com/embed/-8UMbnGtbKg
  - name: honeyhive
    installs:
      - Pepsi
      - Coca Cola
    installer:
      slug: honeyhive
      description: Open Source Feature Management
      name: Honeyhive
    urls:
      documentation: https://docs.honeyhive.ai/introduction
      logo: https://assets-global.website-files.com/65483e3a00a324531a626c4e/65483e3a00a324531a626c95_63f13bee638d6993e08555fb_logo2-p-500.png
      github: https://github.com
      community: https://discord.com/invite/vqctGpqA97
      homepage: https://www.honeyhive.ai/
      demo: 
