---
apps:
  - name: signoz
    installs:
      - Pepsi
      - Coca Cola
    installer:
      slug: signoz
      description: OpenTelemetry-Native Traces, Metrics, and Logs in a single pane
      name: SigNoz
    urls:
      documentation: https://signoz.io/docs
      logo: https://d33wubrfki0l68.cloudfront.net/2b655ea5a90ef409e4b73144da2536ec35bcf69f/a959a/img/signozlogo-orange.svg
      github: https://github.com/signoz/signoz
      community: https://signoz-community.slack.com/join/shared_invite/zt-2421fjjci-RO7y1FrVbkh0bnh~8oy5nA#/shared-invite/email
      homepage: https://signoz.io
      demo: https://www.youtube.com/embed/jD36hjfL1x0
  - name: temporal
    installs:
      - Pepsi
      - Coca Cola
    installer:
      slug: temporal
      description: Code for more reliable systems
      name: Temporal
    urls:
      documentation: https://docs.temporal.io/
      logo: https://cdn.icon-icons.com/icons2/3915/PNG/512/temporal_logo_icon_249430.png
      github: https://github.com/temporalio/temporal
      community: https://community.temporal.io/
      homepage: https://temporal.io/
      demo: https://www.youtube.com/embed/2HjnQlnA5eY
  - name: sourcegraph
    installs:
      - Pepsi
      - Coca Cola
    installer:
      slug: sourcegraph
      description: Code search and an AI assistant with the context of the code graph.
      name: Sourcegraph
    urls:
      documentation: https://docs.sourcegraph.com/
      logo: https://docs.sourcegraph.com/assets/sourcegraph-logo-dark.svg
      github: https://github.com/sourcegraph
      community: https://discord.com/invite/s2qDtYGnAE
      homepage: https://sourcegraph.com/
      demo: https://www.youtube.com/embed/D2x037j3BZ4
  - name: clickhouse
    installs:
      - Pepsi
      - Coca Cola
    installer:
      slug: clickhouse
      description: ClickHouse is the fastest and most resource efficient open-source database for real-time apps and analytics.
      name: ClickHouse
    urls:
      documentation:  https://clickhouse.com/docs/en/intro
      logo: https://upload.wikimedia.org/wikipedia/commons/0/0e/Clickhouse.png
      github: https://github.com/clickhouse
      community: https://clickhousedb.slack.com/join/shared_invite/zt-23y85sfck-crUbdd4RupnjOBxfFIQv5w#/shared-invite/email
      homepage:  https://clickhouse.com
      demo: https://www.youtube.com/embed/FtoWGT7kS-c
  - name: retool
    installs:
      - Pepsi
      - Coca Cola
    installer:
      slug: retool
      description: The fastest way to develop effective software.
      name: Retool
    urls:
      documentation:  https://docs.retool.com/
      logo:  https://logo.clearbit.com/retool.com?size=400
      github: https://github.com/tryretool
      community: https://community.retool.com/
      homepage: https://retool.com/
      demo: https://www.youtube.com/embed/AkcwNwPy7RI
  - name: unstructured
    installs:
      - Pepsi
      - Coca Cola
    installer:
      slug: unstructured
      description: ETL for LLMs
      name: Unstructured
    urls:
      documentation:  https://unstructured-io.github.io/unstructured/
      logo: https://unstructured-io.github.io/unstructured/_static/images/logo-dark-mode.svg
      github: https://github.com/Unstructured-IO/unstructured
      community: https://join.slack.com/t/unstructuredw-kbe4326/shared_invite/zt-23kciff0y-bvzXxJkgtbXe5POo_rxMkw
      homepage: https://unstructured.io/
      demo: https://www.youtube.com/embed/rh40FbpSiCs
