package org

import (
	"strings"
	"testing"

	"github.com/gin-gonic/gin"
)

// publicAPIRouteInventory is the full org-scoped public API route surface at
// the time coverage validation was introduced (2026-08-08). It exists so the
// classification in coverage.go is verified against the real route set even
// in unit tests; the startup assertion covers the live engine.
var publicAPIRouteInventory = []string{
	"GET /docs/*any",
	"GET /httpbin/*any",
	"GET /livez",
	"GET /oapi/v2",
	"GET /oapi/v3",
	"GET /readyz",
	"GET /version",
	"GET /v1/account",
	"POST /v1/account/static-token",
	"GET /v1/account/static-tokens",
	"DELETE /v1/account/static-tokens/:token_id",
	"GET /v1/account/user-journeys",
	"POST /v1/account/user-journeys",
	"POST /v1/account/user-journeys/:journey_name/complete",
	"POST /v1/account/user-journeys/:journey_name/reset",
	"PATCH /v1/account/user-journeys/:journey_name/steps/:step_name",
	"GET /v1/action-workflows/configs/:action_workflow_config_id",
	"GET /v1/action-workflows/:action_workflow_id",
	"PATCH /v1/action-workflows/:action_workflow_id",
	"DELETE /v1/action-workflows/:action_workflow_id",
	"POST /v1/action-workflows/:action_workflow_id/configs",
	"GET /v1/action-workflows/:action_workflow_id/configs",
	"GET /v1/action-workflows/:action_workflow_id/latest-config",
	"POST /v1/apps",
	"GET /v1/apps",
	"GET /v1/apps/:app_id",
	"PATCH /v1/apps/:app_id",
	"DELETE /v1/apps/:app_id",
	"POST /v1/apps/:app_id/action-workflows",
	"GET /v1/apps/:app_id/action-workflows",
	"GET /v1/apps/:app_id/action-workflows/:action_workflow_id",
	"POST /v1/apps/:app_id/actions",
	"GET /v1/apps/:app_id/actions",
	"GET /v1/apps/:app_id/actions/label-keys",
	"GET /v1/apps/:app_id/actions/configs/:action_config_id",
	"GET /v1/apps/:app_id/actions/:action_id",
	"PATCH /v1/apps/:app_id/actions/:action_id",
	"DELETE /v1/apps/:app_id/actions/:action_id",
	"POST /v1/apps/:app_id/actions/:action_id/configs",
	"GET /v1/apps/:app_id/actions/:action_id/configs",
	"POST /v1/apps/:app_id/actions/:action_id/labels",
	"DELETE /v1/apps/:app_id/actions/:action_id/labels",
	"GET /v1/apps/:app_id/actions/:action_id/latest-config",
	"POST /v1/apps/:app_id/branches",
	"GET /v1/apps/:app_id/branches",
	"GET /v1/apps/:app_id/branches/:app_branch_id",
	"PATCH /v1/apps/:app_id/branches/:app_branch_id",
	"DELETE /v1/apps/:app_id/branches/:app_branch_id",
	"GET /v1/apps/:app_id/branches/:app_branch_id/configs",
	"POST /v1/apps/:app_id/branches/:app_branch_id/configs",
	"GET /v1/apps/:app_id/branches/:app_branch_id/latest-config",
	"POST /v1/apps/:app_id/branches/:app_branch_id/runs",
	"GET /v1/apps/:app_id/branches/:app_branch_id/runs",
	"GET /v1/apps/:app_id/branches/:app_branch_id/runs/:run_id/builds",
	"GET /v1/apps/:app_id/branches/:app_branch_id/runs/:run_id/install-group-runs",
	"GET /v1/apps/:app_id/branches/:app_branch_id/runs/:run_id/install-group-runs/:install_group_run_id",
	"GET /v1/apps/:app_id/branches/:app_branch_id/runs/:run_id/install-groups",
	"POST /v1/apps/:app_id/branches/:app_branch_id/sync-install-configs",
	"POST /v1/apps/:app_id/break-glass-configs",
	"GET /v1/apps/:app_id/break-glass-configs/:config_id",
	"GET /v1/apps/:app_id/component/:component_name_or_id",
	"GET /v1/apps/:app_id/components",
	"POST /v1/apps/:app_id/components",
	"POST /v1/apps/:app_id/components/build-all",
	"GET /v1/apps/:app_id/components/label-keys",
	"PATCH /v1/apps/:app_id/components/:component_id",
	"DELETE /v1/apps/:app_id/components/:component_id",
	"POST /v1/apps/:app_id/components/:component_id/builds",
	"GET /v1/apps/:app_id/components/:component_id/builds",
	"GET /v1/apps/:app_id/components/:component_id/builds/latest",
	"GET /v1/apps/:app_id/components/:component_id/builds/:build_id",
	"POST /v1/apps/:app_id/components/:component_id/builds/:build_id/cancel",
	"GET /v1/apps/:app_id/components/:component_id/configs",
	"GET /v1/apps/:app_id/components/:component_id/configs/latest",
	"GET /v1/apps/:app_id/components/:component_id/configs/:config_id",
	"POST /v1/apps/:app_id/components/:component_id/configs/docker-build",
	"POST /v1/apps/:app_id/components/:component_id/configs/external-image",
	"POST /v1/apps/:app_id/components/:component_id/configs/helm",
	"POST /v1/apps/:app_id/components/:component_id/configs/job",
	"POST /v1/apps/:app_id/components/:component_id/configs/kubernetes-manifest",
	"POST /v1/apps/:app_id/components/:component_id/configs/pulumi",
	"POST /v1/apps/:app_id/components/:component_id/configs/terraform-module",
	"GET /v1/apps/:app_id/components/:component_id/dependencies",
	"GET /v1/apps/:app_id/components/:component_id/dependents",
	"POST /v1/apps/:app_id/components/:component_id/labels",
	"DELETE /v1/apps/:app_id/components/:component_id/labels",
	"POST /v1/apps/:app_id/config",
	"GET /v1/apps/:app_id/config/:app_config_id",
	"PATCH /v1/apps/:app_id/config/:app_config_id",
	"GET /v1/apps/:app_id/config/:app_config_id/graph",
	"POST /v1/apps/:app_id/config/:app_config_id/update-installs",
	"GET /v1/apps/:app_id/configs",
	"POST /v1/apps/:app_id/configs",
	"GET /v1/apps/:app_id/configs/:config_id",
	"PATCH /v1/apps/:app_id/configs/:config_id",
	"POST /v1/apps/:app_id/configs/:config_id/build",
	"GET /v1/apps/:app_id/configs/:config_id/diff",
	"GET /v1/apps/:app_id/configs/:config_id/graph",
	"POST /v1/apps/:app_id/configs/:config_id/sync",
	"POST /v1/apps/:app_id/configs/:config_id/update-installs",
	"POST /v1/apps/:app_id/input-config",
	"GET /v1/apps/:app_id/input-configs",
	"GET /v1/apps/:app_id/input-configs/:input_config_id",
	"GET /v1/apps/:app_id/input-latest-config",
	"GET /v1/apps/:app_id/installs",
	"POST /v1/apps/:app_id/installs",
	"POST /v1/apps/:app_id/kubernetes-contexts-configs",
	"GET /v1/apps/:app_id/labels",
	"GET /v1/apps/:app_id/latest-break-glass-config",
	"GET /v1/apps/:app_id/latest-config",
	"GET /v1/apps/:app_id/latest-permissions-config",
	"GET /v1/apps/:app_id/latest-policies-config",
	"GET /v1/apps/:app_id/latest-secrets-config",
	"POST /v1/apps/:app_id/operation-role-configs",
	"GET /v1/apps/:app_id/operation-role-configs/:operation_role_config_id",
	"POST /v1/apps/:app_id/permissions-configs",
	"GET /v1/apps/:app_id/permissions-configs/:config_id",
	"GET /v1/apps/:app_id/policies-configs",
	"POST /v1/apps/:app_id/policies-configs",
	"GET /v1/apps/:app_id/policies-configs/:config_id",
	"GET /v1/apps/:app_id/policy-analytics/breakdown",
	"GET /v1/apps/:app_id/policy-analytics/summary",
	"GET /v1/apps/:app_id/policy-analytics/timeseries",
	"GET /v1/apps/:app_id/policy-config/:policy_config_id",
	"POST /v1/apps/:app_id/runbooks",
	"GET /v1/apps/:app_id/runbooks",
	"GET /v1/apps/:app_id/runbooks/:runbook_id",
	"PATCH /v1/apps/:app_id/runbooks/:runbook_id",
	"DELETE /v1/apps/:app_id/runbooks/:runbook_id",
	"POST /v1/apps/:app_id/runbooks/:runbook_id/configs",
	"GET /v1/apps/:app_id/runbooks/:runbook_id/configs",
	"POST /v1/apps/:app_id/runner-configs",
	"GET /v1/apps/:app_id/runner-configs",
	"GET /v1/apps/:app_id/runner-latest-config",
	"POST /v1/apps/:app_id/sandbox-config",
	"GET /v1/apps/:app_id/sandbox-configs",
	"POST /v1/apps/:app_id/sandbox-configs",
	"GET /v1/apps/:app_id/sandbox-latest-config",
	"GET /v1/apps/:app_id/sandbox/builds",
	"POST /v1/apps/:app_id/sandbox/builds",
	"GET /v1/apps/:app_id/sandbox/builds/:build_id",
	"POST /v1/apps/:app_id/secret",
	"DELETE /v1/apps/:app_id/secret/:secret_id",
	"POST /v1/apps/:app_id/secrets",
	"GET /v1/apps/:app_id/secrets",
	"DELETE /v1/apps/:app_id/secrets/:secret_id",
	"POST /v1/apps/:app_id/secrets-configs",
	"GET /v1/apps/:app_id/secrets-configs/:config_id",
	"POST /v1/apps/:app_id/stack-configs",
	"GET /v1/apps/:app_id/stack-configs/:config_id",
	"GET /v1/apps/:app_id/template-config",
	"GET /v1/auth/me",
	"GET /v1/auth/validate",
	"POST /v1/aws-account-connections",
	"GET /v1/aws-account-connections",
	"GET /v1/aws-account-connections/:connection_id",
	"PATCH /v1/aws-account-connections/:connection_id",
	"DELETE /v1/aws-account-connections/:connection_id",
	"POST /v1/aws-account-connections/:connection_id/verify",
	"GET /v1/builds",
	"GET /v1/component-builds",
	"GET /v1/components",
	"GET /v1/components/builds/:build_id",
	"GET /v1/components/:component_id",
	"PATCH /v1/components/:component_id",
	"DELETE /v1/components/:component_id",
	"POST /v1/components/:component_id/builds",
	"GET /v1/components/:component_id/builds/latest",
	"GET /v1/components/:component_id/builds/:build_id",
	"GET /v1/components/:component_id/configs",
	"GET /v1/components/:component_id/configs/latest",
	"GET /v1/components/:component_id/configs/:config_id",
	"POST /v1/components/:component_id/configs/docker-build",
	"POST /v1/components/:component_id/configs/external-image",
	"POST /v1/components/:component_id/configs/helm",
	"POST /v1/components/:component_id/configs/job",
	"POST /v1/components/:component_id/configs/kubernetes-manifest",
	"POST /v1/components/:component_id/configs/pulumi",
	"POST /v1/components/:component_id/configs/terraform-module",
	"GET /v1/components/:component_id/dependencies",
	"GET /v1/components/:component_id/dependents",
	"POST /v1/event-ingress/:ingress_key",
	"GET /v1/general/cli-config",
	"GET /v1/general/cloud-platform/:cloud_platform/regions",
	"GET /v1/general/config-schema",
	"GET /v1/general/config-schema/:type",
	"GET /v1/general/current-user",
	"POST /v1/general/waitlist",
	"POST /v1/grants",
	"GET /v1/grants",
	"DELETE /v1/grants/:grant_id",
	"GET /v1/install-workflows/:install_workflow_id",
	"PATCH /v1/install-workflows/:install_workflow_id",
	"POST /v1/install-workflows/:install_workflow_id/cancel",
	"GET /v1/install-workflows/:install_workflow_id/steps",
	"GET /v1/install-workflows/:install_workflow_id/steps/:install_workflow_step_id",
	"GET /v1/install-workflows/:install_workflow_id/steps/:install_workflow_step_id/approvals/:approval_id",
	"GET /v1/installs",
	"POST /v1/installs",
	"GET /v1/installs/health",
	"GET /v1/installs/label-keys",
	"GET /v1/installs/sandbox-runs/:run_id",
	"GET /v1/installs/stacks/:stack_id",
	"GET /v1/installs/:install_id",
	"PATCH /v1/installs/:install_id",
	"DELETE /v1/installs/:install_id",
	"GET /v1/installs/:install_id/action-workflows",
	"GET /v1/installs/:install_id/action-workflows/latest-runs",
	"GET /v1/installs/:install_id/action-workflows/runs",
	"POST /v1/installs/:install_id/action-workflows/runs",
	"GET /v1/installs/:install_id/action-workflows/runs/:run_id",
	"GET /v1/installs/:install_id/action-workflows/runs/:run_id/steps/:step_id",
	"GET /v1/installs/:install_id/action-workflows/:action_workflow_id",
	"GET /v1/installs/:install_id/action-workflows/:action_workflow_id/recent-runs",
	"GET /v1/installs/:install_id/actions",
	"POST /v1/installs/:install_id/actions/adhoc-run",
	"GET /v1/installs/:install_id/actions/latest-runs",
	"POST /v1/installs/:install_id/actions/runs",
	"GET /v1/installs/:install_id/actions/runs",
	"GET /v1/installs/:install_id/actions/runs/:run_id",
	"GET /v1/installs/:install_id/actions/runs/:run_id/steps/:step_id",
	"GET /v1/installs/:install_id/actions/:action_id",
	"GET /v1/installs/:install_id/actions/:action_id/outputs",
	"GET /v1/installs/:install_id/actions/:action_id/recent-runs",
	"POST /v1/installs/:install_id/app-config-updates",
	"GET /v1/installs/:install_id/app-config-versions",
	"GET /v1/installs/:install_id/app-config-versions/:version_id/diff",
	"GET /v1/installs/:install_id/app-permissions-config",
	"GET /v1/installs/:install_id/audit_logs",
	"GET /v1/installs/:install_id/available-roles",
	"GET /v1/installs/:install_id/components",
	"GET /v1/installs/:install_id/components/deploys",
	"POST /v1/installs/:install_id/components/deploy-all",
	"POST /v1/installs/:install_id/components/teardown-all",
	"GET /v1/installs/:install_id/components/:component_id",
	"POST /v1/installs/:install_id/components/:component_id/deploys",
	"GET /v1/installs/:install_id/components/:component_id/deploys",
	"GET /v1/installs/:install_id/components/:component_id/deploys/latest",
	"GET /v1/installs/:install_id/components/:component_id/deploys/:deploy_id",
	"POST /v1/installs/:install_id/components/:component_id/forget",
	"GET /v1/installs/:install_id/components/:component_id/health/checks",
	"PUT /v1/installs/:install_id/components/:component_id/health/checks/:check_name",
	"GET /v1/installs/:install_id/components/:component_id/health/incident",
	"GET /v1/installs/:install_id/components/:component_id/health/timeline",
	"GET /v1/installs/:install_id/components/:component_id/outputs",
	"POST /v1/installs/:install_id/components/:component_id/teardown",
	"POST /v1/installs/:install_id/components/:component_id/toggle",
	"GET /v1/installs/:install_id/config-syncs",
	"GET /v1/installs/:install_id/config-versions",
	"GET /v1/installs/:install_id/config-versions/:version_id/diff",
	"POST /v1/installs/:install_id/configs",
	"PATCH /v1/installs/:install_id/configs/:config_id",
	"GET /v1/installs/:install_id/deploys",
	"POST /v1/installs/:install_id/deploys",
	"GET /v1/installs/:install_id/deploys/latest",
	"GET /v1/installs/:install_id/deploys/:deploy_id",
	"POST /v1/installs/:install_id/deprovision",
	"POST /v1/installs/:install_id/deprovision-sandbox",
	"GET /v1/installs/:install_id/dns/check",
	"GET /v1/installs/:install_id/drifted-objects",
	"GET /v1/installs/:install_id/events",
	"GET /v1/installs/:install_id/events/:event_id",
	"POST /v1/installs/:install_id/forget",
	"GET /v1/installs/:install_id/generate-cli-install-config",
	"GET /v1/installs/:install_id/generate-terraform-installer-config",
	"POST /v1/installs/:install_id/health/baseline",
	"POST /v1/installs/:install_id/health/cluster-access",
	"GET /v1/installs/:install_id/health/timeline",
	"GET /v1/installs/:install_id/inputs",
	"POST /v1/installs/:install_id/inputs",
	"PATCH /v1/installs/:install_id/inputs",
	"GET /v1/installs/:install_id/inputs/current",
	"POST /v1/installs/:install_id/labels",
	"DELETE /v1/installs/:install_id/labels",
	"POST /v1/installs/:install_id/notebooks",
	"GET /v1/installs/:install_id/notebooks",
	"GET /v1/installs/:install_id/notebooks/:notebook_id",
	"PATCH /v1/installs/:install_id/notebooks/:notebook_id",
	"DELETE /v1/installs/:install_id/notebooks/:notebook_id",
	"POST /v1/installs/:install_id/notebooks/:notebook_id/cells",
	"PATCH /v1/installs/:install_id/notebooks/:notebook_id/cells/:cell_id",
	"DELETE /v1/installs/:install_id/notebooks/:notebook_id/cells/:cell_id",
	"POST /v1/installs/:install_id/notebooks/:notebook_id/cells/:cell_id/runs",
	"GET /v1/installs/:install_id/notebooks/:notebook_id/cells/:cell_id/runs",
	"PUT /v1/installs/:install_id/notebooks/:notebook_id/cells/reorder",
	"GET /v1/installs/:install_id/notebooks/:notebook_id/runs/:run_id",
	"POST /v1/installs/:install_id/phone-home/:phone_home_id",
	"GET /v1/installs/:install_id/readme",
	"POST /v1/installs/:install_id/reprovision",
	"POST /v1/installs/:install_id/reprovision-sandbox",
	"POST /v1/installs/:install_id/reprovision-stack",
	"GET /v1/installs/:install_id/resources",
	"POST /v1/installs/:install_id/retry-workflow",
	"GET /v1/installs/:install_id/roles",
	"GET /v1/installs/:install_id/roles/latest",
	"GET /v1/installs/:install_id/roles/usages",
	"PATCH /v1/installs/:install_id/roles/:role_id",
	"GET /v1/installs/:install_id/runbook-runs",
	"GET /v1/installs/:install_id/runbook-runs/:run_id",
	"GET /v1/installs/:install_id/runbooks",
	"GET /v1/installs/:install_id/runbooks/:runbook_id",
	"POST /v1/installs/:install_id/runbooks/:runbook_id/runs",
	"POST /v1/installs/:install_id/runner-bootstrap-token",
	"GET /v1/installs/:install_id/runner-group",
	"GET /v1/installs/:install_id/sandbox-runs",
	"GET /v1/installs/:install_id/sandbox-runs/:run_id",
	"GET /v1/installs/:install_id/stack",
	"GET /v1/installs/:install_id/stack-runs",
	"GET /v1/installs/:install_id/state",
	"GET /v1/installs/:install_id/state-history",
	"POST /v1/installs/:install_id/sync-config",
	"POST /v1/installs/:install_id/sync-secrets",
	"GET /v1/installs/:install_id/workflows",
	"GET /v1/log-streams/:log_stream_id",
	"GET /v1/log-streams/:log_stream_id/logs",
	"GET /v1/log-streams/:log_stream_id/logs/tail",
	"GET /v1/log-streams/:log_stream_id/spans",
	"POST /v1/oidc/token",
	"POST /v1/oidc/trust-policies",
	"GET /v1/oidc/trust-policies",
	"GET /v1/oidc/trust-policies/:policy_id",
	"PATCH /v1/oidc/trust-policies/:policy_id",
	"DELETE /v1/oidc/trust-policies/:policy_id",
	"POST /v1/onboarding",
	"GET /v1/onboarding/current",
	"DELETE /v1/onboarding/current",
	"POST /v1/onboarding/current/steps/deploy",
	"POST /v1/onboarding/current/steps/get-started",
	"POST /v1/onboarding/current/steps/install",
	"POST /v1/onboarding/current/steps/organization",
	"POST /v1/onboarding/current/steps/your-stack",
	"POST /v1/orgs",
	"GET /v1/orgs",
	"GET /v1/orgs/current",
	"DELETE /v1/orgs/current",
	"PATCH /v1/orgs/current",
	"GET /v1/orgs/current/accounts",
	"PATCH /v1/orgs/current/accounts/:account_id/role",
	"GET /v1/orgs/current/features",
	"PATCH /v1/orgs/current/features",
	"GET /v1/orgs/current/invites",
	"POST /v1/orgs/current/invites",
	"POST /v1/orgs/current/invites/:invite_id/resend",
	"POST /v1/orgs/current/invites/:invite_id/revoke",
	"POST /v1/orgs/current/remove-user",
	"GET /v1/orgs/current/runner-group",
	"GET /v1/orgs/current/stats",
	"POST /v1/orgs/current/user",
	"GET /v1/orgs/current/webhooks",
	"POST /v1/orgs/current/webhooks",
	"PATCH /v1/orgs/current/webhooks/:webhook_id",
	"DELETE /v1/orgs/current/webhooks/:webhook_id",
	"GET /v1/orgs/features",
	"GET /v1/orgs/:org_id/slack/channel-subscriptions",
	"POST /v1/orgs/:org_id/slack/channel-subscriptions",
	"PATCH /v1/orgs/:org_id/slack/channel-subscriptions/:sub_id",
	"DELETE /v1/orgs/:org_id/slack/channel-subscriptions/:sub_id",
	"GET /v1/orgs/:org_id/slack/install-url",
	"GET /v1/orgs/:org_id/slack/installations",
	"GET /v1/orgs/:org_id/slack/installations/:installation_id/channels",
	"GET /v1/orgs/:org_id/slack/org-links",
	"DELETE /v1/orgs/:org_id/slack/org-links/:link_id",
	"GET /v1/policy-reports",
	"GET /v1/policy-reports/:report_id",
	"GET /v1/policy-reports/:report_id/export",
	"GET /v1/queues",
	"GET /v1/queues/:queue_id",
	"GET /v1/queues/:queue_id/signals",
	"GET /v1/queues/:queue_id/signals/:signal_id",
	"GET /v1/queues/:queue_id/signals/:signal_id/await",
	"GET /v1/queues/:queue_id/signals/:signal_id/graph",
	"GET /v1/queues/:queue_id/status",
	"GET /v1/roles",
	"GET /v1/runner-jobs",
	"GET /v1/runner-jobs/:runner_job_id",
	"POST /v1/runner-jobs/:runner_job_id/cancel",
	"GET /v1/runner-jobs/:runner_job_id/composite-plan",
	"GET /v1/runner-jobs/:runner_job_id/plan",
	"GET /v1/runners/terraform-workspace/:workspace_id/state-json",
	"GET /v1/runners/terraform-workspace/:workspace_id/state-json/:state_id",
	"GET /v1/runners/terraform-workspace/:workspace_id/state-json/:state_id/raw",
	"GET /v1/runners/terraform-workspace/:workspace_id/state-json/:state_id/resources",
	"GET /v1/runners/terraform-workspace/:workspace_id/states",
	"GET /v1/runners/terraform-workspace/:workspace_id/states/:state_id",
	"GET /v1/runners/terraform-workspace/:workspace_id/states/:state_id/resources",
	"GET /v1/runners/:runner_id",
	"GET /v1/runners/:runner_id/card-details",
	"GET /v1/runners/:runner_id/connected",
	"POST /v1/runners/:runner_id/force-shutdown",
	"POST /v1/runners/:runner_id/graceful-shutdown",
	"GET /v1/runners/:runner_id/heart-beats/latest",
	"GET /v1/runners/:runner_id/jobs",
	"GET /v1/runners/:runner_id/latest-heart-beat",
	"POST /v1/runners/:runner_id/mng/restart",
	"POST /v1/runners/:runner_id/mng/shutdown",
	"POST /v1/runners/:runner_id/mng/shutdown-vm",
	"POST /v1/runners/:runner_id/mng/update",
	"GET /v1/runners/:runner_id/processes",
	"GET /v1/runners/:runner_id/processes/current",
	"GET /v1/runners/:runner_id/processes/:process_id",
	"GET /v1/runners/:runner_id/processes/:process_id/heart-beats/latest",
	"POST /v1/runners/:runner_id/processes/:process_id/shutdown",
	"POST /v1/runners/:runner_id/prune-tokens",
	"GET /v1/runners/:runner_id/recent-health-checks",
	"GET /v1/runners/:runner_id/settings",
	"PATCH /v1/runners/:runner_id/settings",
	"GET /v1/service-accounts",
	"POST /v1/service-accounts",
	"PATCH /v1/service-accounts/:account_id",
	"DELETE /v1/service-accounts/:account_id",
	"PATCH /v1/service-accounts/:account_id/role",
	"POST /v1/service-accounts/:account_id/tokens",
	"GET /v1/terraform-backend",
	"POST /v1/terraform-backend",
	"POST /v1/terraform-workspace",
	"GET /v1/terraform-workspaces",
	"POST /v1/terraform-workspaces",
	"GET /v1/terraform-workspaces/:workspace_id",
	"DELETE /v1/terraform-workspaces/:workspace_id",
	"GET /v1/terraform-workspaces/:workspace_id/lock",
	"POST /v1/terraform-workspaces/:workspace_id/lock",
	"POST /v1/terraform-workspaces/:workspace_id/unlock",
	"GET /v1/terraform-workspaces/:workspace_id/state-json",
	"GET /v1/terraform-workspaces/:workspace_id/state-json/:state_id",
	"GET /v1/terraform-workspaces/:workspace_id/state-json/:state_id/raw",
	"GET /v1/terraform-workspaces/:workspace_id/state-json/:state_id/resources",
	"GET /v1/terraform-workspaces/:workspace_id/states",
	"GET /v1/terraform-workspaces/:workspace_id/states/:state_id",
	"GET /v1/terraform-workspaces/:workspace_id/states/:state_id/resources",
	"POST /v1/triggers",
	"GET /v1/triggers",
	"GET /v1/triggers/dispatches",
	"GET /v1/triggers/dispatches/:dispatch_id",
	"POST /v1/triggers/dispatches/:dispatch_id/retry",
	"GET /v1/triggers/events/:event_id",
	"GET /v1/triggers/events/:event_id/raw",
	"POST /v1/triggers/events/:event_id/replay",
	"GET /v1/triggers/:trigger_id",
	"DELETE /v1/triggers/:trigger_id",
	"POST /v1/triggers/:trigger_id/disable",
	"POST /v1/triggers/:trigger_id/enable",
	"GET /v1/triggers/:trigger_id/event-types",
	"GET /v1/triggers/:trigger_id/events",
	"PATCH /v1/triggers/:trigger_id/ingress-url",
	"POST /v1/triggers/:trigger_id/rotate-ingress-url",
	"POST /v1/triggers/:trigger_id/rotate-secret",
	"GET /v1/triggers/:trigger_id/rules",
	"GET /v1/triggers/:trigger_id/rules/:rule_id",
	"PATCH /v1/triggers/:trigger_id/secrets/:secret_id/reveal",
	"POST /v1/triggers/:trigger_id/secrets/:secret_id/revoke",
	"POST /v1/vcs/connection-callback",
	"POST /v1/vcs/connections",
	"GET /v1/vcs/connections",
	"GET /v1/vcs/connections/:connection_id",
	"DELETE /v1/vcs/connections/:connection_id",
	"GET /v1/vcs/connections/:connection_id/branches",
	"GET /v1/vcs/connections/:connection_id/check-status",
	"GET /v1/vcs/connections/:connection_id/repos",
	"GET /v1/vcs/connections/:connection_id/webhook-subscription",
	"POST /v1/vcs/connections/:connection_id/webhook-subscription",
	"POST /v1/vcs/webhooks/:subscription_id/events",
	"POST /v1/vcs/:vcs_connection_id/events",
	"GET /v1/workflows",
	"POST /v1/workflows/cancel",
	"GET /v1/workflows/pending-approvals",
	"GET /v1/workflows/:workflow_id",
	"PATCH /v1/workflows/:workflow_id",
	"POST /v1/workflows/:workflow_id/cancel",
	"GET /v1/workflows/:workflow_id/queue-position",
	"GET /v1/workflows/:workflow_id/step-groups",
	"GET /v1/workflows/:workflow_id/step-groups/:step_group_id",
	"GET /v1/workflows/:workflow_id/steps",
	"GET /v1/workflows/:workflow_id/steps/:step_id",
	"GET /v1/workflows/:workflow_id/steps/:step_id/approvals/:approval_id",
	"GET /v1/workflows/:workflow_id/steps/:step_id/approvals/:approval_id/contents",
	"POST /v1/workflows/:workflow_id/steps/:step_id/approvals/:approval_id/response",
	"GET /v1/workflows/:workflow_id/steps/:step_id/await",
	"POST /v1/workflows/:workflow_id/steps/:step_id/cancel",
	"POST /v1/workflows/:workflow_id/steps/:step_id/retry",
	"POST /v1/workflows/:workflow_id/steps/:step_id/skip",
}

func TestValidateRouteCoverageAgainstInventory(t *testing.T) {
	routes := make(gin.RoutesInfo, 0, len(publicAPIRouteInventory))
	for _, entry := range publicAPIRouteInventory {
		parts := strings.SplitN(entry, " ", 2)
		routes = append(routes, gin.RouteInfo{Method: parts[0], Path: parts[1]})
	}

	if err := ValidateRouteCoverage(routes); err != nil {
		t.Fatalf("route inventory contains unclassified routes:\n%v", err)
	}
}

func TestValidateRouteCoverageRejectsUnclassified(t *testing.T) {
	err := ValidateRouteCoverage(gin.RoutesInfo{
		{Method: "POST", Path: "/v1/new-feature/:feature_id/frobnicate"},
	})
	if err == nil {
		t.Fatal("expected an unclassified route to fail validation")
	}
	if !strings.Contains(err.Error(), "/v1/new-feature/:feature_id/frobnicate") {
		t.Fatalf("error should name the unclassified route, got: %v", err)
	}
}

func TestOwnedResourceRouteMatching(t *testing.T) {
	tests := []struct {
		path      string
		wantParam string
		wantMatch bool
	}{
		{path: "/v1/action-workflows/configs/:action_workflow_config_id", wantParam: "action_workflow_config_id", wantMatch: true},
		{path: "/v1/action-workflows/:action_workflow_id", wantParam: "action_workflow_id", wantMatch: true},
		{path: "/v1/components/builds/:build_id", wantParam: "build_id", wantMatch: true},
		{path: "/v1/components/:component_id/builds/:build_id", wantParam: "component_id", wantMatch: true},
		{path: "/v1/component-builds", wantMatch: false},
		{path: "/v1/builds", wantMatch: false},
		{path: "/v1/workflows/:workflow_id/steps/:step_id", wantParam: "workflow_id", wantMatch: true},
		{path: "/v1/install-workflows/:install_workflow_id", wantParam: "install_workflow_id", wantMatch: true},
		{path: "/v1/installs/sandbox-runs/:run_id", wantParam: "run_id", wantMatch: true},
		{path: "/v1/installs/stacks/:stack_id", wantParam: "stack_id", wantMatch: true},
		{path: "/v1/triggers/:trigger_id", wantMatch: false},
		{path: "/v1/runners/terraform-workspace/:workspace_id/states", wantParam: "workspace_id", wantMatch: true},
		{path: "/v1/runners/:runner_id/mng/restart", wantParam: "runner_id", wantMatch: true},
		{path: "/v1/runner-jobs/:runner_job_id/cancel", wantParam: "runner_job_id", wantMatch: true},
		{path: "/v1/log-streams/:log_stream_id/logs", wantParam: "log_stream_id", wantMatch: true},
		{path: "/v1/terraform-workspaces/:workspace_id/lock", wantParam: "workspace_id", wantMatch: true},
		{path: "/v1/queues/:queue_id/signals/:signal_id", wantParam: "queue_id", wantMatch: true},
		{path: "/v1/policy-reports/:report_id/export", wantParam: "report_id", wantMatch: true},
	}

	for _, tc := range tests {
		t.Run(tc.path, func(t *testing.T) {
			r, ok := matchOwnedResourceRoute(tc.path)
			if ok != tc.wantMatch {
				t.Fatalf("match = %v, want %v", ok, tc.wantMatch)
			}
			if ok && r.idParam != tc.wantParam {
				t.Fatalf("idParam = %q, want %q", r.idParam, tc.wantParam)
			}
		})
	}
}

func TestOwnerChain(t *testing.T) {
	full := ownerChain("org_1", "inl_1", "app_1")
	if len(full) != 3 || full[0].ID != "inl_1" || full[1].ID != "app_1" || full[2].ID != "org_1" {
		t.Fatalf("unexpected install-owned chain: %+v", full)
	}

	appOnly := ownerChain("org_1", "", "app_1")
	if len(appOnly) != 2 || appOnly[0].ID != "app_1" || appOnly[0].Type != "app" || appOnly[1].ID != "org_1" {
		t.Fatalf("unexpected app-owned chain: %+v", appOnly)
	}
}
