//  THIS FILE IS GENERATED. DO NOT EDIT.
//  Generated by temporal-gen-v2

package activities

import (
	"time"

	"github.com/nuonco/nuon/services/ctl-api/internal/app"
	"go.temporal.io/sdk/workflow"
)

// AwaitGetInstallActionWorkflowRun is a wrapper for the GetInstallActionWorkflowRun activity
func AwaitGetInstallActionWorkflowRun(ctx workflow.Context, input GetInstallActionWorkflowRunRequest, opts ...*workflow.ActivityOptions) (*app.InstallActionWorkflowRun, error) {
	var result *app.InstallActionWorkflowRun
	options := workflow.GetActivityOptions(ctx)
	options.StartToCloseTimeout = time.Duration(60000000000) // Default: 1 minute

	for _, opt := range opts {
		if opt != nil {
			if opt.TaskQueue != "" {
				options.TaskQueue = opt.TaskQueue
			}
			if opt.ScheduleToCloseTimeout != 0 {
				options.ScheduleToCloseTimeout = opt.ScheduleToCloseTimeout
			}
			if opt.StartToCloseTimeout != 0 {
				options.StartToCloseTimeout = opt.StartToCloseTimeout
			}
			if opt.ScheduleToStartTimeout != 0 {
				options.ScheduleToStartTimeout = opt.ScheduleToStartTimeout
			}
			if opt.HeartbeatTimeout != 0 {
				options.HeartbeatTimeout = opt.HeartbeatTimeout
			}
			if opt.WaitForCancellation {
				options.WaitForCancellation = opt.WaitForCancellation
			}
			if opt.ActivityID != "" {
				options.ActivityID = opt.ActivityID
			}
			if opt.RetryPolicy != nil {
				options.RetryPolicy = opt.RetryPolicy
			}
			if opt.DisableEagerExecution {
				options.DisableEagerExecution = opt.DisableEagerExecution
			}
		}
	}

	ctx = workflow.WithActivityOptions(ctx, options)
	err := workflow.ExecuteActivity(ctx, (*Activities).GetInstallActionWorkflowRun, input).Get(ctx, &result)
	return result, err
}

// AwaitGetInstallActionWorkflowRunByRunID is a wrapper for the GetInstallActionWorkflowRun activity
func AwaitGetInstallActionWorkflowRunByRunID(ctx workflow.Context, input string, opts ...*workflow.ActivityOptions) (*app.InstallActionWorkflowRun, error) {
	req := GetInstallActionWorkflowRunRequest{
		RunID: input,
	}
	return AwaitGetInstallActionWorkflowRun(ctx, req, opts...)
}
