//  THIS FILE IS GENERATED. DO NOT EDIT.
//  Generated by temporal-gen-v2

package activities

import (
	"time"

	"go.temporal.io/sdk/workflow"
)

// AwaitUpdateWorkflowStepFinishedAt is a wrapper for the UpdateWorkflowStepFinishedAt activity
func AwaitUpdateWorkflowStepFinishedAt(ctx workflow.Context, input UpdateWorkflowStepFinishedAtRequest, opts ...*workflow.ActivityOptions) error {

	options := workflow.GetActivityOptions(ctx)
	options.StartToCloseTimeout = time.Duration(60000000000) // Default: 1 minute

	for _, opt := range opts {
		if opt != nil {
			if opt.TaskQueue != "" {
				options.TaskQueue = opt.TaskQueue
			}
			if opt.ScheduleToCloseTimeout != 0 {
				options.ScheduleToCloseTimeout = opt.ScheduleToCloseTimeout
			}
			if opt.StartToCloseTimeout != 0 {
				options.StartToCloseTimeout = opt.StartToCloseTimeout
			}
			if opt.ScheduleToStartTimeout != 0 {
				options.ScheduleToStartTimeout = opt.ScheduleToStartTimeout
			}
			if opt.HeartbeatTimeout != 0 {
				options.HeartbeatTimeout = opt.HeartbeatTimeout
			}
			if opt.WaitForCancellation {
				options.WaitForCancellation = opt.WaitForCancellation
			}
			if opt.ActivityID != "" {
				options.ActivityID = opt.ActivityID
			}
			if opt.RetryPolicy != nil {
				options.RetryPolicy = opt.RetryPolicy
			}
			if opt.DisableEagerExecution {
				options.DisableEagerExecution = opt.DisableEagerExecution
			}
		}
	}

	ctx = workflow.WithActivityOptions(ctx, options)
	err := workflow.ExecuteActivity(ctx, (*Activities).UpdateWorkflowStepFinishedAt, input).Get(ctx, nil)
	return err
}

// AwaitUpdateWorkflowStepFinishedAtByID is a wrapper for the UpdateWorkflowStepFinishedAt activity
func AwaitUpdateWorkflowStepFinishedAtByID(ctx workflow.Context, input string, opts ...*workflow.ActivityOptions) error {
	req := UpdateWorkflowStepFinishedAtRequest{
		ID: input,
	}
	return AwaitUpdateWorkflowStepFinishedAt(ctx, req, opts...)
}
