VERSION --use-cache-command 0.6

IMPORT github.com/powertoolsdev/shared-configs:main
FROM ghcr.io/powertoolsdev/ci-helm-releaser

ARG GHCR_IMAGE=ghcr.io/${EARTHLY_GIT_PROJECT_NAME}
ARG SERVICE=workers-apps
ARG GITHUB_ACTIONS=

code:
    WORKDIR /work
    COPY --dir . /work/k8s

helm-bump-and-publish:
    FROM +code
    ARG chart_version
    ARG repos
    WORKDIR /work
    DO shared-configs+HELM_RELEASE \
        --EARTHLY_GIT_PROJECT_NAME=workers-apps \
        --chart_version=$chart_version \
        --repos=$repos

deploy:
    FROM +code

    ARG env
    ARG cluster_name
    ARG role_arn
    ARG chart_version
    ARG repository
    ARG image_tag
    ARG tfenv=.tfenv
    ARG repos
    DO shared-configs+HELM_SETUP \
        --repos="$repos"

    WORKDIR /work/k8s
    COPY $tfenv .
    RUN while IFS='=' read -r k v; do eval export "$k='$v'"; done < "$tfenv" \
        && envsubst < "values.$env.tmpl" > "values.$env.yaml"

    DO shared-configs+K8S_DEPLOY \
        --EARTHLY_GIT_PROJECT_NAME=workers-apps \
        --env=$env \
        --cluster_name=$cluster_name \
        --role_arn=$role_arn \
        --chart_version=$chart_version \
        --repository=$repository \
        --image_tag=$image_tag
