---
root_domain: nuon.cloud
region: us-west-2
chart:
  version: "3.54.2"
  repo: "https://helm.datadoghq.com"
  name: datadog
aws_permissions:
  - "apigateway:GET"
  - "autoscaling:Describe*"
  - "backup:List*"
  - "budgets:ViewBudget"
  - "cloudfront:GetDistributionConfig"
  - "cloudfront:ListDistributions"
  - "cloudtrail:DescribeTrails"
  - "cloudtrail:GetTrailStatus"
  - "cloudtrail:LookupEvents"
  - "cloudwatch:Describe*"
  - "cloudwatch:Get*"
  - "cloudwatch:List*"
  - "codedeploy:List*"
  - "codedeploy:BatchGet*"
  - "directconnect:Describe*"
  - "dynamodb:List*"
  - "dynamodb:Describe*"
  - "ec2:Describe*"
  - "ecs:Describe*"
  - "ecs:List*"
  - "elasticache:Describe*"
  - "elasticache:List*"
  - "elasticfilesystem:DescribeFileSystems"
  - "elasticfilesystem:DescribeTags"
  - "elasticfilesystem:DescribeAccessPoints"
  - "elasticloadbalancing:Describe*"
  - "elasticmapreduce:List*"
  - "elasticmapreduce:Describe*"
  - "es:ListTags"
  - "es:ListDomainNames"
  - "es:DescribeElasticsearchDomains"
  - "events:CreateEventBus"
  - "fsx:DescribeFileSystems"
  - "fsx:ListTagsForResource"
  - "health:DescribeEvents"
  - "health:DescribeEventDetails"
  - "health:DescribeAffectedEntities"
  - "kinesis:List*"
  - "kinesis:Describe*"
  - "lambda:GetPolicy"
  - "lambda:List*"
  - "logs:DeleteSubscriptionFilter"
  - "logs:DescribeLogGroups"
  - "logs:DescribeLogStreams"
  - "logs:DescribeSubscriptionFilters"
  - "logs:FilterLogEvents"
  - "logs:PutSubscriptionFilter"
  - "logs:TestMetricFilter"
  - "organizations:Describe*"
  - "organizations:List*"
  - "rds:Describe*"
  - "rds:List*"
  - "redshift:DescribeClusters"
  - "redshift:DescribeLoggingStatus"
  - "route53:List*"
  - "s3:GetBucketLogging"
  - "s3:GetBucketLocation"
  - "s3:GetBucketNotification"
  - "s3:GetBucketTagging"
  - "s3:ListAllMyBuckets"
  - "s3:PutBucketNotification"
  - "ses:Get*"
  - "sns:List*"
  - "sns:Publish"
  - "sqs:ListQueues"
  - "states:ListStateMachines"
  - "states:DescribeStateMachine"
  - "support:DescribeTrustedAdvisor*"
  - "support:RefreshTrustedAdvisorCheck"
  - "tag:GetResources"
  - "tag:GetTagKeys"
  - "tag:GetTagValues"
  - "xray:BatchGetTraces"
  - "xray:GetTraceSummaries"
monitors:
  kubernetes_container_waiting: >
    {
        "name": "${env} - Kubernetes Container Waiting",
        "type": "query alert",
        "query": "sum(last_2m):sum:kubernetes.containers.state.waiting{env:${env}} by {kube_container_name,kube_namespace} > 1",
        "message": "@slack-nuon-alerts-infra \n{{kube_container_name.name}} in {{kube_namespace.name}} has {{value}} containers waiting.",
        "tags": [
          "terraform:true",
          "env:${env}"
        ],
        "options": {
            "groupby_simple_monitor" : false,
            "new_host_delay": 300,
            "thresholds": {
                "critical": 1,
                "warning": 0.5
            },
            "notify_audit": false,
            "include_tags": true,
            "new_group_delay": 60,
            "renotify_interval": 0,
            "escalation_message": "",
            "notify_no_data": false,
            "silenced": {}
        },
        "priority": 1,
        "restricted_roles": null
    }
  waypoint_job_queued: >
    {
        "name": "${env} - Waypoint Job Queued",
        "type": "query alert",
        "query": "max(last_5m):max:waypoint_executor.job_state_change.max{env:${env}, waypoint_job_state:queued} > 120000",
        "message": "@slack-nuon-alerts-infra",
        "tags": [
            "terraform:true",
            "env:${env}",
            "service:workers-executors"
        ],
        "options": {
            "groupby_simple_monitor" : false,
            "new_host_delay": 300,
            "thresholds": {
                "critical": 120000
            },
            "notify_audit": false,
            "include_tags": false,
            "notify_no_data": false,
            "silenced": {}
        },
        "priority": 2,
        "restricted_roles": null
    }
  temporal_schedule_to_start_timeout: >
    {
        "name": "${env} - Temporal schedule-to-start timeout",
        "type": "query alert",
        "query": "sum(last_5m):sum:temporal.server.schedule_to_start.timeout.count{env:${env}}.as_count() > 1",
        "message": "@slack-alerts-infra",
        "tags": [
            "service:temporal",
            "terraform:true",
            "env:${env}"
        ],
        "options": {
            "groupby_simple_monitor" : false,
            "new_host_delay": 300,
            "thresholds": {
                "critical": 1
            },
            "notify_audit": false,
            "include_tags": false,
            "notify_no_data": false,
            "silenced": {}
        },
        "priority": 1,
        "restricted_roles": null
    }
  org_is_unhealthy: >
    {
        "name": "${env} - Org is unhealthy",
        "type": "query alert",
        "query": "sum(last_15m):sum:health_check{status:error, sandbox_mode:false, env:${env}} by {org_id}.as_count() > 15",
        "message": "@slack-alerts-product \n\n{{org_id.name}} is unhealthy.",
        "tags": [
            "service:ctl-api",
            "terraform:true",
            "env:${env}"
        ],
        "options": {
            "groupby_simple_monitor" : false,
            "new_host_delay": 300,
            "thresholds": {
                "critical": 15,
                "warning": 3
            },
            "notify_audit": false,
            "include_tags": true,
            "new_group_delay": 60,
            "notify_no_data": false,
            "silenced": {}
        },
        "priority": 1,
        "restricted_roles": null
    }
  org_failed_to_provision: >
    {
        "name": "${env} - Org failed to provision",
        "type": "event-v2 alert",
        "query": "events(\"\\\"org failed to provision\\\" env:${env}\").rollup(\"count\").last(\"5m\") > 1",
        "message": "@slack-alerts-product",
        "tags": [
            "service:ctl-api",
            "terraform:true",
            "env:${env}"
        ],
        "options": {
            "groupby_simple_monitor" : false,
            "new_host_delay": 300,
            "thresholds": {
                "critical": 1
            },
            "enable_logs_sample": false,
            "notify_audit": false,
            "on_missing_data": "default",
            "include_tags": false,
            "silenced": {}
        },
        "priority": 1,
        "restricted_roles": null
    }
  install_failed_to_provision: >
    {
        "name": "${env} - Install failed to provision",
        "type": "event-v2 alert",
        "query": "events(\"\\\"install failed to provision\\\" env:${env}\").rollup(\"count\").last(\"5m\") > 1",
        "message": "@slack-alerts-product",
        "tags": [
            "service:ctl-api",
            "terraform:true",
            "env:${env}"
        ],
        "options": {
            "groupby_simple_monitor" : false,
            "new_host_delay": 300,
            "thresholds": {
                "critical": 1
            },
            "enable_logs_sample": false,
            "notify_audit": false,
            "on_missing_data": "default",
            "include_tags": false,
            "silenced": {}
        },
        "priority": 4,
        "restricted_roles": null
    }
  failed_to_queue_waypoint_job: >
    {
        "name": "${env} - Failed to queue waypoint job",
        "type": "event-v2 alert",
        "query": "events(\"\\\"Failed to queue waypoint job\\\" env:${env}\").rollup(\"count\").last(\"5m\") > 1",
        "message": "@slack-alerts-infra",
        "tags": [
            "service:workers-executors",
            "terraform:true",
            "env:${env}"
        ],
        "options": {
            "groupby_simple_monitor" : false,
            "new_host_delay": 300,
            "thresholds": {
                "critical": 1
            },
            "enable_logs_sample": false,
            "notify_audit": false,
            "on_missing_data": "default",
            "include_tags": false,
            "silenced": {}
        },
        "priority": 1,
        "restricted_roles": null
    }
  database_running_low_on_free_space: >
    {
        "name": "${env} - Database Running Low on Free Space",
        "type": "query alert",
        "query": "avg(last_1h):avg:aws.rds.free_storage_space{environment:${env}} by {dbname} < 1073741824",
        "message": "@slack-alerts-infra \n{{dbname.name}} is running low on free space.",
        "tags": [
            "terraform:true",
            "env:${env}"
        ],
        "options": {
            "groupby_simple_monitor" : false,
            "new_host_delay": 300,
            "thresholds": {
                "critical": 1073741824
            },
            "notify_audit": false,
            "include_tags": true,
            "evaluation_delay": 900,
            "new_group_delay": 60,
            "notify_no_data": false,
            "silenced": {}
        },
        "priority": 1,
        "restricted_roles": null
    }
  ctl_api_5xx_errors: >
    {
        "name": "${env} - 5xx Errors from CTL API",
        "type": "query alert",
        "query": "sum(last_5m):sum:api.request.status{env:${env}, status_code_class:5xx} by {endpoint}.as_count() > 1",
        "message": "@slack-alerts-product",
        "tags": [
            "ingress.k8s.aws/stack:default/ctl-api-api",
            "terraform:true",
            "env:${env}"
        ],
        "options": {
            "groupby_simple_monitor" : false,
            "new_host_delay": 300,
            "thresholds": {
                "critical": 1
            },
            "notify_audit": false,
            "threshold_windows": null,
            "notify_no_data": false,
            "include_tags": false,
            "renotify_interval": 30,
            "renotify_statuses": [
                "alert",
                "no data"
            ],
            "escalation_message": "",
            "new_group_delay": 0,
            "silenced": {}
        },
        "priority": 1,
        "restricted_roles": null
    }
synthetics: {}
