---
root_domain: nuon.cloud
region: us-west-2
chart:
  version: "3.54.2"
  repo: "https://helm.datadoghq.com"
  name: datadog
aws_permissions:
  - "apigateway:GET"
  - "autoscaling:Describe*"
  - "backup:List*"
  - "budgets:ViewBudget"
  - "cloudfront:GetDistributionConfig"
  - "cloudfront:ListDistributions"
  - "cloudtrail:DescribeTrails"
  - "cloudtrail:GetTrailStatus"
  - "cloudtrail:LookupEvents"
  - "cloudwatch:Describe*"
  - "cloudwatch:Get*"
  - "cloudwatch:List*"
  - "codedeploy:List*"
  - "codedeploy:BatchGet*"
  - "directconnect:Describe*"
  - "dynamodb:List*"
  - "dynamodb:Describe*"
  - "ec2:Describe*"
  - "ecs:Describe*"
  - "ecs:List*"
  - "elasticache:Describe*"
  - "elasticache:List*"
  - "elasticfilesystem:DescribeFileSystems"
  - "elasticfilesystem:DescribeTags"
  - "elasticfilesystem:DescribeAccessPoints"
  - "elasticloadbalancing:Describe*"
  - "elasticmapreduce:List*"
  - "elasticmapreduce:Describe*"
  - "es:ListTags"
  - "es:ListDomainNames"
  - "es:DescribeElasticsearchDomains"
  - "events:CreateEventBus"
  - "fsx:DescribeFileSystems"
  - "fsx:ListTagsForResource"
  - "health:DescribeEvents"
  - "health:DescribeEventDetails"
  - "health:DescribeAffectedEntities"
  - "kinesis:List*"
  - "kinesis:Describe*"
  - "lambda:GetPolicy"
  - "lambda:List*"
  - "logs:DeleteSubscriptionFilter"
  - "logs:DescribeLogGroups"
  - "logs:DescribeLogStreams"
  - "logs:DescribeSubscriptionFilters"
  - "logs:FilterLogEvents"
  - "logs:PutSubscriptionFilter"
  - "logs:TestMetricFilter"
  - "organizations:Describe*"
  - "organizations:List*"
  - "rds:Describe*"
  - "rds:List*"
  - "redshift:DescribeClusters"
  - "redshift:DescribeLoggingStatus"
  - "route53:List*"
  - "s3:GetBucketLogging"
  - "s3:GetBucketLocation"
  - "s3:GetBucketNotification"
  - "s3:GetBucketTagging"
  - "s3:ListAllMyBuckets"
  - "s3:PutBucketNotification"
  - "ses:Get*"
  - "sns:List*"
  - "sns:Publish"
  - "sqs:ListQueues"
  - "states:ListStateMachines"
  - "states:DescribeStateMachine"
  - "support:DescribeTrustedAdvisor*"
  - "support:RefreshTrustedAdvisorCheck"
  - "tag:GetResources"
  - "tag:GetTagKeys"
  - "tag:GetTagValues"
  - "xray:BatchGetTraces"
  - "xray:GetTraceSummaries"
monitors:
  kubernetes_container_waiting: >
    {
        "name": "${env} - Kubernetes Container Waiting",
        "type": "query alert",
        "query": "sum(last_2m):sum:kubernetes.containers.state.waiting{env:${env}} by {kube_container_name,kube_namespace} > 1",
        "message": "@slack-nuon-alerts-infra \n{{kube_container_name.name}} in {{kube_namespace.name}} has {{value}} containers waiting.",
        "tags": [
          "terraform:true",
          "env:${env}"
        ],
        "options": {
            "thresholds": {
                "critical": 1,
                "warning": 0.5
            },
            "notify_audit": false,
            "include_tags": true,
            "new_group_delay": 60,
            "renotify_interval": 0,
            "escalation_message": "",
            "notify_no_data": false,
            "silenced": {}
        },
        "priority": 1,
        "restricted_roles": null
    }
  waypoint_job_queued: >
    {
        "name": "${env} - Waypoint Job Queued",
        "type": "query alert",
        "query": "max(last_5m):max:waypoint_executor.job_state_change.max{env:${env}, waypoint_job_state:queued} > 120000",
        "message": "@slack-nuon-alerts-infra",
        "tags": [
            "terraform:true",
            "env:${env}",
            "service:workers-executors"
        ],
        "options": {
            "thresholds": {
                "critical": 120000
            },
            "notify_audit": false,
            "include_tags": false,
            "notify_no_data": false,
            "silenced": {}
        },
        "priority": 2,
        "restricted_roles": null
    }
