---
pool: main
monitors:
  clickhouse_insert_queries_failed:
    enabled: false
  clickhouse_pod_count_low:
    enabled: false
  clickhouse_containers_restarting:
    enabled: false
  org_is_unhealthy:
    enabled: false
  ctl_api_5xx_errors:
    enabled: false
  ctl_api_db_connection:
    enabled: false
  kubernetes_container_waiting:
    enabled: false
