---
pool: nuon
monitors:
  clickhouse_insert_queries_failed:
    enabled: true
  clickhouse_pod_count_low:
    enabled: true
  clickhouse_containers_restarting:
    enabled: true
  org_container_waiting:
    enabled: false
  database_running_low_on_free_space:
    enabled: true
    json: >
      {
          "name": "${aws_account} - Database Running Low on Free Space",
          "type": "query alert",
          "query": "avg(last_1h):avg:aws.rds.free_storage_space{environment:${aws_account}} by {dbname} < 21474836480",
          "message": "@slack-alerts-${env}-infra \n{{dbname.name}} is running low on free space.",
          "tags": [
              "terraform:true",
              "env:${aws_account}"
          ],
          "options": {
              "groupby_simple_monitor" : false,
              "new_host_delay": 300,
              "thresholds": {
                  "critical": 21474836480
              },
              "notify_audit": false,
              "include_tags": true,
              "evaluation_delay": 900,
              "new_group_delay": 60,
              "notify_no_data": false,
              "silenced": {}
          },
          "priority": 1,
          "restricted_roles": null
      }

synthetics:
  ctl_api_uptime:
    name: "${aws_account} - CTL API Uptime"
    type: "api"
    subtype: "http"
    status: "live"
    message: "@slack-alerts-${env}-product @pagerduty-Datadog \n\nctl-api has experienced a disruption"
    locations: ["aws:ca-central-1", "aws:ap-south-1", "aws:eu-west-1"]
    tags: ["service:ctl-api", "terraform:true", "env:${aws_account}"]
    request_definition:
      method: "GET"
      url: "https://api.nuon.co/livez"
    request_headers: {}
    assertion:
      type: "statusCode"
      operator: "is"
      target: 200
    options_list:
      tick_every: 60
      retry:
        count: 2
        interval: 750
      monitor_options:
        renotify_interval: 30
      monitor_priority: 1
  dashboard_uptime:
    name: "${aws_account} - Dashboard UI Uptime"
    type: "api"
    subtype: "http"
    status: "live"
    message: "@slack-alerts-${env}-product @pagerduty-Datadog \n\ndashboard-ui has experienced a disruption"
    locations: ["aws:ca-central-1", "aws:ap-south-1", "aws:eu-west-1"]
    tags: ["service:dashboard-ui", "terraform:true", "env:${aws_account}"]
    request_definition:
      method: "GET"
      url: "https://app.nuon.co/livez"
    request_headers: {}
    assertion:
      type: "statusCode"
      operator: "is"
      target: 200
    options_list:
      tick_every: 60
      retry:
        count: 2
        interval: 750
      monitor_options:
        renotify_interval: 30
      monitor_priority: 1
  dashboard_uptime:
    name: "${aws_account} - Website Uptime"
    type: "api"
    subtype: "http"
    status: "live"
    message: "@slack-alerts-${env}-product @pagerduty-Datadog \n\nwebsite has experienced a disruption"
    locations: ["aws:ca-central-1", "aws:ap-south-1", "aws:eu-west-1"]
    tags: ["service:website", "terraform:true", "env:${aws_account}"]
    request_definition:
      method: "GET"
      url: "https://nuon.co"
    request_headers: {}
    assertion:
      type: "statusCode"
      operator: "is"
      target: 200
    options_list:
      tick_every: 60
      retry:
        count: 2
        interval: 750
      monitor_options:
        renotify_interval: 30
      monitor_priority: 1

# installers is the list
# config is the synthetic monitor configuration used for all installers accross the board for
# one can get a list of vercel installers with this script:
# vercel projects ls  |& grep installer | tr -s ' ' | cut -d ' ' -f 2,3| jq -R -n -c '[inputs|split(" ")|{(.[0]):.[1]}] | add' | jq
installer_synthetics:
  installers:
    demo-installer: https://demo-installer.vercel.app
    paradedb-installer: https://paradedb-installer.vercel.app
    percona-installer: https://percona-installer.vercel.app
    stardog-installer: https://stardog-installer.vercel.app
    athena-installer: https://athena-installer.vercel.app
    streamkap-installer: https://streamkap-installer.vercel.app
    weaviate-installer: https://weaviate-installer.vercel.app
    warpstream-installer: https://warpstream-installer.vercel.app
    100xdev-installer: https://100xdev-installer.vercel.app
    # installers: https://installers.nuon.co
  config:
    name: "[prod] Installer Uptime"
    type: "api"
    subtype: "http"
    status: "live"
    message: "@slack-alerts-${env}-product"
    locations: ["aws:ca-central-1", "aws:ap-south-1", "aws:eu-west-1"]
    tags: ["service:installers", "terraform:true", "env:${env}"]
    request_definition:
      method: "GET"
      url: ""
    request_headers: {}
    assertion:
      type: "statusCode"
      operator: "is"
      target: 200
    options_list:
      tick_every: 300
      retry:
        count: 2
        interval: 1000
      monitor_options:
        renotify_interval: 120
      monitor_priority: 1
