---
pool: main
monitors:
  clickhouse_insert_queries_failed:
    enabled: false
  clickhouse_pod_count_low:
    enabled: false
  clickhouse_containers_restarting:
    enabled: false
  org_container_waiting:
    enabled: false
  waypoint_job_queued:
    enabled: false
  temporal_schedule_to_start_timeout:
    enabled: false
  org_is_unhealthy:
    enabled: false
  org_failed_to_provision:
    enabled: false
  install_failed_to_provision:
    enabled: false
  failed_to_queue_waypoint_job:
    enabled: false
  database_running_low_on_free_space:
    enabled: false
  ctl_api_public_5xx_errors:
    enabled: false
  ctl_api_runner_5xx_errors:
    enabled: false
