---
pool: nuon

monitors:
  clickhouse_insert_queries_failed:
    enabled: true
  clickhouse_pod_count_low:
    enabled: true
  clickhouse_containers_restarting:
    enabled: true
  org_container_waiting:
    enabled: false
  integration_tests_failed:
    enabled: true
    json: >
      {
        "name": "stage - Integrations test failed",
        "type": "query alert",
        "query": "sum(last_5m):sum:integration.runs.count{status:failure} by {status}.as_count() > 0",
        "message": "@slack-alerts-stage-infra\nIntegrations tests failed",
        "tags": [
              "terraform:true",
              "env:${aws_account}"
        ],
        "options": {
          "thresholds": {
            "critical": 0
          },
          "notify_audit": false,
          "threshold_windows": null,
          "on_missing_data": "default",
          "include_tags": true,
          "new_group_delay": 60
        },
        "priority": null,
        "restriction_policy": {
          "bindings": []
        }
      }

synthetics:
  ctl_api_uptime:
    name: "${env} - CTL API Uptime"
    type: "api"
    subtype: "http"
    status: "live"
    message: "@slack-alerts-${env}-product"
    locations: ["aws:us-east-1", "gcp:us-south1", "aws:us-west-2"]
    tags: ["service:ctl-api", "terraform:true", "env:${env}"]
    request_definition:
      method: "GET"
      url: "https://api.${env}.nuon.co/livez"
    request_headers: {}
    assertion:
      type: "statusCode"
      operator: "is"
      target: 200
    options_list:
      tick_every: 60
      retry:
        count: 2
        interval: 1000
      monitor_options:
        renotify_interval: 5
      monitor_priority: 2

installer_synthetics:
  installers: {}
  config: {}
