---
pool: nuon

monitors:
  clickhouse_insert_queries_failed:
    enabled: true
  clickhouse_pod_count_low:
    enabled: true
  clickhouse_containers_restarting:
    enabled: true
  org_container_waiting:
    enabled: false

synthetics:
  ctl_api_uptime:
    name: "${env} - CTL API Uptime"
    type: "api"
    subtype: "http"
    status: "live"
    message: "@slack-alerts-${env}-product"
    locations: ["aws:us-east-1", "gcp:us-south1", "aws:us-west-2"]
    tags: ["service:ctl-api", "terraform:true", "env:${env}"]
    request_definition:
      method: "GET"
      url: "https://api.${env}.nuon.co/livez"
    request_headers: {}
    assertion:
      type: "statusCode"
      operator: "is"
      target: 200
    options_list:
      tick_every: 60
      retry:
        count: 2
        interval: 1000
      monitor_options:
        renotify_interval: 5
      monitor_priority: 2

installer_synthetics:
  installers: {}
  config: {}
