---
pool: nuon

monitors:
  org_container_waiting:
    enabled: false

  clickhouse_insert_queries_failed:
    enabled: true
    json: >
      {
          "name": "${aws_account} - Clickhouse Query: Insert Failed",
          "type": "query alert",
          "query": "avg(last_1m):avg:clickhouse.query.insert.failed.total{environment:${aws_account}} > 1",
          "message": "@slack-alerts-${env}-infra \nClickhouse insert queries are failing.",
          "tags": [
              "terraform:true",
              "env:${aws_account}"
          ],
          "options": {
              "groupby_simple_monitor" : false,
              "new_host_delay": 60,
              "thresholds": {
                  "critical":1
              },
              "notify_audit": false,
              "include_tags": true,
              "evaluation_delay": 60,
              "new_group_delay": 60,
              "notify_no_data": false,
              "silenced": {}
          },
          "priority": 1,
          "restricted_roles": null
      }

synthetics:
  ctl_api_uptime:
    name: "${env} - CTL API Uptime"
    type: "api"
    subtype: "http"
    status: "live"
    message: "@slack-alerts-${env}-product"
    locations: ["aws:ca-central-1", "aws:ap-south-1", "aws:eu-west-1"]
    tags: ["service:ctl-api", "terraform:true", "env:${env}"]
    request_definition:
      method: "GET"
      url: "https://api.${env}.nuon.co/livez"
    request_headers: {}
    assertion:
      type: "statusCode"
      operator: "is"
      target: 200
    options_list:
      tick_every: 60
      retry:
        count: 2
        interval: 1000
      monitor_options:
        renotify_interval: 5
      monitor_priority: 2

installer_synthetics:
  installers: {}
  config: {}
