---
pool: nuon
monitors:
  - json: >
      {
          "name": "Stage - Kubernetes Container Waiting",
          "type": "query alert",
          "query": "sum(last_2m):sum:kubernetes.containers.state.waiting{env:stage} by {kube_container_name} > 1",
          "message": "@slack-nuon-alerts-product \n{{kube_container_name.name}} has {{value}} containers waiting.",
          "tags": [],
          "options": {
              "thresholds": {
                  "critical": 1,
                  "warning": 0.5
              },
              "notify_audit": false,
              "include_tags": true,
              "new_group_delay": 60,
              "renotify_interval": 0,
              "escalation_message": "",
              "notify_no_data": false,
              "silenced": {}
          },
          "priority": 2,
          "restricted_roles": null
      }
