import type { TBranchActivityItem } from '@/components/orgs/BranchActivityFeed'
import type { IAnnouncement } from '@/components/orgs/AnnouncementCard'

const minsAgo = (n: number) => new Date(Date.now() - n * 60_000).toISOString()

const enterpriseFleet = [
  { name: 'production-acme', runStatus: 'success', health: 'healthy' },
  { name: 'production-globex', runStatus: 'success', health: 'healthy' },
  { name: 'production-initech', runStatus: 'success', health: 'degraded' },
  { name: 'production-umbrella', runStatus: 'in-progress', health: 'healthy' },
  { name: 'production-soylent', runStatus: 'in-progress', health: 'unknown' },
  { name: 'production-hooli', runStatus: 'failed', health: 'unhealthy' },
  { name: 'production-vehement', runStatus: 'success', health: 'healthy' },
  {
    name: 'production-massive',
    runStatus: 'awaiting-approval',
    health: 'healthy',
  },
  { name: 'production-vandelay', runStatus: 'success', health: 'degraded' },
  { name: 'production-wonka', runStatus: 'success', health: 'healthy' },
].map(({ name, runStatus, health }) => ({
  id: `install-${name}`,
  name,
  group: 'enterprise',
  href: `/org-1/installs/install-${name}`,
  runStatus,
  health,
  rolledOut: runStatus === 'success',
}))

export const dashboardLandingRuns: TBranchActivityItem[] = [
  {
    appId: 'app-acme-payments',
    appName: 'acme-payments',
    appHref: '/org-1/apps/app-acme-payments',
    branchId: 'branch-main',
    branchName: 'main',
    branchHref: '/org-1/apps/app-acme-payments/branches/branch-main',
    runId: 'run-001',
    runStatus: 'awaiting-approval',
    runCreatedAt: minsAgo(4),
    runHref: '/org-1/apps/app-acme-payments/branches/branch-main/runs/run-001',
    commitMessage: 'feat: add stripe checkout flow to payment widget (#142)',
    commitSha: 'a1b2c3d',
    commitAuthor: 'Example Developer',
    commitHref: 'https://github.com/acme/payments/commit/a1b2c3d',
    planGroups: [
      { name: 'canary', installs: 1, hasSelector: false },
      { name: 'enterprise', installs: 10, hasSelector: false },
    ],
    updatedInstalls: [
      {
        id: 'install-staging-example',
        name: 'staging-example',
        group: 'canary',
        href: '/org-1/installs/install-staging-example',
        runStatus: 'success',
        health: 'healthy',
        rolledOut: true,
      },
      ...enterpriseFleet,
    ],
    pendingApprovals: [
      {
        id: 'approval-massive-plan',
        installName: 'production-massive',
        type: 'install group plan',
        href: '/org-1/installs/install-production-massive',
      },
      {
        id: 'approval-soylent-terraform',
        installName: 'production-soylent',
        type: 'terraform',
        href: '/org-1/installs/install-production-soylent',
      },
    ],
  },
  {
    appId: 'app-acme-payments',
    appName: 'acme-payments',
    appHref: '/org-1/apps/app-acme-payments',
    branchId: 'branch-main',
    branchName: 'main',
    branchHref: '/org-1/apps/app-acme-payments/branches/branch-main',
    runId: 'run-001-previous',
    runStatus: 'success',
    runCreatedAt: minsAgo(14),
    runHref:
      '/org-1/apps/app-acme-payments/branches/branch-main/runs/run-001-previous',
    commitMessage: 'fix: preserve cart state after checkout redirect (#141)',
    commitSha: '9f8e7d6',
    commitAuthor: 'Example Developer',
    commitHref: 'https://github.com/acme/payments/commit/9f8e7d6',
    planGroups: [
      { name: 'canary', installs: 1, hasSelector: false },
      { name: 'enterprise', installs: 10, hasSelector: false },
    ],
    updatedInstalls: [
      {
        id: 'install-staging-example',
        name: 'staging-example',
        group: 'canary',
        href: '/org-1/installs/install-staging-example',
        runStatus: 'success',
        health: 'healthy',
        rolledOut: true,
      },
      ...enterpriseFleet.map((install) => ({
        ...install,
        runStatus: 'success',
        rolledOut: true,
      })),
    ],
  },
  {
    appId: 'app-acme-gateway',
    appName: 'acme-gateway',
    appHref: '/org-1/apps/app-acme-gateway',
    branchId: 'branch-feature-rate-limit',
    branchName: 'feature/rate-limit',
    branchHref:
      '/org-1/apps/app-acme-gateway/branches/branch-feature-rate-limit',
    runId: 'run-002',
    runStatus: 'failed',
    runCreatedAt: minsAgo(18),
    runHref:
      '/org-1/apps/app-acme-gateway/branches/branch-feature-rate-limit/runs/run-002',
    commitMessage: 'fix: tighten rate-limit headers for downstream services',
    commitSha: 'f4e5d6c',
    commitAuthor: 'Example Developer',
    commitHref: 'https://github.com/acme/gateway/commit/f4e5d6c',
    planGroups: [{ name: 'customers', installs: 1, hasSelector: true }],
    updatedInstalls: [
      {
        id: 'install-development',
        name: 'development',
        group: 'customers',
        href: '/org-1/installs/install-development',
        runStatus: 'failed',
        health: 'unhealthy',
        rolledOut: false,
      },
    ],
  },
  {
    appId: 'app-acme-portal',
    appName: 'acme-portal',
    appHref: '/org-1/apps/app-acme-portal',
    branchId: 'branch-main',
    branchName: 'main',
    branchHref: '/org-1/apps/app-acme-portal/branches/branch-main',
    runId: 'run-003',
    runStatus: 'in-progress',
    runCreatedAt: minsAgo(2),
    runHref: '/org-1/apps/app-acme-portal/branches/branch-main/runs/run-003',
    commitMessage: 'chore: bump node-fetch to 3.3.2',
    commitSha: '7c8b9a0',
    commitAuthor: 'Example Developer',
    commitHref: 'https://github.com/acme/portal/commit/7c8b9a0',
    planGroups: [
      { name: 'canary', installs: 1, hasSelector: false },
      { name: 'rest', installs: 2, hasSelector: false },
    ],
    updatedInstalls: [
      {
        id: 'install-preview-1042',
        name: 'preview-1042',
        group: 'canary',
        href: '/org-1/installs/install-preview-1042',
        runStatus: 'success',
        health: 'healthy',
        rolledOut: true,
      },
      {
        id: 'install-production-acme',
        name: 'production-acme',
        group: 'rest',
        href: '/org-1/installs/install-production-acme',
        runStatus: 'in-progress',
        health: 'healthy',
        rolledOut: false,
      },
      {
        id: 'install-production-globex',
        name: 'production-globex',
        group: 'rest',
        href: '/org-1/installs/install-production-globex',
        runStatus: 'queued',
        health: 'degraded',
        rolledOut: false,
      },
    ],
  },
  {
    appId: 'app-acme-analytics',
    appName: 'acme-analytics',
    appHref: '/org-1/apps/app-acme-analytics',
    branchId: 'branch-main',
    branchName: 'main',
    branchHref: '/org-1/apps/app-acme-analytics/branches/branch-main',
    runId: 'run-004',
    runStatus: 'success',
    runCreatedAt: minsAgo(45),
    runHref: '/org-1/apps/app-acme-analytics/branches/branch-main/runs/run-004',
    commitMessage: 'feat: add export-to-csv button on reports page (#89)',
    commitSha: '2d3e4f5',
    commitAuthor: 'Example Developer',
    commitHref: 'https://github.com/acme/analytics/commit/2d3e4f5',
    planGroups: [{ name: 'default', installs: 1, hasSelector: false }],
    updatedInstalls: [
      {
        id: 'install-development',
        name: 'development',
        group: 'default',
        href: '/org-1/installs/install-development',
        runStatus: 'success',
        health: 'healthy',
        rolledOut: true,
      },
    ],
  },
  {
    appId: 'app-acme-billing',
    appName: 'acme-billing',
    appHref: '/org-1/apps/app-acme-billing',
    branchId: 'branch-main',
    branchName: 'main',
    branchHref: '/org-1/apps/app-acme-billing/branches/branch-main',
    runId: 'run-005',
    runStatus: 'success',
    runCreatedAt: minsAgo(180),
    runHref: '/org-1/apps/app-acme-billing/branches/branch-main/runs/run-005',
    commitMessage: 'fix: correct EU VAT calculation for B2B invoices',
    commitSha: '9f0a1b2',
    commitAuthor: 'Example Developer',
    commitHref: 'https://github.com/acme/billing/commit/9f0a1b2',
    planGroups: [{ name: 'enterprise', installs: 0, hasSelector: false }],
  },
]

export const dashboardLandingAnnouncements: IAnnouncement[] = [
  {
    id: 'story-1',
    title: 'Multi-cloud support',
    date: 'Apr 28, 2026',
    description: 'Deploy to Azure AKS and GCP GKE clusters alongside AWS EKS.',
    ctaText: 'Learn more',
    ctaUrl: 'https://docs.nuon.co/updates/038-multi-cloud',
    dismissible: false,
  },
  {
    id: 'story-2',
    title: 'Workflow approvals v2',
    date: 'Apr 21, 2026',
    description:
      'Redesigned approval flows with bulk approve and Slack notifications.',
    ctaText: 'Learn more',
    ctaUrl: 'https://docs.nuon.co/updates/037-approvals-v2',
    dismissible: true,
  },
  {
    id: 'story-3',
    title: 'Runner health dashboard',
    date: 'Apr 14, 2026',
    description: 'Monitor runner uptime and resource usage from a single view.',
    ctaText: 'Learn more',
    ctaUrl: 'https://docs.nuon.co/updates/036-runner-health',
    dismissible: true,
  },
  {
    id: 'story-4',
    title: 'Install drift detection',
    date: 'Apr 7, 2026',
    description:
      'Automatic drift detection alerts when install state diverges.',
    ctaText: 'Try now',
    ctaUrl: 'https://docs.nuon.co/updates/035-drift-detection',
    dismissible: true,
  },
]
