VERSION --use-cache-command 0.6

IMPORT github.com/powertoolsdev/shared-configs:main

FROM node:alpine

WORKDIR /usr/src/app

# default arguments for ci
ARG GITHUB_ACTIONS=
ARG EARTHLY_GIT_PROJECT_NAME
ARG GHCR_IMAGE=ghcr.io/${EARTHLY_GIT_PROJECT_NAME}

gql-schema:
  COPY --dir src/gql-schema /services/api-gateway/src/
  SAVE ARTIFACT /services

deps:
    RUN apk add --update build-base \
      make \
      python3 \
      py3-pip

    COPY \
      .eslintrc \
      .npmrc \
      .prettierrc \
      jest.config.js \
      package-lock.json \
      package.json \
      tsconfig.build.json \
      tsconfig.json \
     ./
  RUN \
    --secret GITHUB_TOKEN \
    NUON_NPM_GITHUB_TOKEN=$GITHUB_TOKEN \
    npm ci

  COPY --dir src src
  COPY ../../pkg+code/pkg/types/build src/build

test-integration:
  RUN echo "noop..."

lint:
  FROM +deps
  RUN echo "running type check..." && \
    npm run typecheck

  RUN echo "running lint..." && \
    npm run lint

test:
  FROM +deps
  RUN echo "running unit tests..." && \
    npm run test:unit

build:
  FROM +deps
  RUN npm run build
  SAVE ARTIFACT /usr/src/app/dist /dist

docker:
  FROM +build
  EXPOSE 3000
  ARG repo
  ARG image_tag
  ENTRYPOINT ["node", "./dist/src/main.js"]
  LABEL org.opencontainers.image.created=$EARTHLY_SOURCE_DATE_EPOCH
  LABEL org.opencontainers.image.revision=$EARTHLY_BUILD_SHA
  LABEL org.opencontainers.image.version=$IMAGE_TAG
  LABEL org.opencontainers.image.source=$EARTHLY_GIT_ORIGIN_URL
  LABEL org.opencontainers.image.authors=nuon
  LABEL org.opencontainers.image.vendor=nuon
  SAVE IMAGE --push $repo:$image_tag
