import type { TAppInstallListItem } from './AppInstallsList'

export const mockAppInstalls: TAppInstallListItem[] = [
  {
    id: 'install-production-acme',
    name: 'production-acme',
    href: '/org-1/installs/install-production-acme',
    group: 'enterprise',
    lastAppliedCommit: {
      sha: '85d067ecafe1234',
      message: 'bump api image to v1.42.0',
      appliedAt: '2026-09-24T17:42:00Z',
      href: 'https://github.com/acme/platform-configs/commit/85d067ecafe1234',
      isExternal: true,
    },
    deployments: { status: 'active', detail: 'All deployments are active' },
    resources: { status: 'active', detail: 'All resources are deployed' },
    healthChecks: { status: 'healthy', detail: 'All health checks pass' },
  },
  {
    id: 'install-staging-example',
    name: 'staging-example',
    href: '/org-1/installs/install-staging-example',
    group: 'staging',
    lastAppliedCommit: {
      sha: '6987a43568abc82',
      message: 'add new worker component',
      appliedAt: '2026-09-24T16:10:00Z',
      href: 'https://github.com/acme/platform-configs/commit/6987a43568abc82',
      isExternal: true,
    },
    deployments: { status: 'in-progress', detail: 'Deployment in progress' },
    resources: { status: 'pending', detail: '3 resources pending' },
    healthChecks: { status: 'unknown', detail: 'Health checks pending' },
  },
  {
    id: 'install-production-globex',
    name: 'production-globex',
    href: '/org-1/installs/install-production-globex',
    group: 'enterprise',
    lastAppliedCommit: {
      sha: 'b926ce5db442161',
      message: 'fix database connection pooling',
      appliedAt: '2026-09-24T12:30:00Z',
      href: 'https://github.com/acme/platform-configs/commit/b926ce5db442161',
      isExternal: true,
    },
    deployments: { status: 'error', detail: '1 deployment failed' },
    resources: { status: 'error', detail: '2 resources have issues' },
    healthChecks: { status: 'unhealthy', detail: '1 health check failed' },
  },
  {
    id: 'install-preview-1042',
    name: 'preview-1042',
    href: '/org-1/installs/install-preview-1042',
    group: 'previews',
    lastAppliedCommit: {
      sha: 'c18aaf407bcd513',
      message: 'configure preview environment',
      appliedAt: '2026-09-23T22:15:00Z',
      href: 'https://github.com/acme/platform-configs/commit/c18aaf407bcd513',
      isExternal: true,
    },
    deployments: { status: 'active', detail: 'All deployments are active' },
    resources: { status: 'warn', detail: '1 resource is degraded' },
    healthChecks: { status: 'degraded', detail: 'Health checks are degraded' },
  },
  {
    id: 'install-development',
    name: 'development',
    href: '/org-1/installs/install-development',
    deployments: { status: 'active' },
    resources: { status: 'active' },
    healthChecks: { status: 'healthy' },
  },
]
