// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: apps/v1/project/v1/workflow.proto

package projectv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProvisionProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty" faker:"shortID"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" faker:"shortID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionProjectRequest) Reset() {
	*x = ProvisionProjectRequest{}
	mi := &file_apps_v1_project_v1_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionProjectRequest) ProtoMessage() {}

func (x *ProvisionProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_v1_project_v1_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionProjectRequest.ProtoReflect.Descriptor instead.
func (*ProvisionProjectRequest) Descriptor() ([]byte, []int) {
	return file_apps_v1_project_v1_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *ProvisionProjectRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ProvisionProjectRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type ProvisionProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionProjectResponse) Reset() {
	*x = ProvisionProjectResponse{}
	mi := &file_apps_v1_project_v1_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionProjectResponse) ProtoMessage() {}

func (x *ProvisionProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_v1_project_v1_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionProjectResponse.ProtoReflect.Descriptor instead.
func (*ProvisionProjectResponse) Descriptor() ([]byte, []int) {
	return file_apps_v1_project_v1_workflow_proto_rawDescGZIP(), []int{1}
}

var File_apps_v1_project_v1_workflow_proto protoreflect.FileDescriptor

const file_apps_v1_project_v1_workflow_proto_rawDesc = "" +
	"\n" +
	"!apps/v1/project/v1/workflow.proto\x12\x12apps.v1.project.v1\x1a\x13tagger/tagger.proto\x1a\x17validate/validate.proto\"\x83\x01\n" +
	"\x17ProvisionProjectRequest\x123\n" +
	"\x06org_id\x18\x01 \x01(\tB\x1c\xfaB\x05r\x03\x98\x01\x1a\x9a\x84\x9e\x03\x0ffaker:\"shortID\"R\x05orgId\x123\n" +
	"\x06app_id\x18\x02 \x01(\tB\x1c\xfaB\x05r\x03\x98\x01\x1a\x9a\x84\x9e\x03\x0ffaker:\"shortID\"R\x05appId\"\x1a\n" +
	"\x18ProvisionProjectResponseB\xe2\x01\n" +
	"\x16com.apps.v1.project.v1B\rWorkflowProtoP\x01ZNgithub.com/powertoolsdev/mono/pkg/types/workflows/apps/v1/project/v1;projectv1\xa2\x02\x03AVP\xaa\x02\x12Apps.V1.Project.V1\xca\x02\x12Apps\\V1\\Project\\V1\xe2\x02\x1eApps\\V1\\Project\\V1\\GPBMetadata\xea\x02\x15Apps::V1::Project::V1b\x06proto3"

var (
	file_apps_v1_project_v1_workflow_proto_rawDescOnce sync.Once
	file_apps_v1_project_v1_workflow_proto_rawDescData []byte
)

func file_apps_v1_project_v1_workflow_proto_rawDescGZIP() []byte {
	file_apps_v1_project_v1_workflow_proto_rawDescOnce.Do(func() {
		file_apps_v1_project_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_v1_project_v1_workflow_proto_rawDesc), len(file_apps_v1_project_v1_workflow_proto_rawDesc)))
	})
	return file_apps_v1_project_v1_workflow_proto_rawDescData
}

var file_apps_v1_project_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apps_v1_project_v1_workflow_proto_goTypes = []any{
	(*ProvisionProjectRequest)(nil),  // 0: apps.v1.project.v1.ProvisionProjectRequest
	(*ProvisionProjectResponse)(nil), // 1: apps.v1.project.v1.ProvisionProjectResponse
}
var file_apps_v1_project_v1_workflow_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_v1_project_v1_workflow_proto_init() }
func file_apps_v1_project_v1_workflow_proto_init() {
	if File_apps_v1_project_v1_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_v1_project_v1_workflow_proto_rawDesc), len(file_apps_v1_project_v1_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_v1_project_v1_workflow_proto_goTypes,
		DependencyIndexes: file_apps_v1_project_v1_workflow_proto_depIdxs,
		MessageInfos:      file_apps_v1_project_v1_workflow_proto_msgTypes,
	}.Build()
	File_apps_v1_project_v1_workflow_proto = out.File
	file_apps_v1_project_v1_workflow_proto_goTypes = nil
	file_apps_v1_project_v1_workflow_proto_depIdxs = nil
}
