---
name: action-setup-helm
description: |
  Sets up helm by install helm itself, common plugins, and updating dependencies
author: "@powertoolsdev/team"
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  helm_dir:
    description: |
      The directory containing the chart
      Probably needs aws credentials configured before invoking this action
    default: k8s
  repos:
    description: |
      A comma delimited list of name=url key values to add as repos
    default: ""

runs:
  using: 'composite'
  steps:
    # NOTE(jdt): this will set our scripts to trace mode if workflow is ran in "debug"
    - shell: bash
      # run: echo "TRACE=${RUNNER_DEBUG}" >> "$GITHUB_ENV"
      run: echo "TRACE=1" >> "$GITHUB_ENV"

    - uses: azure/setup-helm@v3.5
      with:
        token: ${{ inputs.github_token }}

    # install plugins
    - shell: bash
      working-directory: ${{ inputs.helm_dir }}
      run: $GITHUB_ACTION_PATH/install.sh

    # update dependencies
    - shell: bash
      working-directory: ${{ inputs.helm_dir }}
      run: |
        helm dependency update

    # add repos
    - shell: bash
      run: |
        [[ -n "${TRACE:-}" ]] && set -x

        IFS=',' read -ra repos <<< "${{ inputs.repos }}"
        for repo_pair in "${repos[@]}";
        do
          while IFS='=' read -r repo url;
          do
            helm repo add "$repo" "$url";
          done <<< "$repo_pair"
        done


branding:
  icon: 'check'
  color: 'blue'
