//  THIS FILE IS GENERATED. DO NOT EDIT.
//  Generated by temporal-gen-v2

package activities

import (
	"context"
	"time"

	"github.com/nuonco/nuon/services/ctl-api/internal/pkg/queue/handler"
	"go.temporal.io/sdk/temporal"
	"go.temporal.io/sdk/workflow"
)

type UpdateWorkflowExecuteRequest struct {
	WorkflowID string `validate:"required"`
	UpdateID   string `validate:"required"`
	QueueID    string `validate:"required"`
}

// HandlerInternalUpdateWorkflowExecute is a wrapper for the updateWorkflowExecute activity
func (a *Activities) HandlerInternalUpdateWorkflowExecute(ctx context.Context, req UpdateWorkflowExecuteRequest) (*handler.ExecuteResponse, error) {
	return a.updateWorkflowExecute(ctx, req.WorkflowID, req.UpdateID, req.QueueID)
}

// AwaitUpdateWorkflowExecute is a wrapper for the UpdateWorkflowExecute activity
func AwaitUpdateWorkflowExecute(ctx workflow.Context, input UpdateWorkflowExecuteRequest, opts ...*workflow.ActivityOptions) (*handler.ExecuteResponse, error) {
	var result *handler.ExecuteResponse
	options := workflow.GetActivityOptions(ctx)
	options.StartToCloseTimeout = time.Duration(7200000000000)
	options.RetryPolicy = &temporal.RetryPolicy{
		MaximumAttempts: int32(1),
	}

	for _, opt := range opts {
		if opt != nil {
			if opt.TaskQueue != "" {
				options.TaskQueue = opt.TaskQueue
			}
			if opt.ScheduleToCloseTimeout != 0 {
				options.ScheduleToCloseTimeout = opt.ScheduleToCloseTimeout
			}
			if opt.StartToCloseTimeout != 0 {
				options.StartToCloseTimeout = opt.StartToCloseTimeout
			}
			if opt.ScheduleToStartTimeout != 0 {
				options.ScheduleToStartTimeout = opt.ScheduleToStartTimeout
			}
			if opt.HeartbeatTimeout != 0 {
				options.HeartbeatTimeout = opt.HeartbeatTimeout
			}
			if opt.WaitForCancellation {
				options.WaitForCancellation = opt.WaitForCancellation
			}
			if opt.ActivityID != "" {
				options.ActivityID = opt.ActivityID
			}
			if opt.RetryPolicy != nil {
				options.RetryPolicy = opt.RetryPolicy
			}
			if opt.DisableEagerExecution {
				options.DisableEagerExecution = opt.DisableEagerExecution
			}
		}
	}

	ctx = workflow.WithActivityOptions(ctx, options)
	err := workflow.ExecuteActivity(ctx, (*Activities).HandlerInternalUpdateWorkflowExecute, input).Get(ctx, &result)
	return result, err
}

// AwaitUpdateWorkflowExecuteByWorkflowID is a wrapper for the UpdateWorkflowExecute activity
func AwaitUpdateWorkflowExecuteByWorkflowID(ctx workflow.Context, input string, opts ...*workflow.ActivityOptions) (*handler.ExecuteResponse, error) {
	req := UpdateWorkflowExecuteRequest{
		WorkflowID: input,
	}
	return AwaitUpdateWorkflowExecute(ctx, req, opts...)
}
