// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// NewCancelInstallRunnerJobParams creates a new CancelInstallRunnerJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCancelInstallRunnerJobParams() *CancelInstallRunnerJobParams {
	return &CancelInstallRunnerJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCancelInstallRunnerJobParamsWithTimeout creates a new CancelInstallRunnerJobParams object
// with the ability to set a timeout on a request.
func NewCancelInstallRunnerJobParamsWithTimeout(timeout time.Duration) *CancelInstallRunnerJobParams {
	return &CancelInstallRunnerJobParams{
		timeout: timeout,
	}
}

// NewCancelInstallRunnerJobParamsWithContext creates a new CancelInstallRunnerJobParams object
// with the ability to set a context for a request.
func NewCancelInstallRunnerJobParamsWithContext(ctx context.Context) *CancelInstallRunnerJobParams {
	return &CancelInstallRunnerJobParams{
		Context: ctx,
	}
}

// NewCancelInstallRunnerJobParamsWithHTTPClient creates a new CancelInstallRunnerJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewCancelInstallRunnerJobParamsWithHTTPClient(client *http.Client) *CancelInstallRunnerJobParams {
	return &CancelInstallRunnerJobParams{
		HTTPClient: client,
	}
}

/*
CancelInstallRunnerJobParams contains all the parameters to send to the API endpoint

	for the cancel install runner job operation.

	Typically these are written to a http.Request.
*/
type CancelInstallRunnerJobParams struct {

	/* InstallID.

	   install ID
	*/
	InstallID string

	/* Req.

	   Input
	*/
	Req models.ServiceCancelRunnerJobRequest

	/* RunnerJobID.

	   runner job ID
	*/
	RunnerJobID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cancel install runner job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CancelInstallRunnerJobParams) WithDefaults() *CancelInstallRunnerJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cancel install runner job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CancelInstallRunnerJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cancel install runner job params
func (o *CancelInstallRunnerJobParams) WithTimeout(timeout time.Duration) *CancelInstallRunnerJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cancel install runner job params
func (o *CancelInstallRunnerJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cancel install runner job params
func (o *CancelInstallRunnerJobParams) WithContext(ctx context.Context) *CancelInstallRunnerJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cancel install runner job params
func (o *CancelInstallRunnerJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cancel install runner job params
func (o *CancelInstallRunnerJobParams) WithHTTPClient(client *http.Client) *CancelInstallRunnerJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cancel install runner job params
func (o *CancelInstallRunnerJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstallID adds the installID to the cancel install runner job params
func (o *CancelInstallRunnerJobParams) WithInstallID(installID string) *CancelInstallRunnerJobParams {
	o.SetInstallID(installID)
	return o
}

// SetInstallID adds the installId to the cancel install runner job params
func (o *CancelInstallRunnerJobParams) SetInstallID(installID string) {
	o.InstallID = installID
}

// WithReq adds the req to the cancel install runner job params
func (o *CancelInstallRunnerJobParams) WithReq(req models.ServiceCancelRunnerJobRequest) *CancelInstallRunnerJobParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the cancel install runner job params
func (o *CancelInstallRunnerJobParams) SetReq(req models.ServiceCancelRunnerJobRequest) {
	o.Req = req
}

// WithRunnerJobID adds the runnerJobID to the cancel install runner job params
func (o *CancelInstallRunnerJobParams) WithRunnerJobID(runnerJobID string) *CancelInstallRunnerJobParams {
	o.SetRunnerJobID(runnerJobID)
	return o
}

// SetRunnerJobID adds the runnerJobId to the cancel install runner job params
func (o *CancelInstallRunnerJobParams) SetRunnerJobID(runnerJobID string) {
	o.RunnerJobID = runnerJobID
}

// WriteToRequest writes these params to a swagger request
func (o *CancelInstallRunnerJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param install_id
	if err := r.SetPathParam("install_id", o.InstallID); err != nil {
		return err
	}
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	// path param runner_job_id
	if err := r.SetPathParam("runner_job_id", o.RunnerJobID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
