// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// CreateWorkflowStepApprovalResponseByAppBranchReader is a Reader for the CreateWorkflowStepApprovalResponseByAppBranch structure.
type CreateWorkflowStepApprovalResponseByAppBranchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateWorkflowStepApprovalResponseByAppBranchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewCreateWorkflowStepApprovalResponseByAppBranchCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateWorkflowStepApprovalResponseByAppBranchBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateWorkflowStepApprovalResponseByAppBranchUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateWorkflowStepApprovalResponseByAppBranchForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateWorkflowStepApprovalResponseByAppBranchNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateWorkflowStepApprovalResponseByAppBranchConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateWorkflowStepApprovalResponseByAppBranchInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/steps/{{step_id}}/approvals/{{approval_id}}/response] CreateWorkflowStepApprovalResponseByAppBranch", response, response.Code())
	}
}

// NewCreateWorkflowStepApprovalResponseByAppBranchCreated creates a CreateWorkflowStepApprovalResponseByAppBranchCreated with default headers values
func NewCreateWorkflowStepApprovalResponseByAppBranchCreated() *CreateWorkflowStepApprovalResponseByAppBranchCreated {
	return &CreateWorkflowStepApprovalResponseByAppBranchCreated{}
}

/*
CreateWorkflowStepApprovalResponseByAppBranchCreated describes a response with status code 201, with default header values.

Created
*/
type CreateWorkflowStepApprovalResponseByAppBranchCreated struct {
	Payload *models.ServiceCreateWorkflowStepApprovalResponseResponse
}

// IsSuccess returns true when this create workflow step approval response by app branch created response has a 2xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create workflow step approval response by app branch created response has a 3xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create workflow step approval response by app branch created response has a 4xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create workflow step approval response by app branch created response has a 5xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create workflow step approval response by app branch created response a status code equal to that given
func (o *CreateWorkflowStepApprovalResponseByAppBranchCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create workflow step approval response by app branch created response
func (o *CreateWorkflowStepApprovalResponseByAppBranchCreated) Code() int {
	return 201
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/steps/{{step_id}}/approvals/{{approval_id}}/response][%d] createWorkflowStepApprovalResponseByAppBranchCreated %s", 201, payload)
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/steps/{{step_id}}/approvals/{{approval_id}}/response][%d] createWorkflowStepApprovalResponseByAppBranchCreated %s", 201, payload)
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchCreated) GetPayload() *models.ServiceCreateWorkflowStepApprovalResponseResponse {
	return o.Payload
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceCreateWorkflowStepApprovalResponseResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateWorkflowStepApprovalResponseByAppBranchBadRequest creates a CreateWorkflowStepApprovalResponseByAppBranchBadRequest with default headers values
func NewCreateWorkflowStepApprovalResponseByAppBranchBadRequest() *CreateWorkflowStepApprovalResponseByAppBranchBadRequest {
	return &CreateWorkflowStepApprovalResponseByAppBranchBadRequest{}
}

/*
CreateWorkflowStepApprovalResponseByAppBranchBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateWorkflowStepApprovalResponseByAppBranchBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create workflow step approval response by app branch bad request response has a 2xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create workflow step approval response by app branch bad request response has a 3xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create workflow step approval response by app branch bad request response has a 4xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create workflow step approval response by app branch bad request response has a 5xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create workflow step approval response by app branch bad request response a status code equal to that given
func (o *CreateWorkflowStepApprovalResponseByAppBranchBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create workflow step approval response by app branch bad request response
func (o *CreateWorkflowStepApprovalResponseByAppBranchBadRequest) Code() int {
	return 400
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/steps/{{step_id}}/approvals/{{approval_id}}/response][%d] createWorkflowStepApprovalResponseByAppBranchBadRequest %s", 400, payload)
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/steps/{{step_id}}/approvals/{{approval_id}}/response][%d] createWorkflowStepApprovalResponseByAppBranchBadRequest %s", 400, payload)
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateWorkflowStepApprovalResponseByAppBranchUnauthorized creates a CreateWorkflowStepApprovalResponseByAppBranchUnauthorized with default headers values
func NewCreateWorkflowStepApprovalResponseByAppBranchUnauthorized() *CreateWorkflowStepApprovalResponseByAppBranchUnauthorized {
	return &CreateWorkflowStepApprovalResponseByAppBranchUnauthorized{}
}

/*
CreateWorkflowStepApprovalResponseByAppBranchUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateWorkflowStepApprovalResponseByAppBranchUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create workflow step approval response by app branch unauthorized response has a 2xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create workflow step approval response by app branch unauthorized response has a 3xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create workflow step approval response by app branch unauthorized response has a 4xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create workflow step approval response by app branch unauthorized response has a 5xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create workflow step approval response by app branch unauthorized response a status code equal to that given
func (o *CreateWorkflowStepApprovalResponseByAppBranchUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create workflow step approval response by app branch unauthorized response
func (o *CreateWorkflowStepApprovalResponseByAppBranchUnauthorized) Code() int {
	return 401
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/steps/{{step_id}}/approvals/{{approval_id}}/response][%d] createWorkflowStepApprovalResponseByAppBranchUnauthorized %s", 401, payload)
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/steps/{{step_id}}/approvals/{{approval_id}}/response][%d] createWorkflowStepApprovalResponseByAppBranchUnauthorized %s", 401, payload)
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateWorkflowStepApprovalResponseByAppBranchForbidden creates a CreateWorkflowStepApprovalResponseByAppBranchForbidden with default headers values
func NewCreateWorkflowStepApprovalResponseByAppBranchForbidden() *CreateWorkflowStepApprovalResponseByAppBranchForbidden {
	return &CreateWorkflowStepApprovalResponseByAppBranchForbidden{}
}

/*
CreateWorkflowStepApprovalResponseByAppBranchForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateWorkflowStepApprovalResponseByAppBranchForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create workflow step approval response by app branch forbidden response has a 2xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create workflow step approval response by app branch forbidden response has a 3xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create workflow step approval response by app branch forbidden response has a 4xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create workflow step approval response by app branch forbidden response has a 5xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create workflow step approval response by app branch forbidden response a status code equal to that given
func (o *CreateWorkflowStepApprovalResponseByAppBranchForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create workflow step approval response by app branch forbidden response
func (o *CreateWorkflowStepApprovalResponseByAppBranchForbidden) Code() int {
	return 403
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/steps/{{step_id}}/approvals/{{approval_id}}/response][%d] createWorkflowStepApprovalResponseByAppBranchForbidden %s", 403, payload)
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/steps/{{step_id}}/approvals/{{approval_id}}/response][%d] createWorkflowStepApprovalResponseByAppBranchForbidden %s", 403, payload)
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateWorkflowStepApprovalResponseByAppBranchNotFound creates a CreateWorkflowStepApprovalResponseByAppBranchNotFound with default headers values
func NewCreateWorkflowStepApprovalResponseByAppBranchNotFound() *CreateWorkflowStepApprovalResponseByAppBranchNotFound {
	return &CreateWorkflowStepApprovalResponseByAppBranchNotFound{}
}

/*
CreateWorkflowStepApprovalResponseByAppBranchNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CreateWorkflowStepApprovalResponseByAppBranchNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create workflow step approval response by app branch not found response has a 2xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create workflow step approval response by app branch not found response has a 3xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create workflow step approval response by app branch not found response has a 4xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create workflow step approval response by app branch not found response has a 5xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create workflow step approval response by app branch not found response a status code equal to that given
func (o *CreateWorkflowStepApprovalResponseByAppBranchNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the create workflow step approval response by app branch not found response
func (o *CreateWorkflowStepApprovalResponseByAppBranchNotFound) Code() int {
	return 404
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/steps/{{step_id}}/approvals/{{approval_id}}/response][%d] createWorkflowStepApprovalResponseByAppBranchNotFound %s", 404, payload)
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/steps/{{step_id}}/approvals/{{approval_id}}/response][%d] createWorkflowStepApprovalResponseByAppBranchNotFound %s", 404, payload)
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateWorkflowStepApprovalResponseByAppBranchConflict creates a CreateWorkflowStepApprovalResponseByAppBranchConflict with default headers values
func NewCreateWorkflowStepApprovalResponseByAppBranchConflict() *CreateWorkflowStepApprovalResponseByAppBranchConflict {
	return &CreateWorkflowStepApprovalResponseByAppBranchConflict{}
}

/*
CreateWorkflowStepApprovalResponseByAppBranchConflict describes a response with status code 409, with default header values.

Conflict
*/
type CreateWorkflowStepApprovalResponseByAppBranchConflict struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create workflow step approval response by app branch conflict response has a 2xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create workflow step approval response by app branch conflict response has a 3xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create workflow step approval response by app branch conflict response has a 4xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this create workflow step approval response by app branch conflict response has a 5xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this create workflow step approval response by app branch conflict response a status code equal to that given
func (o *CreateWorkflowStepApprovalResponseByAppBranchConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the create workflow step approval response by app branch conflict response
func (o *CreateWorkflowStepApprovalResponseByAppBranchConflict) Code() int {
	return 409
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/steps/{{step_id}}/approvals/{{approval_id}}/response][%d] createWorkflowStepApprovalResponseByAppBranchConflict %s", 409, payload)
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/steps/{{step_id}}/approvals/{{approval_id}}/response][%d] createWorkflowStepApprovalResponseByAppBranchConflict %s", 409, payload)
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchConflict) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateWorkflowStepApprovalResponseByAppBranchInternalServerError creates a CreateWorkflowStepApprovalResponseByAppBranchInternalServerError with default headers values
func NewCreateWorkflowStepApprovalResponseByAppBranchInternalServerError() *CreateWorkflowStepApprovalResponseByAppBranchInternalServerError {
	return &CreateWorkflowStepApprovalResponseByAppBranchInternalServerError{}
}

/*
CreateWorkflowStepApprovalResponseByAppBranchInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateWorkflowStepApprovalResponseByAppBranchInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create workflow step approval response by app branch internal server error response has a 2xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create workflow step approval response by app branch internal server error response has a 3xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create workflow step approval response by app branch internal server error response has a 4xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create workflow step approval response by app branch internal server error response has a 5xx status code
func (o *CreateWorkflowStepApprovalResponseByAppBranchInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create workflow step approval response by app branch internal server error response a status code equal to that given
func (o *CreateWorkflowStepApprovalResponseByAppBranchInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create workflow step approval response by app branch internal server error response
func (o *CreateWorkflowStepApprovalResponseByAppBranchInternalServerError) Code() int {
	return 500
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/steps/{{step_id}}/approvals/{{approval_id}}/response][%d] createWorkflowStepApprovalResponseByAppBranchInternalServerError %s", 500, payload)
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/steps/{{step_id}}/approvals/{{approval_id}}/response][%d] createWorkflowStepApprovalResponseByAppBranchInternalServerError %s", 500, payload)
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateWorkflowStepApprovalResponseByAppBranchInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
