// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// CreateServiceAccountTokenReader is a Reader for the CreateServiceAccountToken structure.
type CreateServiceAccountTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateServiceAccountTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewCreateServiceAccountTokenCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateServiceAccountTokenBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateServiceAccountTokenUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateServiceAccountTokenForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateServiceAccountTokenNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateServiceAccountTokenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/service-accounts/{account_id}/tokens] CreateServiceAccountToken", response, response.Code())
	}
}

// NewCreateServiceAccountTokenCreated creates a CreateServiceAccountTokenCreated with default headers values
func NewCreateServiceAccountTokenCreated() *CreateServiceAccountTokenCreated {
	return &CreateServiceAccountTokenCreated{}
}

/*
CreateServiceAccountTokenCreated describes a response with status code 201, with default header values.

Created
*/
type CreateServiceAccountTokenCreated struct {
	Payload *models.ServiceCreateServiceAccountTokenResponse
}

// IsSuccess returns true when this create service account token created response has a 2xx status code
func (o *CreateServiceAccountTokenCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create service account token created response has a 3xx status code
func (o *CreateServiceAccountTokenCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create service account token created response has a 4xx status code
func (o *CreateServiceAccountTokenCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create service account token created response has a 5xx status code
func (o *CreateServiceAccountTokenCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create service account token created response a status code equal to that given
func (o *CreateServiceAccountTokenCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create service account token created response
func (o *CreateServiceAccountTokenCreated) Code() int {
	return 201
}

func (o *CreateServiceAccountTokenCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/service-accounts/{account_id}/tokens][%d] createServiceAccountTokenCreated %s", 201, payload)
}

func (o *CreateServiceAccountTokenCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/service-accounts/{account_id}/tokens][%d] createServiceAccountTokenCreated %s", 201, payload)
}

func (o *CreateServiceAccountTokenCreated) GetPayload() *models.ServiceCreateServiceAccountTokenResponse {
	return o.Payload
}

func (o *CreateServiceAccountTokenCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceCreateServiceAccountTokenResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateServiceAccountTokenBadRequest creates a CreateServiceAccountTokenBadRequest with default headers values
func NewCreateServiceAccountTokenBadRequest() *CreateServiceAccountTokenBadRequest {
	return &CreateServiceAccountTokenBadRequest{}
}

/*
CreateServiceAccountTokenBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateServiceAccountTokenBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create service account token bad request response has a 2xx status code
func (o *CreateServiceAccountTokenBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create service account token bad request response has a 3xx status code
func (o *CreateServiceAccountTokenBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create service account token bad request response has a 4xx status code
func (o *CreateServiceAccountTokenBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create service account token bad request response has a 5xx status code
func (o *CreateServiceAccountTokenBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create service account token bad request response a status code equal to that given
func (o *CreateServiceAccountTokenBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create service account token bad request response
func (o *CreateServiceAccountTokenBadRequest) Code() int {
	return 400
}

func (o *CreateServiceAccountTokenBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/service-accounts/{account_id}/tokens][%d] createServiceAccountTokenBadRequest %s", 400, payload)
}

func (o *CreateServiceAccountTokenBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/service-accounts/{account_id}/tokens][%d] createServiceAccountTokenBadRequest %s", 400, payload)
}

func (o *CreateServiceAccountTokenBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateServiceAccountTokenBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateServiceAccountTokenUnauthorized creates a CreateServiceAccountTokenUnauthorized with default headers values
func NewCreateServiceAccountTokenUnauthorized() *CreateServiceAccountTokenUnauthorized {
	return &CreateServiceAccountTokenUnauthorized{}
}

/*
CreateServiceAccountTokenUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateServiceAccountTokenUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create service account token unauthorized response has a 2xx status code
func (o *CreateServiceAccountTokenUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create service account token unauthorized response has a 3xx status code
func (o *CreateServiceAccountTokenUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create service account token unauthorized response has a 4xx status code
func (o *CreateServiceAccountTokenUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create service account token unauthorized response has a 5xx status code
func (o *CreateServiceAccountTokenUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create service account token unauthorized response a status code equal to that given
func (o *CreateServiceAccountTokenUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create service account token unauthorized response
func (o *CreateServiceAccountTokenUnauthorized) Code() int {
	return 401
}

func (o *CreateServiceAccountTokenUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/service-accounts/{account_id}/tokens][%d] createServiceAccountTokenUnauthorized %s", 401, payload)
}

func (o *CreateServiceAccountTokenUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/service-accounts/{account_id}/tokens][%d] createServiceAccountTokenUnauthorized %s", 401, payload)
}

func (o *CreateServiceAccountTokenUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateServiceAccountTokenUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateServiceAccountTokenForbidden creates a CreateServiceAccountTokenForbidden with default headers values
func NewCreateServiceAccountTokenForbidden() *CreateServiceAccountTokenForbidden {
	return &CreateServiceAccountTokenForbidden{}
}

/*
CreateServiceAccountTokenForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateServiceAccountTokenForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create service account token forbidden response has a 2xx status code
func (o *CreateServiceAccountTokenForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create service account token forbidden response has a 3xx status code
func (o *CreateServiceAccountTokenForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create service account token forbidden response has a 4xx status code
func (o *CreateServiceAccountTokenForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create service account token forbidden response has a 5xx status code
func (o *CreateServiceAccountTokenForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create service account token forbidden response a status code equal to that given
func (o *CreateServiceAccountTokenForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create service account token forbidden response
func (o *CreateServiceAccountTokenForbidden) Code() int {
	return 403
}

func (o *CreateServiceAccountTokenForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/service-accounts/{account_id}/tokens][%d] createServiceAccountTokenForbidden %s", 403, payload)
}

func (o *CreateServiceAccountTokenForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/service-accounts/{account_id}/tokens][%d] createServiceAccountTokenForbidden %s", 403, payload)
}

func (o *CreateServiceAccountTokenForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateServiceAccountTokenForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateServiceAccountTokenNotFound creates a CreateServiceAccountTokenNotFound with default headers values
func NewCreateServiceAccountTokenNotFound() *CreateServiceAccountTokenNotFound {
	return &CreateServiceAccountTokenNotFound{}
}

/*
CreateServiceAccountTokenNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CreateServiceAccountTokenNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create service account token not found response has a 2xx status code
func (o *CreateServiceAccountTokenNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create service account token not found response has a 3xx status code
func (o *CreateServiceAccountTokenNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create service account token not found response has a 4xx status code
func (o *CreateServiceAccountTokenNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create service account token not found response has a 5xx status code
func (o *CreateServiceAccountTokenNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create service account token not found response a status code equal to that given
func (o *CreateServiceAccountTokenNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the create service account token not found response
func (o *CreateServiceAccountTokenNotFound) Code() int {
	return 404
}

func (o *CreateServiceAccountTokenNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/service-accounts/{account_id}/tokens][%d] createServiceAccountTokenNotFound %s", 404, payload)
}

func (o *CreateServiceAccountTokenNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/service-accounts/{account_id}/tokens][%d] createServiceAccountTokenNotFound %s", 404, payload)
}

func (o *CreateServiceAccountTokenNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateServiceAccountTokenNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateServiceAccountTokenInternalServerError creates a CreateServiceAccountTokenInternalServerError with default headers values
func NewCreateServiceAccountTokenInternalServerError() *CreateServiceAccountTokenInternalServerError {
	return &CreateServiceAccountTokenInternalServerError{}
}

/*
CreateServiceAccountTokenInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateServiceAccountTokenInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create service account token internal server error response has a 2xx status code
func (o *CreateServiceAccountTokenInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create service account token internal server error response has a 3xx status code
func (o *CreateServiceAccountTokenInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create service account token internal server error response has a 4xx status code
func (o *CreateServiceAccountTokenInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create service account token internal server error response has a 5xx status code
func (o *CreateServiceAccountTokenInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create service account token internal server error response a status code equal to that given
func (o *CreateServiceAccountTokenInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create service account token internal server error response
func (o *CreateServiceAccountTokenInternalServerError) Code() int {
	return 500
}

func (o *CreateServiceAccountTokenInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/service-accounts/{account_id}/tokens][%d] createServiceAccountTokenInternalServerError %s", 500, payload)
}

func (o *CreateServiceAccountTokenInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/service-accounts/{account_id}/tokens][%d] createServiceAccountTokenInternalServerError %s", 500, payload)
}

func (o *CreateServiceAccountTokenInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateServiceAccountTokenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
