// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// NewCreateCustomerManagedBundleBlobGrantsParams creates a new CreateCustomerManagedBundleBlobGrantsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateCustomerManagedBundleBlobGrantsParams() *CreateCustomerManagedBundleBlobGrantsParams {
	return &CreateCustomerManagedBundleBlobGrantsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCustomerManagedBundleBlobGrantsParamsWithTimeout creates a new CreateCustomerManagedBundleBlobGrantsParams object
// with the ability to set a timeout on a request.
func NewCreateCustomerManagedBundleBlobGrantsParamsWithTimeout(timeout time.Duration) *CreateCustomerManagedBundleBlobGrantsParams {
	return &CreateCustomerManagedBundleBlobGrantsParams{
		timeout: timeout,
	}
}

// NewCreateCustomerManagedBundleBlobGrantsParamsWithContext creates a new CreateCustomerManagedBundleBlobGrantsParams object
// with the ability to set a context for a request.
func NewCreateCustomerManagedBundleBlobGrantsParamsWithContext(ctx context.Context) *CreateCustomerManagedBundleBlobGrantsParams {
	return &CreateCustomerManagedBundleBlobGrantsParams{
		Context: ctx,
	}
}

// NewCreateCustomerManagedBundleBlobGrantsParamsWithHTTPClient creates a new CreateCustomerManagedBundleBlobGrantsParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateCustomerManagedBundleBlobGrantsParamsWithHTTPClient(client *http.Client) *CreateCustomerManagedBundleBlobGrantsParams {
	return &CreateCustomerManagedBundleBlobGrantsParams{
		HTTPClient: client,
	}
}

/*
CreateCustomerManagedBundleBlobGrantsParams contains all the parameters to send to the API endpoint

	for the create customer managed bundle blob grants operation.

	Typically these are written to a http.Request.
*/
type CreateCustomerManagedBundleBlobGrantsParams struct {

	/* AppID.

	   app ID
	*/
	AppID string

	/* BundleID.

	   bundle ID
	*/
	BundleID string

	/* Req.

	   blob grant request
	*/
	Req *models.ServiceBlobGrantsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create customer managed bundle blob grants params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateCustomerManagedBundleBlobGrantsParams) WithDefaults() *CreateCustomerManagedBundleBlobGrantsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create customer managed bundle blob grants params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateCustomerManagedBundleBlobGrantsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create customer managed bundle blob grants params
func (o *CreateCustomerManagedBundleBlobGrantsParams) WithTimeout(timeout time.Duration) *CreateCustomerManagedBundleBlobGrantsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create customer managed bundle blob grants params
func (o *CreateCustomerManagedBundleBlobGrantsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create customer managed bundle blob grants params
func (o *CreateCustomerManagedBundleBlobGrantsParams) WithContext(ctx context.Context) *CreateCustomerManagedBundleBlobGrantsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create customer managed bundle blob grants params
func (o *CreateCustomerManagedBundleBlobGrantsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create customer managed bundle blob grants params
func (o *CreateCustomerManagedBundleBlobGrantsParams) WithHTTPClient(client *http.Client) *CreateCustomerManagedBundleBlobGrantsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create customer managed bundle blob grants params
func (o *CreateCustomerManagedBundleBlobGrantsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the create customer managed bundle blob grants params
func (o *CreateCustomerManagedBundleBlobGrantsParams) WithAppID(appID string) *CreateCustomerManagedBundleBlobGrantsParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the create customer managed bundle blob grants params
func (o *CreateCustomerManagedBundleBlobGrantsParams) SetAppID(appID string) {
	o.AppID = appID
}

// WithBundleID adds the bundleID to the create customer managed bundle blob grants params
func (o *CreateCustomerManagedBundleBlobGrantsParams) WithBundleID(bundleID string) *CreateCustomerManagedBundleBlobGrantsParams {
	o.SetBundleID(bundleID)
	return o
}

// SetBundleID adds the bundleId to the create customer managed bundle blob grants params
func (o *CreateCustomerManagedBundleBlobGrantsParams) SetBundleID(bundleID string) {
	o.BundleID = bundleID
}

// WithReq adds the req to the create customer managed bundle blob grants params
func (o *CreateCustomerManagedBundleBlobGrantsParams) WithReq(req *models.ServiceBlobGrantsRequest) *CreateCustomerManagedBundleBlobGrantsParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the create customer managed bundle blob grants params
func (o *CreateCustomerManagedBundleBlobGrantsParams) SetReq(req *models.ServiceBlobGrantsRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCustomerManagedBundleBlobGrantsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_id
	if err := r.SetPathParam("app_id", o.AppID); err != nil {
		return err
	}

	// path param bundle_id
	if err := r.SetPathParam("bundle_id", o.BundleID); err != nil {
		return err
	}
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
