// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// CreateAppBundleDownloadGrantReader is a Reader for the CreateAppBundleDownloadGrant structure.
type CreateAppBundleDownloadGrantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAppBundleDownloadGrantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCreateAppBundleDownloadGrantOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewCreateAppBundleDownloadGrantNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateAppBundleDownloadGrantConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateAppBundleDownloadGrantInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/apps/{app_id}/bundles/{bundle_id}/download-grants] CreateAppBundleDownloadGrant", response, response.Code())
	}
}

// NewCreateAppBundleDownloadGrantOK creates a CreateAppBundleDownloadGrantOK with default headers values
func NewCreateAppBundleDownloadGrantOK() *CreateAppBundleDownloadGrantOK {
	return &CreateAppBundleDownloadGrantOK{}
}

/*
CreateAppBundleDownloadGrantOK describes a response with status code 200, with default header values.

OK
*/
type CreateAppBundleDownloadGrantOK struct {
	Payload *models.ServiceDownloadGrantResponse
}

// IsSuccess returns true when this create app bundle download grant o k response has a 2xx status code
func (o *CreateAppBundleDownloadGrantOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create app bundle download grant o k response has a 3xx status code
func (o *CreateAppBundleDownloadGrantOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create app bundle download grant o k response has a 4xx status code
func (o *CreateAppBundleDownloadGrantOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create app bundle download grant o k response has a 5xx status code
func (o *CreateAppBundleDownloadGrantOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create app bundle download grant o k response a status code equal to that given
func (o *CreateAppBundleDownloadGrantOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create app bundle download grant o k response
func (o *CreateAppBundleDownloadGrantOK) Code() int {
	return 200
}

func (o *CreateAppBundleDownloadGrantOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/bundles/{bundle_id}/download-grants][%d] createAppBundleDownloadGrantOK %s", 200, payload)
}

func (o *CreateAppBundleDownloadGrantOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/bundles/{bundle_id}/download-grants][%d] createAppBundleDownloadGrantOK %s", 200, payload)
}

func (o *CreateAppBundleDownloadGrantOK) GetPayload() *models.ServiceDownloadGrantResponse {
	return o.Payload
}

func (o *CreateAppBundleDownloadGrantOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceDownloadGrantResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateAppBundleDownloadGrantNotFound creates a CreateAppBundleDownloadGrantNotFound with default headers values
func NewCreateAppBundleDownloadGrantNotFound() *CreateAppBundleDownloadGrantNotFound {
	return &CreateAppBundleDownloadGrantNotFound{}
}

/*
CreateAppBundleDownloadGrantNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CreateAppBundleDownloadGrantNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create app bundle download grant not found response has a 2xx status code
func (o *CreateAppBundleDownloadGrantNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create app bundle download grant not found response has a 3xx status code
func (o *CreateAppBundleDownloadGrantNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create app bundle download grant not found response has a 4xx status code
func (o *CreateAppBundleDownloadGrantNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create app bundle download grant not found response has a 5xx status code
func (o *CreateAppBundleDownloadGrantNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create app bundle download grant not found response a status code equal to that given
func (o *CreateAppBundleDownloadGrantNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the create app bundle download grant not found response
func (o *CreateAppBundleDownloadGrantNotFound) Code() int {
	return 404
}

func (o *CreateAppBundleDownloadGrantNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/bundles/{bundle_id}/download-grants][%d] createAppBundleDownloadGrantNotFound %s", 404, payload)
}

func (o *CreateAppBundleDownloadGrantNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/bundles/{bundle_id}/download-grants][%d] createAppBundleDownloadGrantNotFound %s", 404, payload)
}

func (o *CreateAppBundleDownloadGrantNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateAppBundleDownloadGrantNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateAppBundleDownloadGrantConflict creates a CreateAppBundleDownloadGrantConflict with default headers values
func NewCreateAppBundleDownloadGrantConflict() *CreateAppBundleDownloadGrantConflict {
	return &CreateAppBundleDownloadGrantConflict{}
}

/*
CreateAppBundleDownloadGrantConflict describes a response with status code 409, with default header values.

Conflict
*/
type CreateAppBundleDownloadGrantConflict struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create app bundle download grant conflict response has a 2xx status code
func (o *CreateAppBundleDownloadGrantConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create app bundle download grant conflict response has a 3xx status code
func (o *CreateAppBundleDownloadGrantConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create app bundle download grant conflict response has a 4xx status code
func (o *CreateAppBundleDownloadGrantConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this create app bundle download grant conflict response has a 5xx status code
func (o *CreateAppBundleDownloadGrantConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this create app bundle download grant conflict response a status code equal to that given
func (o *CreateAppBundleDownloadGrantConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the create app bundle download grant conflict response
func (o *CreateAppBundleDownloadGrantConflict) Code() int {
	return 409
}

func (o *CreateAppBundleDownloadGrantConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/bundles/{bundle_id}/download-grants][%d] createAppBundleDownloadGrantConflict %s", 409, payload)
}

func (o *CreateAppBundleDownloadGrantConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/bundles/{bundle_id}/download-grants][%d] createAppBundleDownloadGrantConflict %s", 409, payload)
}

func (o *CreateAppBundleDownloadGrantConflict) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateAppBundleDownloadGrantConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateAppBundleDownloadGrantInternalServerError creates a CreateAppBundleDownloadGrantInternalServerError with default headers values
func NewCreateAppBundleDownloadGrantInternalServerError() *CreateAppBundleDownloadGrantInternalServerError {
	return &CreateAppBundleDownloadGrantInternalServerError{}
}

/*
CreateAppBundleDownloadGrantInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateAppBundleDownloadGrantInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create app bundle download grant internal server error response has a 2xx status code
func (o *CreateAppBundleDownloadGrantInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create app bundle download grant internal server error response has a 3xx status code
func (o *CreateAppBundleDownloadGrantInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create app bundle download grant internal server error response has a 4xx status code
func (o *CreateAppBundleDownloadGrantInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create app bundle download grant internal server error response has a 5xx status code
func (o *CreateAppBundleDownloadGrantInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create app bundle download grant internal server error response a status code equal to that given
func (o *CreateAppBundleDownloadGrantInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create app bundle download grant internal server error response
func (o *CreateAppBundleDownloadGrantInternalServerError) Code() int {
	return 500
}

func (o *CreateAppBundleDownloadGrantInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/bundles/{bundle_id}/download-grants][%d] createAppBundleDownloadGrantInternalServerError %s", 500, payload)
}

func (o *CreateAppBundleDownloadGrantInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/apps/{app_id}/bundles/{bundle_id}/download-grants][%d] createAppBundleDownloadGrantInternalServerError %s", 500, payload)
}

func (o *CreateAppBundleDownloadGrantInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateAppBundleDownloadGrantInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
