// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAppGrantReader is a Reader for the DeleteAppGrant structure.
type DeleteAppGrantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAppGrantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAppGrantNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/apps/{app_id}/grants/{grant_id}] DeleteAppGrant", response, response.Code())
	}
}

// NewDeleteAppGrantNoContent creates a DeleteAppGrantNoContent with default headers values
func NewDeleteAppGrantNoContent() *DeleteAppGrantNoContent {
	return &DeleteAppGrantNoContent{}
}

/*
DeleteAppGrantNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteAppGrantNoContent struct {
}

// IsSuccess returns true when this delete app grant no content response has a 2xx status code
func (o *DeleteAppGrantNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete app grant no content response has a 3xx status code
func (o *DeleteAppGrantNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete app grant no content response has a 4xx status code
func (o *DeleteAppGrantNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete app grant no content response has a 5xx status code
func (o *DeleteAppGrantNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete app grant no content response a status code equal to that given
func (o *DeleteAppGrantNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete app grant no content response
func (o *DeleteAppGrantNoContent) Code() int {
	return 204
}

func (o *DeleteAppGrantNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v1/apps/{app_id}/grants/{grant_id}][%d] deleteAppGrantNoContent", 204)
}

func (o *DeleteAppGrantNoContent) String() string {
	return fmt.Sprintf("[DELETE /v1/apps/{app_id}/grants/{grant_id}][%d] deleteAppGrantNoContent", 204)
}

func (o *DeleteAppGrantNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
