// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// GetWorkflowStepGroupsByInstallReader is a Reader for the GetWorkflowStepGroupsByInstall structure.
type GetWorkflowStepGroupsByInstallReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWorkflowStepGroupsByInstallReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetWorkflowStepGroupsByInstallOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetWorkflowStepGroupsByInstallBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetWorkflowStepGroupsByInstallUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetWorkflowStepGroupsByInstallForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetWorkflowStepGroupsByInstallNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetWorkflowStepGroupsByInstallInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/installs/{install_id}/workflows/{workflow_id}/step-groups] GetWorkflowStepGroupsByInstall", response, response.Code())
	}
}

// NewGetWorkflowStepGroupsByInstallOK creates a GetWorkflowStepGroupsByInstallOK with default headers values
func NewGetWorkflowStepGroupsByInstallOK() *GetWorkflowStepGroupsByInstallOK {
	return &GetWorkflowStepGroupsByInstallOK{}
}

/*
GetWorkflowStepGroupsByInstallOK describes a response with status code 200, with default header values.

OK
*/
type GetWorkflowStepGroupsByInstallOK struct {
	Payload []*models.AppWorkflowStepGroup
}

// IsSuccess returns true when this get workflow step groups by install o k response has a 2xx status code
func (o *GetWorkflowStepGroupsByInstallOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get workflow step groups by install o k response has a 3xx status code
func (o *GetWorkflowStepGroupsByInstallOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get workflow step groups by install o k response has a 4xx status code
func (o *GetWorkflowStepGroupsByInstallOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get workflow step groups by install o k response has a 5xx status code
func (o *GetWorkflowStepGroupsByInstallOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get workflow step groups by install o k response a status code equal to that given
func (o *GetWorkflowStepGroupsByInstallOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get workflow step groups by install o k response
func (o *GetWorkflowStepGroupsByInstallOK) Code() int {
	return 200
}

func (o *GetWorkflowStepGroupsByInstallOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows/{workflow_id}/step-groups][%d] getWorkflowStepGroupsByInstallOK %s", 200, payload)
}

func (o *GetWorkflowStepGroupsByInstallOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows/{workflow_id}/step-groups][%d] getWorkflowStepGroupsByInstallOK %s", 200, payload)
}

func (o *GetWorkflowStepGroupsByInstallOK) GetPayload() []*models.AppWorkflowStepGroup {
	return o.Payload
}

func (o *GetWorkflowStepGroupsByInstallOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetWorkflowStepGroupsByInstallBadRequest creates a GetWorkflowStepGroupsByInstallBadRequest with default headers values
func NewGetWorkflowStepGroupsByInstallBadRequest() *GetWorkflowStepGroupsByInstallBadRequest {
	return &GetWorkflowStepGroupsByInstallBadRequest{}
}

/*
GetWorkflowStepGroupsByInstallBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetWorkflowStepGroupsByInstallBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get workflow step groups by install bad request response has a 2xx status code
func (o *GetWorkflowStepGroupsByInstallBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get workflow step groups by install bad request response has a 3xx status code
func (o *GetWorkflowStepGroupsByInstallBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get workflow step groups by install bad request response has a 4xx status code
func (o *GetWorkflowStepGroupsByInstallBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get workflow step groups by install bad request response has a 5xx status code
func (o *GetWorkflowStepGroupsByInstallBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get workflow step groups by install bad request response a status code equal to that given
func (o *GetWorkflowStepGroupsByInstallBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get workflow step groups by install bad request response
func (o *GetWorkflowStepGroupsByInstallBadRequest) Code() int {
	return 400
}

func (o *GetWorkflowStepGroupsByInstallBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows/{workflow_id}/step-groups][%d] getWorkflowStepGroupsByInstallBadRequest %s", 400, payload)
}

func (o *GetWorkflowStepGroupsByInstallBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows/{workflow_id}/step-groups][%d] getWorkflowStepGroupsByInstallBadRequest %s", 400, payload)
}

func (o *GetWorkflowStepGroupsByInstallBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetWorkflowStepGroupsByInstallBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetWorkflowStepGroupsByInstallUnauthorized creates a GetWorkflowStepGroupsByInstallUnauthorized with default headers values
func NewGetWorkflowStepGroupsByInstallUnauthorized() *GetWorkflowStepGroupsByInstallUnauthorized {
	return &GetWorkflowStepGroupsByInstallUnauthorized{}
}

/*
GetWorkflowStepGroupsByInstallUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetWorkflowStepGroupsByInstallUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get workflow step groups by install unauthorized response has a 2xx status code
func (o *GetWorkflowStepGroupsByInstallUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get workflow step groups by install unauthorized response has a 3xx status code
func (o *GetWorkflowStepGroupsByInstallUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get workflow step groups by install unauthorized response has a 4xx status code
func (o *GetWorkflowStepGroupsByInstallUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get workflow step groups by install unauthorized response has a 5xx status code
func (o *GetWorkflowStepGroupsByInstallUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get workflow step groups by install unauthorized response a status code equal to that given
func (o *GetWorkflowStepGroupsByInstallUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get workflow step groups by install unauthorized response
func (o *GetWorkflowStepGroupsByInstallUnauthorized) Code() int {
	return 401
}

func (o *GetWorkflowStepGroupsByInstallUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows/{workflow_id}/step-groups][%d] getWorkflowStepGroupsByInstallUnauthorized %s", 401, payload)
}

func (o *GetWorkflowStepGroupsByInstallUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows/{workflow_id}/step-groups][%d] getWorkflowStepGroupsByInstallUnauthorized %s", 401, payload)
}

func (o *GetWorkflowStepGroupsByInstallUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetWorkflowStepGroupsByInstallUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetWorkflowStepGroupsByInstallForbidden creates a GetWorkflowStepGroupsByInstallForbidden with default headers values
func NewGetWorkflowStepGroupsByInstallForbidden() *GetWorkflowStepGroupsByInstallForbidden {
	return &GetWorkflowStepGroupsByInstallForbidden{}
}

/*
GetWorkflowStepGroupsByInstallForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetWorkflowStepGroupsByInstallForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get workflow step groups by install forbidden response has a 2xx status code
func (o *GetWorkflowStepGroupsByInstallForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get workflow step groups by install forbidden response has a 3xx status code
func (o *GetWorkflowStepGroupsByInstallForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get workflow step groups by install forbidden response has a 4xx status code
func (o *GetWorkflowStepGroupsByInstallForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get workflow step groups by install forbidden response has a 5xx status code
func (o *GetWorkflowStepGroupsByInstallForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get workflow step groups by install forbidden response a status code equal to that given
func (o *GetWorkflowStepGroupsByInstallForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get workflow step groups by install forbidden response
func (o *GetWorkflowStepGroupsByInstallForbidden) Code() int {
	return 403
}

func (o *GetWorkflowStepGroupsByInstallForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows/{workflow_id}/step-groups][%d] getWorkflowStepGroupsByInstallForbidden %s", 403, payload)
}

func (o *GetWorkflowStepGroupsByInstallForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows/{workflow_id}/step-groups][%d] getWorkflowStepGroupsByInstallForbidden %s", 403, payload)
}

func (o *GetWorkflowStepGroupsByInstallForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetWorkflowStepGroupsByInstallForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetWorkflowStepGroupsByInstallNotFound creates a GetWorkflowStepGroupsByInstallNotFound with default headers values
func NewGetWorkflowStepGroupsByInstallNotFound() *GetWorkflowStepGroupsByInstallNotFound {
	return &GetWorkflowStepGroupsByInstallNotFound{}
}

/*
GetWorkflowStepGroupsByInstallNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetWorkflowStepGroupsByInstallNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get workflow step groups by install not found response has a 2xx status code
func (o *GetWorkflowStepGroupsByInstallNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get workflow step groups by install not found response has a 3xx status code
func (o *GetWorkflowStepGroupsByInstallNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get workflow step groups by install not found response has a 4xx status code
func (o *GetWorkflowStepGroupsByInstallNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get workflow step groups by install not found response has a 5xx status code
func (o *GetWorkflowStepGroupsByInstallNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get workflow step groups by install not found response a status code equal to that given
func (o *GetWorkflowStepGroupsByInstallNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get workflow step groups by install not found response
func (o *GetWorkflowStepGroupsByInstallNotFound) Code() int {
	return 404
}

func (o *GetWorkflowStepGroupsByInstallNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows/{workflow_id}/step-groups][%d] getWorkflowStepGroupsByInstallNotFound %s", 404, payload)
}

func (o *GetWorkflowStepGroupsByInstallNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows/{workflow_id}/step-groups][%d] getWorkflowStepGroupsByInstallNotFound %s", 404, payload)
}

func (o *GetWorkflowStepGroupsByInstallNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetWorkflowStepGroupsByInstallNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetWorkflowStepGroupsByInstallInternalServerError creates a GetWorkflowStepGroupsByInstallInternalServerError with default headers values
func NewGetWorkflowStepGroupsByInstallInternalServerError() *GetWorkflowStepGroupsByInstallInternalServerError {
	return &GetWorkflowStepGroupsByInstallInternalServerError{}
}

/*
GetWorkflowStepGroupsByInstallInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetWorkflowStepGroupsByInstallInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get workflow step groups by install internal server error response has a 2xx status code
func (o *GetWorkflowStepGroupsByInstallInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get workflow step groups by install internal server error response has a 3xx status code
func (o *GetWorkflowStepGroupsByInstallInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get workflow step groups by install internal server error response has a 4xx status code
func (o *GetWorkflowStepGroupsByInstallInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get workflow step groups by install internal server error response has a 5xx status code
func (o *GetWorkflowStepGroupsByInstallInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get workflow step groups by install internal server error response a status code equal to that given
func (o *GetWorkflowStepGroupsByInstallInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get workflow step groups by install internal server error response
func (o *GetWorkflowStepGroupsByInstallInternalServerError) Code() int {
	return 500
}

func (o *GetWorkflowStepGroupsByInstallInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows/{workflow_id}/step-groups][%d] getWorkflowStepGroupsByInstallInternalServerError %s", 500, payload)
}

func (o *GetWorkflowStepGroupsByInstallInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows/{workflow_id}/step-groups][%d] getWorkflowStepGroupsByInstallInternalServerError %s", 500, payload)
}

func (o *GetWorkflowStepGroupsByInstallInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetWorkflowStepGroupsByInstallInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
