// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetReleasePackageParams creates a new GetReleasePackageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetReleasePackageParams() *GetReleasePackageParams {
	return &GetReleasePackageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetReleasePackageParamsWithTimeout creates a new GetReleasePackageParams object
// with the ability to set a timeout on a request.
func NewGetReleasePackageParamsWithTimeout(timeout time.Duration) *GetReleasePackageParams {
	return &GetReleasePackageParams{
		timeout: timeout,
	}
}

// NewGetReleasePackageParamsWithContext creates a new GetReleasePackageParams object
// with the ability to set a context for a request.
func NewGetReleasePackageParamsWithContext(ctx context.Context) *GetReleasePackageParams {
	return &GetReleasePackageParams{
		Context: ctx,
	}
}

// NewGetReleasePackageParamsWithHTTPClient creates a new GetReleasePackageParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetReleasePackageParamsWithHTTPClient(client *http.Client) *GetReleasePackageParams {
	return &GetReleasePackageParams{
		HTTPClient: client,
	}
}

/*
GetReleasePackageParams contains all the parameters to send to the API endpoint

	for the get release package operation.

	Typically these are written to a http.Request.
*/
type GetReleasePackageParams struct {

	/* PackageID.

	   package ID
	*/
	PackageID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get release package params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReleasePackageParams) WithDefaults() *GetReleasePackageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get release package params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReleasePackageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get release package params
func (o *GetReleasePackageParams) WithTimeout(timeout time.Duration) *GetReleasePackageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get release package params
func (o *GetReleasePackageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get release package params
func (o *GetReleasePackageParams) WithContext(ctx context.Context) *GetReleasePackageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get release package params
func (o *GetReleasePackageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get release package params
func (o *GetReleasePackageParams) WithHTTPClient(client *http.Client) *GetReleasePackageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get release package params
func (o *GetReleasePackageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPackageID adds the packageID to the get release package params
func (o *GetReleasePackageParams) WithPackageID(packageID string) *GetReleasePackageParams {
	o.SetPackageID(packageID)
	return o
}

// SetPackageID adds the packageId to the get release package params
func (o *GetReleasePackageParams) SetPackageID(packageID string) {
	o.PackageID = packageID
}

// WriteToRequest writes these params to a swagger request
func (o *GetReleasePackageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param package_id
	if err := r.SetPathParam("package_id", o.PackageID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
