// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetWorkflowPlanSummariesParams creates a new GetWorkflowPlanSummariesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetWorkflowPlanSummariesParams() *GetWorkflowPlanSummariesParams {
	return &GetWorkflowPlanSummariesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetWorkflowPlanSummariesParamsWithTimeout creates a new GetWorkflowPlanSummariesParams object
// with the ability to set a timeout on a request.
func NewGetWorkflowPlanSummariesParamsWithTimeout(timeout time.Duration) *GetWorkflowPlanSummariesParams {
	return &GetWorkflowPlanSummariesParams{
		timeout: timeout,
	}
}

// NewGetWorkflowPlanSummariesParamsWithContext creates a new GetWorkflowPlanSummariesParams object
// with the ability to set a context for a request.
func NewGetWorkflowPlanSummariesParamsWithContext(ctx context.Context) *GetWorkflowPlanSummariesParams {
	return &GetWorkflowPlanSummariesParams{
		Context: ctx,
	}
}

// NewGetWorkflowPlanSummariesParamsWithHTTPClient creates a new GetWorkflowPlanSummariesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetWorkflowPlanSummariesParamsWithHTTPClient(client *http.Client) *GetWorkflowPlanSummariesParams {
	return &GetWorkflowPlanSummariesParams{
		HTTPClient: client,
	}
}

/*
GetWorkflowPlanSummariesParams contains all the parameters to send to the API endpoint

	for the get workflow plan summaries operation.

	Typically these are written to a http.Request.
*/
type GetWorkflowPlanSummariesParams struct {

	/* WorkflowID.

	   workflow id
	*/
	WorkflowID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get workflow plan summaries params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWorkflowPlanSummariesParams) WithDefaults() *GetWorkflowPlanSummariesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get workflow plan summaries params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWorkflowPlanSummariesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get workflow plan summaries params
func (o *GetWorkflowPlanSummariesParams) WithTimeout(timeout time.Duration) *GetWorkflowPlanSummariesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get workflow plan summaries params
func (o *GetWorkflowPlanSummariesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get workflow plan summaries params
func (o *GetWorkflowPlanSummariesParams) WithContext(ctx context.Context) *GetWorkflowPlanSummariesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get workflow plan summaries params
func (o *GetWorkflowPlanSummariesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get workflow plan summaries params
func (o *GetWorkflowPlanSummariesParams) WithHTTPClient(client *http.Client) *GetWorkflowPlanSummariesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get workflow plan summaries params
func (o *GetWorkflowPlanSummariesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWorkflowID adds the workflowID to the get workflow plan summaries params
func (o *GetWorkflowPlanSummariesParams) WithWorkflowID(workflowID string) *GetWorkflowPlanSummariesParams {
	o.SetWorkflowID(workflowID)
	return o
}

// SetWorkflowID adds the workflowId to the get workflow plan summaries params
func (o *GetWorkflowPlanSummariesParams) SetWorkflowID(workflowID string) {
	o.WorkflowID = workflowID
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkflowPlanSummariesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param workflow_id
	if err := r.SetPathParam("workflow_id", o.WorkflowID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
