// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// GetInstallTerraformWorkspaceStatesReader is a Reader for the GetInstallTerraformWorkspaceStates structure.
type GetInstallTerraformWorkspaceStatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInstallTerraformWorkspaceStatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetInstallTerraformWorkspaceStatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetInstallTerraformWorkspaceStatesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetInstallTerraformWorkspaceStatesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetInstallTerraformWorkspaceStatesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetInstallTerraformWorkspaceStatesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetInstallTerraformWorkspaceStatesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/states] GetInstallTerraformWorkspaceStates", response, response.Code())
	}
}

// NewGetInstallTerraformWorkspaceStatesOK creates a GetInstallTerraformWorkspaceStatesOK with default headers values
func NewGetInstallTerraformWorkspaceStatesOK() *GetInstallTerraformWorkspaceStatesOK {
	return &GetInstallTerraformWorkspaceStatesOK{}
}

/*
GetInstallTerraformWorkspaceStatesOK describes a response with status code 200, with default header values.

OK
*/
type GetInstallTerraformWorkspaceStatesOK struct {
	Payload []*models.AppTerraformWorkspaceState
}

// IsSuccess returns true when this get install terraform workspace states o k response has a 2xx status code
func (o *GetInstallTerraformWorkspaceStatesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get install terraform workspace states o k response has a 3xx status code
func (o *GetInstallTerraformWorkspaceStatesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install terraform workspace states o k response has a 4xx status code
func (o *GetInstallTerraformWorkspaceStatesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get install terraform workspace states o k response has a 5xx status code
func (o *GetInstallTerraformWorkspaceStatesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get install terraform workspace states o k response a status code equal to that given
func (o *GetInstallTerraformWorkspaceStatesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get install terraform workspace states o k response
func (o *GetInstallTerraformWorkspaceStatesOK) Code() int {
	return 200
}

func (o *GetInstallTerraformWorkspaceStatesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/states][%d] getInstallTerraformWorkspaceStatesOK %s", 200, payload)
}

func (o *GetInstallTerraformWorkspaceStatesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/states][%d] getInstallTerraformWorkspaceStatesOK %s", 200, payload)
}

func (o *GetInstallTerraformWorkspaceStatesOK) GetPayload() []*models.AppTerraformWorkspaceState {
	return o.Payload
}

func (o *GetInstallTerraformWorkspaceStatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetInstallTerraformWorkspaceStatesBadRequest creates a GetInstallTerraformWorkspaceStatesBadRequest with default headers values
func NewGetInstallTerraformWorkspaceStatesBadRequest() *GetInstallTerraformWorkspaceStatesBadRequest {
	return &GetInstallTerraformWorkspaceStatesBadRequest{}
}

/*
GetInstallTerraformWorkspaceStatesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetInstallTerraformWorkspaceStatesBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get install terraform workspace states bad request response has a 2xx status code
func (o *GetInstallTerraformWorkspaceStatesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get install terraform workspace states bad request response has a 3xx status code
func (o *GetInstallTerraformWorkspaceStatesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install terraform workspace states bad request response has a 4xx status code
func (o *GetInstallTerraformWorkspaceStatesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get install terraform workspace states bad request response has a 5xx status code
func (o *GetInstallTerraformWorkspaceStatesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get install terraform workspace states bad request response a status code equal to that given
func (o *GetInstallTerraformWorkspaceStatesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get install terraform workspace states bad request response
func (o *GetInstallTerraformWorkspaceStatesBadRequest) Code() int {
	return 400
}

func (o *GetInstallTerraformWorkspaceStatesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/states][%d] getInstallTerraformWorkspaceStatesBadRequest %s", 400, payload)
}

func (o *GetInstallTerraformWorkspaceStatesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/states][%d] getInstallTerraformWorkspaceStatesBadRequest %s", 400, payload)
}

func (o *GetInstallTerraformWorkspaceStatesBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetInstallTerraformWorkspaceStatesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetInstallTerraformWorkspaceStatesUnauthorized creates a GetInstallTerraformWorkspaceStatesUnauthorized with default headers values
func NewGetInstallTerraformWorkspaceStatesUnauthorized() *GetInstallTerraformWorkspaceStatesUnauthorized {
	return &GetInstallTerraformWorkspaceStatesUnauthorized{}
}

/*
GetInstallTerraformWorkspaceStatesUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetInstallTerraformWorkspaceStatesUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get install terraform workspace states unauthorized response has a 2xx status code
func (o *GetInstallTerraformWorkspaceStatesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get install terraform workspace states unauthorized response has a 3xx status code
func (o *GetInstallTerraformWorkspaceStatesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install terraform workspace states unauthorized response has a 4xx status code
func (o *GetInstallTerraformWorkspaceStatesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get install terraform workspace states unauthorized response has a 5xx status code
func (o *GetInstallTerraformWorkspaceStatesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get install terraform workspace states unauthorized response a status code equal to that given
func (o *GetInstallTerraformWorkspaceStatesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get install terraform workspace states unauthorized response
func (o *GetInstallTerraformWorkspaceStatesUnauthorized) Code() int {
	return 401
}

func (o *GetInstallTerraformWorkspaceStatesUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/states][%d] getInstallTerraformWorkspaceStatesUnauthorized %s", 401, payload)
}

func (o *GetInstallTerraformWorkspaceStatesUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/states][%d] getInstallTerraformWorkspaceStatesUnauthorized %s", 401, payload)
}

func (o *GetInstallTerraformWorkspaceStatesUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetInstallTerraformWorkspaceStatesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetInstallTerraformWorkspaceStatesForbidden creates a GetInstallTerraformWorkspaceStatesForbidden with default headers values
func NewGetInstallTerraformWorkspaceStatesForbidden() *GetInstallTerraformWorkspaceStatesForbidden {
	return &GetInstallTerraformWorkspaceStatesForbidden{}
}

/*
GetInstallTerraformWorkspaceStatesForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetInstallTerraformWorkspaceStatesForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get install terraform workspace states forbidden response has a 2xx status code
func (o *GetInstallTerraformWorkspaceStatesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get install terraform workspace states forbidden response has a 3xx status code
func (o *GetInstallTerraformWorkspaceStatesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install terraform workspace states forbidden response has a 4xx status code
func (o *GetInstallTerraformWorkspaceStatesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get install terraform workspace states forbidden response has a 5xx status code
func (o *GetInstallTerraformWorkspaceStatesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get install terraform workspace states forbidden response a status code equal to that given
func (o *GetInstallTerraformWorkspaceStatesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get install terraform workspace states forbidden response
func (o *GetInstallTerraformWorkspaceStatesForbidden) Code() int {
	return 403
}

func (o *GetInstallTerraformWorkspaceStatesForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/states][%d] getInstallTerraformWorkspaceStatesForbidden %s", 403, payload)
}

func (o *GetInstallTerraformWorkspaceStatesForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/states][%d] getInstallTerraformWorkspaceStatesForbidden %s", 403, payload)
}

func (o *GetInstallTerraformWorkspaceStatesForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetInstallTerraformWorkspaceStatesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetInstallTerraformWorkspaceStatesNotFound creates a GetInstallTerraformWorkspaceStatesNotFound with default headers values
func NewGetInstallTerraformWorkspaceStatesNotFound() *GetInstallTerraformWorkspaceStatesNotFound {
	return &GetInstallTerraformWorkspaceStatesNotFound{}
}

/*
GetInstallTerraformWorkspaceStatesNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetInstallTerraformWorkspaceStatesNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get install terraform workspace states not found response has a 2xx status code
func (o *GetInstallTerraformWorkspaceStatesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get install terraform workspace states not found response has a 3xx status code
func (o *GetInstallTerraformWorkspaceStatesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install terraform workspace states not found response has a 4xx status code
func (o *GetInstallTerraformWorkspaceStatesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get install terraform workspace states not found response has a 5xx status code
func (o *GetInstallTerraformWorkspaceStatesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get install terraform workspace states not found response a status code equal to that given
func (o *GetInstallTerraformWorkspaceStatesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get install terraform workspace states not found response
func (o *GetInstallTerraformWorkspaceStatesNotFound) Code() int {
	return 404
}

func (o *GetInstallTerraformWorkspaceStatesNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/states][%d] getInstallTerraformWorkspaceStatesNotFound %s", 404, payload)
}

func (o *GetInstallTerraformWorkspaceStatesNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/states][%d] getInstallTerraformWorkspaceStatesNotFound %s", 404, payload)
}

func (o *GetInstallTerraformWorkspaceStatesNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetInstallTerraformWorkspaceStatesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetInstallTerraformWorkspaceStatesInternalServerError creates a GetInstallTerraformWorkspaceStatesInternalServerError with default headers values
func NewGetInstallTerraformWorkspaceStatesInternalServerError() *GetInstallTerraformWorkspaceStatesInternalServerError {
	return &GetInstallTerraformWorkspaceStatesInternalServerError{}
}

/*
GetInstallTerraformWorkspaceStatesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetInstallTerraformWorkspaceStatesInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get install terraform workspace states internal server error response has a 2xx status code
func (o *GetInstallTerraformWorkspaceStatesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get install terraform workspace states internal server error response has a 3xx status code
func (o *GetInstallTerraformWorkspaceStatesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install terraform workspace states internal server error response has a 4xx status code
func (o *GetInstallTerraformWorkspaceStatesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get install terraform workspace states internal server error response has a 5xx status code
func (o *GetInstallTerraformWorkspaceStatesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get install terraform workspace states internal server error response a status code equal to that given
func (o *GetInstallTerraformWorkspaceStatesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get install terraform workspace states internal server error response
func (o *GetInstallTerraformWorkspaceStatesInternalServerError) Code() int {
	return 500
}

func (o *GetInstallTerraformWorkspaceStatesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/states][%d] getInstallTerraformWorkspaceStatesInternalServerError %s", 500, payload)
}

func (o *GetInstallTerraformWorkspaceStatesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/states][%d] getInstallTerraformWorkspaceStatesInternalServerError %s", 500, payload)
}

func (o *GetInstallTerraformWorkspaceStatesInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetInstallTerraformWorkspaceStatesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
