// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// GetInstallTerraformWorkspaceStatesJSONReader is a Reader for the GetInstallTerraformWorkspaceStatesJSON structure.
type GetInstallTerraformWorkspaceStatesJSONReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInstallTerraformWorkspaceStatesJSONReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetInstallTerraformWorkspaceStatesJSONOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetInstallTerraformWorkspaceStatesJSONBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetInstallTerraformWorkspaceStatesJSONUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetInstallTerraformWorkspaceStatesJSONForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetInstallTerraformWorkspaceStatesJSONNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetInstallTerraformWorkspaceStatesJSONInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/state-json] GetInstallTerraformWorkspaceStatesJSON", response, response.Code())
	}
}

// NewGetInstallTerraformWorkspaceStatesJSONOK creates a GetInstallTerraformWorkspaceStatesJSONOK with default headers values
func NewGetInstallTerraformWorkspaceStatesJSONOK() *GetInstallTerraformWorkspaceStatesJSONOK {
	return &GetInstallTerraformWorkspaceStatesJSONOK{}
}

/*
GetInstallTerraformWorkspaceStatesJSONOK describes a response with status code 200, with default header values.

OK
*/
type GetInstallTerraformWorkspaceStatesJSONOK struct {
	Payload []*models.AppTerraformWorkspaceStateJSON
}

// IsSuccess returns true when this get install terraform workspace states Json o k response has a 2xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get install terraform workspace states Json o k response has a 3xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install terraform workspace states Json o k response has a 4xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get install terraform workspace states Json o k response has a 5xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get install terraform workspace states Json o k response a status code equal to that given
func (o *GetInstallTerraformWorkspaceStatesJSONOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get install terraform workspace states Json o k response
func (o *GetInstallTerraformWorkspaceStatesJSONOK) Code() int {
	return 200
}

func (o *GetInstallTerraformWorkspaceStatesJSONOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/state-json][%d] getInstallTerraformWorkspaceStatesJsonOK %s", 200, payload)
}

func (o *GetInstallTerraformWorkspaceStatesJSONOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/state-json][%d] getInstallTerraformWorkspaceStatesJsonOK %s", 200, payload)
}

func (o *GetInstallTerraformWorkspaceStatesJSONOK) GetPayload() []*models.AppTerraformWorkspaceStateJSON {
	return o.Payload
}

func (o *GetInstallTerraformWorkspaceStatesJSONOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetInstallTerraformWorkspaceStatesJSONBadRequest creates a GetInstallTerraformWorkspaceStatesJSONBadRequest with default headers values
func NewGetInstallTerraformWorkspaceStatesJSONBadRequest() *GetInstallTerraformWorkspaceStatesJSONBadRequest {
	return &GetInstallTerraformWorkspaceStatesJSONBadRequest{}
}

/*
GetInstallTerraformWorkspaceStatesJSONBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetInstallTerraformWorkspaceStatesJSONBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get install terraform workspace states Json bad request response has a 2xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get install terraform workspace states Json bad request response has a 3xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install terraform workspace states Json bad request response has a 4xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get install terraform workspace states Json bad request response has a 5xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get install terraform workspace states Json bad request response a status code equal to that given
func (o *GetInstallTerraformWorkspaceStatesJSONBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get install terraform workspace states Json bad request response
func (o *GetInstallTerraformWorkspaceStatesJSONBadRequest) Code() int {
	return 400
}

func (o *GetInstallTerraformWorkspaceStatesJSONBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/state-json][%d] getInstallTerraformWorkspaceStatesJsonBadRequest %s", 400, payload)
}

func (o *GetInstallTerraformWorkspaceStatesJSONBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/state-json][%d] getInstallTerraformWorkspaceStatesJsonBadRequest %s", 400, payload)
}

func (o *GetInstallTerraformWorkspaceStatesJSONBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetInstallTerraformWorkspaceStatesJSONBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetInstallTerraformWorkspaceStatesJSONUnauthorized creates a GetInstallTerraformWorkspaceStatesJSONUnauthorized with default headers values
func NewGetInstallTerraformWorkspaceStatesJSONUnauthorized() *GetInstallTerraformWorkspaceStatesJSONUnauthorized {
	return &GetInstallTerraformWorkspaceStatesJSONUnauthorized{}
}

/*
GetInstallTerraformWorkspaceStatesJSONUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetInstallTerraformWorkspaceStatesJSONUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get install terraform workspace states Json unauthorized response has a 2xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get install terraform workspace states Json unauthorized response has a 3xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install terraform workspace states Json unauthorized response has a 4xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get install terraform workspace states Json unauthorized response has a 5xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get install terraform workspace states Json unauthorized response a status code equal to that given
func (o *GetInstallTerraformWorkspaceStatesJSONUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get install terraform workspace states Json unauthorized response
func (o *GetInstallTerraformWorkspaceStatesJSONUnauthorized) Code() int {
	return 401
}

func (o *GetInstallTerraformWorkspaceStatesJSONUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/state-json][%d] getInstallTerraformWorkspaceStatesJsonUnauthorized %s", 401, payload)
}

func (o *GetInstallTerraformWorkspaceStatesJSONUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/state-json][%d] getInstallTerraformWorkspaceStatesJsonUnauthorized %s", 401, payload)
}

func (o *GetInstallTerraformWorkspaceStatesJSONUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetInstallTerraformWorkspaceStatesJSONUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetInstallTerraformWorkspaceStatesJSONForbidden creates a GetInstallTerraformWorkspaceStatesJSONForbidden with default headers values
func NewGetInstallTerraformWorkspaceStatesJSONForbidden() *GetInstallTerraformWorkspaceStatesJSONForbidden {
	return &GetInstallTerraformWorkspaceStatesJSONForbidden{}
}

/*
GetInstallTerraformWorkspaceStatesJSONForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetInstallTerraformWorkspaceStatesJSONForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get install terraform workspace states Json forbidden response has a 2xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get install terraform workspace states Json forbidden response has a 3xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install terraform workspace states Json forbidden response has a 4xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get install terraform workspace states Json forbidden response has a 5xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get install terraform workspace states Json forbidden response a status code equal to that given
func (o *GetInstallTerraformWorkspaceStatesJSONForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get install terraform workspace states Json forbidden response
func (o *GetInstallTerraformWorkspaceStatesJSONForbidden) Code() int {
	return 403
}

func (o *GetInstallTerraformWorkspaceStatesJSONForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/state-json][%d] getInstallTerraformWorkspaceStatesJsonForbidden %s", 403, payload)
}

func (o *GetInstallTerraformWorkspaceStatesJSONForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/state-json][%d] getInstallTerraformWorkspaceStatesJsonForbidden %s", 403, payload)
}

func (o *GetInstallTerraformWorkspaceStatesJSONForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetInstallTerraformWorkspaceStatesJSONForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetInstallTerraformWorkspaceStatesJSONNotFound creates a GetInstallTerraformWorkspaceStatesJSONNotFound with default headers values
func NewGetInstallTerraformWorkspaceStatesJSONNotFound() *GetInstallTerraformWorkspaceStatesJSONNotFound {
	return &GetInstallTerraformWorkspaceStatesJSONNotFound{}
}

/*
GetInstallTerraformWorkspaceStatesJSONNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetInstallTerraformWorkspaceStatesJSONNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get install terraform workspace states Json not found response has a 2xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get install terraform workspace states Json not found response has a 3xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install terraform workspace states Json not found response has a 4xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get install terraform workspace states Json not found response has a 5xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get install terraform workspace states Json not found response a status code equal to that given
func (o *GetInstallTerraformWorkspaceStatesJSONNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get install terraform workspace states Json not found response
func (o *GetInstallTerraformWorkspaceStatesJSONNotFound) Code() int {
	return 404
}

func (o *GetInstallTerraformWorkspaceStatesJSONNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/state-json][%d] getInstallTerraformWorkspaceStatesJsonNotFound %s", 404, payload)
}

func (o *GetInstallTerraformWorkspaceStatesJSONNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/state-json][%d] getInstallTerraformWorkspaceStatesJsonNotFound %s", 404, payload)
}

func (o *GetInstallTerraformWorkspaceStatesJSONNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetInstallTerraformWorkspaceStatesJSONNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetInstallTerraformWorkspaceStatesJSONInternalServerError creates a GetInstallTerraformWorkspaceStatesJSONInternalServerError with default headers values
func NewGetInstallTerraformWorkspaceStatesJSONInternalServerError() *GetInstallTerraformWorkspaceStatesJSONInternalServerError {
	return &GetInstallTerraformWorkspaceStatesJSONInternalServerError{}
}

/*
GetInstallTerraformWorkspaceStatesJSONInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetInstallTerraformWorkspaceStatesJSONInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get install terraform workspace states Json internal server error response has a 2xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get install terraform workspace states Json internal server error response has a 3xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install terraform workspace states Json internal server error response has a 4xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get install terraform workspace states Json internal server error response has a 5xx status code
func (o *GetInstallTerraformWorkspaceStatesJSONInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get install terraform workspace states Json internal server error response a status code equal to that given
func (o *GetInstallTerraformWorkspaceStatesJSONInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get install terraform workspace states Json internal server error response
func (o *GetInstallTerraformWorkspaceStatesJSONInternalServerError) Code() int {
	return 500
}

func (o *GetInstallTerraformWorkspaceStatesJSONInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/state-json][%d] getInstallTerraformWorkspaceStatesJsonInternalServerError %s", 500, payload)
}

func (o *GetInstallTerraformWorkspaceStatesJSONInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/state-json][%d] getInstallTerraformWorkspaceStatesJsonInternalServerError %s", 500, payload)
}

func (o *GetInstallTerraformWorkspaceStatesJSONInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetInstallTerraformWorkspaceStatesJSONInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
