// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// GetWorkflowStepGroupByAppBranchReader is a Reader for the GetWorkflowStepGroupByAppBranch structure.
type GetWorkflowStepGroupByAppBranchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWorkflowStepGroupByAppBranchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetWorkflowStepGroupByAppBranchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetWorkflowStepGroupByAppBranchBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetWorkflowStepGroupByAppBranchUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetWorkflowStepGroupByAppBranchForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetWorkflowStepGroupByAppBranchNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetWorkflowStepGroupByAppBranchInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/step-groups/{{step_group_id}}] GetWorkflowStepGroupByAppBranch", response, response.Code())
	}
}

// NewGetWorkflowStepGroupByAppBranchOK creates a GetWorkflowStepGroupByAppBranchOK with default headers values
func NewGetWorkflowStepGroupByAppBranchOK() *GetWorkflowStepGroupByAppBranchOK {
	return &GetWorkflowStepGroupByAppBranchOK{}
}

/*
GetWorkflowStepGroupByAppBranchOK describes a response with status code 200, with default header values.

OK
*/
type GetWorkflowStepGroupByAppBranchOK struct {
	Payload *models.AppWorkflowStepGroup
}

// IsSuccess returns true when this get workflow step group by app branch o k response has a 2xx status code
func (o *GetWorkflowStepGroupByAppBranchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get workflow step group by app branch o k response has a 3xx status code
func (o *GetWorkflowStepGroupByAppBranchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get workflow step group by app branch o k response has a 4xx status code
func (o *GetWorkflowStepGroupByAppBranchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get workflow step group by app branch o k response has a 5xx status code
func (o *GetWorkflowStepGroupByAppBranchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get workflow step group by app branch o k response a status code equal to that given
func (o *GetWorkflowStepGroupByAppBranchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get workflow step group by app branch o k response
func (o *GetWorkflowStepGroupByAppBranchOK) Code() int {
	return 200
}

func (o *GetWorkflowStepGroupByAppBranchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/step-groups/{{step_group_id}}][%d] getWorkflowStepGroupByAppBranchOK %s", 200, payload)
}

func (o *GetWorkflowStepGroupByAppBranchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/step-groups/{{step_group_id}}][%d] getWorkflowStepGroupByAppBranchOK %s", 200, payload)
}

func (o *GetWorkflowStepGroupByAppBranchOK) GetPayload() *models.AppWorkflowStepGroup {
	return o.Payload
}

func (o *GetWorkflowStepGroupByAppBranchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppWorkflowStepGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetWorkflowStepGroupByAppBranchBadRequest creates a GetWorkflowStepGroupByAppBranchBadRequest with default headers values
func NewGetWorkflowStepGroupByAppBranchBadRequest() *GetWorkflowStepGroupByAppBranchBadRequest {
	return &GetWorkflowStepGroupByAppBranchBadRequest{}
}

/*
GetWorkflowStepGroupByAppBranchBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetWorkflowStepGroupByAppBranchBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get workflow step group by app branch bad request response has a 2xx status code
func (o *GetWorkflowStepGroupByAppBranchBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get workflow step group by app branch bad request response has a 3xx status code
func (o *GetWorkflowStepGroupByAppBranchBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get workflow step group by app branch bad request response has a 4xx status code
func (o *GetWorkflowStepGroupByAppBranchBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get workflow step group by app branch bad request response has a 5xx status code
func (o *GetWorkflowStepGroupByAppBranchBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get workflow step group by app branch bad request response a status code equal to that given
func (o *GetWorkflowStepGroupByAppBranchBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get workflow step group by app branch bad request response
func (o *GetWorkflowStepGroupByAppBranchBadRequest) Code() int {
	return 400
}

func (o *GetWorkflowStepGroupByAppBranchBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/step-groups/{{step_group_id}}][%d] getWorkflowStepGroupByAppBranchBadRequest %s", 400, payload)
}

func (o *GetWorkflowStepGroupByAppBranchBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/step-groups/{{step_group_id}}][%d] getWorkflowStepGroupByAppBranchBadRequest %s", 400, payload)
}

func (o *GetWorkflowStepGroupByAppBranchBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetWorkflowStepGroupByAppBranchBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetWorkflowStepGroupByAppBranchUnauthorized creates a GetWorkflowStepGroupByAppBranchUnauthorized with default headers values
func NewGetWorkflowStepGroupByAppBranchUnauthorized() *GetWorkflowStepGroupByAppBranchUnauthorized {
	return &GetWorkflowStepGroupByAppBranchUnauthorized{}
}

/*
GetWorkflowStepGroupByAppBranchUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetWorkflowStepGroupByAppBranchUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get workflow step group by app branch unauthorized response has a 2xx status code
func (o *GetWorkflowStepGroupByAppBranchUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get workflow step group by app branch unauthorized response has a 3xx status code
func (o *GetWorkflowStepGroupByAppBranchUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get workflow step group by app branch unauthorized response has a 4xx status code
func (o *GetWorkflowStepGroupByAppBranchUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get workflow step group by app branch unauthorized response has a 5xx status code
func (o *GetWorkflowStepGroupByAppBranchUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get workflow step group by app branch unauthorized response a status code equal to that given
func (o *GetWorkflowStepGroupByAppBranchUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get workflow step group by app branch unauthorized response
func (o *GetWorkflowStepGroupByAppBranchUnauthorized) Code() int {
	return 401
}

func (o *GetWorkflowStepGroupByAppBranchUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/step-groups/{{step_group_id}}][%d] getWorkflowStepGroupByAppBranchUnauthorized %s", 401, payload)
}

func (o *GetWorkflowStepGroupByAppBranchUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/step-groups/{{step_group_id}}][%d] getWorkflowStepGroupByAppBranchUnauthorized %s", 401, payload)
}

func (o *GetWorkflowStepGroupByAppBranchUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetWorkflowStepGroupByAppBranchUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetWorkflowStepGroupByAppBranchForbidden creates a GetWorkflowStepGroupByAppBranchForbidden with default headers values
func NewGetWorkflowStepGroupByAppBranchForbidden() *GetWorkflowStepGroupByAppBranchForbidden {
	return &GetWorkflowStepGroupByAppBranchForbidden{}
}

/*
GetWorkflowStepGroupByAppBranchForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetWorkflowStepGroupByAppBranchForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get workflow step group by app branch forbidden response has a 2xx status code
func (o *GetWorkflowStepGroupByAppBranchForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get workflow step group by app branch forbidden response has a 3xx status code
func (o *GetWorkflowStepGroupByAppBranchForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get workflow step group by app branch forbidden response has a 4xx status code
func (o *GetWorkflowStepGroupByAppBranchForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get workflow step group by app branch forbidden response has a 5xx status code
func (o *GetWorkflowStepGroupByAppBranchForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get workflow step group by app branch forbidden response a status code equal to that given
func (o *GetWorkflowStepGroupByAppBranchForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get workflow step group by app branch forbidden response
func (o *GetWorkflowStepGroupByAppBranchForbidden) Code() int {
	return 403
}

func (o *GetWorkflowStepGroupByAppBranchForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/step-groups/{{step_group_id}}][%d] getWorkflowStepGroupByAppBranchForbidden %s", 403, payload)
}

func (o *GetWorkflowStepGroupByAppBranchForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/step-groups/{{step_group_id}}][%d] getWorkflowStepGroupByAppBranchForbidden %s", 403, payload)
}

func (o *GetWorkflowStepGroupByAppBranchForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetWorkflowStepGroupByAppBranchForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetWorkflowStepGroupByAppBranchNotFound creates a GetWorkflowStepGroupByAppBranchNotFound with default headers values
func NewGetWorkflowStepGroupByAppBranchNotFound() *GetWorkflowStepGroupByAppBranchNotFound {
	return &GetWorkflowStepGroupByAppBranchNotFound{}
}

/*
GetWorkflowStepGroupByAppBranchNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetWorkflowStepGroupByAppBranchNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get workflow step group by app branch not found response has a 2xx status code
func (o *GetWorkflowStepGroupByAppBranchNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get workflow step group by app branch not found response has a 3xx status code
func (o *GetWorkflowStepGroupByAppBranchNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get workflow step group by app branch not found response has a 4xx status code
func (o *GetWorkflowStepGroupByAppBranchNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get workflow step group by app branch not found response has a 5xx status code
func (o *GetWorkflowStepGroupByAppBranchNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get workflow step group by app branch not found response a status code equal to that given
func (o *GetWorkflowStepGroupByAppBranchNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get workflow step group by app branch not found response
func (o *GetWorkflowStepGroupByAppBranchNotFound) Code() int {
	return 404
}

func (o *GetWorkflowStepGroupByAppBranchNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/step-groups/{{step_group_id}}][%d] getWorkflowStepGroupByAppBranchNotFound %s", 404, payload)
}

func (o *GetWorkflowStepGroupByAppBranchNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/step-groups/{{step_group_id}}][%d] getWorkflowStepGroupByAppBranchNotFound %s", 404, payload)
}

func (o *GetWorkflowStepGroupByAppBranchNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetWorkflowStepGroupByAppBranchNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetWorkflowStepGroupByAppBranchInternalServerError creates a GetWorkflowStepGroupByAppBranchInternalServerError with default headers values
func NewGetWorkflowStepGroupByAppBranchInternalServerError() *GetWorkflowStepGroupByAppBranchInternalServerError {
	return &GetWorkflowStepGroupByAppBranchInternalServerError{}
}

/*
GetWorkflowStepGroupByAppBranchInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetWorkflowStepGroupByAppBranchInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get workflow step group by app branch internal server error response has a 2xx status code
func (o *GetWorkflowStepGroupByAppBranchInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get workflow step group by app branch internal server error response has a 3xx status code
func (o *GetWorkflowStepGroupByAppBranchInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get workflow step group by app branch internal server error response has a 4xx status code
func (o *GetWorkflowStepGroupByAppBranchInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get workflow step group by app branch internal server error response has a 5xx status code
func (o *GetWorkflowStepGroupByAppBranchInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get workflow step group by app branch internal server error response a status code equal to that given
func (o *GetWorkflowStepGroupByAppBranchInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get workflow step group by app branch internal server error response
func (o *GetWorkflowStepGroupByAppBranchInternalServerError) Code() int {
	return 500
}

func (o *GetWorkflowStepGroupByAppBranchInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/step-groups/{{step_group_id}}][%d] getWorkflowStepGroupByAppBranchInternalServerError %s", 500, payload)
}

func (o *GetWorkflowStepGroupByAppBranchInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/workflows/{workflow_id}/step-groups/{{step_group_id}}][%d] getWorkflowStepGroupByAppBranchInternalServerError %s", 500, payload)
}

func (o *GetWorkflowStepGroupByAppBranchInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetWorkflowStepGroupByAppBranchInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
