// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetWorkflowStepApprovalContentsByInstallParams creates a new GetWorkflowStepApprovalContentsByInstallParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetWorkflowStepApprovalContentsByInstallParams() *GetWorkflowStepApprovalContentsByInstallParams {
	return &GetWorkflowStepApprovalContentsByInstallParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetWorkflowStepApprovalContentsByInstallParamsWithTimeout creates a new GetWorkflowStepApprovalContentsByInstallParams object
// with the ability to set a timeout on a request.
func NewGetWorkflowStepApprovalContentsByInstallParamsWithTimeout(timeout time.Duration) *GetWorkflowStepApprovalContentsByInstallParams {
	return &GetWorkflowStepApprovalContentsByInstallParams{
		timeout: timeout,
	}
}

// NewGetWorkflowStepApprovalContentsByInstallParamsWithContext creates a new GetWorkflowStepApprovalContentsByInstallParams object
// with the ability to set a context for a request.
func NewGetWorkflowStepApprovalContentsByInstallParamsWithContext(ctx context.Context) *GetWorkflowStepApprovalContentsByInstallParams {
	return &GetWorkflowStepApprovalContentsByInstallParams{
		Context: ctx,
	}
}

// NewGetWorkflowStepApprovalContentsByInstallParamsWithHTTPClient creates a new GetWorkflowStepApprovalContentsByInstallParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetWorkflowStepApprovalContentsByInstallParamsWithHTTPClient(client *http.Client) *GetWorkflowStepApprovalContentsByInstallParams {
	return &GetWorkflowStepApprovalContentsByInstallParams{
		HTTPClient: client,
	}
}

/*
GetWorkflowStepApprovalContentsByInstallParams contains all the parameters to send to the API endpoint

	for the get workflow step approval contents by install operation.

	Typically these are written to a http.Request.
*/
type GetWorkflowStepApprovalContentsByInstallParams struct {

	/* ApprovalID.

	   approval id
	*/
	ApprovalID string

	/* InstallID.

	   install ID
	*/
	InstallID string

	/* StepID.

	   step id
	*/
	StepID string

	/* WorkflowID.

	   workflow id
	*/
	WorkflowID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get workflow step approval contents by install params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWorkflowStepApprovalContentsByInstallParams) WithDefaults() *GetWorkflowStepApprovalContentsByInstallParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get workflow step approval contents by install params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWorkflowStepApprovalContentsByInstallParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get workflow step approval contents by install params
func (o *GetWorkflowStepApprovalContentsByInstallParams) WithTimeout(timeout time.Duration) *GetWorkflowStepApprovalContentsByInstallParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get workflow step approval contents by install params
func (o *GetWorkflowStepApprovalContentsByInstallParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get workflow step approval contents by install params
func (o *GetWorkflowStepApprovalContentsByInstallParams) WithContext(ctx context.Context) *GetWorkflowStepApprovalContentsByInstallParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get workflow step approval contents by install params
func (o *GetWorkflowStepApprovalContentsByInstallParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get workflow step approval contents by install params
func (o *GetWorkflowStepApprovalContentsByInstallParams) WithHTTPClient(client *http.Client) *GetWorkflowStepApprovalContentsByInstallParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get workflow step approval contents by install params
func (o *GetWorkflowStepApprovalContentsByInstallParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApprovalID adds the approvalID to the get workflow step approval contents by install params
func (o *GetWorkflowStepApprovalContentsByInstallParams) WithApprovalID(approvalID string) *GetWorkflowStepApprovalContentsByInstallParams {
	o.SetApprovalID(approvalID)
	return o
}

// SetApprovalID adds the approvalId to the get workflow step approval contents by install params
func (o *GetWorkflowStepApprovalContentsByInstallParams) SetApprovalID(approvalID string) {
	o.ApprovalID = approvalID
}

// WithInstallID adds the installID to the get workflow step approval contents by install params
func (o *GetWorkflowStepApprovalContentsByInstallParams) WithInstallID(installID string) *GetWorkflowStepApprovalContentsByInstallParams {
	o.SetInstallID(installID)
	return o
}

// SetInstallID adds the installId to the get workflow step approval contents by install params
func (o *GetWorkflowStepApprovalContentsByInstallParams) SetInstallID(installID string) {
	o.InstallID = installID
}

// WithStepID adds the stepID to the get workflow step approval contents by install params
func (o *GetWorkflowStepApprovalContentsByInstallParams) WithStepID(stepID string) *GetWorkflowStepApprovalContentsByInstallParams {
	o.SetStepID(stepID)
	return o
}

// SetStepID adds the stepId to the get workflow step approval contents by install params
func (o *GetWorkflowStepApprovalContentsByInstallParams) SetStepID(stepID string) {
	o.StepID = stepID
}

// WithWorkflowID adds the workflowID to the get workflow step approval contents by install params
func (o *GetWorkflowStepApprovalContentsByInstallParams) WithWorkflowID(workflowID string) *GetWorkflowStepApprovalContentsByInstallParams {
	o.SetWorkflowID(workflowID)
	return o
}

// SetWorkflowID adds the workflowId to the get workflow step approval contents by install params
func (o *GetWorkflowStepApprovalContentsByInstallParams) SetWorkflowID(workflowID string) {
	o.WorkflowID = workflowID
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkflowStepApprovalContentsByInstallParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param approval_id
	if err := r.SetPathParam("approval_id", o.ApprovalID); err != nil {
		return err
	}

	// path param install_id
	if err := r.SetPathParam("install_id", o.InstallID); err != nil {
		return err
	}

	// path param step_id
	if err := r.SetPathParam("step_id", o.StepID); err != nil {
		return err
	}

	// path param workflow_id
	if err := r.SetPathParam("workflow_id", o.WorkflowID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
