// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInstallConfigSyncsParams creates a new GetInstallConfigSyncsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInstallConfigSyncsParams() *GetInstallConfigSyncsParams {
	return &GetInstallConfigSyncsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstallConfigSyncsParamsWithTimeout creates a new GetInstallConfigSyncsParams object
// with the ability to set a timeout on a request.
func NewGetInstallConfigSyncsParamsWithTimeout(timeout time.Duration) *GetInstallConfigSyncsParams {
	return &GetInstallConfigSyncsParams{
		timeout: timeout,
	}
}

// NewGetInstallConfigSyncsParamsWithContext creates a new GetInstallConfigSyncsParams object
// with the ability to set a context for a request.
func NewGetInstallConfigSyncsParamsWithContext(ctx context.Context) *GetInstallConfigSyncsParams {
	return &GetInstallConfigSyncsParams{
		Context: ctx,
	}
}

// NewGetInstallConfigSyncsParamsWithHTTPClient creates a new GetInstallConfigSyncsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInstallConfigSyncsParamsWithHTTPClient(client *http.Client) *GetInstallConfigSyncsParams {
	return &GetInstallConfigSyncsParams{
		HTTPClient: client,
	}
}

/*
GetInstallConfigSyncsParams contains all the parameters to send to the API endpoint

	for the get install config syncs operation.

	Typically these are written to a http.Request.
*/
type GetInstallConfigSyncsParams struct {

	/* InstallID.

	   install ID
	*/
	InstallID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get install config syncs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallConfigSyncsParams) WithDefaults() *GetInstallConfigSyncsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get install config syncs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallConfigSyncsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get install config syncs params
func (o *GetInstallConfigSyncsParams) WithTimeout(timeout time.Duration) *GetInstallConfigSyncsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get install config syncs params
func (o *GetInstallConfigSyncsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get install config syncs params
func (o *GetInstallConfigSyncsParams) WithContext(ctx context.Context) *GetInstallConfigSyncsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get install config syncs params
func (o *GetInstallConfigSyncsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get install config syncs params
func (o *GetInstallConfigSyncsParams) WithHTTPClient(client *http.Client) *GetInstallConfigSyncsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get install config syncs params
func (o *GetInstallConfigSyncsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstallID adds the installID to the get install config syncs params
func (o *GetInstallConfigSyncsParams) WithInstallID(installID string) *GetInstallConfigSyncsParams {
	o.SetInstallID(installID)
	return o
}

// SetInstallID adds the installId to the get install config syncs params
func (o *GetInstallConfigSyncsParams) SetInstallID(installID string) {
	o.InstallID = installID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstallConfigSyncsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param install_id
	if err := r.SetPathParam("install_id", o.InstallID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
