// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInstallTerraformWorkspaceStateParams creates a new GetInstallTerraformWorkspaceStateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInstallTerraformWorkspaceStateParams() *GetInstallTerraformWorkspaceStateParams {
	return &GetInstallTerraformWorkspaceStateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstallTerraformWorkspaceStateParamsWithTimeout creates a new GetInstallTerraformWorkspaceStateParams object
// with the ability to set a timeout on a request.
func NewGetInstallTerraformWorkspaceStateParamsWithTimeout(timeout time.Duration) *GetInstallTerraformWorkspaceStateParams {
	return &GetInstallTerraformWorkspaceStateParams{
		timeout: timeout,
	}
}

// NewGetInstallTerraformWorkspaceStateParamsWithContext creates a new GetInstallTerraformWorkspaceStateParams object
// with the ability to set a context for a request.
func NewGetInstallTerraformWorkspaceStateParamsWithContext(ctx context.Context) *GetInstallTerraformWorkspaceStateParams {
	return &GetInstallTerraformWorkspaceStateParams{
		Context: ctx,
	}
}

// NewGetInstallTerraformWorkspaceStateParamsWithHTTPClient creates a new GetInstallTerraformWorkspaceStateParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInstallTerraformWorkspaceStateParamsWithHTTPClient(client *http.Client) *GetInstallTerraformWorkspaceStateParams {
	return &GetInstallTerraformWorkspaceStateParams{
		HTTPClient: client,
	}
}

/*
GetInstallTerraformWorkspaceStateParams contains all the parameters to send to the API endpoint

	for the get install terraform workspace state operation.

	Typically these are written to a http.Request.
*/
type GetInstallTerraformWorkspaceStateParams struct {

	/* InstallID.

	   install ID
	*/
	InstallID string

	/* StateID.

	   state ID
	*/
	StateID string

	/* WorkspaceID.

	   workspace ID
	*/
	WorkspaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get install terraform workspace state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallTerraformWorkspaceStateParams) WithDefaults() *GetInstallTerraformWorkspaceStateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get install terraform workspace state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallTerraformWorkspaceStateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get install terraform workspace state params
func (o *GetInstallTerraformWorkspaceStateParams) WithTimeout(timeout time.Duration) *GetInstallTerraformWorkspaceStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get install terraform workspace state params
func (o *GetInstallTerraformWorkspaceStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get install terraform workspace state params
func (o *GetInstallTerraformWorkspaceStateParams) WithContext(ctx context.Context) *GetInstallTerraformWorkspaceStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get install terraform workspace state params
func (o *GetInstallTerraformWorkspaceStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get install terraform workspace state params
func (o *GetInstallTerraformWorkspaceStateParams) WithHTTPClient(client *http.Client) *GetInstallTerraformWorkspaceStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get install terraform workspace state params
func (o *GetInstallTerraformWorkspaceStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstallID adds the installID to the get install terraform workspace state params
func (o *GetInstallTerraformWorkspaceStateParams) WithInstallID(installID string) *GetInstallTerraformWorkspaceStateParams {
	o.SetInstallID(installID)
	return o
}

// SetInstallID adds the installId to the get install terraform workspace state params
func (o *GetInstallTerraformWorkspaceStateParams) SetInstallID(installID string) {
	o.InstallID = installID
}

// WithStateID adds the stateID to the get install terraform workspace state params
func (o *GetInstallTerraformWorkspaceStateParams) WithStateID(stateID string) *GetInstallTerraformWorkspaceStateParams {
	o.SetStateID(stateID)
	return o
}

// SetStateID adds the stateId to the get install terraform workspace state params
func (o *GetInstallTerraformWorkspaceStateParams) SetStateID(stateID string) {
	o.StateID = stateID
}

// WithWorkspaceID adds the workspaceID to the get install terraform workspace state params
func (o *GetInstallTerraformWorkspaceStateParams) WithWorkspaceID(workspaceID string) *GetInstallTerraformWorkspaceStateParams {
	o.SetWorkspaceID(workspaceID)
	return o
}

// SetWorkspaceID adds the workspaceId to the get install terraform workspace state params
func (o *GetInstallTerraformWorkspaceStateParams) SetWorkspaceID(workspaceID string) {
	o.WorkspaceID = workspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstallTerraformWorkspaceStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param install_id
	if err := r.SetPathParam("install_id", o.InstallID); err != nil {
		return err
	}

	// path param state_id
	if err := r.SetPathParam("state_id", o.StateID); err != nil {
		return err
	}

	// path param workspace_id
	if err := r.SetPathParam("workspace_id", o.WorkspaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
