// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// ListOrgComponentBuildsReader is a Reader for the ListOrgComponentBuilds structure.
type ListOrgComponentBuildsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListOrgComponentBuildsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListOrgComponentBuildsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListOrgComponentBuildsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListOrgComponentBuildsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/component-builds] ListOrgComponentBuilds", response, response.Code())
	}
}

// NewListOrgComponentBuildsOK creates a ListOrgComponentBuildsOK with default headers values
func NewListOrgComponentBuildsOK() *ListOrgComponentBuildsOK {
	return &ListOrgComponentBuildsOK{}
}

/*
ListOrgComponentBuildsOK describes a response with status code 200, with default header values.

OK
*/
type ListOrgComponentBuildsOK struct {
	Payload *models.ServiceOrgComponentBuildHistoryResponse
}

// IsSuccess returns true when this list org component builds o k response has a 2xx status code
func (o *ListOrgComponentBuildsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list org component builds o k response has a 3xx status code
func (o *ListOrgComponentBuildsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list org component builds o k response has a 4xx status code
func (o *ListOrgComponentBuildsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list org component builds o k response has a 5xx status code
func (o *ListOrgComponentBuildsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list org component builds o k response a status code equal to that given
func (o *ListOrgComponentBuildsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list org component builds o k response
func (o *ListOrgComponentBuildsOK) Code() int {
	return 200
}

func (o *ListOrgComponentBuildsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/component-builds][%d] listOrgComponentBuildsOK %s", 200, payload)
}

func (o *ListOrgComponentBuildsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/component-builds][%d] listOrgComponentBuildsOK %s", 200, payload)
}

func (o *ListOrgComponentBuildsOK) GetPayload() *models.ServiceOrgComponentBuildHistoryResponse {
	return o.Payload
}

func (o *ListOrgComponentBuildsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceOrgComponentBuildHistoryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListOrgComponentBuildsBadRequest creates a ListOrgComponentBuildsBadRequest with default headers values
func NewListOrgComponentBuildsBadRequest() *ListOrgComponentBuildsBadRequest {
	return &ListOrgComponentBuildsBadRequest{}
}

/*
ListOrgComponentBuildsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ListOrgComponentBuildsBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this list org component builds bad request response has a 2xx status code
func (o *ListOrgComponentBuildsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list org component builds bad request response has a 3xx status code
func (o *ListOrgComponentBuildsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list org component builds bad request response has a 4xx status code
func (o *ListOrgComponentBuildsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list org component builds bad request response has a 5xx status code
func (o *ListOrgComponentBuildsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list org component builds bad request response a status code equal to that given
func (o *ListOrgComponentBuildsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list org component builds bad request response
func (o *ListOrgComponentBuildsBadRequest) Code() int {
	return 400
}

func (o *ListOrgComponentBuildsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/component-builds][%d] listOrgComponentBuildsBadRequest %s", 400, payload)
}

func (o *ListOrgComponentBuildsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/component-builds][%d] listOrgComponentBuildsBadRequest %s", 400, payload)
}

func (o *ListOrgComponentBuildsBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *ListOrgComponentBuildsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListOrgComponentBuildsInternalServerError creates a ListOrgComponentBuildsInternalServerError with default headers values
func NewListOrgComponentBuildsInternalServerError() *ListOrgComponentBuildsInternalServerError {
	return &ListOrgComponentBuildsInternalServerError{}
}

/*
ListOrgComponentBuildsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ListOrgComponentBuildsInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this list org component builds internal server error response has a 2xx status code
func (o *ListOrgComponentBuildsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list org component builds internal server error response has a 3xx status code
func (o *ListOrgComponentBuildsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list org component builds internal server error response has a 4xx status code
func (o *ListOrgComponentBuildsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list org component builds internal server error response has a 5xx status code
func (o *ListOrgComponentBuildsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list org component builds internal server error response a status code equal to that given
func (o *ListOrgComponentBuildsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list org component builds internal server error response
func (o *ListOrgComponentBuildsInternalServerError) Code() int {
	return 500
}

func (o *ListOrgComponentBuildsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/component-builds][%d] listOrgComponentBuildsInternalServerError %s", 500, payload)
}

func (o *ListOrgComponentBuildsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/component-builds][%d] listOrgComponentBuildsInternalServerError %s", 500, payload)
}

func (o *ListOrgComponentBuildsInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *ListOrgComponentBuildsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
