// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// LockInstallTerraformWorkspaceReader is a Reader for the LockInstallTerraformWorkspace structure.
type LockInstallTerraformWorkspaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LockInstallTerraformWorkspaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewLockInstallTerraformWorkspaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewLockInstallTerraformWorkspaceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewLockInstallTerraformWorkspaceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewLockInstallTerraformWorkspaceForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewLockInstallTerraformWorkspaceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewLockInstallTerraformWorkspaceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/lock] LockInstallTerraformWorkspace", response, response.Code())
	}
}

// NewLockInstallTerraformWorkspaceOK creates a LockInstallTerraformWorkspaceOK with default headers values
func NewLockInstallTerraformWorkspaceOK() *LockInstallTerraformWorkspaceOK {
	return &LockInstallTerraformWorkspaceOK{}
}

/*
LockInstallTerraformWorkspaceOK describes a response with status code 200, with default header values.

OK
*/
type LockInstallTerraformWorkspaceOK struct {
	Payload *models.AppTerraformWorkspaceState
}

// IsSuccess returns true when this lock install terraform workspace o k response has a 2xx status code
func (o *LockInstallTerraformWorkspaceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this lock install terraform workspace o k response has a 3xx status code
func (o *LockInstallTerraformWorkspaceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lock install terraform workspace o k response has a 4xx status code
func (o *LockInstallTerraformWorkspaceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this lock install terraform workspace o k response has a 5xx status code
func (o *LockInstallTerraformWorkspaceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this lock install terraform workspace o k response a status code equal to that given
func (o *LockInstallTerraformWorkspaceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the lock install terraform workspace o k response
func (o *LockInstallTerraformWorkspaceOK) Code() int {
	return 200
}

func (o *LockInstallTerraformWorkspaceOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/lock][%d] lockInstallTerraformWorkspaceOK %s", 200, payload)
}

func (o *LockInstallTerraformWorkspaceOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/lock][%d] lockInstallTerraformWorkspaceOK %s", 200, payload)
}

func (o *LockInstallTerraformWorkspaceOK) GetPayload() *models.AppTerraformWorkspaceState {
	return o.Payload
}

func (o *LockInstallTerraformWorkspaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppTerraformWorkspaceState)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewLockInstallTerraformWorkspaceBadRequest creates a LockInstallTerraformWorkspaceBadRequest with default headers values
func NewLockInstallTerraformWorkspaceBadRequest() *LockInstallTerraformWorkspaceBadRequest {
	return &LockInstallTerraformWorkspaceBadRequest{}
}

/*
LockInstallTerraformWorkspaceBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type LockInstallTerraformWorkspaceBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this lock install terraform workspace bad request response has a 2xx status code
func (o *LockInstallTerraformWorkspaceBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this lock install terraform workspace bad request response has a 3xx status code
func (o *LockInstallTerraformWorkspaceBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lock install terraform workspace bad request response has a 4xx status code
func (o *LockInstallTerraformWorkspaceBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this lock install terraform workspace bad request response has a 5xx status code
func (o *LockInstallTerraformWorkspaceBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this lock install terraform workspace bad request response a status code equal to that given
func (o *LockInstallTerraformWorkspaceBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the lock install terraform workspace bad request response
func (o *LockInstallTerraformWorkspaceBadRequest) Code() int {
	return 400
}

func (o *LockInstallTerraformWorkspaceBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/lock][%d] lockInstallTerraformWorkspaceBadRequest %s", 400, payload)
}

func (o *LockInstallTerraformWorkspaceBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/lock][%d] lockInstallTerraformWorkspaceBadRequest %s", 400, payload)
}

func (o *LockInstallTerraformWorkspaceBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *LockInstallTerraformWorkspaceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewLockInstallTerraformWorkspaceUnauthorized creates a LockInstallTerraformWorkspaceUnauthorized with default headers values
func NewLockInstallTerraformWorkspaceUnauthorized() *LockInstallTerraformWorkspaceUnauthorized {
	return &LockInstallTerraformWorkspaceUnauthorized{}
}

/*
LockInstallTerraformWorkspaceUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type LockInstallTerraformWorkspaceUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this lock install terraform workspace unauthorized response has a 2xx status code
func (o *LockInstallTerraformWorkspaceUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this lock install terraform workspace unauthorized response has a 3xx status code
func (o *LockInstallTerraformWorkspaceUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lock install terraform workspace unauthorized response has a 4xx status code
func (o *LockInstallTerraformWorkspaceUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this lock install terraform workspace unauthorized response has a 5xx status code
func (o *LockInstallTerraformWorkspaceUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this lock install terraform workspace unauthorized response a status code equal to that given
func (o *LockInstallTerraformWorkspaceUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the lock install terraform workspace unauthorized response
func (o *LockInstallTerraformWorkspaceUnauthorized) Code() int {
	return 401
}

func (o *LockInstallTerraformWorkspaceUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/lock][%d] lockInstallTerraformWorkspaceUnauthorized %s", 401, payload)
}

func (o *LockInstallTerraformWorkspaceUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/lock][%d] lockInstallTerraformWorkspaceUnauthorized %s", 401, payload)
}

func (o *LockInstallTerraformWorkspaceUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *LockInstallTerraformWorkspaceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewLockInstallTerraformWorkspaceForbidden creates a LockInstallTerraformWorkspaceForbidden with default headers values
func NewLockInstallTerraformWorkspaceForbidden() *LockInstallTerraformWorkspaceForbidden {
	return &LockInstallTerraformWorkspaceForbidden{}
}

/*
LockInstallTerraformWorkspaceForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type LockInstallTerraformWorkspaceForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this lock install terraform workspace forbidden response has a 2xx status code
func (o *LockInstallTerraformWorkspaceForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this lock install terraform workspace forbidden response has a 3xx status code
func (o *LockInstallTerraformWorkspaceForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lock install terraform workspace forbidden response has a 4xx status code
func (o *LockInstallTerraformWorkspaceForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this lock install terraform workspace forbidden response has a 5xx status code
func (o *LockInstallTerraformWorkspaceForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this lock install terraform workspace forbidden response a status code equal to that given
func (o *LockInstallTerraformWorkspaceForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the lock install terraform workspace forbidden response
func (o *LockInstallTerraformWorkspaceForbidden) Code() int {
	return 403
}

func (o *LockInstallTerraformWorkspaceForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/lock][%d] lockInstallTerraformWorkspaceForbidden %s", 403, payload)
}

func (o *LockInstallTerraformWorkspaceForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/lock][%d] lockInstallTerraformWorkspaceForbidden %s", 403, payload)
}

func (o *LockInstallTerraformWorkspaceForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *LockInstallTerraformWorkspaceForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewLockInstallTerraformWorkspaceNotFound creates a LockInstallTerraformWorkspaceNotFound with default headers values
func NewLockInstallTerraformWorkspaceNotFound() *LockInstallTerraformWorkspaceNotFound {
	return &LockInstallTerraformWorkspaceNotFound{}
}

/*
LockInstallTerraformWorkspaceNotFound describes a response with status code 404, with default header values.

Not Found
*/
type LockInstallTerraformWorkspaceNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this lock install terraform workspace not found response has a 2xx status code
func (o *LockInstallTerraformWorkspaceNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this lock install terraform workspace not found response has a 3xx status code
func (o *LockInstallTerraformWorkspaceNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lock install terraform workspace not found response has a 4xx status code
func (o *LockInstallTerraformWorkspaceNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this lock install terraform workspace not found response has a 5xx status code
func (o *LockInstallTerraformWorkspaceNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this lock install terraform workspace not found response a status code equal to that given
func (o *LockInstallTerraformWorkspaceNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the lock install terraform workspace not found response
func (o *LockInstallTerraformWorkspaceNotFound) Code() int {
	return 404
}

func (o *LockInstallTerraformWorkspaceNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/lock][%d] lockInstallTerraformWorkspaceNotFound %s", 404, payload)
}

func (o *LockInstallTerraformWorkspaceNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/lock][%d] lockInstallTerraformWorkspaceNotFound %s", 404, payload)
}

func (o *LockInstallTerraformWorkspaceNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *LockInstallTerraformWorkspaceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewLockInstallTerraformWorkspaceInternalServerError creates a LockInstallTerraformWorkspaceInternalServerError with default headers values
func NewLockInstallTerraformWorkspaceInternalServerError() *LockInstallTerraformWorkspaceInternalServerError {
	return &LockInstallTerraformWorkspaceInternalServerError{}
}

/*
LockInstallTerraformWorkspaceInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type LockInstallTerraformWorkspaceInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this lock install terraform workspace internal server error response has a 2xx status code
func (o *LockInstallTerraformWorkspaceInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this lock install terraform workspace internal server error response has a 3xx status code
func (o *LockInstallTerraformWorkspaceInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lock install terraform workspace internal server error response has a 4xx status code
func (o *LockInstallTerraformWorkspaceInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this lock install terraform workspace internal server error response has a 5xx status code
func (o *LockInstallTerraformWorkspaceInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this lock install terraform workspace internal server error response a status code equal to that given
func (o *LockInstallTerraformWorkspaceInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the lock install terraform workspace internal server error response
func (o *LockInstallTerraformWorkspaceInternalServerError) Code() int {
	return 500
}

func (o *LockInstallTerraformWorkspaceInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/lock][%d] lockInstallTerraformWorkspaceInternalServerError %s", 500, payload)
}

func (o *LockInstallTerraformWorkspaceInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/installs/{install_id}/terraform-workspaces/{workspace_id}/lock][%d] lockInstallTerraformWorkspaceInternalServerError %s", 500, payload)
}

func (o *LockInstallTerraformWorkspaceInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *LockInstallTerraformWorkspaceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
