// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewReadInstallRunnerJobLogsParams creates a new ReadInstallRunnerJobLogsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReadInstallRunnerJobLogsParams() *ReadInstallRunnerJobLogsParams {
	return &ReadInstallRunnerJobLogsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReadInstallRunnerJobLogsParamsWithTimeout creates a new ReadInstallRunnerJobLogsParams object
// with the ability to set a timeout on a request.
func NewReadInstallRunnerJobLogsParamsWithTimeout(timeout time.Duration) *ReadInstallRunnerJobLogsParams {
	return &ReadInstallRunnerJobLogsParams{
		timeout: timeout,
	}
}

// NewReadInstallRunnerJobLogsParamsWithContext creates a new ReadInstallRunnerJobLogsParams object
// with the ability to set a context for a request.
func NewReadInstallRunnerJobLogsParamsWithContext(ctx context.Context) *ReadInstallRunnerJobLogsParams {
	return &ReadInstallRunnerJobLogsParams{
		Context: ctx,
	}
}

// NewReadInstallRunnerJobLogsParamsWithHTTPClient creates a new ReadInstallRunnerJobLogsParams object
// with the ability to set a custom HTTPClient for a request.
func NewReadInstallRunnerJobLogsParamsWithHTTPClient(client *http.Client) *ReadInstallRunnerJobLogsParams {
	return &ReadInstallRunnerJobLogsParams{
		HTTPClient: client,
	}
}

/*
ReadInstallRunnerJobLogsParams contains all the parameters to send to the API endpoint

	for the read install runner job logs operation.

	Typically these are written to a http.Request.
*/
type ReadInstallRunnerJobLogsParams struct {

	/* XNuonAPIOffset.

	   log stream offset
	*/
	XNuonAPIOffset *string

	/* HelmOperation.

	   filter by log_attributes['helm.operation']
	*/
	HelmOperation *string

	/* HelmReleaseName.

	   filter by log_attributes['helm.release_name']
	*/
	HelmReleaseName *string

	/* InstallID.

	   install ID
	*/
	InstallID string

	/* K8sKind.

	   filter by log_attributes['k8s.kind']
	*/
	K8sKind *string

	/* K8sName.

	   filter by log_attributes['k8s.name']
	*/
	K8sName *string

	/* K8sNamespace.

	   filter by log_attributes['k8s.namespace']
	*/
	K8sNamespace *string

	/* Order.

	   sort direction

	   Default: "asc"
	*/
	Order *string

	/* Q.

	   case-insensitive substring filter on log body
	*/
	Q *string

	/* RunnerJobID.

	   runner job ID
	*/
	RunnerJobID string

	/* ScopeName.

	   filter by scope_name (repeatable)
	*/
	ScopeName []string

	/* ServiceName.

	   filter by service_name (repeatable)
	*/
	ServiceName []string

	/* SeverityText.

	   filter by severity_text (repeatable)
	*/
	SeverityText []string

	/* SpanID.

	   filter by exact span_id (dedicated CH column)
	*/
	SpanID *string

	/* TfOperation.

	   filter by log_attributes['tf.operation']
	*/
	TfOperation *string

	/* TfWorkspaceID.

	   filter by log_attributes['tf.workspace_id']
	*/
	TfWorkspaceID *string

	/* Tool.

	   filter by log_attributes['nuon.tool']
	*/
	Tool *string

	/* TraceID.

	   filter by exact trace_id (dedicated CH column)
	*/
	TraceID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the read install runner job logs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReadInstallRunnerJobLogsParams) WithDefaults() *ReadInstallRunnerJobLogsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the read install runner job logs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReadInstallRunnerJobLogsParams) SetDefaults() {
	var (
		orderDefault = string("asc")
	)

	val := ReadInstallRunnerJobLogsParams{
		Order: &orderDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithTimeout(timeout time.Duration) *ReadInstallRunnerJobLogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithContext(ctx context.Context) *ReadInstallRunnerJobLogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithHTTPClient(client *http.Client) *ReadInstallRunnerJobLogsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXNuonAPIOffset adds the xNuonAPIOffset to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithXNuonAPIOffset(xNuonAPIOffset *string) *ReadInstallRunnerJobLogsParams {
	o.SetXNuonAPIOffset(xNuonAPIOffset)
	return o
}

// SetXNuonAPIOffset adds the xNuonApiOffset to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetXNuonAPIOffset(xNuonAPIOffset *string) {
	o.XNuonAPIOffset = xNuonAPIOffset
}

// WithHelmOperation adds the helmOperation to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithHelmOperation(helmOperation *string) *ReadInstallRunnerJobLogsParams {
	o.SetHelmOperation(helmOperation)
	return o
}

// SetHelmOperation adds the helmOperation to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetHelmOperation(helmOperation *string) {
	o.HelmOperation = helmOperation
}

// WithHelmReleaseName adds the helmReleaseName to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithHelmReleaseName(helmReleaseName *string) *ReadInstallRunnerJobLogsParams {
	o.SetHelmReleaseName(helmReleaseName)
	return o
}

// SetHelmReleaseName adds the helmReleaseName to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetHelmReleaseName(helmReleaseName *string) {
	o.HelmReleaseName = helmReleaseName
}

// WithInstallID adds the installID to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithInstallID(installID string) *ReadInstallRunnerJobLogsParams {
	o.SetInstallID(installID)
	return o
}

// SetInstallID adds the installId to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetInstallID(installID string) {
	o.InstallID = installID
}

// WithK8sKind adds the k8sKind to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithK8sKind(k8sKind *string) *ReadInstallRunnerJobLogsParams {
	o.SetK8sKind(k8sKind)
	return o
}

// SetK8sKind adds the k8sKind to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetK8sKind(k8sKind *string) {
	o.K8sKind = k8sKind
}

// WithK8sName adds the k8sName to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithK8sName(k8sName *string) *ReadInstallRunnerJobLogsParams {
	o.SetK8sName(k8sName)
	return o
}

// SetK8sName adds the k8sName to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetK8sName(k8sName *string) {
	o.K8sName = k8sName
}

// WithK8sNamespace adds the k8sNamespace to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithK8sNamespace(k8sNamespace *string) *ReadInstallRunnerJobLogsParams {
	o.SetK8sNamespace(k8sNamespace)
	return o
}

// SetK8sNamespace adds the k8sNamespace to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetK8sNamespace(k8sNamespace *string) {
	o.K8sNamespace = k8sNamespace
}

// WithOrder adds the order to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithOrder(order *string) *ReadInstallRunnerJobLogsParams {
	o.SetOrder(order)
	return o
}

// SetOrder adds the order to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetOrder(order *string) {
	o.Order = order
}

// WithQ adds the q to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithQ(q *string) *ReadInstallRunnerJobLogsParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetQ(q *string) {
	o.Q = q
}

// WithRunnerJobID adds the runnerJobID to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithRunnerJobID(runnerJobID string) *ReadInstallRunnerJobLogsParams {
	o.SetRunnerJobID(runnerJobID)
	return o
}

// SetRunnerJobID adds the runnerJobId to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetRunnerJobID(runnerJobID string) {
	o.RunnerJobID = runnerJobID
}

// WithScopeName adds the scopeName to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithScopeName(scopeName []string) *ReadInstallRunnerJobLogsParams {
	o.SetScopeName(scopeName)
	return o
}

// SetScopeName adds the scopeName to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetScopeName(scopeName []string) {
	o.ScopeName = scopeName
}

// WithServiceName adds the serviceName to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithServiceName(serviceName []string) *ReadInstallRunnerJobLogsParams {
	o.SetServiceName(serviceName)
	return o
}

// SetServiceName adds the serviceName to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetServiceName(serviceName []string) {
	o.ServiceName = serviceName
}

// WithSeverityText adds the severityText to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithSeverityText(severityText []string) *ReadInstallRunnerJobLogsParams {
	o.SetSeverityText(severityText)
	return o
}

// SetSeverityText adds the severityText to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetSeverityText(severityText []string) {
	o.SeverityText = severityText
}

// WithSpanID adds the spanID to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithSpanID(spanID *string) *ReadInstallRunnerJobLogsParams {
	o.SetSpanID(spanID)
	return o
}

// SetSpanID adds the spanId to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetSpanID(spanID *string) {
	o.SpanID = spanID
}

// WithTfOperation adds the tfOperation to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithTfOperation(tfOperation *string) *ReadInstallRunnerJobLogsParams {
	o.SetTfOperation(tfOperation)
	return o
}

// SetTfOperation adds the tfOperation to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetTfOperation(tfOperation *string) {
	o.TfOperation = tfOperation
}

// WithTfWorkspaceID adds the tfWorkspaceID to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithTfWorkspaceID(tfWorkspaceID *string) *ReadInstallRunnerJobLogsParams {
	o.SetTfWorkspaceID(tfWorkspaceID)
	return o
}

// SetTfWorkspaceID adds the tfWorkspaceId to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetTfWorkspaceID(tfWorkspaceID *string) {
	o.TfWorkspaceID = tfWorkspaceID
}

// WithTool adds the tool to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithTool(tool *string) *ReadInstallRunnerJobLogsParams {
	o.SetTool(tool)
	return o
}

// SetTool adds the tool to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetTool(tool *string) {
	o.Tool = tool
}

// WithTraceID adds the traceID to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) WithTraceID(traceID *string) *ReadInstallRunnerJobLogsParams {
	o.SetTraceID(traceID)
	return o
}

// SetTraceID adds the traceId to the read install runner job logs params
func (o *ReadInstallRunnerJobLogsParams) SetTraceID(traceID *string) {
	o.TraceID = traceID
}

// WriteToRequest writes these params to a swagger request
func (o *ReadInstallRunnerJobLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XNuonAPIOffset != nil {

		// header param X-Nuon-API-Offset
		if err := r.SetHeaderParam("X-Nuon-API-Offset", *o.XNuonAPIOffset); err != nil {
			return err
		}
	}

	if o.HelmOperation != nil {

		// query param helm_operation
		var qrHelmOperation string

		if o.HelmOperation != nil {
			qrHelmOperation = *o.HelmOperation
		}
		qHelmOperation := qrHelmOperation
		if qHelmOperation != "" {

			if err := r.SetQueryParam("helm_operation", qHelmOperation); err != nil {
				return err
			}
		}
	}

	if o.HelmReleaseName != nil {

		// query param helm_release_name
		var qrHelmReleaseName string

		if o.HelmReleaseName != nil {
			qrHelmReleaseName = *o.HelmReleaseName
		}
		qHelmReleaseName := qrHelmReleaseName
		if qHelmReleaseName != "" {

			if err := r.SetQueryParam("helm_release_name", qHelmReleaseName); err != nil {
				return err
			}
		}
	}

	// path param install_id
	if err := r.SetPathParam("install_id", o.InstallID); err != nil {
		return err
	}

	if o.K8sKind != nil {

		// query param k8s_kind
		var qrK8sKind string

		if o.K8sKind != nil {
			qrK8sKind = *o.K8sKind
		}
		qK8sKind := qrK8sKind
		if qK8sKind != "" {

			if err := r.SetQueryParam("k8s_kind", qK8sKind); err != nil {
				return err
			}
		}
	}

	if o.K8sName != nil {

		// query param k8s_name
		var qrK8sName string

		if o.K8sName != nil {
			qrK8sName = *o.K8sName
		}
		qK8sName := qrK8sName
		if qK8sName != "" {

			if err := r.SetQueryParam("k8s_name", qK8sName); err != nil {
				return err
			}
		}
	}

	if o.K8sNamespace != nil {

		// query param k8s_namespace
		var qrK8sNamespace string

		if o.K8sNamespace != nil {
			qrK8sNamespace = *o.K8sNamespace
		}
		qK8sNamespace := qrK8sNamespace
		if qK8sNamespace != "" {

			if err := r.SetQueryParam("k8s_namespace", qK8sNamespace); err != nil {
				return err
			}
		}
	}

	if o.Order != nil {

		// query param order
		var qrOrder string

		if o.Order != nil {
			qrOrder = *o.Order
		}
		qOrder := qrOrder
		if qOrder != "" {

			if err := r.SetQueryParam("order", qOrder); err != nil {
				return err
			}
		}
	}

	if o.Q != nil {

		// query param q
		var qrQ string

		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {

			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}
	}

	// path param runner_job_id
	if err := r.SetPathParam("runner_job_id", o.RunnerJobID); err != nil {
		return err
	}

	if o.ScopeName != nil {

		// binding items for scope_name
		joinedScopeName := o.bindParamScopeName(reg)

		// query array param scope_name
		if err := r.SetQueryParam("scope_name", joinedScopeName...); err != nil {
			return err
		}
	}

	if o.ServiceName != nil {

		// binding items for service_name
		joinedServiceName := o.bindParamServiceName(reg)

		// query array param service_name
		if err := r.SetQueryParam("service_name", joinedServiceName...); err != nil {
			return err
		}
	}

	if o.SeverityText != nil {

		// binding items for severity_text
		joinedSeverityText := o.bindParamSeverityText(reg)

		// query array param severity_text
		if err := r.SetQueryParam("severity_text", joinedSeverityText...); err != nil {
			return err
		}
	}

	if o.SpanID != nil {

		// query param span_id
		var qrSpanID string

		if o.SpanID != nil {
			qrSpanID = *o.SpanID
		}
		qSpanID := qrSpanID
		if qSpanID != "" {

			if err := r.SetQueryParam("span_id", qSpanID); err != nil {
				return err
			}
		}
	}

	if o.TfOperation != nil {

		// query param tf_operation
		var qrTfOperation string

		if o.TfOperation != nil {
			qrTfOperation = *o.TfOperation
		}
		qTfOperation := qrTfOperation
		if qTfOperation != "" {

			if err := r.SetQueryParam("tf_operation", qTfOperation); err != nil {
				return err
			}
		}
	}

	if o.TfWorkspaceID != nil {

		// query param tf_workspace_id
		var qrTfWorkspaceID string

		if o.TfWorkspaceID != nil {
			qrTfWorkspaceID = *o.TfWorkspaceID
		}
		qTfWorkspaceID := qrTfWorkspaceID
		if qTfWorkspaceID != "" {

			if err := r.SetQueryParam("tf_workspace_id", qTfWorkspaceID); err != nil {
				return err
			}
		}
	}

	if o.Tool != nil {

		// query param tool
		var qrTool string

		if o.Tool != nil {
			qrTool = *o.Tool
		}
		qTool := qrTool
		if qTool != "" {

			if err := r.SetQueryParam("tool", qTool); err != nil {
				return err
			}
		}
	}

	if o.TraceID != nil {

		// query param trace_id
		var qrTraceID string

		if o.TraceID != nil {
			qrTraceID = *o.TraceID
		}
		qTraceID := qrTraceID
		if qTraceID != "" {

			if err := r.SetQueryParam("trace_id", qTraceID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamReadInstallRunnerJobLogs binds the parameter scope_name
func (o *ReadInstallRunnerJobLogsParams) bindParamScopeName(formats strfmt.Registry) []string {
	scopeNameIR := o.ScopeName

	var scopeNameIC []string
	for _, scopeNameIIR := range scopeNameIR { // explode []string

		scopeNameIIV := scopeNameIIR // string as string
		scopeNameIC = append(scopeNameIC, scopeNameIIV)
	}

	// items.CollectionFormat: "csv"
	scopeNameIS := swag.JoinByFormat(scopeNameIC, "csv")

	return scopeNameIS
}

// bindParamReadInstallRunnerJobLogs binds the parameter service_name
func (o *ReadInstallRunnerJobLogsParams) bindParamServiceName(formats strfmt.Registry) []string {
	serviceNameIR := o.ServiceName

	var serviceNameIC []string
	for _, serviceNameIIR := range serviceNameIR { // explode []string

		serviceNameIIV := serviceNameIIR // string as string
		serviceNameIC = append(serviceNameIC, serviceNameIIV)
	}

	// items.CollectionFormat: "csv"
	serviceNameIS := swag.JoinByFormat(serviceNameIC, "csv")

	return serviceNameIS
}

// bindParamReadInstallRunnerJobLogs binds the parameter severity_text
func (o *ReadInstallRunnerJobLogsParams) bindParamSeverityText(formats strfmt.Registry) []string {
	severityTextIR := o.SeverityText

	var severityTextIC []string
	for _, severityTextIIR := range severityTextIR { // explode []string

		severityTextIIV := severityTextIIR // string as string
		severityTextIC = append(severityTextIC, severityTextIIV)
	}

	// items.CollectionFormat: "csv"
	severityTextIS := swag.JoinByFormat(severityTextIC, "csv")

	return severityTextIS
}
