// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// RegisterInstallReader is a Reader for the RegisterInstall structure.
type RegisterInstallReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RegisterInstallReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewRegisterInstallOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewRegisterInstallCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRegisterInstallBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRegisterInstallNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/install-registrations] RegisterInstall", response, response.Code())
	}
}

// NewRegisterInstallOK creates a RegisterInstallOK with default headers values
func NewRegisterInstallOK() *RegisterInstallOK {
	return &RegisterInstallOK{}
}

/*
RegisterInstallOK describes a response with status code 200, with default header values.

OK
*/
type RegisterInstallOK struct {
	Payload *models.ServiceInstallRegistrationResponse
}

// IsSuccess returns true when this register install o k response has a 2xx status code
func (o *RegisterInstallOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this register install o k response has a 3xx status code
func (o *RegisterInstallOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this register install o k response has a 4xx status code
func (o *RegisterInstallOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this register install o k response has a 5xx status code
func (o *RegisterInstallOK) IsServerError() bool {
	return false
}

// IsCode returns true when this register install o k response a status code equal to that given
func (o *RegisterInstallOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the register install o k response
func (o *RegisterInstallOK) Code() int {
	return 200
}

func (o *RegisterInstallOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/install-registrations][%d] registerInstallOK %s", 200, payload)
}

func (o *RegisterInstallOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/install-registrations][%d] registerInstallOK %s", 200, payload)
}

func (o *RegisterInstallOK) GetPayload() *models.ServiceInstallRegistrationResponse {
	return o.Payload
}

func (o *RegisterInstallOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceInstallRegistrationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRegisterInstallCreated creates a RegisterInstallCreated with default headers values
func NewRegisterInstallCreated() *RegisterInstallCreated {
	return &RegisterInstallCreated{}
}

/*
RegisterInstallCreated describes a response with status code 201, with default header values.

Created
*/
type RegisterInstallCreated struct {
	Payload *models.ServiceInstallRegistrationResponse
}

// IsSuccess returns true when this register install created response has a 2xx status code
func (o *RegisterInstallCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this register install created response has a 3xx status code
func (o *RegisterInstallCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this register install created response has a 4xx status code
func (o *RegisterInstallCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this register install created response has a 5xx status code
func (o *RegisterInstallCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this register install created response a status code equal to that given
func (o *RegisterInstallCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the register install created response
func (o *RegisterInstallCreated) Code() int {
	return 201
}

func (o *RegisterInstallCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/install-registrations][%d] registerInstallCreated %s", 201, payload)
}

func (o *RegisterInstallCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/install-registrations][%d] registerInstallCreated %s", 201, payload)
}

func (o *RegisterInstallCreated) GetPayload() *models.ServiceInstallRegistrationResponse {
	return o.Payload
}

func (o *RegisterInstallCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceInstallRegistrationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRegisterInstallBadRequest creates a RegisterInstallBadRequest with default headers values
func NewRegisterInstallBadRequest() *RegisterInstallBadRequest {
	return &RegisterInstallBadRequest{}
}

/*
RegisterInstallBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type RegisterInstallBadRequest struct {
	Payload map[string]string
}

// IsSuccess returns true when this register install bad request response has a 2xx status code
func (o *RegisterInstallBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this register install bad request response has a 3xx status code
func (o *RegisterInstallBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this register install bad request response has a 4xx status code
func (o *RegisterInstallBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this register install bad request response has a 5xx status code
func (o *RegisterInstallBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this register install bad request response a status code equal to that given
func (o *RegisterInstallBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the register install bad request response
func (o *RegisterInstallBadRequest) Code() int {
	return 400
}

func (o *RegisterInstallBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/install-registrations][%d] registerInstallBadRequest %s", 400, payload)
}

func (o *RegisterInstallBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/install-registrations][%d] registerInstallBadRequest %s", 400, payload)
}

func (o *RegisterInstallBadRequest) GetPayload() map[string]string {
	return o.Payload
}

func (o *RegisterInstallBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRegisterInstallNotFound creates a RegisterInstallNotFound with default headers values
func NewRegisterInstallNotFound() *RegisterInstallNotFound {
	return &RegisterInstallNotFound{}
}

/*
RegisterInstallNotFound describes a response with status code 404, with default header values.

Not Found
*/
type RegisterInstallNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this register install not found response has a 2xx status code
func (o *RegisterInstallNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this register install not found response has a 3xx status code
func (o *RegisterInstallNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this register install not found response has a 4xx status code
func (o *RegisterInstallNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this register install not found response has a 5xx status code
func (o *RegisterInstallNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this register install not found response a status code equal to that given
func (o *RegisterInstallNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the register install not found response
func (o *RegisterInstallNotFound) Code() int {
	return 404
}

func (o *RegisterInstallNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/install-registrations][%d] registerInstallNotFound %s", 404, payload)
}

func (o *RegisterInstallNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/install-registrations][%d] registerInstallNotFound %s", 404, payload)
}

func (o *RegisterInstallNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *RegisterInstallNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
