// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// NewReprovisionInstallStackParams creates a new ReprovisionInstallStackParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReprovisionInstallStackParams() *ReprovisionInstallStackParams {
	return &ReprovisionInstallStackParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReprovisionInstallStackParamsWithTimeout creates a new ReprovisionInstallStackParams object
// with the ability to set a timeout on a request.
func NewReprovisionInstallStackParamsWithTimeout(timeout time.Duration) *ReprovisionInstallStackParams {
	return &ReprovisionInstallStackParams{
		timeout: timeout,
	}
}

// NewReprovisionInstallStackParamsWithContext creates a new ReprovisionInstallStackParams object
// with the ability to set a context for a request.
func NewReprovisionInstallStackParamsWithContext(ctx context.Context) *ReprovisionInstallStackParams {
	return &ReprovisionInstallStackParams{
		Context: ctx,
	}
}

// NewReprovisionInstallStackParamsWithHTTPClient creates a new ReprovisionInstallStackParams object
// with the ability to set a custom HTTPClient for a request.
func NewReprovisionInstallStackParamsWithHTTPClient(client *http.Client) *ReprovisionInstallStackParams {
	return &ReprovisionInstallStackParams{
		HTTPClient: client,
	}
}

/*
ReprovisionInstallStackParams contains all the parameters to send to the API endpoint

	for the reprovision install stack operation.

	Typically these are written to a http.Request.
*/
type ReprovisionInstallStackParams struct {

	/* InstallID.

	   install ID
	*/
	InstallID string

	/* Req.

	   Input
	*/
	Req *models.ServiceReprovisionInstallStackRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the reprovision install stack params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReprovisionInstallStackParams) WithDefaults() *ReprovisionInstallStackParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the reprovision install stack params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReprovisionInstallStackParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the reprovision install stack params
func (o *ReprovisionInstallStackParams) WithTimeout(timeout time.Duration) *ReprovisionInstallStackParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the reprovision install stack params
func (o *ReprovisionInstallStackParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the reprovision install stack params
func (o *ReprovisionInstallStackParams) WithContext(ctx context.Context) *ReprovisionInstallStackParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the reprovision install stack params
func (o *ReprovisionInstallStackParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the reprovision install stack params
func (o *ReprovisionInstallStackParams) WithHTTPClient(client *http.Client) *ReprovisionInstallStackParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the reprovision install stack params
func (o *ReprovisionInstallStackParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstallID adds the installID to the reprovision install stack params
func (o *ReprovisionInstallStackParams) WithInstallID(installID string) *ReprovisionInstallStackParams {
	o.SetInstallID(installID)
	return o
}

// SetInstallID adds the installId to the reprovision install stack params
func (o *ReprovisionInstallStackParams) SetInstallID(installID string) {
	o.InstallID = installID
}

// WithReq adds the req to the reprovision install stack params
func (o *ReprovisionInstallStackParams) WithReq(req *models.ServiceReprovisionInstallStackRequest) *ReprovisionInstallStackParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the reprovision install stack params
func (o *ReprovisionInstallStackParams) SetReq(req *models.ServiceReprovisionInstallStackRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *ReprovisionInstallStackParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param install_id
	if err := r.SetPathParam("install_id", o.InstallID); err != nil {
		return err
	}
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
