// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTailInstallRunnerJobLogsParams creates a new TailInstallRunnerJobLogsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTailInstallRunnerJobLogsParams() *TailInstallRunnerJobLogsParams {
	return &TailInstallRunnerJobLogsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTailInstallRunnerJobLogsParamsWithTimeout creates a new TailInstallRunnerJobLogsParams object
// with the ability to set a timeout on a request.
func NewTailInstallRunnerJobLogsParamsWithTimeout(timeout time.Duration) *TailInstallRunnerJobLogsParams {
	return &TailInstallRunnerJobLogsParams{
		timeout: timeout,
	}
}

// NewTailInstallRunnerJobLogsParamsWithContext creates a new TailInstallRunnerJobLogsParams object
// with the ability to set a context for a request.
func NewTailInstallRunnerJobLogsParamsWithContext(ctx context.Context) *TailInstallRunnerJobLogsParams {
	return &TailInstallRunnerJobLogsParams{
		Context: ctx,
	}
}

// NewTailInstallRunnerJobLogsParamsWithHTTPClient creates a new TailInstallRunnerJobLogsParams object
// with the ability to set a custom HTTPClient for a request.
func NewTailInstallRunnerJobLogsParamsWithHTTPClient(client *http.Client) *TailInstallRunnerJobLogsParams {
	return &TailInstallRunnerJobLogsParams{
		HTTPClient: client,
	}
}

/*
TailInstallRunnerJobLogsParams contains all the parameters to send to the API endpoint

	for the tail install runner job logs operation.

	Typically these are written to a http.Request.
*/
type TailInstallRunnerJobLogsParams struct {

	/* InstallID.

	   install ID
	*/
	InstallID string

	/* RunnerJobID.

	   runner job ID
	*/
	RunnerJobID string

	/* Since.

	   composite cursor in the form `<unix_nano>:<id>`; empty starts from the oldest row
	*/
	Since *string

	/* Wait.

	   max wait for new rows (Go duration, capped server-side at 30s)
	*/
	Wait *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the tail install runner job logs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TailInstallRunnerJobLogsParams) WithDefaults() *TailInstallRunnerJobLogsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the tail install runner job logs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TailInstallRunnerJobLogsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the tail install runner job logs params
func (o *TailInstallRunnerJobLogsParams) WithTimeout(timeout time.Duration) *TailInstallRunnerJobLogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tail install runner job logs params
func (o *TailInstallRunnerJobLogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tail install runner job logs params
func (o *TailInstallRunnerJobLogsParams) WithContext(ctx context.Context) *TailInstallRunnerJobLogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tail install runner job logs params
func (o *TailInstallRunnerJobLogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tail install runner job logs params
func (o *TailInstallRunnerJobLogsParams) WithHTTPClient(client *http.Client) *TailInstallRunnerJobLogsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tail install runner job logs params
func (o *TailInstallRunnerJobLogsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstallID adds the installID to the tail install runner job logs params
func (o *TailInstallRunnerJobLogsParams) WithInstallID(installID string) *TailInstallRunnerJobLogsParams {
	o.SetInstallID(installID)
	return o
}

// SetInstallID adds the installId to the tail install runner job logs params
func (o *TailInstallRunnerJobLogsParams) SetInstallID(installID string) {
	o.InstallID = installID
}

// WithRunnerJobID adds the runnerJobID to the tail install runner job logs params
func (o *TailInstallRunnerJobLogsParams) WithRunnerJobID(runnerJobID string) *TailInstallRunnerJobLogsParams {
	o.SetRunnerJobID(runnerJobID)
	return o
}

// SetRunnerJobID adds the runnerJobId to the tail install runner job logs params
func (o *TailInstallRunnerJobLogsParams) SetRunnerJobID(runnerJobID string) {
	o.RunnerJobID = runnerJobID
}

// WithSince adds the since to the tail install runner job logs params
func (o *TailInstallRunnerJobLogsParams) WithSince(since *string) *TailInstallRunnerJobLogsParams {
	o.SetSince(since)
	return o
}

// SetSince adds the since to the tail install runner job logs params
func (o *TailInstallRunnerJobLogsParams) SetSince(since *string) {
	o.Since = since
}

// WithWait adds the wait to the tail install runner job logs params
func (o *TailInstallRunnerJobLogsParams) WithWait(wait *string) *TailInstallRunnerJobLogsParams {
	o.SetWait(wait)
	return o
}

// SetWait adds the wait to the tail install runner job logs params
func (o *TailInstallRunnerJobLogsParams) SetWait(wait *string) {
	o.Wait = wait
}

// WriteToRequest writes these params to a swagger request
func (o *TailInstallRunnerJobLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param install_id
	if err := r.SetPathParam("install_id", o.InstallID); err != nil {
		return err
	}

	// path param runner_job_id
	if err := r.SetPathParam("runner_job_id", o.RunnerJobID); err != nil {
		return err
	}

	if o.Since != nil {

		// query param since
		var qrSince string

		if o.Since != nil {
			qrSince = *o.Since
		}
		qSince := qrSince
		if qSince != "" {

			if err := r.SetQueryParam("since", qSince); err != nil {
				return err
			}
		}
	}

	if o.Wait != nil {

		// query param wait
		var qrWait string

		if o.Wait != nil {
			qrWait = *o.Wait
		}
		qWait := qrWait
		if qWait != "" {

			if err := r.SetQueryParam("wait", qWait); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
