// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// UntaintRunnerReader is a Reader for the UntaintRunner structure.
type UntaintRunnerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UntaintRunnerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewUntaintRunnerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewUntaintRunnerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUntaintRunnerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/runners/{runner_id}/untaint] UntaintRunner", response, response.Code())
	}
}

// NewUntaintRunnerOK creates a UntaintRunnerOK with default headers values
func NewUntaintRunnerOK() *UntaintRunnerOK {
	return &UntaintRunnerOK{}
}

/*
UntaintRunnerOK describes a response with status code 200, with default header values.

OK
*/
type UntaintRunnerOK struct {
	Payload *models.AppRunner
}

// IsSuccess returns true when this untaint runner o k response has a 2xx status code
func (o *UntaintRunnerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this untaint runner o k response has a 3xx status code
func (o *UntaintRunnerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this untaint runner o k response has a 4xx status code
func (o *UntaintRunnerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this untaint runner o k response has a 5xx status code
func (o *UntaintRunnerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this untaint runner o k response a status code equal to that given
func (o *UntaintRunnerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the untaint runner o k response
func (o *UntaintRunnerOK) Code() int {
	return 200
}

func (o *UntaintRunnerOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runners/{runner_id}/untaint][%d] untaintRunnerOK %s", 200, payload)
}

func (o *UntaintRunnerOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runners/{runner_id}/untaint][%d] untaintRunnerOK %s", 200, payload)
}

func (o *UntaintRunnerOK) GetPayload() *models.AppRunner {
	return o.Payload
}

func (o *UntaintRunnerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppRunner)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUntaintRunnerNotFound creates a UntaintRunnerNotFound with default headers values
func NewUntaintRunnerNotFound() *UntaintRunnerNotFound {
	return &UntaintRunnerNotFound{}
}

/*
UntaintRunnerNotFound describes a response with status code 404, with default header values.

Not Found
*/
type UntaintRunnerNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this untaint runner not found response has a 2xx status code
func (o *UntaintRunnerNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this untaint runner not found response has a 3xx status code
func (o *UntaintRunnerNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this untaint runner not found response has a 4xx status code
func (o *UntaintRunnerNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this untaint runner not found response has a 5xx status code
func (o *UntaintRunnerNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this untaint runner not found response a status code equal to that given
func (o *UntaintRunnerNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the untaint runner not found response
func (o *UntaintRunnerNotFound) Code() int {
	return 404
}

func (o *UntaintRunnerNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runners/{runner_id}/untaint][%d] untaintRunnerNotFound %s", 404, payload)
}

func (o *UntaintRunnerNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runners/{runner_id}/untaint][%d] untaintRunnerNotFound %s", 404, payload)
}

func (o *UntaintRunnerNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *UntaintRunnerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUntaintRunnerInternalServerError creates a UntaintRunnerInternalServerError with default headers values
func NewUntaintRunnerInternalServerError() *UntaintRunnerInternalServerError {
	return &UntaintRunnerInternalServerError{}
}

/*
UntaintRunnerInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type UntaintRunnerInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this untaint runner internal server error response has a 2xx status code
func (o *UntaintRunnerInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this untaint runner internal server error response has a 3xx status code
func (o *UntaintRunnerInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this untaint runner internal server error response has a 4xx status code
func (o *UntaintRunnerInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this untaint runner internal server error response has a 5xx status code
func (o *UntaintRunnerInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this untaint runner internal server error response a status code equal to that given
func (o *UntaintRunnerInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the untaint runner internal server error response
func (o *UntaintRunnerInternalServerError) Code() int {
	return 500
}

func (o *UntaintRunnerInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runners/{runner_id}/untaint][%d] untaintRunnerInternalServerError %s", 500, payload)
}

func (o *UntaintRunnerInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runners/{runner_id}/untaint][%d] untaintRunnerInternalServerError %s", 500, payload)
}

func (o *UntaintRunnerInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *UntaintRunnerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
