// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// UpdateOIDCTrustPolicyReader is a Reader for the UpdateOIDCTrustPolicy structure.
type UpdateOIDCTrustPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateOIDCTrustPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateOIDCTrustPolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateOIDCTrustPolicyBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateOIDCTrustPolicyForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateOIDCTrustPolicyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PATCH /v1/oidc/trust-policies/{policy_id}] UpdateOIDCTrustPolicy", response, response.Code())
	}
}

// NewUpdateOIDCTrustPolicyOK creates a UpdateOIDCTrustPolicyOK with default headers values
func NewUpdateOIDCTrustPolicyOK() *UpdateOIDCTrustPolicyOK {
	return &UpdateOIDCTrustPolicyOK{}
}

/*
UpdateOIDCTrustPolicyOK describes a response with status code 200, with default header values.

OK
*/
type UpdateOIDCTrustPolicyOK struct {
	Payload *models.AppOIDCTrustPolicy
}

// IsSuccess returns true when this update o Id c trust policy o k response has a 2xx status code
func (o *UpdateOIDCTrustPolicyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update o Id c trust policy o k response has a 3xx status code
func (o *UpdateOIDCTrustPolicyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update o Id c trust policy o k response has a 4xx status code
func (o *UpdateOIDCTrustPolicyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update o Id c trust policy o k response has a 5xx status code
func (o *UpdateOIDCTrustPolicyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update o Id c trust policy o k response a status code equal to that given
func (o *UpdateOIDCTrustPolicyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update o Id c trust policy o k response
func (o *UpdateOIDCTrustPolicyOK) Code() int {
	return 200
}

func (o *UpdateOIDCTrustPolicyOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/oidc/trust-policies/{policy_id}][%d] updateOIdCTrustPolicyOK %s", 200, payload)
}

func (o *UpdateOIDCTrustPolicyOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/oidc/trust-policies/{policy_id}][%d] updateOIdCTrustPolicyOK %s", 200, payload)
}

func (o *UpdateOIDCTrustPolicyOK) GetPayload() *models.AppOIDCTrustPolicy {
	return o.Payload
}

func (o *UpdateOIDCTrustPolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppOIDCTrustPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateOIDCTrustPolicyBadRequest creates a UpdateOIDCTrustPolicyBadRequest with default headers values
func NewUpdateOIDCTrustPolicyBadRequest() *UpdateOIDCTrustPolicyBadRequest {
	return &UpdateOIDCTrustPolicyBadRequest{}
}

/*
UpdateOIDCTrustPolicyBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UpdateOIDCTrustPolicyBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this update o Id c trust policy bad request response has a 2xx status code
func (o *UpdateOIDCTrustPolicyBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update o Id c trust policy bad request response has a 3xx status code
func (o *UpdateOIDCTrustPolicyBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update o Id c trust policy bad request response has a 4xx status code
func (o *UpdateOIDCTrustPolicyBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update o Id c trust policy bad request response has a 5xx status code
func (o *UpdateOIDCTrustPolicyBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update o Id c trust policy bad request response a status code equal to that given
func (o *UpdateOIDCTrustPolicyBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update o Id c trust policy bad request response
func (o *UpdateOIDCTrustPolicyBadRequest) Code() int {
	return 400
}

func (o *UpdateOIDCTrustPolicyBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/oidc/trust-policies/{policy_id}][%d] updateOIdCTrustPolicyBadRequest %s", 400, payload)
}

func (o *UpdateOIDCTrustPolicyBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/oidc/trust-policies/{policy_id}][%d] updateOIdCTrustPolicyBadRequest %s", 400, payload)
}

func (o *UpdateOIDCTrustPolicyBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *UpdateOIDCTrustPolicyBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateOIDCTrustPolicyForbidden creates a UpdateOIDCTrustPolicyForbidden with default headers values
func NewUpdateOIDCTrustPolicyForbidden() *UpdateOIDCTrustPolicyForbidden {
	return &UpdateOIDCTrustPolicyForbidden{}
}

/*
UpdateOIDCTrustPolicyForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type UpdateOIDCTrustPolicyForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this update o Id c trust policy forbidden response has a 2xx status code
func (o *UpdateOIDCTrustPolicyForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update o Id c trust policy forbidden response has a 3xx status code
func (o *UpdateOIDCTrustPolicyForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update o Id c trust policy forbidden response has a 4xx status code
func (o *UpdateOIDCTrustPolicyForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this update o Id c trust policy forbidden response has a 5xx status code
func (o *UpdateOIDCTrustPolicyForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this update o Id c trust policy forbidden response a status code equal to that given
func (o *UpdateOIDCTrustPolicyForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the update o Id c trust policy forbidden response
func (o *UpdateOIDCTrustPolicyForbidden) Code() int {
	return 403
}

func (o *UpdateOIDCTrustPolicyForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/oidc/trust-policies/{policy_id}][%d] updateOIdCTrustPolicyForbidden %s", 403, payload)
}

func (o *UpdateOIDCTrustPolicyForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/oidc/trust-policies/{policy_id}][%d] updateOIdCTrustPolicyForbidden %s", 403, payload)
}

func (o *UpdateOIDCTrustPolicyForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *UpdateOIDCTrustPolicyForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateOIDCTrustPolicyNotFound creates a UpdateOIDCTrustPolicyNotFound with default headers values
func NewUpdateOIDCTrustPolicyNotFound() *UpdateOIDCTrustPolicyNotFound {
	return &UpdateOIDCTrustPolicyNotFound{}
}

/*
UpdateOIDCTrustPolicyNotFound describes a response with status code 404, with default header values.

Not Found
*/
type UpdateOIDCTrustPolicyNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this update o Id c trust policy not found response has a 2xx status code
func (o *UpdateOIDCTrustPolicyNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update o Id c trust policy not found response has a 3xx status code
func (o *UpdateOIDCTrustPolicyNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update o Id c trust policy not found response has a 4xx status code
func (o *UpdateOIDCTrustPolicyNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update o Id c trust policy not found response has a 5xx status code
func (o *UpdateOIDCTrustPolicyNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update o Id c trust policy not found response a status code equal to that given
func (o *UpdateOIDCTrustPolicyNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update o Id c trust policy not found response
func (o *UpdateOIDCTrustPolicyNotFound) Code() int {
	return 404
}

func (o *UpdateOIDCTrustPolicyNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/oidc/trust-policies/{policy_id}][%d] updateOIdCTrustPolicyNotFound %s", 404, payload)
}

func (o *UpdateOIDCTrustPolicyNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/oidc/trust-policies/{policy_id}][%d] updateOIdCTrustPolicyNotFound %s", 404, payload)
}

func (o *UpdateOIDCTrustPolicyNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *UpdateOIDCTrustPolicyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
