query GetApps($id: ID!) {
  apps(orgId: $id, options: {}) {
    totalCount

    pageInfo {
      endCursor
      startCursor
    }

    edges {
      cursor
      node {
        id
        name
        slug
     }
    }
  }
}

## variables

id: ${ORG_ID}
