{
  orgs(options: {}) {
    totalCount

    pageInfo {
      endCursor
      startCursor
    }
    edges {
      cursor
      node {
	id
	name
      }
    }
  }
}

## variables

id: ${INSTALLATION_ID}
