---
cluster_version: "1.32"

managed_node_group:
  desired_size: 1
  min_size: 1
  max_size: 1
  instance_types:
    - t3a.medium

tier: stable

karpenter:
  instance_types:
    - t3a.medium


ec2nodeclasses:
 - buildkit


additional_nodepools:
  - name: buildkit
    instance_types:
      - c5a.4xlarge
    limits:
      cpu: 20
      memory: "40Gi"
    expireAfter: "732h"
    disruption:
      consolidationPolicy: "WhenEmptyOrUnderutilized"
      consolidateAfter: "1m"
      # NOTE(fd): perform disruptions during off hours
      # in this case, between 3AM EST/8AM UTC 7AM EST/12PM UTC
      # we start the node=0 budget at 3AM and it lasts for 20 hours
      budgets:
        - nodes: "1" # allow empty nodes to be consolidated
          reasons:
          - "Empty"
          - "Drifted"
        - nodes: "1"
          schedule: "0 8 * * 1,2,3,4,5" # https://crontab.guru/#0_8_*_*_1,2,3,4,5
          duration: "20h"
          reasons:
          - "Underutilized"