---
cluster_version: "1.32"

managed_node_group:
  desired_size: 1
  min_size: 1
  max_size: 1
  instance_types:
    - t3a.medium

tier: stable

karpenter:
  instance_types:
    - t3a.medium


ec2nodeclasses:
 - buildkit
 - self-hosted-runners


additional_nodepools:
  - name: buildkit
    instance_types:
      - c5a.8xlarge
    limits:
      cpu: 32
      memory: "62Gi"
    expireAfter: "Never"
    disruption:
      consolidationPolicy: "WhenEmpty"
      consolidateAfter: "30m"

  - name: self-hosted-runners
    instance_types:
      - c5a.xlarge
    limits:
      cpu: 32
      memory: "62Gi"
    expireAfter: "Never"
    disruption:
      consolidationPolicy: "WhenEmpty"
      consolidateAfter: "30m"
