---
cluster_version: "1.32"

managed_node_group:
  desired_size: 1
  min_size: 1
  max_size: 1
  instance_types:
    - t3a.medium

tier: stable

karpenter:
  instance_types:
    - t3a.medium


ec2nodeclasses:
  - name: buildkit
  - name: self-hosted-runners
    block_devices:
      device_name: "/dev/xvda"
      volume_size: "250Gi"
      volume_type: "gp3"

additional_nodepools:
  - name: buildkit
    instance_types:
      - c5a.8xlarge
    limits:
      cpu: 32
      memory: "62Gi"
    expireAfter: "Never"
    disruption:
      consolidationPolicy: "WhenEmpty"
      consolidateAfter: "30m"

  - name: self-hosted-runners
    instance_types:
      - m6a.16xlarge   # 64 vCPU, 256GB - PRIMARY
      - m6a.24xlarge   # 96 vCPU, 384GB
      - m6i.16xlarge   # Intel alternative
      - m6i.24xlarge   # Intel alternative
    limits:
      cpu: 500
      memory: "2000Gi"
    expireAfter: "Never"
    disruption:
      consolidationPolicy: "WhenEmpty"
      consolidateAfter: "30m"
