---
auth_map_additions:
  - name: eks-workers-executors
    account: prod
    groups:
      - "system:masters"
    trust:
      - "arn:aws:iam::814326426574:role/nuon-internal-support-prod"

managed_node_group:
  min_size: 3
  max_size: 10
  desired_size: 3
  instance_types:
    - t3a.medium

tier: stable

ec2nodeclasses:
 - clickhouse-installation
 - clickhouse-keeper
 - ctl-api-api
 - ctl-api-worker
 - public

additional_nodepools:
  - name: public
    instance_types:
      - t3a.xlarge
    limits:
      cpu: 500
      memory: "1000Gi"
    expireAfter: "732h"
    disruption:
      consolidationPolicy: "WhenEmptyOrUnderutilized"
      consolidateAfter: "1m"
      # NOTE(fd): perform disruptions during off hours
      # in this case, between 3AM EST/8AM UTC 7AM EST/12PM UTC
      # we start the node=0 budget at 3AM and it lasts for 20 hours
      budgets:
        - nodes: "1" # allow empty nodes to be consolidated
          reasons:
          - "Empty"
          - "Drifted"
        - nodes: "1"
          schedule: "0 8 * * 1,2,3,4,5" # https://crontab.guru/#0_8_*_*_1,2,3,4,5
          duration: "20h"
          reasons:
          - "Underutilized"
    taints:
      - key: pool.nuon.co/public
        effect: NoSchedule
