---
auth_map_additions:
  - name: eks-ctl-api
    account: stage
    groups:
      - "system:masters"
    trust:
      - "arn:aws:iam::766121324316:role/nuon-internal-support-stage"
  - name: eks-workers-executors
    account: stage
    groups:
      - "system:masters"
    trust:
      - "arn:aws:iam::766121324316:role/nuon-internal-support-stage"

managed_node_group:
  desired_size: 2
  min_size: 2
  max_size: 5
  instance_types:
    - t3a.medium

tier: beta

karpenter:
  instance_types:
    - t3a.small
    - t3a.medium
