---
tier: beta
auth_map_additions:
  - name: eks-workers-executors
    account: stage
    groups:
      - "system:masters"
    trust:
      - "arn:aws:iam::766121324316:role/nuon-internal-support-stage"

managed_node_group:
  min_size: 2
  max_size: 10
  desired_size: 2
  instance_types:
    - t3a.medium

ec2nodeclasses:
 - clickhouse-installation
 - clickhouse-keeper
 - ctl-api-api
 - ctl-api-worker
 - public
