---
tier: beta
auth_map_additions:
  - name: eks-workers-executors
    account: stage
    groups:
      - "system:masters"
    trust:
      - "arn:aws:iam::766121324316:role/nuon-internal-support-stage"

managed_node_group:
  min_size: 2
  max_size: 10
  desired_size: 2
  instance_types:
    - t3a.medium

ec2nodeclasses:
 - clickhouse-installation
 - clickhouse-keeper
 - ctl-api-api
 - ctl-api-worker
 - public
 - temporal

additional_nodepools:
  - name: public
    instance_types:
      - t3a.xlarge
    limits:
      cpu: 250
      memory: "500Gi"
    expireAfter: "24h"
    disruption:
      consolidationPolicy: "WhenEmptyOrUnderutilized"
      consolidateAfter: "1m"
      # NOTE(fd): perform disruptions during off hours
      # in this case, between 3AM EST/8AM UTC 7AM EST/12PM UTC
      # we start the node=0 budget at 3AM and it lasts for 20 hours
      budgets:
        - nodes: "1" # allow empty nodes to be consolidated
          reasons:
          - "Empty"
          - "Drifted"
        - nodes: "1"
          schedule: "0 8 * * 1,2,3,4,5" # https://crontab.guru/#0_8_*_*_1,2,3,4,5
          duration: "20h"
          reasons:
          - "Underutilized"
  - name: public-otel
    instance_types:
      - t3a.xlarge
    limits:
      cpu: 50
      memory: "100Gi"
    expireAfter: "24h"
    disruption:
      consolidationPolicy: "WhenEmptyOrUnderutilized"
      consolidateAfter: "1m"
      # NOTE(fd): perform disruptions during off hours
      # in this case, between 3AM EST/8AM UTC 7AM EST/12PM UTC
      # we start the node=0 budget at 3AM and it lasts for 20 hours
      budgets:
        - nodes: "1" # allow empty nodes to be consolidated
          reasons:
          - "Empty"
          - "Drifted"
        - nodes: "1"
          schedule: "0 7 * * 1,2,3,4,5" # https://crontab.guru/#0_8_*_*_1,2,3,4,5
          duration: "20h"
          reasons:
          - "Underutilized"
  - name: temporal
    instance_types:
      - t3a.large
    limits:
      cpu: 50
      memory: "100Gi"
    expireAfter: "2160h"
    disruption:
      consolidationPolicy: "WhenEmptyOrUnderutilized"
      consolidateAfter: "1m"
      # NOTE(fd): perform disruptions during off hours
      # in this case, between 3AM EST/8AM UTC 7AM EST/12PM UTC
      # we start the node=0 budget at 3AM and it lasts for 20 hours
      budgets:
        - nodes: "1"
          schedule: "0 10 * * 1,2,3,4,5" # https://crontab.guru/#0_8_*_*_1,2,3,4,5
          duration: "23h"
          reasons:
          - "Underutilized"
        - nodes: "1" # allow empty nodes to be consolidated
          reasons:
          - "Empty"
          - "Drifted"

karpenter:
  instance_types:
    - t3a.medium
    - t3a.large
