---
public_root_domain: nuon.co
region: us-west-2
pool: nuon
rds:
  engine: postgres
  engine_version: "14.10"
  family: "postgres14"
  parameters:
    - name: max_connections
      value: 300
    - name: idle_in_transaction_session_timeout
      value: 3600000
  major_engine_version: "14"
  instance_class: "db.t4g.small"
  allocated_storage: "20"
  db_name: ctlapi
  port: 5432
  username: nuonadmin
  multi_az: false
  backup_retention_period: 1
  skip_final_snapshot: true
  deletion_protection: true
  storage_encrypted: true
  enabled_cloudwatch_logs_exports:
    - postgresql
    - upgrade
  enable_replica: false
