---
public_root_domain: nuon.co
region: us-west-2
pool: nuon
rds:
  engine: postgres
  engine_version: "14.10"
  family: "postgres14"
  parameters:
    - name: max_connections
      # we limit each api and worker process to 10 connections at a time. This means we have head room to scale this up
      # to 100 instances total, between the two.
      value: 1000
      apply_method: pending-reboot
      # we require that each connection in our pools send a keepalive every 10 seconds max. If this is not received for
    - name: tcp_keepalives_idle
      value: 10
      # after 3 lost/unacked keepalives, we consider the connection dead from the db side
    - name: tcp_keepalives_count
      value: 3
  major_engine_version: "14"
  instance_class: "db.t4g.small"
  allocated_storage: "20"
  db_name: ctlapi
  port: 5432
  username: nuonadmin
  multi_az: false
  backup_retention_period: 1
  skip_final_snapshot: true
  deletion_protection: true
  storage_encrypted: true
  enabled_cloudwatch_logs_exports:
    - postgresql
    - upgrade
  enable_replica: false
