---
targetSystem: "linux"
datadog:
  site: us5.datadoghq.com

  # TODO(jm): exclude other namespaces once we have logs running to save costs
  #containerExclude: kube_namespace:logging kube_namespace:monitoring
  logs:
    enabled: true
    containerCollectAll: true
    #containerCollectUsingFiles: true
  apm:
    portEnabled: true
    socketPath: /var/run/datadog/apm.socket
    hostSocketPath: /var/run/datadog/
  processAgent:
    enabled: true
    processCollection: false
  systemProbe:
    enableTCPQueueLength: false
    enableOOMKill: true
    collectDNSStats: false
  dogstatsd:
    useHostPort: true
    port: 8125
  prometheusScrape:
    enabled: true
    serviceEndpoints: true
agents:
  tolerations:
    # this toleration affects nodes limited to a specific deployment
    # e.g. ctl-api-api and runner node groups
    - effect: NoSchedule
      key: CriticalAddonsOnly
      value: "true"
    - key: "karpenter.sh/controller"
      effect: NoSchedule
      value: "true"
    - key: "deployment"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "installation"
      operator: "Equal"
      value: "clickhouse-installation"
      effect: "NoSchedule"
    - key: "pool.nuon.co/public"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "pool.nuon.co"
      operator: "Exists"
      effect: "NoSchedule"
