---
targetSystem: "linux"
datadog:
  site: us5.datadoghq.com

  # TODO(jm): exclude other namespaces once we have logs running to save costs
  #containerExclude: kube_namespace:logging kube_namespace:monitoring
  logs:
    enabled: true
    containerCollectAll: true
    #containerCollectUsingFiles: true
  apm:
    portEnabled: true
    socketPath: /var/run/datadog/apm.socket
    hostSocketPath: /var/run/datadog/
  processAgent:
    enabled: true
    processCollection: false
  systemProbe:
    enableTCPQueueLength: false
    enableOOMKill: true
    collectDNSStats: false
  dogstatsd:
    useHostPort: true
    port: 8125
  # TODO(fd): we need a solution to manage these tolerations for runners
  tolerations:
    - key: "deployment"
      operator: "Equal"
      value: ctl-api-api
      effect: "NoSchedule"
    - key: "installation"
      operator: "Equal"
      value: "clickhouse-installation"
      effect: "NoSchedule"
