VERSION --use-cache-command 0.6

FROM ../../images/go-base+build-base

WORKDIR /src

ARG BIN=waypoint-plugin-exp
ARG GOCACHE=/go-cache
ARG GOMODCACHE=/go-mod-cache
CACHE $GOCACHE
CACHE $GOMODCACHE

code:
    FROM ../../.+deps
    COPY ../../pkg+code/pkg pkg
    COPY --dir . ./bins/$BIN
    WORKDIR bins/$BIN
    RUN go generate ./...

lint:
    FROM +code

test:
    FROM +code
    RUN go test ./...

artifacts:
    FROM +code
    RUN mkdir -p out && \
      go build -o ./out/$BIN .

    SAVE ARTIFACT out AS LOCAL ./out

oci-artifacts:
    FROM ../../images/go-base+alpine-base

    COPY +artifacts/out/$BIN /bin/$BIN

    ARG repo=
    ARG image_tag=
    SAVE IMAGE --push $repo:$image_tag
