// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: installs/v1/runner/v1/eks_cluster.proto

package runnerv1

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EKSClusterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" faker:"len=20"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty" faker:"len=20"`
	CaData        string                 `protobuf:"bytes,3,opt,name=ca_data,json=caData,proto3" json:"ca_data,omitempty" faker:"len=20"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EKSClusterInfo) Reset() {
	*x = EKSClusterInfo{}
	mi := &file_installs_v1_runner_v1_eks_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EKSClusterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EKSClusterInfo) ProtoMessage() {}

func (x *EKSClusterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_installs_v1_runner_v1_eks_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EKSClusterInfo.ProtoReflect.Descriptor instead.
func (*EKSClusterInfo) Descriptor() ([]byte, []int) {
	return file_installs_v1_runner_v1_eks_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *EKSClusterInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EKSClusterInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *EKSClusterInfo) GetCaData() string {
	if x != nil {
		return x.CaData
	}
	return ""
}

var File_installs_v1_runner_v1_eks_cluster_proto protoreflect.FileDescriptor

const file_installs_v1_runner_v1_eks_cluster_proto_rawDesc = "" +
	"\n" +
	"'installs/v1/runner/v1/eks_cluster.proto\x12\x15installs.v1.runner.v1\x1a\x13tagger/tagger.proto\"\x94\x01\n" +
	"\x0eEKSClusterInfo\x12#\n" +
	"\x02id\x18\x01 \x01(\tB\x13\x9a\x84\x9e\x03\x0efaker:\"len=20\"R\x02id\x12/\n" +
	"\bendpoint\x18\x02 \x01(\tB\x13\x9a\x84\x9e\x03\x0efaker:\"len=20\"R\bendpoint\x12,\n" +
	"\aca_data\x18\x03 \x01(\tB\x13\x9a\x84\x9e\x03\x0efaker:\"len=20\"R\x06caDataB\xf5\x01\n" +
	"\x19com.installs.v1.runner.v1B\x0fEksClusterProtoP\x01ZPgithub.com/powertoolsdev/mono/pkg/types/workflows/installs/v1/runner/v1;runnerv1\xa2\x02\x03IVR\xaa\x02\x15Installs.V1.Runner.V1\xca\x02\x15Installs\\V1\\Runner\\V1\xe2\x02!Installs\\V1\\Runner\\V1\\GPBMetadata\xea\x02\x18Installs::V1::Runner::V1b\x06proto3"

var (
	file_installs_v1_runner_v1_eks_cluster_proto_rawDescOnce sync.Once
	file_installs_v1_runner_v1_eks_cluster_proto_rawDescData []byte
)

func file_installs_v1_runner_v1_eks_cluster_proto_rawDescGZIP() []byte {
	file_installs_v1_runner_v1_eks_cluster_proto_rawDescOnce.Do(func() {
		file_installs_v1_runner_v1_eks_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_installs_v1_runner_v1_eks_cluster_proto_rawDesc), len(file_installs_v1_runner_v1_eks_cluster_proto_rawDesc)))
	})
	return file_installs_v1_runner_v1_eks_cluster_proto_rawDescData
}

var file_installs_v1_runner_v1_eks_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_installs_v1_runner_v1_eks_cluster_proto_goTypes = []any{
	(*EKSClusterInfo)(nil), // 0: installs.v1.runner.v1.EKSClusterInfo
}
var file_installs_v1_runner_v1_eks_cluster_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_installs_v1_runner_v1_eks_cluster_proto_init() }
func file_installs_v1_runner_v1_eks_cluster_proto_init() {
	if File_installs_v1_runner_v1_eks_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_installs_v1_runner_v1_eks_cluster_proto_rawDesc), len(file_installs_v1_runner_v1_eks_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_installs_v1_runner_v1_eks_cluster_proto_goTypes,
		DependencyIndexes: file_installs_v1_runner_v1_eks_cluster_proto_depIdxs,
		MessageInfos:      file_installs_v1_runner_v1_eks_cluster_proto_msgTypes,
	}.Build()
	File_installs_v1_runner_v1_eks_cluster_proto = out.File
	file_installs_v1_runner_v1_eks_cluster_proto_goTypes = nil
	file_installs_v1_runner_v1_eks_cluster_proto_depIdxs = nil
}
