VERSION --use-cache-command 0.6

FROM ../images/go-base+build-base

WORKDIR /src

# code should be used to consume pkg as code. It exports the fully generated pkg
code:
    COPY --dir . ./charts
    SAVE ARTIFACT charts
