// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AirgapFinding airgap finding
//
// swagger:model airgap.Finding
type AirgapFinding struct {

	// code
	Code string `json:"code,omitempty"`

	// member
	Member string `json:"member,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this airgap finding
func (m *AirgapFinding) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this airgap finding based on context it is used
func (m *AirgapFinding) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AirgapFinding) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AirgapFinding) UnmarshalBinary(b []byte) error {
	var res AirgapFinding
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
