// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppAppConfigIntermediate app app config intermediate
//
// swagger:model app.AppConfigIntermediate
type AppAppConfigIntermediate struct {

	// app branch id
	AppBranchID string `json:"app_branch_id,omitempty"`

	// app id
	AppID string `json:"app_id,omitempty"`

	// checksum
	Checksum string `json:"checksum,omitempty"`

	// cli version
	CliVersion string `json:"cli_version,omitempty"`

	// config
	Config *ConfigAppConfig `json:"config,omitempty"`

	// config id
	ConfigID string `json:"config_id,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// created by id
	CreatedByID string `json:"created_by_id,omitempty"`

	// resources
	Resources []*AppAppConfigResource `json:"resources"`

	// size
	Size int64 `json:"size,omitempty"`

	// status
	Status AppAppConfigStatus `json:"status,omitempty"`

	// status v2
	StatusV2 *AppCompositeStatus `json:"status_v2,omitempty"`

	// vcs connection commit
	VcsConnectionCommit *AppVCSConnectionCommit `json:"vcs_connection_commit,omitempty"`

	// version
	Version int64 `json:"version,omitempty"`
}

// Validate validates this app app config intermediate
func (m *AppAppConfigIntermediate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResources(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatusV2(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVcsConnectionCommit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppAppConfigIntermediate) validateConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.Config) { // not required
		return nil
	}

	if m.Config != nil {
		if err := m.Config.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("config")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("config")
			}

			return err
		}
	}

	return nil
}

func (m *AppAppConfigIntermediate) validateResources(formats strfmt.Registry) error {
	if swag.IsZero(m.Resources) { // not required
		return nil
	}

	for i := 0; i < len(m.Resources); i++ {
		if swag.IsZero(m.Resources[i]) { // not required
			continue
		}

		if m.Resources[i] != nil {
			if err := m.Resources[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("resources" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("resources" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *AppAppConfigIntermediate) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if err := m.Status.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("status")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("status")
		}

		return err
	}

	return nil
}

func (m *AppAppConfigIntermediate) validateStatusV2(formats strfmt.Registry) error {
	if swag.IsZero(m.StatusV2) { // not required
		return nil
	}

	if m.StatusV2 != nil {
		if err := m.StatusV2.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("status_v2")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("status_v2")
			}

			return err
		}
	}

	return nil
}

func (m *AppAppConfigIntermediate) validateVcsConnectionCommit(formats strfmt.Registry) error {
	if swag.IsZero(m.VcsConnectionCommit) { // not required
		return nil
	}

	if m.VcsConnectionCommit != nil {
		if err := m.VcsConnectionCommit.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("vcs_connection_commit")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("vcs_connection_commit")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this app app config intermediate based on the context it is used
func (m *AppAppConfigIntermediate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateResources(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStatusV2(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVcsConnectionCommit(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppAppConfigIntermediate) contextValidateConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.Config != nil {

		if swag.IsZero(m.Config) { // not required
			return nil
		}

		if err := m.Config.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("config")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("config")
			}

			return err
		}
	}

	return nil
}

func (m *AppAppConfigIntermediate) contextValidateResources(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Resources); i++ {

		if m.Resources[i] != nil {

			if swag.IsZero(m.Resources[i]) { // not required
				return nil
			}

			if err := m.Resources[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("resources" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("resources" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *AppAppConfigIntermediate) contextValidateStatus(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if err := m.Status.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("status")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("status")
		}

		return err
	}

	return nil
}

func (m *AppAppConfigIntermediate) contextValidateStatusV2(ctx context.Context, formats strfmt.Registry) error {

	if m.StatusV2 != nil {

		if swag.IsZero(m.StatusV2) { // not required
			return nil
		}

		if err := m.StatusV2.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("status_v2")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("status_v2")
			}

			return err
		}
	}

	return nil
}

func (m *AppAppConfigIntermediate) contextValidateVcsConnectionCommit(ctx context.Context, formats strfmt.Registry) error {

	if m.VcsConnectionCommit != nil {

		if swag.IsZero(m.VcsConnectionCommit) { // not required
			return nil
		}

		if err := m.VcsConnectionCommit.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("vcs_connection_commit")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("vcs_connection_commit")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppAppConfigIntermediate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppAppConfigIntermediate) UnmarshalBinary(b []byte) error {
	var res AppAppConfigIntermediate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
