// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AppAppBundleRuntime app app bundle runtime
//
// swagger:model app.AppBundleRuntime
type AppAppBundleRuntime struct {

	// platforms
	Platforms map[string]AppAppBundlePlatformRuntime `json:"platforms,omitempty"`

	// runner image tag
	RunnerImageTag string `json:"runner_image_tag,omitempty"`

	// runner image url
	RunnerImageURL string `json:"runner_image_url,omitempty"`
}

// Validate validates this app app bundle runtime
func (m *AppAppBundleRuntime) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlatforms(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppAppBundleRuntime) validatePlatforms(formats strfmt.Registry) error {
	if swag.IsZero(m.Platforms) { // not required
		return nil
	}

	for k := range m.Platforms {

		if err := validate.Required("platforms"+"."+k, "body", m.Platforms[k]); err != nil {
			return err
		}
		if val, ok := m.Platforms[k]; ok {
			if err := val.Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("platforms" + "." + k)
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("platforms" + "." + k)
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this app app bundle runtime based on the context it is used
func (m *AppAppBundleRuntime) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePlatforms(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppAppBundleRuntime) contextValidatePlatforms(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Platforms {

		if val, ok := m.Platforms[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppAppBundleRuntime) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppAppBundleRuntime) UnmarshalBinary(b []byte) error {
	var res AppAppBundleRuntime
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
