// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// AppOrgMemberStatus app org member status
//
// swagger:model app.OrgMemberStatus
type AppOrgMemberStatus string

func NewAppOrgMemberStatus(value AppOrgMemberStatus) *AppOrgMemberStatus {
	return &value
}

// Pointer returns a pointer to a freshly-allocated AppOrgMemberStatus.
func (m AppOrgMemberStatus) Pointer() *AppOrgMemberStatus {
	return &m
}

const (

	// AppOrgMemberStatusActive captures enum value "active"
	AppOrgMemberStatusActive AppOrgMemberStatus = "active"

	// AppOrgMemberStatusInvited captures enum value "invited"
	AppOrgMemberStatusInvited AppOrgMemberStatus = "invited"
)

// for schema
var appOrgMemberStatusEnum []any

func init() {
	var res []AppOrgMemberStatus
	if err := json.Unmarshal([]byte(`["active","invited"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		appOrgMemberStatusEnum = append(appOrgMemberStatusEnum, v)
	}
}

func (m AppOrgMemberStatus) validateAppOrgMemberStatusEnum(path, location string, value AppOrgMemberStatus) error {
	if err := validate.EnumCase(path, location, value, appOrgMemberStatusEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this app org member status
func (m AppOrgMemberStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAppOrgMemberStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this app org member status based on context it is used
func (m AppOrgMemberStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
