// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppInstallRegistration app install registration
//
// swagger:model app.InstallRegistration
type AppInstallRegistration struct {

	// association status
	AssociationStatus string `json:"association_status,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// created by id
	CreatedByID string `json:"created_by_id,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// imported at
	ImportedAt string `json:"imported_at,omitempty"`

	// install id
	InstallID string `json:"install_id,omitempty"`

	// integrity status
	IntegrityStatus string `json:"integrity_status,omitempty"`

	// package id
	PackageID string `json:"package_id,omitempty"`

	// registration
	Registration *CustomermanagedInstallationRegistration `json:"registration,omitempty"`

	// release id
	ReleaseID string `json:"release_id,omitempty"`

	// source
	Source string `json:"source,omitempty"`
}

// Validate validates this app install registration
func (m *AppInstallRegistration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRegistration(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppInstallRegistration) validateRegistration(formats strfmt.Registry) error {
	if swag.IsZero(m.Registration) { // not required
		return nil
	}

	if m.Registration != nil {
		if err := m.Registration.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("registration")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("registration")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this app install registration based on the context it is used
func (m *AppInstallRegistration) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRegistration(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppInstallRegistration) contextValidateRegistration(ctx context.Context, formats strfmt.Registry) error {

	if m.Registration != nil {

		if swag.IsZero(m.Registration) { // not required
			return nil
		}

		if err := m.Registration.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("registration")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("registration")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppInstallRegistration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppInstallRegistration) UnmarshalBinary(b []byte) error {
	var res AppInstallRegistration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
