// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppAWSECRImageConfig app a w s e c r image config
//
// swagger:model app.AWSECRImageConfig
type AppAWSECRImageConfig struct {

	// aws region
	AwsRegion string `json:"aws_region,omitempty"`

	// cloud connection
	CloudConnection *AppCloudConnection `json:"cloud_connection,omitempty"`

	// cloud connection id
	CloudConnectionID string `json:"cloud_connection_id,omitempty"`

	// connection to parent model
	ComponentConfigID string `json:"component_config_id,omitempty"`

	// component config type
	ComponentConfigType string `json:"component_config_type,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// created by id
	CreatedByID string `json:"created_by_id,omitempty"`

	// actual configuration
	IamRoleArn string `json:"iam_role_arn,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this app a w s e c r image config
func (m *AppAWSECRImageConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCloudConnection(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppAWSECRImageConfig) validateCloudConnection(formats strfmt.Registry) error {
	if swag.IsZero(m.CloudConnection) { // not required
		return nil
	}

	if m.CloudConnection != nil {
		if err := m.CloudConnection.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cloud_connection")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cloud_connection")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this app a w s e c r image config based on the context it is used
func (m *AppAWSECRImageConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCloudConnection(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppAWSECRImageConfig) contextValidateCloudConnection(ctx context.Context, formats strfmt.Registry) error {

	if m.CloudConnection != nil {

		if swag.IsZero(m.CloudConnection) { // not required
			return nil
		}

		if err := m.CloudConnection.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cloud_connection")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cloud_connection")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppAWSECRImageConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppAWSECRImageConfig) UnmarshalBinary(b []byte) error {
	var res AppAWSECRImageConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
