// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigOperationRolesConfig config operation roles config
//
// swagger:model config.OperationRolesConfig
type ConfigOperationRolesConfig struct {

	// rule matrix
	RuleMatrix []*ConfigOperationRoleRule `json:"RuleMatrix"`

	// Should be "matrix"
	Type struct {
		ConfigOperationRuleConfigType
	} `json:"Type,omitempty"`
}

// Validate validates this config operation roles config
func (m *ConfigOperationRolesConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRuleMatrix(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigOperationRolesConfig) validateRuleMatrix(formats strfmt.Registry) error {
	if swag.IsZero(m.RuleMatrix) { // not required
		return nil
	}

	for i := 0; i < len(m.RuleMatrix); i++ {
		if swag.IsZero(m.RuleMatrix[i]) { // not required
			continue
		}

		if m.RuleMatrix[i] != nil {
			if err := m.RuleMatrix[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("RuleMatrix" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("RuleMatrix" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *ConfigOperationRolesConfig) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this config operation roles config based on the context it is used
func (m *ConfigOperationRolesConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRuleMatrix(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigOperationRolesConfig) contextValidateRuleMatrix(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.RuleMatrix); i++ {

		if m.RuleMatrix[i] != nil {

			if swag.IsZero(m.RuleMatrix[i]) { // not required
				return nil
			}

			if err := m.RuleMatrix[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("RuleMatrix" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("RuleMatrix" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *ConfigOperationRolesConfig) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *ConfigOperationRolesConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigOperationRolesConfig) UnmarshalBinary(b []byte) error {
	var res ConfigOperationRolesConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
