// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigTriggerFilterConfig config trigger filter config
//
// swagger:model config.TriggerFilterConfig
type ConfigTriggerFilterConfig struct {

	// from
	From string `json:"From,omitempty"`

	// op
	Op string `json:"Op,omitempty"`

	// path
	Path string `json:"Path,omitempty"`

	// value
	Value any `json:"Value,omitempty"`
}

// Validate validates this config trigger filter config
func (m *ConfigTriggerFilterConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this config trigger filter config based on context it is used
func (m *ConfigTriggerFilterConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConfigTriggerFilterConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigTriggerFilterConfig) UnmarshalBinary(b []byte) error {
	var res ConfigTriggerFilterConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
