// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigActionStepConfig config action step config
//
// swagger:model config.ActionStepConfig
type ConfigActionStepConfig struct {

	// command
	Command string `json:"Command,omitempty"`

	// connected repo
	ConnectedRepo *ConfigConnectedRepoConfig `json:"ConnectedRepo,omitempty"`

	// env var map
	EnvVarMap map[string]string `json:"EnvVarMap,omitempty"`

	// inline contents
	InlineContents string `json:"InlineContents,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// public repo
	PublicRepo *ConfigPublicRepoConfig `json:"PublicRepo,omitempty"`

	// created during parsing
	References []*RefsRef `json:"References"`
}

// Validate validates this config action step config
func (m *ConfigActionStepConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConnectedRepo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicRepo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReferences(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigActionStepConfig) validateConnectedRepo(formats strfmt.Registry) error {
	if swag.IsZero(m.ConnectedRepo) { // not required
		return nil
	}

	if m.ConnectedRepo != nil {
		if err := m.ConnectedRepo.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("ConnectedRepo")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("ConnectedRepo")
			}

			return err
		}
	}

	return nil
}

func (m *ConfigActionStepConfig) validatePublicRepo(formats strfmt.Registry) error {
	if swag.IsZero(m.PublicRepo) { // not required
		return nil
	}

	if m.PublicRepo != nil {
		if err := m.PublicRepo.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("PublicRepo")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("PublicRepo")
			}

			return err
		}
	}

	return nil
}

func (m *ConfigActionStepConfig) validateReferences(formats strfmt.Registry) error {
	if swag.IsZero(m.References) { // not required
		return nil
	}

	for i := 0; i < len(m.References); i++ {
		if swag.IsZero(m.References[i]) { // not required
			continue
		}

		if m.References[i] != nil {
			if err := m.References[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("References" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("References" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this config action step config based on the context it is used
func (m *ConfigActionStepConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConnectedRepo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePublicRepo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateReferences(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigActionStepConfig) contextValidateConnectedRepo(ctx context.Context, formats strfmt.Registry) error {

	if m.ConnectedRepo != nil {

		if swag.IsZero(m.ConnectedRepo) { // not required
			return nil
		}

		if err := m.ConnectedRepo.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("ConnectedRepo")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("ConnectedRepo")
			}

			return err
		}
	}

	return nil
}

func (m *ConfigActionStepConfig) contextValidatePublicRepo(ctx context.Context, formats strfmt.Registry) error {

	if m.PublicRepo != nil {

		if swag.IsZero(m.PublicRepo) { // not required
			return nil
		}

		if err := m.PublicRepo.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("PublicRepo")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("PublicRepo")
			}

			return err
		}
	}

	return nil
}

func (m *ConfigActionStepConfig) contextValidateReferences(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.References); i++ {

		if m.References[i] != nil {

			if swag.IsZero(m.References[i]) { // not required
				return nil
			}

			if err := m.References[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("References" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("References" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConfigActionStepConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigActionStepConfig) UnmarshalBinary(b []byte) error {
	var res ConfigActionStepConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
