// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigExternalImageComponentConfig config external image component config
//
// swagger:model config.ExternalImageComponentConfig
type ConfigExternalImageComponentConfig struct {

	// a w s e c r image config
	AWSECRImageConfig *ConfigAWSECRConfig `json:"AWSECRImageConfig,omitempty"`

	// azure a c r image config
	AzureACRImageConfig *ConfigAzureACRConfig `json:"AzureACRImageConfig,omitempty"`

	// build timeout
	BuildTimeout string `json:"BuildTimeout,omitempty"`

	// deploy timeout
	DeployTimeout string `json:"DeployTimeout,omitempty"`

	// g c p g a r image config
	GCPGARImageConfig *ConfigGCPGARConfig `json:"GCPGARImageConfig,omitempty"`

	// public image config
	PublicImageConfig *ConfigPublicImageConfig `json:"PublicImageConfig,omitempty"`

	// verification
	Verification *SignatureVerification `json:"Verification,omitempty"`
}

// Validate validates this config external image component config
func (m *ConfigExternalImageComponentConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAWSECRImageConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAzureACRImageConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGCPGARImageConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicImageConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVerification(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigExternalImageComponentConfig) validateAWSECRImageConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.AWSECRImageConfig) { // not required
		return nil
	}

	if m.AWSECRImageConfig != nil {
		if err := m.AWSECRImageConfig.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("AWSECRImageConfig")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("AWSECRImageConfig")
			}

			return err
		}
	}

	return nil
}

func (m *ConfigExternalImageComponentConfig) validateAzureACRImageConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.AzureACRImageConfig) { // not required
		return nil
	}

	if m.AzureACRImageConfig != nil {
		if err := m.AzureACRImageConfig.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("AzureACRImageConfig")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("AzureACRImageConfig")
			}

			return err
		}
	}

	return nil
}

func (m *ConfigExternalImageComponentConfig) validateGCPGARImageConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.GCPGARImageConfig) { // not required
		return nil
	}

	if m.GCPGARImageConfig != nil {
		if err := m.GCPGARImageConfig.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("GCPGARImageConfig")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("GCPGARImageConfig")
			}

			return err
		}
	}

	return nil
}

func (m *ConfigExternalImageComponentConfig) validatePublicImageConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.PublicImageConfig) { // not required
		return nil
	}

	if m.PublicImageConfig != nil {
		if err := m.PublicImageConfig.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("PublicImageConfig")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("PublicImageConfig")
			}

			return err
		}
	}

	return nil
}

func (m *ConfigExternalImageComponentConfig) validateVerification(formats strfmt.Registry) error {
	if swag.IsZero(m.Verification) { // not required
		return nil
	}

	if m.Verification != nil {
		if err := m.Verification.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("Verification")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("Verification")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this config external image component config based on the context it is used
func (m *ConfigExternalImageComponentConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAWSECRImageConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAzureACRImageConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateGCPGARImageConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePublicImageConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVerification(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigExternalImageComponentConfig) contextValidateAWSECRImageConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.AWSECRImageConfig != nil {

		if swag.IsZero(m.AWSECRImageConfig) { // not required
			return nil
		}

		if err := m.AWSECRImageConfig.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("AWSECRImageConfig")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("AWSECRImageConfig")
			}

			return err
		}
	}

	return nil
}

func (m *ConfigExternalImageComponentConfig) contextValidateAzureACRImageConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.AzureACRImageConfig != nil {

		if swag.IsZero(m.AzureACRImageConfig) { // not required
			return nil
		}

		if err := m.AzureACRImageConfig.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("AzureACRImageConfig")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("AzureACRImageConfig")
			}

			return err
		}
	}

	return nil
}

func (m *ConfigExternalImageComponentConfig) contextValidateGCPGARImageConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.GCPGARImageConfig != nil {

		if swag.IsZero(m.GCPGARImageConfig) { // not required
			return nil
		}

		if err := m.GCPGARImageConfig.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("GCPGARImageConfig")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("GCPGARImageConfig")
			}

			return err
		}
	}

	return nil
}

func (m *ConfigExternalImageComponentConfig) contextValidatePublicImageConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.PublicImageConfig != nil {

		if swag.IsZero(m.PublicImageConfig) { // not required
			return nil
		}

		if err := m.PublicImageConfig.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("PublicImageConfig")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("PublicImageConfig")
			}

			return err
		}
	}

	return nil
}

func (m *ConfigExternalImageComponentConfig) contextValidateVerification(ctx context.Context, formats strfmt.Registry) error {

	if m.Verification != nil {

		if swag.IsZero(m.Verification) { // not required
			return nil
		}

		if err := m.Verification.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("Verification")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("Verification")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConfigExternalImageComponentConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigExternalImageComponentConfig) UnmarshalBinary(b []byte) error {
	var res ConfigExternalImageComponentConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
