// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigAppInputGroup config app input group
//
// swagger:model config.AppInputGroup
type ConfigAppInputGroup struct {

	// description
	Description string `json:"Description,omitempty"`

	// display name
	DisplayName string `json:"DisplayName,omitempty"`

	// name
	Name string `json:"Name,omitempty"`
}

// Validate validates this config app input group
func (m *ConfigAppInputGroup) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this config app input group based on context it is used
func (m *ConfigAppInputGroup) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConfigAppInputGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigAppInputGroup) UnmarshalBinary(b []byte) error {
	var res ConfigAppInputGroup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
