// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComGoogleGoGithubV50GithubPlan github com google go github v50 github plan
//
// swagger:model github_com_google_go-github_v50_github.Plan
type GithubComGoogleGoGithubV50GithubPlan struct {

	// collaborators
	Collaborators int64 `json:"collaborators,omitempty"`

	// filled seats
	FilledSeats int64 `json:"filled_seats,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// private repos
	PrivateRepos int64 `json:"private_repos,omitempty"`

	// seats
	Seats int64 `json:"seats,omitempty"`

	// space
	Space int64 `json:"space,omitempty"`
}

// Validate validates this github com google go github v50 github plan
func (m *GithubComGoogleGoGithubV50GithubPlan) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com google go github v50 github plan based on context it is used
func (m *GithubComGoogleGoGithubV50GithubPlan) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComGoogleGoGithubV50GithubPlan) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComGoogleGoGithubV50GithubPlan) UnmarshalBinary(b []byte) error {
	var res GithubComGoogleGoGithubV50GithubPlan
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
