// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OperationCatalog operation catalog
//
// swagger:model operation.Catalog
type OperationCatalog struct {

	// bundle digest
	BundleDigest string `json:"bundle_digest,omitempty"`

	// deployment id
	DeploymentID string `json:"deployment_id,omitempty"`

	// generated at
	GeneratedAt string `json:"generated_at,omitempty"`

	// refs
	Refs []*OperationCatalogRef `json:"refs"`

	// schema version
	SchemaVersion int64 `json:"schema_version,omitempty"`
}

// Validate validates this operation catalog
func (m *OperationCatalog) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRefs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OperationCatalog) validateRefs(formats strfmt.Registry) error {
	if swag.IsZero(m.Refs) { // not required
		return nil
	}

	for i := 0; i < len(m.Refs); i++ {
		if swag.IsZero(m.Refs[i]) { // not required
			continue
		}

		if m.Refs[i] != nil {
			if err := m.Refs[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("refs" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("refs" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this operation catalog based on the context it is used
func (m *OperationCatalog) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRefs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OperationCatalog) contextValidateRefs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Refs); i++ {

		if m.Refs[i] != nil {

			if swag.IsZero(m.Refs[i]) { // not required
				return nil
			}

			if err := m.Refs[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("refs" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("refs" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OperationCatalog) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationCatalog) UnmarshalBinary(b []byte) error {
	var res OperationCatalog
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
