// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceHealthTransitionResponse service health transition response
//
// swagger:model service.HealthTransitionResponse
type ServiceHealthTransitionResponse struct {

	// correlated deploy id
	CorrelatedDeployID string `json:"correlated_deploy_id,omitempty"`

	// diagnosis
	Diagnosis string `json:"diagnosis,omitempty"`

	// from health
	FromHealth string `json:"from_health,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// observed at
	ObservedAt string `json:"observed_at,omitempty"`

	// root resource kind
	RootResourceKind string `json:"root_resource_kind,omitempty"`

	// root resource name
	RootResourceName string `json:"root_resource_name,omitempty"`

	// root resource namespace
	RootResourceNamespace string `json:"root_resource_namespace,omitempty"`

	// to health
	ToHealth string `json:"to_health,omitempty"`
}

// Validate validates this service health transition response
func (m *ServiceHealthTransitionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service health transition response based on context it is used
func (m *ServiceHealthTransitionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceHealthTransitionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceHealthTransitionResponse) UnmarshalBinary(b []byte) error {
	var res ServiceHealthTransitionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
