// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceInstallDeploymentAffectedResources service install deployment affected resources
//
// swagger:model service.InstallDeploymentAffectedResources
type ServiceInstallDeploymentAffectedResources struct {

	// components
	Components []string `json:"components"`

	// images
	Images []string `json:"images"`

	// sandbox
	Sandbox bool `json:"sandbox,omitempty"`

	// stack
	Stack bool `json:"stack,omitempty"`
}

// Validate validates this service install deployment affected resources
func (m *ServiceInstallDeploymentAffectedResources) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service install deployment affected resources based on context it is used
func (m *ServiceInstallDeploymentAffectedResources) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceInstallDeploymentAffectedResources) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceInstallDeploymentAffectedResources) UnmarshalBinary(b []byte) error {
	var res ServiceInstallDeploymentAffectedResources
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
