// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServiceMoveInstallToAppBranchRequest service move install to app branch request
//
// swagger:model service.MoveInstallToAppBranchRequest
type ServiceMoveInstallToAppBranchRequest struct {

	// app branch group
	AppBranchGroup string `json:"app_branch_group,omitempty"`

	// AppBranchID is the branch to move the install to. It must belong to the
	// install's app and have an app config to deploy.
	// Required: true
	AppBranchID *string `json:"app_branch_id"`
}

// Validate validates this service move install to app branch request
func (m *ServiceMoveInstallToAppBranchRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAppBranchID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceMoveInstallToAppBranchRequest) validateAppBranchID(formats strfmt.Registry) error {

	if err := validate.Required("app_branch_id", "body", m.AppBranchID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this service move install to app branch request based on context it is used
func (m *ServiceMoveInstallToAppBranchRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceMoveInstallToAppBranchRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceMoveInstallToAppBranchRequest) UnmarshalBinary(b []byte) error {
	var res ServiceMoveInstallToAppBranchRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
