// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServiceCreateRequest service create request
//
// swagger:model service.CreateRequest
type ServiceCreateRequest struct {

	// default region
	DefaultRegion string `json:"default_region,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// platform
	// Enum: ["aws"]
	Platform string `json:"platform,omitempty"`

	// preset
	Preset AppCloudConnectionPreset `json:"preset,omitempty"`

	// principal
	Principal string `json:"principal,omitempty"`

	// target id
	TargetID string `json:"target_id,omitempty"`
}

// Validate validates this service create request
func (m *ServiceCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlatform(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePreset(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var serviceCreateRequestTypePlatformPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["aws"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		serviceCreateRequestTypePlatformPropEnum = append(serviceCreateRequestTypePlatformPropEnum, v)
	}
}

const (

	// ServiceCreateRequestPlatformAws captures enum value "aws"
	ServiceCreateRequestPlatformAws string = "aws"
)

// prop value enum
func (m *ServiceCreateRequest) validatePlatformEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, serviceCreateRequestTypePlatformPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ServiceCreateRequest) validatePlatform(formats strfmt.Registry) error {
	if swag.IsZero(m.Platform) { // not required
		return nil
	}

	// value enum
	if err := m.validatePlatformEnum("platform", "body", m.Platform); err != nil {
		return err
	}

	return nil
}

func (m *ServiceCreateRequest) validatePreset(formats strfmt.Registry) error {
	if swag.IsZero(m.Preset) { // not required
		return nil
	}

	if err := m.Preset.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("preset")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("preset")
		}

		return err
	}

	return nil
}

// ContextValidate validate this service create request based on the context it is used
func (m *ServiceCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePreset(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceCreateRequest) contextValidatePreset(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Preset) { // not required
		return nil
	}

	if err := m.Preset.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("preset")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("preset")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ServiceCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceCreateRequest) UnmarshalBinary(b []byte) error {
	var res ServiceCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
