// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SupportsnapshotManifest supportsnapshot manifest
//
// swagger:model supportsnapshot.Manifest
type SupportsnapshotManifest struct {

	// bundle digest
	BundleDigest string `json:"bundle_digest,omitempty"`

	// captured at
	CapturedAt string `json:"captured_at,omitempty"`

	// entries
	Entries []*SupportsnapshotManifestEntry `json:"entries"`

	// producer
	Producer *SupportsnapshotProducer `json:"producer,omitempty"`

	// registration id
	RegistrationID string `json:"registration_id,omitempty"`

	// schema version
	SchemaVersion int64 `json:"schema_version,omitempty"`
}

// Validate validates this supportsnapshot manifest
func (m *SupportsnapshotManifest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEntries(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProducer(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SupportsnapshotManifest) validateEntries(formats strfmt.Registry) error {
	if swag.IsZero(m.Entries) { // not required
		return nil
	}

	for i := 0; i < len(m.Entries); i++ {
		if swag.IsZero(m.Entries[i]) { // not required
			continue
		}

		if m.Entries[i] != nil {
			if err := m.Entries[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("entries" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("entries" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *SupportsnapshotManifest) validateProducer(formats strfmt.Registry) error {
	if swag.IsZero(m.Producer) { // not required
		return nil
	}

	if m.Producer != nil {
		if err := m.Producer.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("producer")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("producer")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this supportsnapshot manifest based on the context it is used
func (m *SupportsnapshotManifest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEntries(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProducer(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SupportsnapshotManifest) contextValidateEntries(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Entries); i++ {

		if m.Entries[i] != nil {

			if swag.IsZero(m.Entries[i]) { // not required
				return nil
			}

			if err := m.Entries[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("entries" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("entries" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *SupportsnapshotManifest) contextValidateProducer(ctx context.Context, formats strfmt.Registry) error {

	if m.Producer != nil {

		if swag.IsZero(m.Producer) { // not required
			return nil
		}

		if err := m.Producer.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("producer")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("producer")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SupportsnapshotManifest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SupportsnapshotManifest) UnmarshalBinary(b []byte) error {
	var res SupportsnapshotManifest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
