---
name: setup-ci
description: |
  Sets up everything necessary to run earthly for CI
author: "@powertoolsdev/team"
inputs:
  # TODO(jdt): add to earthly and remove from here
  tfcloud_token:
    description: The token used to authenticate to Terraform Cloud
  github_token:
    description: "GITHUB_TOKEN"
    default: "${{ github.token }}"
  aws_role:
    description: |
      (Optional) The AWS role to assume.
      Used for setting up AWS credentials.
    default: ""
  aws_region:
    description: |
      (Optional) The AWS region to use.
      Used for setting up AWS credentials.
    default: "us-west-2"
  ecr_registries:
    description: |
      (Optional) The ECR registries to log into.
    default: ""

runs:
  using: "composite"
  steps:
    - shell: bash
      # run: echo "TRACE=${RUNNER_DEBUG}" >> "$GITHUB_ENV"
      run: echo "TRACE=1" >> "$GITHUB_ENV"

    - name: Setup earthly
      uses: earthly/actions-setup@v1.0.5
      with:
        version: latest
        github-token: ${{ inputs.github_token }}

    # TODO(jdt): add to earthly and remove from here
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ inputs.tfcloud_token }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2.0.0
      if: ${{ inputs.aws_role != '' }}
      with:
        role-to-assume: ${{ inputs.aws_role }}
        aws-region: ${{ inputs.aws_region }}

    - name: Login to Amazon ECR
      if: ${{ inputs.ecr_registries != '' }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registries: ${{ inputs.ecr_registries }}

    - name: get commit short SHA
      shell: bash
      run: echo "GIT_SHORT_SHA=`echo ${GITHUB_SHA::7}`" >> $GITHUB_ENV

    - name: Setup earthly args
      shell: bash
      run: |
        [[ -n "${TRACE:-}" ]] && set -x

        # grab existing build args
        readarray -d ',' -t build_args < <(printf "%s" "$EARTHLY_BUILD_ARGS")
        # append additional args
        build_args+=("GITHUB_ACTIONS=1")
        build_args+=("GIT_SHORT_REF=${{env.GIT_SHORT_SHA}}")
        printf -v build_args "%s," "${build_args[@]}"

        # grab existing earthly args
        readarray -d ' ' -t extra_args < <(printf "%s" "$EARTHLY_EXTRA_ARGS")
        # append additional args
        [[ ${{ github.event_name }} != "pull_request" ]] && extra_args+=(--push)
        extra_args+=("--strict")
        printf -v extra_args "%s " "${extra_args[@]}"

        # grab existing secrets
        readarray -d ',' -t secrets < <(printf "%s" "$EARTHLY_SECRETS")
        # append additional secrets
        secrets+=("github_token=${{ inputs.github_token }}")
        secrets+=("GITHUB_TOKEN=${{ inputs.github_token }}")
        secrets+=("AWS_REGION=${{ env.AWS_REGION}}")
        secrets+=("AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID}}")
        secrets+=("AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY}}")
        secrets+=("AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN}}")
        printf -v secrets "%s," "${secrets[@]}"

        # export to env
        {
          echo "EARTHLY_BUILD_ARGS=${build_args%,}"
          echo "EARTHLY_EXTRA_ARGS=${extra_args% }"
          echo "EARTHLY_SECRETS=${secrets%,}"
        } >> "$GITHUB_ENV"

    - shell: bash
      run: |
        [[ -n "${TRACE:-}" ]] && set -x

        [[ -n "${{ inputs.aws_role }}" ]] \
                                      && [[ -d ./k8s ]] \
                                      && [[ "${{ inputs.setup_helm }}" = 'true' ]] \
                                      && echo "NEEDS_HELM=true" >> "$GITHUB_ENV"
        exit 0

branding:
  icon: "check"
  color: "blue"
