VERSION --shell-out-anywhere 0.6
FROM scratch

lint:
    FROM ghcr.io/powertoolsdev/ci-reviewdog
    ARG GITHUB_ACTIONS
    WORKDIR /work
    COPY . .
    DO github.com/powertoolsdev/shared-configs+LINT --GITHUB_ACTIONS=$GITHUB_ACTIONS
    SAVE IMAGE --push ghcr.io/powertoolsdev/action-setup-ci:lint
