package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode/utf8"
)

type options struct {
	swaggerTypes map[string]bool
}

type violation struct {
	line  int
	text  string
	start int
	end   int
}

type checker func(path string, src []byte, o options) ([]violation, []byte, error)

var skipDirs = []string{
	"node_modules/", "vendor/", "testdata/", "dist/", "__snapshots__/",
	".agents/", ".claude/", ".cursor/", ".github/", "plans/", "docs/", "specs/", "rules/", "rules-test/",
}

var skipFiles = map[string]bool{
	".golangci.yml":   true,
	"pnpm-lock.yaml":  true,
	"ast-grep.yml":    true,
	"sgconfig.yml":    true,
	"ci-triggers.yml": true,
}

var generatedMarker = regexp.MustCompile(`(?i)(code generated .* do not edit|do not edit|do not make direct changes|this file is generated|auto-generated|autogenerated|@generated)`)

func main() {
	fix := flag.Bool("fix", false, "remove disallowed comments in place")
	swaggerSpecs := flag.String("swagger-specs", "", "comma-separated swagger specs; limits type and field docs to their definitions")
	flag.Parse()

	var o options
	if *swaggerSpecs != "" {
		types, err := loadSwaggerTypes(strings.Split(*swaggerSpecs, ","))
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(2)
		}
		o.swaggerTypes = types
	}

	files, err := trackedFiles(flag.Args())
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(2)
	}

	var found, failed int
	for _, path := range files {
		check := checkerFor(path)
		if check == nil || skipped(path) {
			continue
		}
		src, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		if generated(src) {
			continue
		}
		vs, fixed, err := check(path, src, o)
		if err != nil {
			fmt.Fprintf(os.Stderr, "%s: %v\n", path, err)
			failed++
			continue
		}
		found += len(vs)
		if *fix {
			if utf8.Valid(src) && !utf8.Valid(fixed) {
				fmt.Fprintf(os.Stderr, "%s: fix produced invalid UTF-8, left unchanged\n", path)
				failed++
				continue
			}
			if len(vs) > 0 && !bytes.Equal(fixed, src) {
				if err := os.WriteFile(path, fixed, 0o644); err != nil {
					fmt.Fprintf(os.Stderr, "%s: %v\n", path, err)
					failed++
				}
			}
			continue
		}
		for _, v := range vs {
			fmt.Printf("%s:%d: %s\n", path, v.line, truncate(v.text))
		}
	}

	if failed > 0 {
		os.Exit(2)
	}
	if found > 0 && !*fix {
		fmt.Fprintf(os.Stderr, "\n%d disallowed comments. See the Comments section of AGENTS.md.\n", found)
		os.Exit(1)
	}
}

func checkerFor(path string) checker {
	base := filepath.Base(path)
	switch {
	case strings.HasSuffix(path, ".go"):
		return checkGo
	case strings.HasSuffix(path, ".d.ts"):
		return nil
	case strings.HasSuffix(path, ".ts"), strings.HasSuffix(path, ".tsx"), strings.HasSuffix(path, ".js"),
		strings.HasSuffix(path, ".jsx"), strings.HasSuffix(path, ".mjs"), strings.HasSuffix(path, ".cjs"):
		return jsChecker(false)
	case strings.HasSuffix(path, ".css"):
		return jsChecker(true)
	case strings.HasSuffix(path, ".sh"), strings.HasSuffix(path, ".bash"):
		return hashChecker(langShell)
	case strings.HasSuffix(path, ".yml"), strings.HasSuffix(path, ".yaml"):
		return hashChecker(langYAML)
	case strings.HasSuffix(path, ".py"):
		return hashChecker(langPython)
	case strings.HasSuffix(path, ".tf"), strings.HasSuffix(path, ".tfvars"):
		return hashChecker(langHCL)
	case base == "Dockerfile" || strings.HasPrefix(base, "Dockerfile.") || strings.HasSuffix(base, ".Dockerfile"):
		return hashChecker(langDocker)
	}
	return nil
}

func skipped(path string) bool {
	if skipFiles[filepath.Base(path)] {
		return true
	}
	p := "/" + path
	for _, d := range skipDirs {
		if strings.Contains(p, "/"+d) {
			return true
		}
	}
	return strings.HasSuffix(path, "_gen.go") || strings.HasSuffix(path, ".pb.go") ||
		strings.HasPrefix(filepath.Base(path), "mock_")
}

func generated(src []byte) bool {
	head := src
	if len(head) > 2048 {
		head = head[:2048]
	}
	return generatedMarker.Match(head)
}

func trackedFiles(roots []string) ([]string, error) {
	args := append([]string{"ls-files", "-z", "--cached", "--others", "--exclude-standard", "--"}, roots...)
	out, err := exec.Command("git", args...).Output()
	if err != nil {
		return nil, fmt.Errorf("git ls-files: %w", err)
	}
	var files []string
	for _, f := range strings.Split(string(out), "\x00") {
		if f != "" {
			files = append(files, f)
		}
	}
	sort.Strings(files)
	return files, nil
}

func loadSwaggerTypes(paths []string) (map[string]bool, error) {
	types := map[string]bool{}
	for _, p := range paths {
		byts, err := os.ReadFile(p)
		if err != nil {
			return nil, err
		}
		var spec struct {
			Definitions map[string]json.RawMessage `json:"definitions"`
		}
		if err := json.Unmarshal(byts, &spec); err != nil {
			return nil, fmt.Errorf("%s: %w", p, err)
		}
		for name := range spec.Definitions {
			types[name] = true
			pkg, typ, ok := strings.Cut(name, ".")
			if !ok {
				continue
			}
			parts := strings.Split(pkg, "_")
			for i := range parts {
				types[strings.Join(parts[i:], "_")+"."+typ] = true
			}
		}
	}
	return types, nil
}

func truncate(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	if r := []rune(s); len(r) > 120 {
		return string(r[:120]) + "…"
	}
	return s
}

func lineOf(src []byte, offset int) int {
	return bytes.Count(src[:offset], []byte("\n")) + 1
}
