VERSION --use-cache-command 0.6

FROM alpine:latest

ARG GHCR_IMAGE=ghcr.io/${EARTHLY_GIT_PROJECT_NAME}
ARG GITHUB_ACTIONS=

WORKDIR /src

deps:
  RUN apk add --update \
    aws-cli \
    alpine-baselayout-data \
    binutils \
    curl \
    git \
    grep \
    helm \
    gettext \
    sed \
    less

  RUN echo "fetching latest kubernetes version" && \
    version=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt) && \
    curl -LO https://storage.googleapis.com/kubernetes-release/release/$version/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/bin/kubectl

chart:
    COPY --dir . chart
    SAVE ARTIFACT chart

code:
    FROM +deps
    COPY --dir . .
    SAVE ARTIFACT .

lint:
    FROM +code
    RUN echo "updating chart version" && \
      sed -i "s/CHART_VERSION/0.0.1/g" Chart.yaml

    RUN echo "running helm lint..." && \
      helm lint

test:
    FROM +code
    RUN echo "noop..."

artifacts:
    FROM +code
    RUN mkdir -p out
    SAVE ARTIFACT out AS LOCAL ./out

oci-artifacts:
    FROM +code
    # TODO: set this at the top level
    ARG chart=helm-waypoint
    ARG repo
    ARG region
    ARG image_tag

    # NOTE: the following values are set by action/setup-ci
    RUN \
        --secret AWS_ACCESS_KEY_ID \
        --secret AWS_SECRET_ACCESS_KEY \
        --secret AWS_SESSION_TOKEN \
      \
      echo "logging into ecr" && \
      aws ecr-public get-login-password --region=$region \
      | helm registry login --username AWS --password-stdin public.ecr.aws && \
      \
      echo "updating helm chart version" && \
      sed -i "s/CHART_VERSION/0.0.1-${image_tag}/g" Chart.yaml && \
      \
      echo "packaging chart..." && \
      helm package . && \
      helm push ${chart}-0.0.1-${image_tag}.tgz oci://public.ecr.aws/p7e3r5y0
