// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceCreateRunnerProcessResponse service create runner process response
//
// swagger:model service.CreateRunnerProcessResponse
type ServiceCreateRunnerProcessResponse struct {

	// composite status
	CompositeStatus *AppCompositeStatus `json:"composite_status,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// log stream id
	LogStreamID string `json:"log_stream_id,omitempty"`

	// runner id
	RunnerID string `json:"runner_id,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this service create runner process response
func (m *ServiceCreateRunnerProcessResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCompositeStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceCreateRunnerProcessResponse) validateCompositeStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.CompositeStatus) { // not required
		return nil
	}

	if m.CompositeStatus != nil {
		if err := m.CompositeStatus.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("composite_status")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("composite_status")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this service create runner process response based on the context it is used
func (m *ServiceCreateRunnerProcessResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCompositeStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceCreateRunnerProcessResponse) contextValidateCompositeStatus(ctx context.Context, formats strfmt.Registry) error {

	if m.CompositeStatus != nil {

		if swag.IsZero(m.CompositeStatus) { // not required
			return nil
		}

		if err := m.CompositeStatus.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("composite_status")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("composite_status")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ServiceCreateRunnerProcessResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceCreateRunnerProcessResponse) UnmarshalBinary(b []byte) error {
	var res ServiceCreateRunnerProcessResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
