// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServiceComponentHealthContextRequest service component health context request
//
// swagger:model service.ComponentHealthContextRequest
type ServiceComponentHealthContextRequest struct {

	// cluster info json
	// Required: true
	ClusterInfoJSON *string `json:"cluster_info_json"`

	// component kinds
	ComponentKinds []string `json:"component_kinds"`

	// sandbox helm releases
	SandboxHelmReleases []string `json:"sandbox_helm_releases"`
}

// Validate validates this service component health context request
func (m *ServiceComponentHealthContextRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClusterInfoJSON(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceComponentHealthContextRequest) validateClusterInfoJSON(formats strfmt.Registry) error {

	if err := validate.Required("cluster_info_json", "body", m.ClusterInfoJSON); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this service component health context request based on context it is used
func (m *ServiceComponentHealthContextRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceComponentHealthContextRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceComponentHealthContextRequest) UnmarshalBinary(b []byte) error {
	var res ServiceComponentHealthContextRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
