---
name: setup-nuonctl
description: |
  Sets up everything necessary to run nuonctl
author: "@jonmorehouse"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    # this is used to expose ACTION env-vars, so we can use docker directly, within nuonctl
    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v3

    # we default to using a docker-container driver for builds, that uses buildkit
    # only run on GitHub-hosted runners (self-hosted runners have Docker pre-configured)
    - name: Set up Docker Buildx
      if: ${{ runner.environment != 'self-hosted' }}
      uses: docker/setup-buildx-action@v3

    - name: install nuonctl (from repo)
      if: ${{ github.repository != 'nuonco/nuon' }}
      shell: bash
      run: |
        chmod +x ./bins/nuonctl/install.sh
        export NUONCTL_VERSION="${{ github.event.pull_request.number || '' }}"
        echo "y" | ./bins/nuonctl/install.sh

    - name: install nuonctl (from S3)
      if: ${{ github.repository == 'nuonco/nuon' }}
      shell: bash
      run: |
        set -e
        BASE_URL=https://nuon-artifacts.s3.us-west-2.amazonaws.com/nuonctl

        # Detect OS and architecture
        ARCH=$(uname -m)
        [ "$ARCH" = "x86_64" ] && ARCH=amd64
        OS=$(uname -s | awk '{print tolower($0)}')

        # Fetch latest version
        LATEST_VERSION=$(curl -s $BASE_URL/latest.txt)
        echo "Downloading nuonctl $LATEST_VERSION for ${OS}_${ARCH}..."

        # Download and install
        curl -sL "$BASE_URL/$LATEST_VERSION/nuonctl_${OS}_${ARCH}" -o /tmp/nuonctl
        sudo mv /tmp/nuonctl /usr/local/bin/nuonctl
        sudo chmod +x /usr/local/bin/nuonctl
        echo "✅ nuonctl installed successfully"

    - name: test-nuonctl
      shell: bash
      run: nuonctl version

branding:
  icon: "check"
  color: "blue"
