---
name: setup-nuonctl
description: |
  Sets up everything necessary to run nuonctl
author: "@jonmorehouse"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    # this is used to expose ACTION env-vars, so we can use docker directly, within nuonctl
    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v3

    # we default to using a docker-container driver for builds, that uses buildkit
    # only run on GitHub-hosted runners (self-hosted runners have Docker pre-configured)
    - name: Set up Docker Buildx
      if: ${{ runner.environment != 'self-hosted' }}
      uses: docker/setup-buildx-action@v3

    - name: install nuonctl
      shell: bash
      run: |
        chmod +x ./bins/nuonctl/install.sh
        export NUONCTL_VERSION="${{ github.event.pull_request.number || '' }}"
        echo "y" | ./bins/nuonctl/install.sh

    - name: test-nuonctl
      shell: bash
      run: nuonctl version

branding:
  icon: "check"
  color: "blue"
