# Nuon values for vantage-kubernetes-agent.
# src: https://github.com/vantage-sh/helm-charts/blob/main/charts/vantage-kubernetes-agent/values.yaml
# these are defaults but they are combined with variables inside of the tf that invokes it
image:
  repository: "quay.io/vantage-sh/kubernetes-agent"
  pullPolicy: IfNotPresent

agent:
  # The agent can be deployed as a Deployment instead of StatefulSet but requires persistS3 to be present.
  useDeployment: "true"
  debug: "false"
  # logLevel corresponds to https://pkg.go.dev/log/slog#Level
  logLevel: "0"
  # Unique identifier for your cluster.
  clusterID: "${local.env}" # from tf
  # Vantage API Token
  token: "${local.vantage-api-key}" # from tf
  # Optional. When enabled, includes the labels of that pod's namespace in the pod metadata.
  collectNamespaceLabels: "true"

  # Optional. Whether the agent should scrape GPU metrics or not. Requires NVIDIA dcgm-exporter to be deployed and configured with DCGM_FI_DEV_FB_USED and DCGM_FI_DEV_FB_TOTAL
  gpu:
    usageMetrics: "false"

# Configuration for persisting to S3. The agent will use IAM Roles for Service Accounts to authenticate. This should be setup prior to deploying the agent. See the agent docs for what policy is necessary, https://docs.vantage.sh/kubernetes_agent
persistS3:
  # S3 Bucket Name
  bucket: "${local.vantage-k8s-agent-bucket-name}" # from tf

service:
  name: report
  type: ClusterIP
  port: 9010

resources:
  limits:
    cpu: 500m
    memory: 1000Mi
  requests:
    cpu: 100m
    memory: 100Mi

nameOverride: ""
fullnameOverride: ""

# serviceAccount:
#   annotations: {}
#   # The name of the service account to use.
#   # If not set and create is true, a name is generated using the fullname template
#   name: ""
