//  THIS FILE IS GENERATED. DO NOT EDIT.
//  Generated by temporal-gen-v2

package runner

import (
	"time"

	"go.temporal.io/sdk/temporal"
	"go.temporal.io/sdk/workflow"
)

// AwaitInstallOrUpgrade is a wrapper for the InstallOrUpgrade activity
func AwaitInstallOrUpgrade(ctx workflow.Context, input *InstallOrUpgradeRequest, opts ...*workflow.ActivityOptions) (*InstallOrUpgradeResponse, error) {
	var result *InstallOrUpgradeResponse
	options := workflow.GetActivityOptions(ctx)
	options.ScheduleToCloseTimeout = time.Duration(600000000000)
	options.StartToCloseTimeout = time.Duration(600000000000)
	options.RetryPolicy = &temporal.RetryPolicy{
		MaximumAttempts: int32(5),
	}

	for _, opt := range opts {
		if opt != nil {
			if opt.TaskQueue != "" {
				options.TaskQueue = opt.TaskQueue
			}
			if opt.ScheduleToCloseTimeout != 0 {
				options.ScheduleToCloseTimeout = opt.ScheduleToCloseTimeout
			}
			if opt.StartToCloseTimeout != 0 {
				options.StartToCloseTimeout = opt.StartToCloseTimeout
			}
			if opt.ScheduleToStartTimeout != 0 {
				options.ScheduleToStartTimeout = opt.ScheduleToStartTimeout
			}
			if opt.HeartbeatTimeout != 0 {
				options.HeartbeatTimeout = opt.HeartbeatTimeout
			}
			if opt.WaitForCancellation {
				options.WaitForCancellation = opt.WaitForCancellation
			}
			if opt.ActivityID != "" {
				options.ActivityID = opt.ActivityID
			}
			if opt.RetryPolicy != nil {
				options.RetryPolicy = opt.RetryPolicy
			}
			if opt.DisableEagerExecution {
				options.DisableEagerExecution = opt.DisableEagerExecution
			}
		}
	}

	ctx = workflow.WithActivityOptions(ctx, options)
	err := workflow.ExecuteActivity(ctx, (*Activities).InstallOrUpgrade, input).Get(ctx, &result)
	return result, err
}
