// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-runner-go/models"
)

// NewPutComponentHealthContextParams creates a new PutComponentHealthContextParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutComponentHealthContextParams() *PutComponentHealthContextParams {
	return &PutComponentHealthContextParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutComponentHealthContextParamsWithTimeout creates a new PutComponentHealthContextParams object
// with the ability to set a timeout on a request.
func NewPutComponentHealthContextParamsWithTimeout(timeout time.Duration) *PutComponentHealthContextParams {
	return &PutComponentHealthContextParams{
		timeout: timeout,
	}
}

// NewPutComponentHealthContextParamsWithContext creates a new PutComponentHealthContextParams object
// with the ability to set a context for a request.
func NewPutComponentHealthContextParamsWithContext(ctx context.Context) *PutComponentHealthContextParams {
	return &PutComponentHealthContextParams{
		Context: ctx,
	}
}

// NewPutComponentHealthContextParamsWithHTTPClient creates a new PutComponentHealthContextParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutComponentHealthContextParamsWithHTTPClient(client *http.Client) *PutComponentHealthContextParams {
	return &PutComponentHealthContextParams{
		HTTPClient: client,
	}
}

/*
PutComponentHealthContextParams contains all the parameters to send to the API endpoint

	for the put component health context operation.

	Typically these are written to a http.Request.
*/
type PutComponentHealthContextParams struct {

	/* Req.

	   Input
	*/
	Req *models.ServiceComponentHealthContextRequest

	/* RunnerID.

	   runner ID
	*/
	RunnerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put component health context params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutComponentHealthContextParams) WithDefaults() *PutComponentHealthContextParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put component health context params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutComponentHealthContextParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put component health context params
func (o *PutComponentHealthContextParams) WithTimeout(timeout time.Duration) *PutComponentHealthContextParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put component health context params
func (o *PutComponentHealthContextParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put component health context params
func (o *PutComponentHealthContextParams) WithContext(ctx context.Context) *PutComponentHealthContextParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put component health context params
func (o *PutComponentHealthContextParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put component health context params
func (o *PutComponentHealthContextParams) WithHTTPClient(client *http.Client) *PutComponentHealthContextParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put component health context params
func (o *PutComponentHealthContextParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReq adds the req to the put component health context params
func (o *PutComponentHealthContextParams) WithReq(req *models.ServiceComponentHealthContextRequest) *PutComponentHealthContextParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the put component health context params
func (o *PutComponentHealthContextParams) SetReq(req *models.ServiceComponentHealthContextRequest) {
	o.Req = req
}

// WithRunnerID adds the runnerID to the put component health context params
func (o *PutComponentHealthContextParams) WithRunnerID(runnerID string) *PutComponentHealthContextParams {
	o.SetRunnerID(runnerID)
	return o
}

// SetRunnerID adds the runnerId to the put component health context params
func (o *PutComponentHealthContextParams) SetRunnerID(runnerID string) {
	o.RunnerID = runnerID
}

// WriteToRequest writes these params to a swagger request
func (o *PutComponentHealthContextParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	// path param runner_id
	if err := r.SetPathParam("runner_id", o.RunnerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
