VERSION --use-cache-command --use-copy-link 0.6

IMPORT github.com/powertoolsdev/shared-configs:main

FROM ghcr.io/powertoolsdev/ci-go-builder

WORKDIR /app

ARG GITHUB_ACTIONS=
ARG REPO=

ARG EARTHLY_GIT_PROJECT_NAME
ARG GHCR_IMAGE=ghcr.io/$EARTHLY_GIT_PROJECT_NAME

proto:
    FROM bufbuild/buf
    WORKDIR /work
    COPY --dir . .
    WORKDIR $REPO

push-proto:
  RUN "printf noop"

lint:
    FROM +proto
    RUN sh -c "buf lint && buf format -d --exit-code" \
            || sh -c "printf '%s\n' 'Buf Format changes exist in current branch' >&2 && exit 1"
