package services

import (
	"context"

	"github.com/powertoolsdev/api/internal/models"
	"github.com/powertoolsdev/api/internal/repos"
	"github.com/powertoolsdev/api/internal/utils"
	"github.com/powertoolsdev/api/internal/workflows"
	tclient "go.temporal.io/sdk/client"
	"gorm.io/gorm"
)

//go:generate -command mockgen go run github.com/golang/mock/mockgen
//go:generate mockgen -destination=mock_install_service.go -source=install_service.go -package=services
type InstallService interface {
	DeleteInstall(context.Context, string) (bool, error)
	GetInstall(context.Context, string) (*models.Install, error)
	GetAppInstalls(context.Context, string, *models.ConnectionOptions) ([]*models.Install, *utils.Page, error)
	UpsertInstall(context.Context, models.InstallInput) (*models.Install, error)
}

var _ InstallService = (*installService)(nil)

type installService struct {
	repo      repos.InstallRepo
	wkflowMgr workflows.InstallWorkflowManager
	appRepo   repos.AppRepo
}

func NewInstallService(db *gorm.DB, temporalClient tclient.Client) *installService {
	installRepo := repos.NewInstallRepo(db)
	return &installService{
		repo:      installRepo,
		wkflowMgr: workflows.NewInstallWorkflowManager(temporalClient),
		appRepo:   repos.NewAppRepo(db),
	}
}

func (i *installService) deprovisionInstall(ctx context.Context, install *models.Install) error {
	// NOTE(jm): this is a hack, we should figure out how to grab the app id without having to pass the appRepo in
	// here etc. Maybe a method on the installRepo, called GetAppOrgID?
	app, err := i.appRepo.Get(ctx, install.AppID)
	if err != nil {
		return err
	}

	return i.wkflowMgr.Deprovision(ctx, install, app.OrgID.String())
}

func (i *installService) DeleteInstall(ctx context.Context, inputID string) (bool, error) {
	installID, err := parseID(inputID)
	if err != nil {
		return false, err
	}

	savedInstall, err := i.repo.Get(ctx, installID)
	if err != nil {
		return false, err
	}

	success, err := i.repo.Delete(ctx, installID)
	if err != nil {
		return false, err
	}

	if err := i.deprovisionInstall(ctx, savedInstall); err != nil {
		return false, err
	}

	return success, nil
}

func (i *installService) GetInstall(ctx context.Context, inputID string) (*models.Install, error) {
	installID, err := parseID(inputID)
	if err != nil {
		return nil, err
	}

	return i.repo.Get(ctx, installID)
}

func (i *installService) GetAppInstalls(
	ctx context.Context,
	id string,
	options *models.ConnectionOptions,
) ([]*models.Install, *utils.Page, error) {
	appID, err := parseID(id)
	if err != nil {
		return nil, nil, err
	}
	return i.repo.ListByApp(ctx, appID, options)
}

func (i *installService) updateInstall(ctx context.Context, input models.InstallInput) (*models.Install, error) {
	install, err := i.GetInstall(ctx, *input.ID)
	if err != nil {
		return nil, err
	}

	// NOTE: we do not support changing region or account ID on an install
	install.Name = input.Name
	if input.AwsSettings != nil && install.AWSSettings == nil {
		install.AWSSettings = &models.AWSSettings{
			Region: input.AwsSettings.Region,
			// TODO: support accepting cloud account ids from inputs
			AccountID: "548377525120",
		}
		install.Settings = install.AWSSettings
	}

	updatedInstall, err := i.repo.Update(ctx, install)
	if err != nil {
		return nil, err
	}

	if err := i.provisionInstall(ctx, install); err != nil {
		return nil, err
	}
	return updatedInstall, nil
}

func (i *installService) provisionInstall(ctx context.Context, install *models.Install) error {
	// NOTE(jm): this is a hack, we should figure out how to grab the app id without having to pass the appRepo in
	// here etc. Maybe a method on the installRepo, called GetAppOrgID?
	app, err := i.appRepo.Get(ctx, install.AppID)
	if err != nil {
		return err
	}

	return i.wkflowMgr.Provision(ctx, install, app.OrgID.String())
}

func (i *installService) UpsertInstall(ctx context.Context, input models.InstallInput) (*models.Install, error) {
	if input.ID != nil {
		return i.updateInstall(ctx, input)
	}

	var install models.Install
	install.Name = input.Name
	appID, err := parseID(input.AppID)
	if err != nil {
		return nil, err
	}
	install.AppID = appID
	install.CreatedByID = *input.CreatedByID
	install.Domain = models.Domain{
		// NOTE: this will need to be passed onto the app install job to set up the root domain once it's
		// created
		Domain:        "nuon.run",
		AutoGenerated: true,
	}
	if input.AwsSettings != nil {
		install.AWSSettings = &models.AWSSettings{
			Region: input.AwsSettings.Region,
			// TODO: support accepting cloud account ids from inputs
			AccountID:  "548377525120",
			IamRoleArn: input.AwsSettings.IamRoleArn,
		}
		install.Settings = install.AWSSettings
	}

	savedInstall, err := i.repo.Create(ctx, &install)
	if err != nil {
		return nil, err
	}

	if err := i.provisionInstall(ctx, savedInstall); err != nil {
		return nil, err
	}
	return savedInstall, nil
}
