VERSION --use-cache-command 0.6

FROM golang:1.21

ARG GITHUB_ACTIONS=

deps:
  # configure repos for kubectl
  RUN curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | \
    gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg && \
    chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg && \
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'| \
    tee /etc/apt/sources.list.d/kubernetes.list && \
    chmod 644 /etc/apt/sources.list.d/kubernetes.list   # helps tools such as command-not-found to work correctly
	
   # configure repos for helm
   RUN curl https://baltocdn.com/helm/signing.asc |\ 
       gpg --dearmor |\
       tee /usr/share/keyrings/helm.gpg > /dev/null && \
       apt-get install apt-transport-https --yes && \
       echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" |\ 
       tee /etc/apt/sources.list.d/helm-stable-debian.list

  RUN apt-get update && \
    apt-get install -y ca-certificates \
      coreutils \
      make \
      git \
      helm \
      kubectl \
      gettext-base \
      awscli \
      less \
      curl \
      protobuf-compiler \
      jq

K8S_DEPLOY:
    COMMAND
    ARG EARTHLY_GIT_PROJECT_NAME
    ARG EARTHLY_GIT_SHORT_HASH
    ARG namespace=default
    ARG --required service
    ARG --required env
    ARG --required cluster_name
    ARG --required role_arn
    ARG --required chart_name
    ARG --required chart_version
    ARG --required repository
    ARG --required image_tag

    RUN \
        --push \
        --no-cache \
        --secret AWS_REGION \
        --secret AWS_ACCESS_KEY_ID \
        --secret AWS_SECRET_ACCESS_KEY \
        --secret AWS_SESSION_TOKEN \
	helm dependency update && \
        helm dependency build && \
        aws \
            eks \
            update-kubeconfig \
            --region "$AWS_REGION" \
            --name "$cluster_name" \
            --role-arn="$role_arn" \
        && helm upgrade \
            "$chart_name-$env" \
	    . \
            --install \
            --debug \
            --atomic \
            --namespace "$namespace" \
            --version "$chart_version" \
            --reset-values \
            --values values.yaml \
            --values "values.$env.yaml" \
            --set fullnameOverride="$chart_name" \
            --set-string env.GIT_REF="$EARTHLY_GIT_SHORT_HASH" \
            --set-string env.VERSION="$image_tag" \
            --set image.repository="$repository" \
            --set image.tag="$image_tag"

deploy:
    FROM +deps

    ARG --required service
    ARG --required env
    ARG --required cluster_name
    ARG --required role_arn
    ARG --required chart_version
    ARG --required chart_name
    ARG --required repository
    ARG --required image_tag

    COPY ../../services/$service+k8s/k8s k8s
    WORKDIR k8s

    ARG tfenv=.tfenv

    COPY $tfenv .
    RUN mv values.yaml values.yaml.tmpl
    RUN while IFS='=' read -r k v; do eval export "$k='$v'"; done < "$tfenv" \
     && envsubst < "values.yaml.tmpl" > "values.yaml"
     
    RUN while IFS='=' read -r k v; do eval export "$k='$v'"; done < "$tfenv" \
        && envsubst < "values.$env.tmpl" > "values.$env.yaml"

    DO +K8S_DEPLOY \
        --service=$service \
        --env=$env \
        --cluster_name=$cluster_name \
        --role_arn=$role_arn \
        --chart_version=$chart_version \
        --chart_name=$chart_name \
        --repository=$repository \
        --image_tag=$image_tag
