// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: canary/v1/provision.proto

package canaryv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProvisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanaryId      string                 `protobuf:"bytes,1,opt,name=canary_id,json=canaryId,proto3" json:"canary_id,omitempty" faker:"shortID"`
	SandboxMode   bool                   `protobuf:"varint,3,opt,name=sandbox_mode,json=sandboxMode,proto3" json:"sandbox_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionRequest) Reset() {
	*x = ProvisionRequest{}
	mi := &file_canary_v1_provision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRequest) ProtoMessage() {}

func (x *ProvisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_canary_v1_provision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRequest) Descriptor() ([]byte, []int) {
	return file_canary_v1_provision_proto_rawDescGZIP(), []int{0}
}

func (x *ProvisionRequest) GetCanaryId() string {
	if x != nil {
		return x.CanaryId
	}
	return ""
}

func (x *ProvisionRequest) GetSandboxMode() bool {
	if x != nil {
		return x.SandboxMode
	}
	return false
}

type ProvisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanaryId      string                 `protobuf:"bytes,1,opt,name=canary_id,json=canaryId,proto3" json:"canary_id,omitempty" faker:"shortID"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty" faker:"shortID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionResponse) Reset() {
	*x = ProvisionResponse{}
	mi := &file_canary_v1_provision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionResponse) ProtoMessage() {}

func (x *ProvisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_canary_v1_provision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionResponse.ProtoReflect.Descriptor instead.
func (*ProvisionResponse) Descriptor() ([]byte, []int) {
	return file_canary_v1_provision_proto_rawDescGZIP(), []int{1}
}

func (x *ProvisionResponse) GetCanaryId() string {
	if x != nil {
		return x.CanaryId
	}
	return ""
}

func (x *ProvisionResponse) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

var File_canary_v1_provision_proto protoreflect.FileDescriptor

const file_canary_v1_provision_proto_rawDesc = "" +
	"\n" +
	"\x19canary/v1/provision.proto\x12\tcanary.v1\x1a\x13tagger/tagger.proto\x1a\x17validate/validate.proto\"s\n" +
	"\x10ProvisionRequest\x12<\n" +
	"\tcanary_id\x18\x01 \x01(\tB\x1f\xfaB\br\x06\x98\x01\x1a\xd0\x01\x01\x9a\x84\x9e\x03\x0ffaker:\"shortID\"R\bcanaryId\x12!\n" +
	"\fsandbox_mode\x18\x03 \x01(\bR\vsandboxMode\"\x83\x01\n" +
	"\x11ProvisionResponse\x129\n" +
	"\tcanary_id\x18\x01 \x01(\tB\x1c\xfaB\x05r\x03\x98\x01\x1a\x9a\x84\x9e\x03\x0ffaker:\"shortID\"R\bcanaryId\x123\n" +
	"\x06org_id\x18\x02 \x01(\tB\x1c\xfaB\x05r\x03\x98\x01\x1a\x9a\x84\x9e\x03\x0ffaker:\"shortID\"R\x05orgIdB\xaa\x01\n" +
	"\rcom.canary.v1B\x0eProvisionProtoP\x01ZDgithub.com/powertoolsdev/mono/pkg/types/workflows/canary/v1;canaryv1\xa2\x02\x03CXX\xaa\x02\tCanary.V1\xca\x02\tCanary\\V1\xe2\x02\x15Canary\\V1\\GPBMetadata\xea\x02\n" +
	"Canary::V1b\x06proto3"

var (
	file_canary_v1_provision_proto_rawDescOnce sync.Once
	file_canary_v1_provision_proto_rawDescData []byte
)

func file_canary_v1_provision_proto_rawDescGZIP() []byte {
	file_canary_v1_provision_proto_rawDescOnce.Do(func() {
		file_canary_v1_provision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_canary_v1_provision_proto_rawDesc), len(file_canary_v1_provision_proto_rawDesc)))
	})
	return file_canary_v1_provision_proto_rawDescData
}

var file_canary_v1_provision_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_canary_v1_provision_proto_goTypes = []any{
	(*ProvisionRequest)(nil),  // 0: canary.v1.ProvisionRequest
	(*ProvisionResponse)(nil), // 1: canary.v1.ProvisionResponse
}
var file_canary_v1_provision_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_canary_v1_provision_proto_init() }
func file_canary_v1_provision_proto_init() {
	if File_canary_v1_provision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_canary_v1_provision_proto_rawDesc), len(file_canary_v1_provision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_canary_v1_provision_proto_goTypes,
		DependencyIndexes: file_canary_v1_provision_proto_depIdxs,
		MessageInfos:      file_canary_v1_provision_proto_msgTypes,
	}.Build()
	File_canary_v1_provision_proto = out.File
	file_canary_v1_provision_proto_goTypes = nil
	file_canary_v1_provision_proto_depIdxs = nil
}
