VERSION --use-cache-command 0.6

FROM ghcr.io/powertoolsdev/ci-go-builder

WORKDIR /src

ARG EARTHLY_GIT_PROJECT_NAME
ARG GHCR_IMAGE=ghcr.io/${EARTHLY_GIT_PROJECT_NAME}-api
ARG SERVICE=api
ARG GOCACHE=/go-cache
ARG GOMODCACHE=/go-mod-cache
ARG GITHUB_ACTIONS=

ARG ETCSSL=/etc/ssl/cert.pem

CACHE $GOCACHE
CACHE $GOMODCACHE

code:
    FROM ../../.+deps --GITHUB_ACTIONS=$GITHUB_ACTIONS
    COPY ../../pkg+code/pkg pkg
    COPY --dir . ./services/$SERVICE
    WORKDIR services/$SERVICE
    RUN go generate ./...

test:
    FROM +code
    RUN echo "not running tests, just running build./... for now."
    RUN go build ./...

test-integration:
    RUN echo "noop..."
    #FROM +code
    #RUN apk add --update --no-cache jq

    #COPY docker-compose.yml ./
    #COPY wait_for_pg.sh /bin

    #WITH DOCKER \
        #--compose docker-compose.yml \
        #--pull ghcr.io/powertoolsdev/ci-temporalite:latest \
        #--pull postgres:13.4-alpine
        #RUN \
            #wait_for_pg.sh \
            #&& go run main.go migrate up\
            #&& go test \
                #-tags=integration \
                #./...
    #END

certs:
    FROM alpine:3.16
    # NOTE(jdt): ideally we would wget -a but busybox doesn't support it
    # or use `update-ca-certificate` but it can't handle a single file w/ multiple certs
    RUN wget \
            https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem \
        && cat global-bundle.pem >> "$ETCSSL"
    SAVE ARTIFACT "$ETCSSL" /cert.pem
    SAVE IMAGE --cache-hint

lint:
    RUN echo "noop..."

build:
    FROM +code
    RUN go \
        build \
        -ldflags="-X 'github.com/powertoolsdev/mono/pkg/config.Version=$EARTHLY_TARGET_TAG_DOCKER'" \
        -o bin/service \
        .
    SAVE ARTIFACT bin/service /service
    SAVE IMAGE --push $GHCR_IMAGE:build

iamauthenticator:
    WORKDIR /tmp
    # iam authenticator download url
    ARG version=0.6.2
    RUN curl \
            -Lo aws-iam-authenticator \
            "https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v${version}/aws-iam-authenticator_${version}_linux_amd64" \
        && chmod +x aws-iam-authenticator
    SAVE ARTIFACT aws-iam-authenticator

docker:
    FROM alpine:3.16
    ARG EARTHLY_GIT_ORIGIN_URL
    ARG EARTHLY_GIT_SHORT_HASH
    ARG EARTHLY_SOURCE_DATE_EPOCH
    ARG EARTHLY_TARGET_PROJECT_NO_TAG
    ARG EARTHLY_TARGET_TAG_DOCKER

    # These are set to run locally. They _must_ be overridden in CI.
    ARG repo=$EARTHLY_TARGET_PROJECT_NO_TAG
    ARG cache_tag=$EARTHLY_TARGET_TAG_DOCKER
    ARG image_tag=$EARTHLY_TARGET_TAG_DOCKER

    COPY +build/service /bin/service
    COPY +certs/cert.pem "$ETCSSL"
    COPY --dir migrations /migrations

    ENTRYPOINT ["/bin/service"]

    LABEL org.opencontainers.image.created=$EARTHLY_SOURCE_DATE_EPOCH
    LABEL org.opencontainers.image.revision=$EARTHLY_GIT_SHORT_HASH
    LABEL org.opencontainers.image.version=$image_tag
    LABEL org.opencontainers.image.source=$EARTHLY_GIT_ORIGIN_URL
    LABEL org.opencontainers.image.authors=nuon
    LABEL org.opencontainers.image.vendor=nuon
    SAVE IMAGE --push --cache-from=$repo:$cache_tag $repo:$image_tag
