//  THIS FILE IS GENERATED. DO NOT EDIT.
//  Generated by temporal-gen-v2

package activities

import (
	"context"
	"time"

	"go.temporal.io/sdk/workflow"
)

type CreateAppConfigRequest struct {
	Req *CreateAppConfigInput `validate:"required"`
}

// CreateAppConfig is a wrapper for the createAppConfig activity
func (a *Activities) CreateAppConfig(ctx context.Context, req CreateAppConfigRequest) (*CreateAppConfigOutput, error) {
	return a.createAppConfig(ctx, req.Req)
}

// AwaitCreateAppConfig is a wrapper for the CreateAppConfig activity
func AwaitCreateAppConfig(ctx workflow.Context, input CreateAppConfigRequest, opts ...*workflow.ActivityOptions) (*CreateAppConfigOutput, error) {
	var result *CreateAppConfigOutput
	options := workflow.GetActivityOptions(ctx)
	options.StartToCloseTimeout = time.Duration(60000000000)

	for _, opt := range opts {
		if opt != nil {
			if opt.TaskQueue != "" {
				options.TaskQueue = opt.TaskQueue
			}
			if opt.ScheduleToCloseTimeout != 0 {
				options.ScheduleToCloseTimeout = opt.ScheduleToCloseTimeout
			}
			if opt.StartToCloseTimeout != 0 {
				options.StartToCloseTimeout = opt.StartToCloseTimeout
			}
			if opt.ScheduleToStartTimeout != 0 {
				options.ScheduleToStartTimeout = opt.ScheduleToStartTimeout
			}
			if opt.HeartbeatTimeout != 0 {
				options.HeartbeatTimeout = opt.HeartbeatTimeout
			}
			if opt.WaitForCancellation {
				options.WaitForCancellation = opt.WaitForCancellation
			}
			if opt.ActivityID != "" {
				options.ActivityID = opt.ActivityID
			}
			if opt.RetryPolicy != nil {
				options.RetryPolicy = opt.RetryPolicy
			}
			if opt.DisableEagerExecution {
				options.DisableEagerExecution = opt.DisableEagerExecution
			}
		}
	}

	ctx = workflow.WithActivityOptions(ctx, options)
	err := workflow.ExecuteActivity(ctx, (*Activities).CreateAppConfig, input).Get(ctx, &result)
	return result, err
}
