//  THIS FILE IS GENERATED. DO NOT EDIT.
//  Generated by temporal-gen-v2

package activities

import (
	"context"
	"time"

	"github.com/nuonco/nuon/pkg/config"
	"go.temporal.io/sdk/workflow"
)

type FetchIntermediateConfigRequest struct {
	SourceDir string `validate:"required"`
}

// FetchIntermediateConfig is a wrapper for the fetchIntermediateConfig activity
func (a *Activities) FetchIntermediateConfig(ctx context.Context, req FetchIntermediateConfigRequest) (*config.AppConfig, error) {
	return a.fetchIntermediateConfig(ctx, req.SourceDir)
}

// AwaitFetchIntermediateConfig is a wrapper for the FetchIntermediateConfig activity
func AwaitFetchIntermediateConfig(ctx workflow.Context, input FetchIntermediateConfigRequest, opts ...*workflow.ActivityOptions) (*config.AppConfig, error) {
	var result *config.AppConfig
	options := workflow.GetActivityOptions(ctx)
	options.StartToCloseTimeout = time.Duration(300000000000)

	for _, opt := range opts {
		if opt != nil {
			if opt.TaskQueue != "" {
				options.TaskQueue = opt.TaskQueue
			}
			if opt.ScheduleToCloseTimeout != 0 {
				options.ScheduleToCloseTimeout = opt.ScheduleToCloseTimeout
			}
			if opt.StartToCloseTimeout != 0 {
				options.StartToCloseTimeout = opt.StartToCloseTimeout
			}
			if opt.ScheduleToStartTimeout != 0 {
				options.ScheduleToStartTimeout = opt.ScheduleToStartTimeout
			}
			if opt.HeartbeatTimeout != 0 {
				options.HeartbeatTimeout = opt.HeartbeatTimeout
			}
			if opt.WaitForCancellation {
				options.WaitForCancellation = opt.WaitForCancellation
			}
			if opt.ActivityID != "" {
				options.ActivityID = opt.ActivityID
			}
			if opt.RetryPolicy != nil {
				options.RetryPolicy = opt.RetryPolicy
			}
			if opt.DisableEagerExecution {
				options.DisableEagerExecution = opt.DisableEagerExecution
			}
		}
	}

	ctx = workflow.WithActivityOptions(ctx, options)
	err := workflow.ExecuteActivity(ctx, (*Activities).FetchIntermediateConfig, input).Get(ctx, &result)
	return result, err
}

// AwaitFetchIntermediateConfigBySourceDir is a wrapper for the FetchIntermediateConfig activity
func AwaitFetchIntermediateConfigBySourceDir(ctx workflow.Context, input string, opts ...*workflow.ActivityOptions) (*config.AppConfig, error) {
	req := FetchIntermediateConfigRequest{
		SourceDir: input,
	}
	return AwaitFetchIntermediateConfig(ctx, req, opts...)
}
