//  THIS FILE IS GENERATED. DO NOT EDIT.
//  Generated by temporal-gen-v2

package activities

import (
	"time"

	"github.com/nuonco/nuon/services/ctl-api/internal/app"
	"go.temporal.io/sdk/workflow"
)

// AwaitPkgWorkflowsJobGetRunnerJobQueue is a wrapper for the PkgWorkflowsJobGetRunnerJobQueue activity
func AwaitPkgWorkflowsJobGetRunnerJobQueue(ctx workflow.Context, input *GetRunnerJobQueueRequest, opts ...*workflow.ActivityOptions) ([]*app.RunnerJob, error) {
	var result []*app.RunnerJob
	options := workflow.GetActivityOptions(ctx)
	options.StartToCloseTimeout = time.Duration(60000000000) // Default: 1 minute

	for _, opt := range opts {
		if opt != nil {
			if opt.TaskQueue != "" {
				options.TaskQueue = opt.TaskQueue
			}
			if opt.ScheduleToCloseTimeout != 0 {
				options.ScheduleToCloseTimeout = opt.ScheduleToCloseTimeout
			}
			if opt.StartToCloseTimeout != 0 {
				options.StartToCloseTimeout = opt.StartToCloseTimeout
			}
			if opt.ScheduleToStartTimeout != 0 {
				options.ScheduleToStartTimeout = opt.ScheduleToStartTimeout
			}
			if opt.HeartbeatTimeout != 0 {
				options.HeartbeatTimeout = opt.HeartbeatTimeout
			}
			if opt.WaitForCancellation {
				options.WaitForCancellation = opt.WaitForCancellation
			}
			if opt.ActivityID != "" {
				options.ActivityID = opt.ActivityID
			}
			if opt.RetryPolicy != nil {
				options.RetryPolicy = opt.RetryPolicy
			}
			if opt.DisableEagerExecution {
				options.DisableEagerExecution = opt.DisableEagerExecution
			}
		}
	}

	ctx = workflow.WithActivityOptions(ctx, options)
	err := workflow.ExecuteActivity(ctx, (*Activities).PkgWorkflowsJobGetRunnerJobQueue, input).Get(ctx, &result)
	return result, err
}

// AwaitPkgWorkflowsJobGetRunnerJobQueueByJobID is a wrapper for the PkgWorkflowsJobGetRunnerJobQueue activity
func AwaitPkgWorkflowsJobGetRunnerJobQueueByJobID(ctx workflow.Context, input string, opts ...*workflow.ActivityOptions) ([]*app.RunnerJob, error) {
	req := &GetRunnerJobQueueRequest{
		JobID: input,
	}
	return AwaitPkgWorkflowsJobGetRunnerJobQueue(ctx, req, opts...)
}
