---
name: action-setup-node
description: |
  Sets up node.js, creates cache & installs dependencies
author: "@powertoolsdev/team"

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
        registry-url: 'https://npm.pkg.github.com'

    - name: NPM install
      shell: bash
      run: npm ci
