VERSION --use-cache-command 0.6

FROM ghcr.io/powertoolsdev/ci-go-builder

WORKDIR /src

lint:
    RUN echo "noop..."

test:
    RUN echo "noop..."

artifacts:
    RUN mkdir -p out
    COPY --dir artifacts/* ./out
    SAVE ARTIFACT out AS LOCAL ./out

oci-artifacts:
    RUN echo "noop..."
