VERSION --use-cache-command 0.6

FROM ../../images/go-base+build-base

WORKDIR /src

lint:
    RUN echo "noop..."

test:
    RUN echo "noop..."

artifacts:
    RUN mkdir -p out
    COPY --dir artifacts/* ./out
    SAVE ARTIFACT out AS LOCAL ./out

oci-artifacts:
    RUN echo "noop..."
