// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/stack/models"
)

// GetStackConfigReader is a Reader for the GetStackConfig structure.
type GetStackConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStackConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetStackConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetStackConfigUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetStackConfigForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetStackConfigNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetStackConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/stacks/{install_id}/config] GetStackConfig", response, response.Code())
	}
}

// NewGetStackConfigOK creates a GetStackConfigOK with default headers values
func NewGetStackConfigOK() *GetStackConfigOK {
	return &GetStackConfigOK{}
}

/*
GetStackConfigOK describes a response with status code 200, with default header values.

OK
*/
type GetStackConfigOK struct {
	Payload *models.ServiceStackConfigResponse
}

// IsSuccess returns true when this get stack config o k response has a 2xx status code
func (o *GetStackConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get stack config o k response has a 3xx status code
func (o *GetStackConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get stack config o k response has a 4xx status code
func (o *GetStackConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get stack config o k response has a 5xx status code
func (o *GetStackConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get stack config o k response a status code equal to that given
func (o *GetStackConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get stack config o k response
func (o *GetStackConfigOK) Code() int {
	return 200
}

func (o *GetStackConfigOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/stacks/{install_id}/config][%d] getStackConfigOK %s", 200, payload)
}

func (o *GetStackConfigOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/stacks/{install_id}/config][%d] getStackConfigOK %s", 200, payload)
}

func (o *GetStackConfigOK) GetPayload() *models.ServiceStackConfigResponse {
	return o.Payload
}

func (o *GetStackConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStackConfigResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetStackConfigUnauthorized creates a GetStackConfigUnauthorized with default headers values
func NewGetStackConfigUnauthorized() *GetStackConfigUnauthorized {
	return &GetStackConfigUnauthorized{}
}

/*
GetStackConfigUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetStackConfigUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get stack config unauthorized response has a 2xx status code
func (o *GetStackConfigUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get stack config unauthorized response has a 3xx status code
func (o *GetStackConfigUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get stack config unauthorized response has a 4xx status code
func (o *GetStackConfigUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get stack config unauthorized response has a 5xx status code
func (o *GetStackConfigUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get stack config unauthorized response a status code equal to that given
func (o *GetStackConfigUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get stack config unauthorized response
func (o *GetStackConfigUnauthorized) Code() int {
	return 401
}

func (o *GetStackConfigUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/stacks/{install_id}/config][%d] getStackConfigUnauthorized %s", 401, payload)
}

func (o *GetStackConfigUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/stacks/{install_id}/config][%d] getStackConfigUnauthorized %s", 401, payload)
}

func (o *GetStackConfigUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetStackConfigUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetStackConfigForbidden creates a GetStackConfigForbidden with default headers values
func NewGetStackConfigForbidden() *GetStackConfigForbidden {
	return &GetStackConfigForbidden{}
}

/*
GetStackConfigForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetStackConfigForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get stack config forbidden response has a 2xx status code
func (o *GetStackConfigForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get stack config forbidden response has a 3xx status code
func (o *GetStackConfigForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get stack config forbidden response has a 4xx status code
func (o *GetStackConfigForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get stack config forbidden response has a 5xx status code
func (o *GetStackConfigForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get stack config forbidden response a status code equal to that given
func (o *GetStackConfigForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get stack config forbidden response
func (o *GetStackConfigForbidden) Code() int {
	return 403
}

func (o *GetStackConfigForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/stacks/{install_id}/config][%d] getStackConfigForbidden %s", 403, payload)
}

func (o *GetStackConfigForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/stacks/{install_id}/config][%d] getStackConfigForbidden %s", 403, payload)
}

func (o *GetStackConfigForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetStackConfigForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetStackConfigNotFound creates a GetStackConfigNotFound with default headers values
func NewGetStackConfigNotFound() *GetStackConfigNotFound {
	return &GetStackConfigNotFound{}
}

/*
GetStackConfigNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetStackConfigNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get stack config not found response has a 2xx status code
func (o *GetStackConfigNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get stack config not found response has a 3xx status code
func (o *GetStackConfigNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get stack config not found response has a 4xx status code
func (o *GetStackConfigNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get stack config not found response has a 5xx status code
func (o *GetStackConfigNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get stack config not found response a status code equal to that given
func (o *GetStackConfigNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get stack config not found response
func (o *GetStackConfigNotFound) Code() int {
	return 404
}

func (o *GetStackConfigNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/stacks/{install_id}/config][%d] getStackConfigNotFound %s", 404, payload)
}

func (o *GetStackConfigNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/stacks/{install_id}/config][%d] getStackConfigNotFound %s", 404, payload)
}

func (o *GetStackConfigNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetStackConfigNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetStackConfigInternalServerError creates a GetStackConfigInternalServerError with default headers values
func NewGetStackConfigInternalServerError() *GetStackConfigInternalServerError {
	return &GetStackConfigInternalServerError{}
}

/*
GetStackConfigInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetStackConfigInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get stack config internal server error response has a 2xx status code
func (o *GetStackConfigInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get stack config internal server error response has a 3xx status code
func (o *GetStackConfigInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get stack config internal server error response has a 4xx status code
func (o *GetStackConfigInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get stack config internal server error response has a 5xx status code
func (o *GetStackConfigInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get stack config internal server error response a status code equal to that given
func (o *GetStackConfigInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get stack config internal server error response
func (o *GetStackConfigInternalServerError) Code() int {
	return 500
}

func (o *GetStackConfigInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/stacks/{install_id}/config][%d] getStackConfigInternalServerError %s", 500, payload)
}

func (o *GetStackConfigInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/stacks/{install_id}/config][%d] getStackConfigInternalServerError %s", 500, payload)
}

func (o *GetStackConfigInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetStackConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
