---
fullnameOverride: temporal

cassandra:
  enabled: false
elasticsearch:
  enabled: false
grafana:
  enabled: false
mysql:
  enabled: false
postgresql:
  enabled: true
prometheus:
  enabled: false

schema:
  setup:
    enabled: false
  update:
    enabled: false

server:
  replicaCount: 3
  config:
    prometheus:
      framework: opentelemetry
      listenAddress: "0.0.0.0:9090"
    persistence:
      default:
        driver: sql
        sql:
          database: temporal
          driver: postgres
          maxConnLifetime: 1h
          maxConns: 20
      visibility:
        driver: sql
        sql:
          database: temporal_visibility
          driver: postgres
          maxConnLifetime: 1h
          maxConns: 20

web:
  additionalEnv:
    - name: TEMPORAL_CSRF_COOKIE_INSECURE
      value: !!str "true"
