VERSION --use-cache-command 0.6

FROM ../../images/go-base+build-base

WORKDIR /src

ARG BIN=waypoint-plugin-terraform
ARG GOCACHE=/go-cache
ARG GOMODCACHE=/go-mod-cache
ARG ODR_VERSION=v0.2.1

CACHE $GOCACHE
CACHE $GOMODCACHE

code:
    FROM ../../.+deps
    COPY ../../pkg+code/pkg pkg
    COPY --dir . ./bins/$BIN
    WORKDIR bins/$BIN
    RUN go generate ./...

lint:
    FROM +code

test:
    FROM +code
    RUN go test ./...

artifacts:
    FROM +code

    ARG GOOS=linux
    ARG GOARCH=amd64

    RUN mkdir -p out && \
      go build -o ./out/$BIN .

    RUN chmod +x ./out/$BIN
    SAVE ARTIFACT out AS LOCAL ./out

oci-artifacts:
    FROM public.ecr.aws/p7e3r5y0/waypoint-odr-base:$ODR_VERSION
    RUN apk add --no-cache \
      libc6-compat \
      build-base \
      make \
      ca-certificates-bundle \
      coreutils \
      curl \
      protoc \
      jq \
      git \
      aws-cli \
      zip

    ARG repo=
    ARG image_tag=

    # note waypoint plugins need to be loaded from a specific path on disk
    ENV XDG_CONFIG_HOME=/home/waypoint/.config
    COPY +artifacts/out/$BIN /home/waypoint/.config/waypoint/plugins/$BIN
    COPY ../../images/aws-iam-authenticator+aws-iam-authenticator/aws-iam-authenticator /usr/local/bin/aws-iam-authenticator

    SAVE IMAGE --push $repo:$image_tag
