VERSION --use-cache-command 0.6

FROM ghcr.io/powertoolsdev/ci-go-builder

WORKDIR /src

ARG BIN=waypoint-plugin-terraform
ARG GOCACHE=/go-cache
ARG GOMODCACHE=/go-mod-cache
ARG ODR_VERSION=v0.0.5

CACHE $GOCACHE
CACHE $GOMODCACHE

code:
    FROM ../../.+deps
    COPY ../../pkg+code/pkg pkg
    COPY --dir . ./bins/$BIN
    WORKDIR bins/$BIN
    RUN go generate ./...

lint:
    FROM +code

test:
    FROM +code
    RUN go test ./...

test-integration:
    RUN echo "noop..."

artifacts:
    FROM +code
    RUN mkdir -p out && \
      go build -o ./out/$BIN .

    SAVE ARTIFACT out AS LOCAL ./out

oci-artifacts:
    FROM public.ecr.aws/p7e3r5y0/waypoint-odr:$ODR_VERSION
    COPY +artifacts/out/$BIN /bin/$BIN

    ARG repo=
    ARG image_tag=
    SAVE IMAGE --push $repo:$image_tag
