// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: executors/v1/plan/v1/component_input.proto

package planv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ComponentInput with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ComponentInput) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ComponentInput with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ComponentInputMultiError,
// or nil if none found.
func (m *ComponentInput) ValidateAll() error {
	return m.validate(true)
}

func (m *ComponentInput) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetOrgId()) != 26 {
		err := ComponentInputValidationError{
			field:  "OrgId",
			reason: "value length must be 26 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)

	}

	if utf8.RuneCountInString(m.GetAppId()) != 26 {
		err := ComponentInputValidationError{
			field:  "AppId",
			reason: "value length must be 26 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)

	}

	// no validation rules for InstallId

	// no validation rules for BuildId

	// no validation rules for DeployId

	if all {
		switch v := interface{}(m.GetComponent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ComponentInputValidationError{
					field:  "Component",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ComponentInputValidationError{
					field:  "Component",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetComponent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ComponentInputValidationError{
				field:  "Component",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Type

	if all {
		switch v := interface{}(m.GetContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ComponentInputValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ComponentInputValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ComponentInputValidationError{
				field:  "Context",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ComponentInputMultiError(errors)
	}

	return nil
}

// ComponentInputMultiError is an error wrapping multiple validation errors
// returned by ComponentInput.ValidateAll() if the designated constraints
// aren't met.
type ComponentInputMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ComponentInputMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ComponentInputMultiError) AllErrors() []error { return m }

// ComponentInputValidationError is the validation error returned by
// ComponentInput.Validate if the designated constraints aren't met.
type ComponentInputValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ComponentInputValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ComponentInputValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ComponentInputValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ComponentInputValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ComponentInputValidationError) ErrorName() string { return "ComponentInputValidationError" }

// Error satisfies the builtin error interface
func (e ComponentInputValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sComponentInput.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ComponentInputValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ComponentInputValidationError{}
