// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: executors/v1/plan/v1/ecr_repository_ref.proto

package planv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ECRRepositoryRef contains all of the information for referencing the app's ECR repo. Note, that all ECR repos are
// created with the format `orgShortID/appShortID` so we can use prefix based IAM roles to limit them.
type ECRRepositoryRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TODO(jm): make these optional + enforce validations if set
	// 12 digit aws account id
	RegistryId string `protobuf:"bytes,1,opt,name=registry_id,json=registryId,proto3" json:"registry_id,omitempty" faker:"len=12"`
	// org format is: <org_short_id>/<app_short_id>
	// install format is: <org_short_id>/<app_short_id>
	RepositoryName string `protobuf:"bytes,2,opt,name=repository_name,json=repositoryName,proto3" json:"repository_name,omitempty" faker:"len=53"`
	// format is: arn:aws:ecr:<region>:<account_id>:repository/<org_short_id>/<app_short_id>.
	RepositoryArn string `protobuf:"bytes,3,opt,name=repository_arn,json=repositoryArn,proto3" json:"repository_arn,omitempty" faker:"len=99"`
	// format: <account_id>.dkr.ecr.<region>.amazonaws.com/<org_short_id>/<app_short_id>
	RepositoryUri string `protobuf:"bytes,4,opt,name=repository_uri,json=repositoryUri,proto3" json:"repository_uri,omitempty" faker:"len=98"`
	Tag           string `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty" faker:"len=10"`
	Region        string `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty" faker:"oneof: us-west-2"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ECRRepositoryRef) Reset() {
	*x = ECRRepositoryRef{}
	mi := &file_executors_v1_plan_v1_ecr_repository_ref_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECRRepositoryRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECRRepositoryRef) ProtoMessage() {}

func (x *ECRRepositoryRef) ProtoReflect() protoreflect.Message {
	mi := &file_executors_v1_plan_v1_ecr_repository_ref_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECRRepositoryRef.ProtoReflect.Descriptor instead.
func (*ECRRepositoryRef) Descriptor() ([]byte, []int) {
	return file_executors_v1_plan_v1_ecr_repository_ref_proto_rawDescGZIP(), []int{0}
}

func (x *ECRRepositoryRef) GetRegistryId() string {
	if x != nil {
		return x.RegistryId
	}
	return ""
}

func (x *ECRRepositoryRef) GetRepositoryName() string {
	if x != nil {
		return x.RepositoryName
	}
	return ""
}

func (x *ECRRepositoryRef) GetRepositoryArn() string {
	if x != nil {
		return x.RepositoryArn
	}
	return ""
}

func (x *ECRRepositoryRef) GetRepositoryUri() string {
	if x != nil {
		return x.RepositoryUri
	}
	return ""
}

func (x *ECRRepositoryRef) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ECRRepositoryRef) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

var File_executors_v1_plan_v1_ecr_repository_ref_proto protoreflect.FileDescriptor

const file_executors_v1_plan_v1_ecr_repository_ref_proto_rawDesc = "" +
	"\n" +
	"-executors/v1/plan/v1/ecr_repository_ref.proto\x12\x14executors.v1.plan.v1\x1a\x13tagger/tagger.proto\x1a\x17validate/validate.proto\"\x9c\x03\n" +
	"\x10ECRRepositoryRef\x124\n" +
	"\vregistry_id\x18\x01 \x01(\tB\x13\x9a\x84\x9e\x03\x0efaker:\"len=12\"R\n" +
	"registryId\x12D\n" +
	"\x0frepository_name\x18\x02 \x01(\tB\x1b\xfaB\x05r\x03\x98\x015\x9a\x84\x9e\x03\x0efaker:\"len=53\"R\x0erepositoryName\x12:\n" +
	"\x0erepository_arn\x18\x03 \x01(\tB\x13\x9a\x84\x9e\x03\x0efaker:\"len=99\"R\rrepositoryArn\x12:\n" +
	"\x0erepository_uri\x18\x04 \x01(\tB\x13\x9a\x84\x9e\x03\x0efaker:\"len=98\"R\rrepositoryUri\x12,\n" +
	"\x03tag\x18\x05 \x01(\tB\x1a\xfaB\x04r\x02\x10\x01\x9a\x84\x9e\x03\x0efaker:\"len=10\"R\x03tag\x12f\n" +
	"\x06region\x18\x06 \x01(\tBN\xfaB.r,R\tus-west-2R\tus-east-2R\tus-east-1R\tus-west-1\x9a\x84\x9e\x03\x18faker:\"oneof: us-west-2\"R\x06regionB\xf3\x01\n" +
	"\x18com.executors.v1.plan.v1B\x15EcrRepositoryRefProtoP\x01ZMgithub.com/powertoolsdev/mono/pkg/types/workflows/executors/v1/plan/v1;planv1\xa2\x02\x03EVP\xaa\x02\x14Executors.V1.Plan.V1\xca\x02\x14Executors\\V1\\Plan\\V1\xe2\x02 Executors\\V1\\Plan\\V1\\GPBMetadata\xea\x02\x17Executors::V1::Plan::V1b\x06proto3"

var (
	file_executors_v1_plan_v1_ecr_repository_ref_proto_rawDescOnce sync.Once
	file_executors_v1_plan_v1_ecr_repository_ref_proto_rawDescData []byte
)

func file_executors_v1_plan_v1_ecr_repository_ref_proto_rawDescGZIP() []byte {
	file_executors_v1_plan_v1_ecr_repository_ref_proto_rawDescOnce.Do(func() {
		file_executors_v1_plan_v1_ecr_repository_ref_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_executors_v1_plan_v1_ecr_repository_ref_proto_rawDesc), len(file_executors_v1_plan_v1_ecr_repository_ref_proto_rawDesc)))
	})
	return file_executors_v1_plan_v1_ecr_repository_ref_proto_rawDescData
}

var file_executors_v1_plan_v1_ecr_repository_ref_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_executors_v1_plan_v1_ecr_repository_ref_proto_goTypes = []any{
	(*ECRRepositoryRef)(nil), // 0: executors.v1.plan.v1.ECRRepositoryRef
}
var file_executors_v1_plan_v1_ecr_repository_ref_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_executors_v1_plan_v1_ecr_repository_ref_proto_init() }
func file_executors_v1_plan_v1_ecr_repository_ref_proto_init() {
	if File_executors_v1_plan_v1_ecr_repository_ref_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_executors_v1_plan_v1_ecr_repository_ref_proto_rawDesc), len(file_executors_v1_plan_v1_ecr_repository_ref_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_executors_v1_plan_v1_ecr_repository_ref_proto_goTypes,
		DependencyIndexes: file_executors_v1_plan_v1_ecr_repository_ref_proto_depIdxs,
		MessageInfos:      file_executors_v1_plan_v1_ecr_repository_ref_proto_msgTypes,
	}.Build()
	File_executors_v1_plan_v1_ecr_repository_ref_proto = out.File
	file_executors_v1_plan_v1_ecr_repository_ref_proto_goTypes = nil
	file_executors_v1_plan_v1_ecr_repository_ref_proto_depIdxs = nil
}
