---
env:
  NUON_DEBUG: 'true'
  RUNNER_ID: <must-be-set>
  API_TOKEN: <must-be-set>
  API_URL: <must-be-set>

image:
  repository: ""
  tag: "latest"

serviceAccount:
  name: runner
  annotations: {}

podLabels: {}

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 100
  targetMemoryUtilizationPercentage: 100

resources:
  requests:
    cpu: 750m
    memory: 1.5Gi

node_pool:
  enabled: false
  node_class_ref:
    group: karpenter.k8s.aws
    kind: EC2NodeClass
    name: default
  capacity_types:
    - on-demand
  instance_type:
    name: t3a.medium
    cpu: 2
    memory: 4096  # int so we can do math, rendered with Mi

  runner_count: 1
