VERSION --use-cache-command 0.6

FROM ghcr.io/powertoolsdev/ci-go-builder

WORKDIR /src

ARG GOCACHE=/go-cache
ARG GOMODCACHE=/go-mod-cache
CACHE $GOCACHE
CACHE $GOMODCACHE
ARG GITHUB_ACTIONS=1

# code should be used to consume pkg as code. It exports the fully generated pkg.
code:
    FROM ../.+deps --GITHUB_ACTIONS=$GITHUB_ACTIONS
    COPY --dir . ./pkg
    DO +GEN
    SAVE ARTIFACT pkg

test:
    FROM +code
    RUN go test -cover ./...

test-integration:
    FROM +code
    RUN go test -tags=integration ./...

lint:
    RUN echo "noop..."

GEN:
    COMMAND
    DO ./types+BUF_LOGIN
    RUN go generate ./...
