VERSION --use-cache-command 0.6

FROM ../images/go-base+build-base

WORKDIR /src

ARG GOCACHE=/go-cache
ARG GOMODCACHE=/go-mod-cache
CACHE $GOCACHE
CACHE $GOMODCACHE
ARG GHCR_IMAGE=ghcr.io/powertoolsdev/mono-pkg:cache

# code should be used to consume pkg as code. It exports the fully generated pkg
code:
    FROM ../.+deps
    COPY --dir . ./pkg
    COPY ../services/ctl-api+swagger-schema/services /src/services
    DO +GEN

    SAVE ARTIFACT pkg
    SAVE IMAGE --push $GHCR_IMAGE

test:
    FROM +code
    RUN go test -cover ./...

test-integration:
    FROM +code
    RUN go test -tags=integration ./...

lint:
    RUN echo "noop..."

GEN:
    COMMAND
    RUN go generate ./...
