VERSION --use-cache-command 0.6

FROM ../../images/go-base+build-base

WORKDIR /src

ARG EARTHLY_GIT_PROJECT_NAME
ARG GHCR_IMAGE=ghcr.io/${EARTHLY_GIT_PROJECT_NAME}-workers-installs
ARG SERVICE=workers-installs
ARG GOCACHE=/go-cache
ARG GOMODCACHE=/go-mod-cache

CACHE $GOCACHE
CACHE $GOMODCACHE

code:
    FROM ../../.+deps
    COPY ../../pkg+code/pkg pkg
    COPY --dir . ./services/$SERVICE
    WORKDIR services/$SERVICE
    RUN go generate ./...

test:
    FROM +code
    RUN go test ./...

test-integration:
    FROM +code
    RUN echo "noop..."
    ## This should match our running version of k8s as closely as possible.
    ## Use `+get-envtest-versions` to get the list of supported binaries
    ## as they don't publish envtest binaries for every patch release.
    #ENV K8S_VERSION=1.23.5
    #RUN curl \
            #-sSLo /tmp/envtest-bins.tar.gz \
            #"https://go.kubebuilder.io/test-tools/${K8S_VERSION}/$(go env GOOS)/$(go env GOARCH)" \
        #&& mkdir -p /usr/local/kubebuilder \
        #&& tar -C /usr/local/kubebuilder --strip-components=1 -zvxf /tmp/envtest-bins.tar.gz \
        #&& rm -f /tmp/envtest-bins.tar.gz
    #ENV ACK_GINKGO_DEPRECATIONS=1.16.5
    #RUN go test -tags=integration ./...
    #SAVE IMAGE --push $GHCR_IMAGE:test-integration

get-envtest-versions:
    FROM alpine:3.16
    RUN apk add --update --no-cache curl ca-certificates xmlstarlet
    RUN xmlstarlet select --help
    # This file is actually in GCS but uses same XMLNS as S3
    RUN curl -L "https://go.kubebuilder.io/test-tools" \
        | xmlstarlet \
            select \
            -N x="http://doc.s3.amazonaws.com/2006-03-01" \
            --template \
            --value-of "//x:Key"

lint:
    FROM +code
    RUN golangci-lint \
      run -c ../../.golangci-lint.yaml \
      --issues-exit-code 0 \
      ./...

build:
    FROM +code
    RUN go \
        build \
        -ldflags="-X 'github.com/powertoolsdev/mono/pkg/config.Version=$EARTHLY_TARGET_TAG_DOCKER'" \
        -o bin/service \
        .
    SAVE ARTIFACT bin/service /service
    SAVE IMAGE --push $GHCR_IMAGE:build


docker:
    FROM ../../images/go-base+alpine-base

    ARG EARTHLY_GIT_ORIGIN_URL
    ARG EARTHLY_GIT_SHORT_HASH
    ARG EARTHLY_SOURCE_DATE_EPOCH
    ARG EARTHLY_TARGET_PROJECT_NO_TAG
    ARG EARTHLY_TARGET_TAG_DOCKER

    # These are set to run locally. They _must_ be overridden in CI.
    ARG repo=$EARTHLY_TARGET_PROJECT_NO_TAG
    ARG cache_tag=$EARTHLY_TARGET_TAG_DOCKER
    ARG image_tag=$EARTHLY_TARGET_TAG_DOCKER

    COPY +build/service /bin/service
    COPY ../../charts/waypoint+chart/chart /charts/waypoint
    COPY ../../images/aws-iam-authenticator+aws-iam-authenticator/aws-iam-authenticator /usr/local/bin/aws-iam-authenticator

    ENTRYPOINT ["/bin/service", "all"]

    LABEL org.opencontainers.image.created=$EARTHLY_SOURCE_DATE_EPOCH
    LABEL org.opencontainers.image.revision=$EARTHLY_GIT_SHORT_HASH
    LABEL org.opencontainers.image.version=$image_tag
    LABEL org.opencontainers.image.source=$EARTHLY_GIT_ORIGIN_URL
    LABEL org.opencontainers.image.authors=nuon
    LABEL org.opencontainers.image.vendor=nuon
    SAVE IMAGE --push --cache-from=$repo:$cache_tag $repo:$image_tag

