---
dist:
  name: nuon-runner-otelcol
  description: Nuon Runner Telemetry Export Collector
  otelcol_version: 0.150.0
  output_path: ./otelcol-build
  version: 1.0.0
  module: github.com/nuonco/nuon/bins/runner/otelcol

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.150.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.150.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.150.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.150.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.150.0
