VERSION --use-cache-command 0.6

FROM ../../images/go-base+build-base

WORKDIR /src

ARG EARTHLY_GIT_PROJECT_NAME
ARG GHCR_IMAGE=ghcr.io/${EARTHLY_GIT_PROJECT_NAME}-runner
ARG BIN=runner
ARG GOCACHE=/go-cache
ARG GOMODCACHE=/go-mod-cache
ARG PKG_ROOT=github.com/powertoolsdev/mono/bins/runner
ARG ETCSSL=/etc/ssl/cert.pem

CACHE $GOCACHE
CACHE $GOMODCACHE

code:
    FROM ../../.+deps
    COPY ../../pkg+code/pkg pkg
    COPY --dir . ./bins/$BIN
    WORKDIR bins/$BIN
    RUN go generate ./...

test:
    FROM +code
    RUN go test ./...

integration:
    FROM +code

lint:
    FROM +code
    RUN golangci-lint \
      run -c ../../.golangci.yml \
      --issues-exit-code 0 \
      ./...

build:
    FROM +code
    RUN go \
        build \
        -ldflags="-X '${PKG_ROOT}/internal.Version=${GIT_SHORT_REF}'" \
        -o bin/runner \
        .
    SAVE ARTIFACT bin/runner /runner
    SAVE IMAGE --push $GHCR_IMAGE:build

bundle:
    COPY ./bundle /bundle
    SAVE ARTIFACT /bundle

artifacts:
    FROM +code

    ARG GOOS=linux
    ARG GOARCH=amd64

    RUN mkdir -p out && \
      go build -o ./out/$BIN .

    RUN chmod +x ./out/$BIN
    SAVE ARTIFACT out AS LOCAL ./out

kaniko:
    # Use this FROM instruction as shortcut to use --copy=from kaniko below
    # It's also possible to use directly COPY --from=gcr.io/kaniko-project/executor
    FROM gcr.io/kaniko-project/executor

    SAVE ARTIFACT /kaniko
    SAVE ARTIFACT /etc/nsswitch.conf nsswitch.conf

nuon-cli:
    RUN curl https://nuon-artifacts.s3.us-west-2.amazonaws.com/cli/0.19.519/nuon_linux_amd64 -o /nuon && chmod +x /nuon
    SAVE ARTIFACT /nuon

oci-artifacts:
    FROM ../../images/go-base+alpine-base

    ARG EARTHLY_GIT_ORIGIN_URL
    ARG EARTHLY_GIT_SHORT_HASH
    ARG EARTHLY_SOURCE_DATE_EPOCH
    ARG EARTHLY_TARGET_PROJECT_NO_TAG
    ARG EARTHLY_TARGET_TAG_DOCKER

    # These are set to run locally. They _must_ be overridden in CI.
    ARG repo=
    ARG image_tag=
    ARG cache_tag=
    ARG cache_repo=
    ARG push_latest_tag=

    RUN apk add --no-cache \
      libc6-compat \
      build-base \
      make \
      ca-certificates-bundle \
      coreutils \
      curl \
      protoc \
      jq \
      git \
      aws-cli \
      kubectl \
      zip \
      openssl

    # copy kaniko into the final binary
    COPY +kaniko/kaniko/* /kaniko/
    COPY +kaniko/kaniko/.docker /kaniko/.docker
    COPY +kaniko/nsswitch.conf /etc/nsswitch.conf

    # copy the nuon cli
    COPY +nuon-cli/nuon /usr/bin/nuon

    # copy nuon specific artifacts into the final binary
    COPY +build/runner /bin/runner
    COPY ../../images/certs+certs/cert.pem "$ETCSSL"
    COPY ../../images/aws-iam-authenticator+aws-iam-authenticator/aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
    COPY ./bundle /bundle

    ENV GIT_REF=$image_tag

    LABEL org.opencontainers.image.created=$EARTHLY_SOURCE_DATE_EPOCH
    LABEL org.opencontainers.image.revision=$EARTHLY_GIT_SHORT_HASH
    LABEL org.opencontainers.image.version=$image_tag
    LABEL org.opencontainers.image.source=$EARTHLY_GIT_ORIGIN_URL
    LABEL org.opencontainers.image.authors=nuon
    LABEL org.opencontainers.image.vendor=nuon

    ENTRYPOINT ["/bin/runner"]

    IF [ "$push_latest_tag" == "true" ]
	SAVE IMAGE --push --cache-from=$cache_repo:$cache_tag $repo:latest
    END
    SAVE IMAGE --push --cache-from=$cache_repo:$cache_tag $repo:$image_tag
